### ISSUE TITLE
Sticky Feature Audit

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1004]
### Description:
Once we're done with the current sets of tasks, we must take a look at other plugins, platforms, and solutions to see what is possible to do with their sticky features and compare it with our limitations of ours and then improve accordingly.

It's not the most important task right now so we can do it once everything important is out of the way. Can the @Codeinwp/design-team help with this?

**Comment by mghenciu** [comment]
**Note to Self** >>>
maybe we can add the **Sticky Icon** Feature **in the Blocks Toolbar**, as it's available on all blocks.
This way the feature will be more visible.
<img width="533" alt="image" src="https://user-images.githubusercontent.com/52494172/181244242-70078764-195b-492a-a114-cb928397da24.png">

**Comment by HardeepAsrani** [comment]
Also, it will be nice to make it work with Section blocks of other popular block plugins as many people use multiple plugins.

**Comment by HardeepAsrani** [comment]
Closing this as it was done on Slack and many changed implemented.
