### ISSUE TITLE
Section block: desktop padding and margin values should be inherited across viewports by default

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#1030]
After a discussion in Slack, we agreed with @HardeepAsrani to create this issue. 
Here is some context:

Wherever we manage responsive values in the UI, we expect that the desktop values for properties like padding etc, get inherited by default to the tabled and mobile viewports.

For example when a user sets a section padding of 24px in the desktop, this padding should apply to tablet and mobile by default, unless the user edits the value for any of the viewports specifically. 

![Screenshot 2022-07-08 at 21 28 30](https://user-images.githubusercontent.com/4193672/178050497-15acffa9-198e-4a02-8783-88b0916e7c49.png)

It can be very time-consuming and confusing to need to enter the same set of values for all viewports, for every section.

[Here is a 2-min video to show in practice](https://www.loom.com/share/8e6ddad73a064a5ea696d26a0f0a084d)

I believe it is worth applying this logic across our blocks in general on each revision rounds, since it's a common industry practice and meets the user's expectations.

For the Section block specifically, we should make sure that:

- [ ] Values are inherited for both padding and margin controls
- [ ] Values are inherited for both the section and the section column.

**Comment by JohnPixle** [comment]
I can't be 100% sure, but maybe this has something to do with it:
 #1001 

I see many similar issues on other blocks too, and I believe they are affected with the broader iFrame thing.

**Comment by HardeepAsrani** [comment]
But this also happens in the front-end, right @JohnPixle

**Comment by JohnPixle** [comment]
@HardeepAsrani Interestingly, it works for the frontend. Back not in the editor :(

**Comment by HardeepAsrani** [comment]
Ahaa, got it. Thanks!

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani this is mostly caused by the strict scoping https://github.com/Codeinwp/otter-blocks/blob/07b0bccb4dcea4ccae1ea73856df5bdc952a7d45/src/blocks/blocks/section/column/edit.js#L162-L173

if we just enable the CSS for all, the inheritance will work like in the frontend.

**Comment by HardeepAsrani** [comment]
@HardeepAsrani I remember there were some bottlenecks there but we can do it now to see. Can you take care of this?
