### ISSUE TITLE
Animation optimization

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1033]
### Description:
Few suggestions made by our users on how we can optimize animations:

- We can remove (or give an option) the -webkit prefixes that show animations on old browsers which can reduce the blueprint of the file by around 2/3 and make it from 66kb to something like 20kb. However, I see some stats that even browsers from 2 years back use -webkit prefixes so maybe some compromise here on adding an option to load them or dropping support.

- Loading animations in the front based on the usage where we only load the CSS from the animations which are loaded in the front. It's a bit more complex and we will need some mechanism to detect and extract CSS based on this but it can reduce 60/70kbs of page size when user is using only few animations the page.

Any thoughts? @selul

**Comment by selul** [comment]
love the ideas.

**Comment by HardeepAsrani** [comment]
Note to self to remember for myself & QA:

- The option will have a toggle, which will be disabled for pre-existing users to prevent already existing posts from not loading animations. Still, they will get a notice inside the Animations panel about the new option + to clear all stored CSS to make it work with existing posts.
