### ISSUE TITLE
Migrating Woo Comparison table to Sparks

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1034]
### Description:
We need to migrate the current comparison table to Sparks and remove it from Otter.

**Comment by mskapusuz** [comment]
@irinelenache 

**Description**
Migrating **Comparison Table block** entirely to Sparks side. So, the idea is; Comparison Table Block can be run without needs Otter.

Issue needs both PRs on Otter repo and Sparks repo:

- https://github.com/Codeinwp/sparks-for-woocommerce/pull/36
- https://github.com/Codeinwp/otter-blocks/pull/1035

**Test cases:**
* Case 1: (Old user's block should be migrated) Comparison table blocks added to any page on Otter side should be migrated to Sparks side
	**Instructions:**
	1. Install&Activate stable versions of Neve, Neve Pro, Otter, Otter Pro, Sparks
	2. Enable comparison table from Sparks
	3. Create a page and add the comparison table block (fyi: in stable versions the style is broken, that's a regression that occurred after the CSS lowercase stuff we made a few months ago)
	4. Visit front side and make sure block works well
	5. Install&Activate https://github.com/Codeinwp/sparks-for-woocommerce/pull/36 https://github.com/Codeinwp/otter-blocks/pull/1035 PR builds of Otter, Otter Pro and Sparks
	6. Visit the post/page that contains comparison table block, you'll see comparison table block renders empty (blank content)
	7. Visit block editor of the page/post, here we expect comparison table block is visible and editable, update the page.
	8. From now on, migration should be completed and on the front side comparison table block should be visible again

* Case 2: (Fresh usage of the block) Comparison Table block should work well independently from Otter.
	
	**Instructions:**
	1. Comparison table block should work well without needs Otter
	2. Style regression has been fixed. (color customizations etc. should be work well.)

**Comment by mskapusuz** [comment]
@irinelenache 

The issue has been ready for a new test round 🚀 I've tried to list all test instructions on here:

**Description**
Migrating **Comparison Table block** entirely to Sparks side. So, the idea is; Comparison Table Block can be run without needs Otter.

Issue needs both PRs on Otter repo and Sparks repo:

- https://github.com/Codeinwp/sparks-for-woocommerce/pull/36
- https://github.com/Codeinwp/otter-blocks/pull/1035

**Test cases:**
* Case 1: (Old user's block should be migrated) Comparison table blocks added to any page on Otter side should be migrated to Sparks side
	**Instructions:**
	1. Install&Activate stable versions of Neve, Neve Pro, Otter, Otter Pro, Sparks
	2. Enable comparison table from Sparks
	3. Create a page and add the comparison table block (fyi: in stable versions the style is broken, that's a regression that occurred after the CSS lowercase stuff we made a few months ago)
	4. Visit front side and make sure block works well
	5. Install&Activate https://github.com/Codeinwp/sparks-for-woocommerce/pull/36 https://github.com/Codeinwp/otter-blocks/pull/1035 PR builds of Otter, Otter Pro and Sparks
	6. Visit the post/page that contains comparison table block, you'll see comparison table block renders empty (blank content)
	7. Visit block editor of the page/post, here we expect comparison table block is visible and editable, update the page.
	8. From now on, migration should be completed and on the front side comparison table block should be visible again

* Case 2: (Fresh usage of the block) Comparison Table block should work well independently from Otter.
	
	**Instructions:**
	1. Comparison table block should work well without needs Otter
	2. Style regression has been fixed. (color customizations etc. should be work well.)

**Comment by irinelenache** [comment]
@mskapusuz Thanks for the detailed instructions 🤝 

Tested the PRs and here are my findings:

- [ ] If i don't have Otter activated, the fields section in the editor will look like this https://vertis.d.pr/i/0ghich
- [ ] When i try to reorder the fields (with Otter activated) it won't work and there is an error thrown in console https://vertis.d.pr/v/Eu4pVP

Besides these, the migration works fine following your instructions 🚀

**Comment by mskapusuz** [comment]
> @mskapusuz Thanks for the detailed instructions 🤝
> 
> Tested the PRs and here are my findings:
> 
> * [x]  If i don't have Otter activated, the fields section in the editor will look like this https://vertis.d.pr/i/0ghich
> * [x]  When i try to reorder the fields (with Otter activated) it won't work and there is an error thrown in console https://vertis.d.pr/v/Eu4pVP
> 
> Besides these, the migration works fine following your instructions 🚀

@irinelenache Thanks for your test! Nice catches, both of them were fixed and ready for testing again. 🚀

**Comment by irinelenache** [comment]
@mskapusuz Checked again and the issues are fixed now, thank you 🚀

**Comment by mskapusuz** [comment]
@HardeepAsrani I merged the PR on the Sparks side. You can merge the one on Otter's side whenever you want.

I'll make a Sparks release on the same day as Otter's upcoming release. Thanks!
