### ISSUE TITLE
5px margin not applying on the Icon Block

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1038]
### Description:

The Icon margin works with values below and above 5px, **but not with 5px**
Is this an expected behaviour? 
  
[Test Instance](https://app.instawp.io/wordpress-auto-login?site=$2y$10$HUWbFEJAZo5cyRywWqsPLOH2wCl8aDskT5Q67dxh8c9CLUsdTV07O)

https://user-images.githubusercontent.com/52494172/178525222-1486af5e-269f-4024-93ec-e0a0a11cb046.mov

### How to reproduce:

1.
2.
3.

### Technical info
* WordPress version: x.x.x
* Plugin version: x.x.x

**Comment by HardeepAsrani** [comment]
Thanks, fixed it!
