### ISSUE TITLE
don't load otter styles if no otter block or feature is being used on the page

### ISSUE THREAD

**Issue by selul** [Codeinwp/otter-blocks#1040]
Right now if we don't use any block or block feature from Otter we still load some CSS always https://vertis.d.pr/BCWn7y

We need to have some mechanism of detection and dequeue that if nothing from Otter is being used.

**Comment by HardeepAsrani** [comment]
We will enqueued all the CSS in-line as discussed in a previous issue. Do you think it'll be worth putting it then as it'll be few lines of CSS less than a bite at most. As all the CSS in blocks.css is actually non block-specific, so not related to any block but plenty different features which didn't need a file of their own.
