### ISSUE TITLE
Pro notice appear even if Otter Pro is installed

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/otter-blocks#1042]
### Description:
Not a big issue since the notice is dismissible but the notice is displayed even if Otter Pro is installed and it doesn't make that much sense.

<img width="1495" alt="Screenshot 2022-07-14 at 17 49 32" src="https://user-images.githubusercontent.com/9929553/179011599-e973f970-f0ba-41a8-bf76-44b4901ae30b.png">

### How to reproduce:
1. Install Otter + Otter Pro

### Expected behavior:
No notice if pro installed

### Current behavior:
The notice appears even if the pro is enabled

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.7

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu This is next-level upsell technology; we make you buy it again for your friends. 😆 

Will fix it.

**Comment by HardeepAsrani** [comment]
Fixed it, seems like the filter to get license status is fired later than our init function. Thanks for spotting it quickly!

**Comment by MarinescuLucia** [comment]
+1 https://secure.helpscout.net/conversation/1957512151/330564/

This user reported that the notice appears in the editor as well.
