### ISSUE TITLE
Pagination in Posts Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1046]
### Description:
Exploring if having pagination for the Posts Block will be a nice addition. I can imagine two ways of doing it. PHP based where the page will reload and show the pagination based on the query string or we can load a JS file and do it client-side.

Feedback is appreciated if you think the post block that we have should have a pagination option or if you think that's quite outside the scope for a block that it more like a recent posts block.

@Codeinwp/design-team 
### Alternatives:

 
Not to have it and closing this ticket happily ever after.

**Comment by JohnPixle** [comment]
@HardeepAsrani Pagination would not hurt, there might be cases where it'd make sense, sure. Any plans to be able to use the Otter Posts block in the context of FSE btw ? I mean to be able to use it in an archive page. I have a feeling we had talked about that in the past 🤔

**Comment by HardeepAsrani** [comment]
To be fair, I don't have much idea of how that would work. We will need to experiment on FSE handles those; maybe we will have more input on it once we've made the block theme if it'll be possible to use something like the posts block.

**Comment by mghenciu** [comment]
Sorry for the late reply @HardeepAsrani ,
 
as discussed in the meeting, not a lot of plugins/blocks have this option, so it's a nice to have in future - not a priority right now. The main use case here being that it should allow users to creat Custom Blog pages, otherwise - in a section context with posts, it doesn't makes a lot of sense.

From the competition, only Qubely has this feature, and for Kadence Blocks it's a feature request from users: 
![image](https://user-images.githubusercontent.com/52494172/188453221-c6c3492c-d478-451e-8fd7-6bae86194a5b.png)

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani 

What will be the behavior of this? It will be like Live Search with js re-rendering or the traditional way with going to a URL that has`?page=5`? 

I prefer the second method since it will be much easier to implement.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel I do like the traditional way too, but we will need it to work more like Qubely if possible: https://inconclusivehelp.s3-tastewp.com/2023/09/20/16/ - let me know your thoughts.

**Comment by Soare-Robert-Daniel** [comment]
ℹ️ The provided link does not work, so I installed the plugin locally.

@HardeepAsrani I see that they use the traditional way

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/c36f205c-44bb-4e05-8c57-d84a94a6b01e)

By working, were you mainly referring to how it looks? Do they have something special?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yea, I was referring to this, the way they use pretty permalinks.
