### ISSUE TITLE
add hCaptcha Integration

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1053]
### Description:

A user wants to use hcaptcha, with their WordPress plugin, on a contact form built with Otter.
This is the plugin - https://wordpress.org/plugins/hcaptcha-for-forms-and-more
### Alternatives:

 We already have recaptcha integration.

**Comment by HardeepAsrani** [comment]
Not sure, we need this. We can just keep this open and see if more people ask for this.

**Comment by kushh23** [comment]
+1: https://wordpress.org/support/topic/adding-hcaptcha/

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2013907781/337523/
