### ISSUE TITLE
Add AggregateRating to schema.org of Review Block

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#1057]
### Description:
Currently, our schema.org that is added to review block looks like this:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/36594177/181025203-1bfbb574-48a5-4628-a16b-536158a09628.png">

So we don't have aggregateRating in Schema.org defined with the aggregate Rating value. Correct me if I'm wrong but without having aggregateRating defined, you cannot have Rich Snippets/Rich results on search engine.

Even though it's an optional one when analyzing the page via rich results tool - https://search.google.com/test/rich-results it's mandatory to have stars on search results, so my suggestion is to add it.

One important note about this is that there could be only one aggregateRating on a single page so having multiple will cause issues so we shouldn't add multiple aggregateRatings and if there are multiple review blocks added on a single product pages then we shouldn't render it (unless those blocks are for one product but we wouldn't know that).

We had aggregateRating being added with WP Product review plugin

### Alternatives:
Do nothing
 
Client asked about optional fields missing here - https://secure.helpscout.net/conversation/1957519462/330566
I see that another users asked about it here too - https://wordpress.org/support/topic/warnings-in-search-console/

**Comment by HardeepAsrani** [comment]
Thanks I didn't know about this @vytisbulkevicius

**Comment by HardeepAsrani** [comment]
Added, it will be out in the next version!
