### ISSUE TITLE
Animated elements in viewport flash before animating

### ISSUE THREAD

**Issue by rinart73** [Codeinwp/otter-blocks#1060]
### Description:
If an element with animation is immediately visible (in viewport) on page load, the element is fully visible for a brief moment and then it starts playing animation. This results in a visual "flash" for this element.

I understand that you could say "just don't add animation to elements that are immediately visible". But it's not that simple. Firstly, which elements are visible depends on screen size and mode (portrait/landscape). Secondly, it just may be a design choice to immediately show animation.

### How to reproduce:
1. Add any animation (Fade In for example) to an element that will be visible immediately
2. Load/reload a page with the element. Simulating slow network speed helps to observe the issue

### Expected behaviour:
Elements should be hidden until animation starts

### Current behaviour:
Elements are fully visible until animation starts

### Reference:
Here I refresh the page: https://drive.google.com/file/d/13i8jEGqEgmNix43emsrqVyd_66aI5stu/view?usp=sharing

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.8

From what I see it't because of the animation script. It's in the page footer so it takes a while for it to load and during that time elements are visible. Obviously moving it to the start of the page is not a solution.
Maybe instead of applying `hidden-animated` class via script, reverse the behaviour? Have all `animated` elements `visibility: hidden` by-default and then apply `visible-animated` via script?

**Comment by HardeepAsrani** [comment]
Thank you, @rinart73 for the report. We will look into it.

**Comment by HardeepAsrani** [comment]
If anyone is thinking of doing this, let's wait for this to get merged: https://github.com/Codeinwp/otter-blocks/pull/1059

**Comment by rinart73** [comment]
Yeah, with my suggestion disabled JavaScript would cause invisible images. You could add tiny JavaScript into the `head` tag that would add `animated-js` to the `html` or `body` tag. That way your CSS classes would look similar to this:
```js
.animated-js .animated {
  visibility: hidden;
}
```
