### ISSUE TITLE
One of the latest updates broke 'content' property in the custom CSS

### ISSUE THREAD

**Issue by rinart73** [Codeinwp/otter-blocks#1061]
### Description:
Property `content: ''` that is commonly used for `:before` and `:after` pseudo-elements now gets escaped, turns into invalid `content:\'\'` and as a result the whole pseudo-element doesn't work.

### How to reproduce:
1. Add custom css that uses `content: ''` property declaration.
2. Observe the resulting page

### Expected behaviour:
Pseudo-elements work as expected.

### Current behaviour:
Pseudo-elements don't work because `content:\'\'` is invalid

### Reference:
[This is how it looked before update and how it currently looks in the editor.](https://i.ibb.co/MZJ3hcL/otter-pseudo-elements-1.png)
[This is how it looks for a visitor after update. ](https://i.ibb.co/fVWS7DL/otter-pseudo-elements-2.png)

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.9

**Comment by HardeepAsrani** [comment]
Can you check @Soare-Robert-Daniel if this was due to changes done while adding the validation?

Thanks @rinart73, it'll be fixed and released soon.

**Comment by HardeepAsrani** [comment]
For now, you can fix this by disabling the CSS extension in Otter and installing a previous version of Blocks CSS https://wordpress.org/plugins/blocks-css/

It's the same as Otter's CSS extension just packaged as a separate plugin, so you can go back to the previous version and hopefully that should do the trick.

Let me know it works thanks again for the report @rinart73!

**Comment by rinart73** [comment]
The website that I'm using it on is currently in development, so I'm not suffering from the bug much).
I disabled the CSS feature in the "Otter" plugin, installed Block CSS version 2.0.8 and pressed the "Regenerate styles" button. This fixed the issue.
After that I uninstalled the plugin, re-enabled the feature and pressed "Regenerate styles" button again, the issue returned. So yes, it's related to the changes made in 2.0.9

**Comment by Soare-Robert-Daniel** [comment]
@rinart73 thank you for the feedback. 

I made a video to test the issue and did not find anything suspicious. If I am missing something, don't hesitate to point it out.

https://user-images.githubusercontent.com/17597852/182087815-13873628-4335-48e1-bd3f-0ed69e40f45f.mp4

If you can provide more details about the problem, like a code sample that you use, or a test instance would be awesome.

**Comment by HardeepAsrani** [comment]
<img width="522" alt="Screenshot 2022-08-01 at 7 21 31 PM" src="https://user-images.githubusercontent.com/2649903/182163180-ebe0cbba-df81-48ba-8f73-586fbbb1d109.png">

Might be related, I saw a user having the same issue with Blocks CSS where font-family is not working properly. @Soare-Robert-Daniel

**Comment by rinart73** [comment]
I added Wordpress Group block and inside of it placed paragraph block:
```html
<div class="wp-container-2 wp-block-group ticss-9ca7b0b2"><div class="wp-block-group__inner-container">
<p>Text</p>
</div></div>
```
My styles for the group block are:
```css
selector:before {
  content: "Before";
  font-weight: bold;
}
```
However they result in:
```html
<style id='otter-post-v2-946-1659395441.css-inline-css'>
.ticss-9ca7b0b2:before{content:\"Before\";font-weight:700}
</style>
```

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel It's definitely with properties with quotes being escaped so we can see where we made the change and ensure we don't escape them.

**Comment by rinart73** [comment]
Apparently when I press the "Regenerate" styles button custom CSS with quotes actually gets fixed and starts working normally for one page load. After that it stops working again. Maybe it's something related to the custom CSS cache?

**Comment by rinart73** [comment]
Ok I think I found the source of the issue:
https://github.com/Codeinwp/otter-blocks/blob/466e2126f77c521e05b736588ea9db21887abf1f/inc/css/class-css-handler.php#L238
[wp_filter_nohtml_kses](https://developer.wordpress.org/reference/functions/wp_filter_nohtml_kses/) strip and adds slashes. Doesn't work well with CSS.

**Comment by HardeepAsrani** [comment]
Umm, I think I might know why and if that's the case, it's thanks to the Core. I'll take a look @Soare-Robert-Daniel

**Comment by HardeepAsrani** [comment]
This should also be fixed here: https://github.com/Codeinwp/otter-blocks/pull/1059 - it's just what was happening when we were using core's function to render CSS inline, in this we changed back to using our own as we wanted to load the CSS in the footer, not the head.

**Comment by rinart73** [comment]
Um.. loading CSS in the footer (like Wordpress core does with block inline styles) actually causes Cumulative Layout Shift for elements.

**Comment by selul** [comment]
@HardeepAsrani, I agree with @rinart73, I don't think it's a good solution to load everything in the footer; we can do some testing to see how the CLS is behaving for some starter sites or sample data.

**Comment by HardeepAsrani** [comment]
@HardeepAsrani We don't load everything in Footer, we just load our Custom CSS (this + the one that we generated from our blocks) in Footer. But yes, we can do some testing and decide on this better.
