### ISSUE TITLE
Otter 2.0.9 adds inline styles to all pages even though I'm not using them

### ISSUE THREAD

**Issue by rinart73** [Codeinwp/otter-blocks#1062]
### Description:
Otter now adds the following style tag to all pages:
```html
<style id="otter-blocks-inline-css">
.otter-masonry .blocks-gallery-grid .blocks-gallery-item img{width:100%}.wp-block-themeisle-blocks-woo-comparison .nv-ct-layout-row tbody tr td:first-child{border-left:1px solid var(--border-color)}.o-is-sticky{position:fixed;z-index:9999}.o-woocommerce-builder .woocommerce-product-gallery{width:100%!important}
.fab.wp-block-navigation-item,.far.wp-block-navigation-item,.fas.wp-block-navigation-item{-moz-osx-font-smoothing:inherit;-webkit-font-smoothing:inherit;font-weight:inherit}.fab.wp-block-navigation-item:before,.far.wp-block-navigation-item:before,.fas.wp-block-navigation-item:before{font-family:Font Awesome\ 5 Free;margin-right:5px}.fab.wp-block-navigation-item:before,.far.wp-block-navigation-item:before{font-weight:400;padding-right:5px}.fas.wp-block-navigation-item:before{font-weight:900;padding-right:5px}.fab.wp-block-navigation-item:before{font-family:Font Awesome\ 5 Brands}
</style>
```

### How to reproduce:
1. Create a page/post. Don't add Otter blocks.
2. Take a look at the page source code

### Expected behaviour:
Otter block styles shouldn't be added to pages unless that page uses Otter blocks.

### Current behaviour:
A portion of Otter block styles always gets added to pages.

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.9

**Comment by HardeepAsrani** [comment]
Hey @rinart73,

We recently converted all of our stylesheets to load inline if the space permits. These styles were always loaded, but before this version, they were loaded from a CSS file instead of being inline.

Putting them inline is better for page performance. These are the styles that we can't really detect if they're being used or not so we have to load them everywhere.

**Comment by HardeepAsrani** [comment]
Just to add more here: I have been doing some work on it and we have removed most of the CSS in the PR but few of it will appear in a couple of releases until we can remove all of it. Thank you for all the suggestions and reports so far!

**Comment by HardeepAsrani** [comment]
It should be addressed in https://github.com/Codeinwp/otter-blocks/pull/1059 - thanks!
