### ISSUE TITLE
Add Option to Remove Schema.ORG from the Product Review All Together

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/otter-blocks#1072]
### Description:
Currently, there is no option to remove the entire schema generated by the Product Review block which might come in handy in situations where not all fields are completed in the plugin since Google starts throwing Warnings in that case.

At the moment the only way to achieve this is to remove [this](https://github.com/Codeinwp/otter-blocks/blob/master/inc/render/class-review-block.php#L31-L38) code from the plugin.

However, maybe we can do it as Ultimate Blocks does it:
![Screenshot 2022-08-02 at 09 28 23](https://user-images.githubusercontent.com/82535909/182307087-52584397-4d7c-4761-9969-3fdc43d5a852.png)

### Alternatives:
Create a filter or hook that can take out that code mentioned above.

**Comment by HardeepAsrani** [comment]
I'm guessing we can do it with an option instead of per block.
