### ISSUE TITLE
Section Block padding inheritance between Devices

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1077]
### How to reproduce:

1. Create a fresh instance with Otter
2. Make a new Section
3. Try to set the padding like this: **Desktop**: 80px 20px 80px 20px |  **Tablet:** 40px 20px 40px 20px | **Mobile:**   20px 20px 20px
4. Switch between devices and see if those changes are saved on Desktop

### Expected behaviour:
Users should be able to have different padding between Devices, and inheritance shouldn't affect this, when some values are present.

### Current behaviour:
https://user-images.githubusercontent.com/52494172/182419205-5ffac23c-825f-42d9-94c2-aea0d3d8ca06.mov

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.9

**Comment by JohnPixle** [comment]
Hey, @mghenciu I came here to submit the same issue, literally freaked out today with it 🙃 . 
Keep in mind that the same thing happens with column paddings as well, I dont know if @Soare-Robert-Daniel's PR fixes the columns issue as well.

**Comment by JohnPixle** [comment]
Just to add that in my opinion this bug is worth pushing a patch as soon as we fix this issue internally. It's very serious for user sites and very hard for them to work around it.
