### ISSUE TITLE
Alignment Control in Button Group not appearing in FSE

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1078]
### Description:

In FSE, you can't see the Alignment controls in Button Group

### How to reproduce:

1. Add Button Group in FSE

### Expected behaviour:
It should appear.
### Current behaviour:
Not appearing.
### Reference:

<img width="294" alt="Screenshot 2022-08-02 at 11 58 13 PM" src="https://user-images.githubusercontent.com/2649903/182447259-5e739827-aeea-4574-8095-25c18b5ea4d7.png">

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.9

**Comment by Soare-Robert-Daniel** [comment]
So `BlockAlignmentToolbar` does not render on FSE. I think this is a bug from the Core.

Latest Posts use this in Controls; not even for them is rendering in FSE.

Post:

![image](https://user-images.githubusercontent.com/17597852/182620742-20e70434-387b-4c14-8aa4-35143dec7976.png)


FSE:

![image](https://user-images.githubusercontent.com/17597852/182620650-7592bc37-80d4-4a12-b110-6bc57aa7de2f.png)

---

We should switch back to SelectControl until this is fixed.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Sure, we can switch back to a Button Group with icons then instead of a select field.
