### ISSUE TITLE
Accommodate "visibility conditions" where expected

### ISSUE THREAD

**Issue by mackaaij** [Codeinwp/otter-blocks#1080]
### Description:
Would be great if the [The Visibility Conditions Feature](https://docs.themeisle.com/article/1552-the-visibility-conditions-feature-otter-features-library) would support WordPress Menus as well.

I [filed this issue for Otter - Page Builder Blocks & Extensions for Gutenberg](https://wordpress.org/support/topic/extend-visibility-conditions-to-menus/) but Hardeep Asrani explained the scope of the block is limited to the Block Editor.

Technically, that probably makes sense. But functionally, it would be great if ThemeIsle could somehow accommodate "visibility conditions" where expected in WordPress.

### Alternatives:
I installed [User Menus](https://nl.wordpress.org/plugins/user-menus/) a separate plugin for this. Hardeep Asrani told me you use [If Menu](https://wordpress.org/plugins/if-menu/).

**Comment by selul** [comment]
Hey @mackaaij,

Thanks for your suggestion. Just to confirm, you are not talking about menu blocks but the standard navigation menus in WordaPress?

**Comment by selul** [comment]
Thanks for clarification ! I was curious to know where do you build those menus, in the standard menu dashboard, i.e https://codex.wordpress.org/WordPress_Menu_User_Guide or the Block Editor ( Gutenberg )

**Comment by mackaaij** [comment]
The standard menu dashboard, I’m not aware of a new way via Gutenberg. I’m currently switching sites over to theme Neve. I don’t care how to build the menu’s, for me they’re just a list of links on a specific location of a webpage of which I can set title, link and visibility. So now you’re going to tell me this is already possible? :) 👍🏻

**Comment by selul** [comment]
Oh, understand now. Unfortunately no, you can't use Visibility conditions to control the standard menus as they are built for blocks only. 

If you build your header in Gutenberg yes, you can build menus using the Navigation Block which has the visibility conditions.

**Comment by mackaaij** [comment]
I know I cannot use the Visibility conditions to control the standard menus, which is why I first [filed an issue for Otter - Page Builder Blocks & Extensions for Gutenberg](https://wordpress.org/support/topic/extend-visibility-conditions-to-menus/). Hardeep Asrani explained the scope of the block is limited to the Block Editor, thus I filed this issue at GitHub to hopefully get a solution for ThemeIsle to accommodate "visibility conditions" where expected in WordPress.

Using the Navigation Block sounds like a feasible option. Can you help me with "build your header in Gutenberg" using ThemeIsle theme Neve? I tried to find out how to do this, for instance by following [Mastering The New WordPress Menu System and Gutenberg Navigation Block](https://www.pootlepress.com/2022/01/mastering-the-new-wordpress-menu-system-and-gutenberg-navigation-block/), but this doesn't seem to work as Neve doesn't support "FSE" (Full Site Editing) yet?

**Comment by selul** [comment]
@mackaaij indeed, you are right. You can build your header with Neve's Custom Layout feature available in the Premium version or you could try or minimal FSE theme called Raft https://themeisle.com/themes/raft.

I hope this helps.

**Comment by mackaaij** [comment]
I've just purchased Neve Pro so I'm not looking for another theme :) I did find [Custom Layouts Module Documentation](https://docs.themeisle.com/article/1062-custom-layouts-module) plus [The Custom Layout Component - Neve Header / Footer Builder (PRO)](https://docs.themeisle.com/article/1300-custom-layout-pro).

I've built a Custom Layout as a lay-out for Header to function as a menu. I added the Navigation block and was able to set the visible per menu item. So far, so good.

I could only get the menu tiny top left, instead of having a site logo ("Logo & site identity") left aligned and the menu on the right, followed by WooCommerce My Account ("My Account"). It looks like these menu components and lay-out options are not available in Custom Layout?

**Comment by selul** [comment]
Hi @mackaaij,

Yes, it's a bit more complicated to build those with Custom Layouts only, you will need to design them from the scratch using the Block editor.

Another solution is to design the menu only in Block Editor as Custom Layout and set as type individual and use that in Header builder inside customizer.

On another note we try to keep this place for feature requests and bugs, I would encourage you to get in touch with our support team to get faster answers and a more detailed explanation.

I hope you understand.

**Comment by mackaaij** [comment]
Sure, I'll look into what you sent me and will contact Support for any extra help.

I was not aware WordPress menu is being deprecated and I guess Hardeep Asrani wasn't aware either when he pointed me to this place to file a feature request.

**Comment by mackaaij** [comment]
Sure, I'll look into what you sent me and will contact Support for any extra help.

I was not aware WordPress menu is being deprecated and I guess Hardeep Asrani wasn't aware either when he pointed me to this place to file a feature request.
