### ISSUE TITLE
Icon List block not working as expected when adding new items

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1083]
### Description:

When you add an Icon List and choose a default icon which is a Font Awesome brand icon, and then enter press enter, the other list item inherits the icon but not the fab class.

https://user-images.githubusercontent.com/52494172/182655622-7dfe4bb8-fad8-4158-a726-f7cc8a07d0c8.mov

### How to reproduce:

1.
2.
3.

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.9

**Comment by HardeepAsrani** [comment]
@mghenciu Works just fine for me. I tried on localhost with development and tastewp with the wporg build, and in both places it works fine.

Can you let me know a few things:

- Which browser you used?
- Which theme you used?
- Were there any plugins involved, especially any other plugins related to the editor?
- Can you pass the login creds for a test env?

**Comment by mghenciu** [comment]
Chrome
Neve installed
Just a basic InstaWP instance, but also happens on demosites.io
Sent the details on Slack

**Comment by mghenciu** [comment]
Did more testing @HardeepAsrani , and apparently it happens only when the Text is pasted.

By following the repro steps in the video, but when it comes to inserting the Text (_**First item**_ ), make sure that is pasted from the Clipboard - the issue will be visible.

**Comment by HardeepAsrani** [comment]
@irinelenache can you help me here to see if you can reproduce this issue? So far I can't. I've tried on both FF and Chrome.

**Comment by HardeepAsrani** [comment]
@irinelenache Nevermind, I can see why this is happening. I was able to reproduce it.
