### ISSUE TITLE
Page is blocking when inserting a block in Query Loop

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/otter-blocks#1089]
### Description:

Page is breaking if you insert an Otter block to Query Loop.

### How to reproduce:

1. Insert a Query Loop
2. Add an Otter block to it
3.

### Expected behaviour:

Otter blocks should behave normally.

### Current behaviour:

Otter blocks are breaking the page.

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.9

**Comment by HardeepAsrani** [comment]
@irinelenache This PR fixes the issues you mentioned in https://github.com/Codeinwp/otter-blocks/pull/1023 - I've also merged it to that PR, so you can check that straight to make sure both of the issues were fixed.
