### ISSUE TITLE
Gradient control shows the normal colors too

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1093]
### Description:
In the background settings, where I can add the gradient / image / color, the gradient tab contains normal colors too, but they can't be used.
### How to reproduce:
1. Insert section block.
2. Go to style tab > background settings.
3. Pick the gradient style.

### Expected behaviour:
It only displays gradient options.
### Current behaviour:
It displays normal colors too.
### Reference:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/86592992/183115123-d8557aaa-bba3-46db-aa82-a33ef39931f9.png">

### Technical info
* WordPress version: latest
* Plugin version: latest

**Comment by HardeepAsrani** [comment]
Which theme were you using @AndreeaCristinaRadacina?

**Comment by AndreeaCristinaRadacina** [comment]
In this case was Hestia Pro, but I noticed this with Neve too
