### ISSUE TITLE
Align Countdown separators to the Numbers and not to the Container - when using the Plan Style

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1109]
### Description:

Maybe in a boxed layout, it makes sense to align the separators vertically, based on the containers (for example I want to built this):
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/52494172/183924707-4f68c012-dcff-4960-8556-8776f6d3a398.png">
Users should be able to create something like this: 
<img width="923" alt="image" src="https://user-images.githubusercontent.com/52494172/183925939-8ecf9c47-da35-4e21-8d5c-fbe696665ff4.png">

for example in a **Plain Context**, the separators should be aligned to the numbers:
<img width="1384" alt="Screenshot 2022-08-10 at 17 16 38" src="https://user-images.githubusercontent.com/52494172/183924859-fb5cf734-0313-4994-9b5f-20ef0ce6565d.png">

<img width="1303" alt="Screenshot 2022-08-10 at 17 29 30" src="https://user-images.githubusercontent.com/52494172/183927592-6a3d2ce0-5911-45b2-a01f-b020bb701551.png">

Check Kadence Blocks for reference.
Additionally, **Text Transform options for the Labels would be nice**, for example to have al the labels in Uppercase.

### Alternatives:

 Do nothing

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu We had some suggestions from @JohnPixle about the position of the separator to be centered: https://github.com/Codeinwp/otter-blocks/pull/1029#issuecomment-1180440683

Did I misinterpret the suggestion?

**Comment by mghenciu** [comment]
The whole idea is making things look centered/visually right, for both Style we have.
So in the case that John mentioned, where are are talking about a Boxed Layout, probably it makes sense to align the Separators, **vertically to the Boxes.**

Now **in a Plain Style, I think it would make more sense to align them to the Numbers**, not to the Boxes.
So even in a case with Big Labels (low probability someone will use this), it will still look better, imo:
![image](https://user-images.githubusercontent.com/52494172/184105474-9c559ae6-571f-4455-876c-49a272c898ac.png)

Here [is the page with Countdowns from Kadence](http://misha2.stefancoti.com/index.php/countdown/).
___
Few examples from google:

![image](https://user-images.githubusercontent.com/52494172/184105936-25a6cd39-0d7e-4332-b125-02a8d07b3193.png)
![image](https://user-images.githubusercontent.com/52494172/184106012-f4414ca4-50d9-46c0-a837-4f8640b956d4.png)
![image](https://user-images.githubusercontent.com/52494172/184106182-07a67915-3e26-42e9-9830-bed989cd76d8.png)
![image](https://user-images.githubusercontent.com/52494172/184106456-2d51d6fa-256d-46ad-905e-1bcf2240dd98.png)

Let me know if this makes more sense now.
