### ISSUE TITLE
Section block with Plugin Card dimension problem

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1110]
### Description:
If I use the section block and add plugin cards, the section block does not cover all the section columns if they are greater than expected.
### How to reproduce:
1. Add section block
2. Pick the 3 columns layout.
3. Insert 3 plugin cards

### Expected behaviour:
The parent section will include all the 3 columns.
### Current behaviour:
The parent section is not big enough.
### Reference:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/183945938-69a641ed-406e-41d0-b089-c6c535495469.png">

### Technical info
* WordPress version: latest
* Plugin version: latest

**Comment by Soare-Robert-Daniel** [comment]
The Plugin has a fixed width. I do not know if they are supposed to be used in sections since they do not squeeze. @HardeepAsrani

**Comment by HardeepAsrani** [comment]
I'll leave this for @Codeinwp/design-team to decide. The same will happen when the plugin card is used inside a Column.

**Comment by HardeepAsrani** [comment]
Makes sense, thanks @JohnPixle
