### ISSUE TITLE
Warning undefined variable

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/otter-blocks#1111]
### Description:

OTTER-BUG

Warning: Undefined variable $content in /home/httpd/vhosts/mydomain/htpdocs/wp-content/plugins/otter-blocks/inc/class-base-css.php on line 272

using Otter Pro 2.0.10 w/ PHP 8.1.9

### Reference:

Reported on https://www.facebook.com/groups/648646435537266/permalink/1595496397518927/

### Technical info
* WordPress version: x.x.x
* Plugin version: 2.0.10

**Comment by HardeepAsrani** [comment]
Thanks @cristian-ungureanu, we're fixed it and put it in QA for release!
