### ISSUE TITLE
Discontinuing Author Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1115]
### Description:

Now Core has an Author Block, which works well and does everything. our block can do + a lot more. I think we should discontinue Author Block (without breaking the existing sites, obviously).

It's not that we can't do what Core's block is doing, but I don't think it's worth putting much time in an Author block. When it didn't exist, we gave users a solution. Now that they've better one they can use that instead.

Plus, we also have Dynamic Values that we can use to make Patterns for Author Block if we ever want to.

Thoughts?

### Alternatives:

 
We continue as usual.

**Comment by mghenciu** [comment]
I agree with you @HardeepAsrani , that usually it's best to keep only blocks that make sense and **that are not already covered by Core**.

___

However with the Author Box this is partially true, meaning that in Figma we have more features that are not covered in Core. And the current author block from Otter, has no options at all, except Custom CSS.

**A few examples of enhancements we thought about in [Figma](https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=1147%3A17344)**, are Styles (Plain, Card, Border), Social Icons, Image position, Content alignment, Shadow options.

![image](https://user-images.githubusercontent.com/52494172/184924744-c603d323-7763-433a-9ffe-1b0e4fe05675.png)

So while **I agree with you that this can be done using the Dynamic Values**, **I think for beginner-medior users it's much easier to just add the block**, make 2 click for selecting the Style, and that's it. While building it from scratch with Dynamic Values, will require more effort.

**Comment by JohnPixle** [comment]
I would agree with what @mghenciu said BUT we can do the exact same thing with patterns, and drop the widget no?

Essentially if we provide some "Author box" patterns made with 

- dynamic image
- author bio
- social icons

we should be good. And of course, all different styles of the author box would come as patterns, and not _Style Variations_ in the sidebar. In this case, we should make some tests and see how such patterns with dynamic otter elements would be previewed in the pattern inserter. 

Same approach we can do for the Service Boxes as well, pricing tables etc. 

What's your thoughts?

**Comment by HardeepAsrani** [comment]
@JohnPixle Yea, in the coming quarter, we will put some focus on Patterns. And even if the pattern preview doesn't show the dynamic values nicely, we always have the option to show good defaults there.

@mghenciu As we had talked about in that ticket with Ionut, we decided to keep it very simple and just add patterns. In the end, an Author Block isn't something that users will install Otter for. And to make things better, to give users something nice to start with, we can always add some styles to Core's author block too.

My whole POV here is:

- Core has a better block than we do.
- We can spend the time we would've spent on Author Block on something else that gives us an edge, like Patterns, new features, or existing blocks.

One less Block to maintain for us. 😄

**Comment by JohnPixle** [comment]
> And even if the pattern preview doesn't show the dynamic values nicely, we always have the option to show good defaults there.

This sounds good, got it.

Overall, with patterns it is a good opportunity to try out a more atomic approach which is simpler and low-maintenance. 

A service box block for example is an icon block, two Text instances and a button. Following the same approach for the blocks that is possible to re-create with patterns, we will end up with a manage-able setup that relies more on layout and design instead of css, code and settings.

Generateblocks is doing a very good work in this context, with just a limited collection of atomic blocks: https://generateblocks.com/

If you think about it, it's 100% applicable.

**Comment by mghenciu** [comment]
ok, then dropping the Author Block makes sense - if we are going with a **Pattern approach** or/and **extending the Core one**. That's because in terms of Style, even the Core one has more potential.
___
I agree with arguments you've mentioned, my only point here is to keep in mind the more common users (beginners, basic editor knowledge), as Dynamic Content is awesome, but it requires some knowledge to make it work (so more for medior, freelancers, experienced users).

**Comment by mghenciu** [comment]
Interesting approach on Generate Blocks, @JohnPixle .
I see that they have some kind of accounts. Does this means they are going for a community based approach?
<img width="1726" alt="Screenshot 2022-08-17 at 11 07 43" src="https://user-images.githubusercontent.com/52494172/185068377-d5e74c86-f675-4b5a-aa3c-4cd355fae564.png">

That would be even more interesting.

**Comment by JohnPixle** [comment]
@mghenciu Yeah, about GenerateBlocks, I don't think it's a community based thing, must be some contractors or collaborators publishing in the library. Will take a deeper look but it must not be 100% open to community, It would be an interesting approach though, no doubt.

But overall I really like how they offer patterns which are based on just a few atomic blocks, and they have a very good reputation. I have personally

**Comment by HardeepAsrani** [comment]
Closing https://github.com/Codeinwp/otter-blocks/issues/788 in favor of this ticket.

**Comment by HardeepAsrani** [comment]
With this: https://github.com/Codeinwp/otter-blocks/pull/1120

The block will no longer appear in Inserter for uses on WP 5.9 or above. If you're using 5.8, it will still appear in the Inserter.

We won't be making any changes to this block now that it has been retired, apart from fixing error-causing bugs.
