### ISSUE TITLE
Slider Block not working inside Section

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1125]
### Description:

JSON for the page in the video >> 
[blocks-export.json.zip](https://github.com/Codeinwp/otter-blocks/files/9396429/blocks-export.json.zip)

https://user-images.githubusercontent.com/52494172/185983712-08605d8b-8738-4fa2-b9bb-57bb7711ec00.mov

### How to reproduce:

1. Create a fresh instance
2. Install Otter
3. Import the JSON above on a page 

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.11

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel The refresh issue seems to be happening only in Full Side Editing themes, works fine in Neve. Maybe worth checking if the issue is with Slider not being initialized.
