### ISSUE TITLE
What happens when the countdown ends?

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1136]
### Description:

What do we do when the countdown ends? There can be few ways this can go:

- Nothing.
- User can be redirected to some place.
- The countdown block disappears.
- We can make another block appear that has a particular class that stays invisible until the countdown is ongoing.

It will be a Pro feature.

What do you think @mghenciu @JohnPixle

**Comment by mghenciu** [comment]
Sounds like solid ideas, Hardeep, especially the 4th one.
This are from Kadence:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/52494172/186630972-2d5ee8e3-e07d-44d3-ba8c-1664153f96ab.png">

**Comment by HardeepAsrani** [comment]
@mghenciu Do you have any idea (or video) on how the Replace with Content works in Kadence? As in what is their workflow for that?

**Comment by JohnPixle** [comment]
Nice ideas. I think we could just use a class for that. We could perhaps use this logic:

- apply a class e.g. .`timer-off` on a group or section that contains the content that you want to appear when the timer has ended.
- When the timer ends, hide the countdown block and display the content.

Other option would be to have custom input fields in the countdown block where the user adds a custom message to be displayed when timer ends, within the same block.

**Comment by HardeepAsrani** [comment]
I like the idea of a timer-off class. We will make something unique in case someone has multiple countdowns on a page.

@JohnPixle Here's how Kadence is doing it: https://youtu.be/zOVoCx3a6E4?t=343 - using a Container, similar to how the Flip block works.

I like their idea, too, but I think doing it with a class is easier, just that their idea gives a better backend page. Both ideas have their advantages and disadvantages.

**Comment by bderaguts** [comment]
How about doing this like pop-ups are done. Give a button that opens up a full size modal. Whatever is entered into that modal is given the class without the user having to do that, and replaces the Countdown timer when the "Replace with Content" option is selected.

**Comment by HardeepAsrani** [comment]
@bderaguts As discussed above, it's a similar approach that Kadence is using, but the issue with this is that you can only have the items appear instead of the Countdown but not elsewhere on the page.

We can make adding the class easier, ie also allowing user to just use Visibility Condition option and choose to show/hide a particular section based on the Countdown.
