### ISSUE TITLE
Evergreen Countdown Feature

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1138]
### Description:

A repeating countdown widget is a timer that displays the amount of time a particular user has to get the offer. The user can define how long the countdown will be there for after the user's first visit. This can be stored in local cache.

What I need more help is how we handle the end of the countdown for the evergreen countdown. Do we have a class to add to parent block that hides the entire section?

It will be a Pro feature.

@Codeinwp/design-team

**Comment by selul** [comment]
One is on complete, it can hide some area which the user can target via some class or id.

**Comment by JohnPixle** [comment]
@HardeepAsrani I like the idea, and it sounds like a feature suited for the PRO version, especially if we blend in the  #1136 functionality. The end for the evergreen countdown can be the same as the normal countdown, no?

> - Nothing happens (zero time).
> - User can be redirected to some place.
> - The countdown block disappears.
> - We can make another block appear that has a particular class

So essentially the admin has to choose what type of countdown it is (normal or evergreen) and then have the same set of options for when the timer ends (regardless of the type of countdown).

**Comment by Soare-Robert-Daniel** [comment]
> We can make another block appear that has a particular class

For this case, we can make something similar to sticky.

You set the countdown block to make other blocks to appears.

Then, when you go to another block, on the Inspector, you will find a panel name `Countdown Trigger`.

You will have a button that says `Link` (or something similar) and another button that will select when you click the targeted Countdown to see it.

If you press `Link`, a custom CSS class like `o-countdown-link-{ countdown block ID }` will be attached.

In the front end, the block will be invisible until is triggered by a countdown.

@HardeepAsrani, what do you think?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel That's just making things too complex. When you select the option to show some blocks in Countdown, it will give you a unique className (based on id of the Countdown) that the users can just add to the class itself.

Better than overcomplicating things, users might not like to see such option in all the blocks.
