### ISSUE TITLE
Posts block doesn't display all categories of a post

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1148]
### Description:

If a post has multiple categories assigned to it, only the first one will be displayed for that post in the Posts block.

(start: added by Hardeep)
Things to do:
- Categories should be a link.
- Allow multiple categories. 
(end: added by Hardeep)

### How to reproduce:

1. Add multiple categories to a post
2. Add the Posts block on a page
3. Observe that only the first category of that post is displayed

### Expected behaviour:
All the categories will be displayed.

### Current behaviour:
Only the first category is displayed.

### Reference:

The post on the blog page:
![Capture2](https://user-images.githubusercontent.com/86592341/187530394-7b07b2ba-5d74-4b73-a39e-7782f51c9662.PNG)

The post in the Posts block (only Standard category appears):
![Capture1](https://user-images.githubusercontent.com/86592341/187530473-ef7071c7-40de-4b58-ac8b-bf3e1fa62c75.PNG)

Reported [here](https://secure.helpscout.net/conversation/1994425766/335062/).

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.13

**Comment by HardeepAsrani** [comment]
@MarinescuLucia Yea, that's a design decision and I don't think that really needs to be changed. Let me know what you all think @mghenciu @JohnPixle

**Comment by mghenciu** [comment]
> @MarinescuLucia Yea, that's a design decision and I don't think that really needs to be changed. Let me know what you all think @mghenciu @JohnPixle

What is assumption behind this, Hardeep? that we don't need to change this.

It looks to be a common UIX pattern to have multiple categories displayed ([example here](http://misha2.stefancoti.com/index.php/post/) ); even with the Core Query Loop. My only concern would be just if we should have a limit of how many to render, maybe limit it to just one line.
Also it would make sense to add links on them, so when a user clicks on a category - it takes him to the Category Page.

**Comment by HardeepAsrani** [comment]
@mghenciu With various posts having a different number of categories, the design can look weird in many cases, with sometimes categories taking more than one line and so on.

Something similar to: https://elementor.com/marketing/wp-content/uploads/sites/14/2022/05/image-4.png

**Comment by JohnPixle** [comment]
That's a tricky one. Both suggestions make sense. At this point I think it would be better to only show the primary category, and keep things more controlled in the context of UI. 

BUT if it's not too much trouble, we can have a toggle in the block settings that says "display all categories". So by default we would show only one category, and per user selection we can allow them to show all categories. 

I agree about the category being an active link to the category page. Let me know your thoughts.

**Comment by HardeepAsrani** [comment]
<img width="278" alt="Screenshot 2022-09-03 at 9 33 25 AM" src="https://user-images.githubusercontent.com/2649903/188255166-7eee4d11-7afd-4043-be90-0ad7d07b3766.png">

Just a small item:

Should we give this option in both places (Top Category area & Meta Area) or just once? Also, if it's in both places, should it sync or both should have different controls? @JohnPixle @mghenciu

**Comment by JohnPixle** [comment]
> Also, if it's in both places, should it sync or both should have different controls?

@HardeepAsrani In most cases, I'd expect the users to choose to display the category either on the top OR in the meta, but not both. So they will most probably choose disable one or the other.

I think it's better for both of them to be synced instead of having different controls.
