### ISSUE TITLE
Add Hyperlink to the Category Page when Displaying Category in the Posts Block

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/otter-blocks#1149]
### Description:
At the moment, if you choose to use the Posts Block and also show the category for each post when the meta is shown it will only appear as a Span (text) however, one user suggested that it would make more sense (navigation-wise) if that meta is a hyperlink redirecting to the category page rather than just text and I agree.

I think we can just replace that span with a link as a simple implementation but I'm not sure if that's the way to go.

If we want to offer alternatives, we can also add a switch under the Category meta that could say "Redirect to Category Page".
![Annotation on 2022-08-31 at 10-39-15](https://user-images.githubusercontent.com/82535909/187623109-6eab33d1-1ce9-4c7a-9146-847b1fbbf8cf.png)

User mentioned it [here](https://secure.helpscout.net/conversation/1994401031/335059?folderId=212390)

What do you think?

**Comment by HardeepAsrani** [comment]
Makes complete sense, thank you for the suggestion!

**Comment by HardeepAsrani** [comment]
I'll close this in favor of this as I've noted it down there: https://github.com/Codeinwp/otter-blocks/issues/1148
