### ISSUE TITLE
Add support for .lottie files

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1151]
### Description:

We need to add support for .lottie format for the Animations.

You can take a look at how the player here handles when you use these two different files, the code changes:

- https://assets6.lottiefiles.com/packages/lf20_dkvlmxed.json
- https://assets8.lottiefiles.com/dotlotties/dlf10_cSNnXm5euH.lottie

You can find the lottie-player component here that works with .lottie files: https://github.com/dotlottie/player-component - so we can load them based on which file is being used. We just need to make sure the both files work the same way in the front and backend.

### Alternatives:

 Find some way to convert .lottie to .json

**Comment by arinaturcu** [comment]
**Note**: I checked what @Soare-Robert-Daniel said in the meeting about newer versions of `lottie-player`, and they still doesn't support `.lottie` files. So, the [dotLottie player component](https://github.com/dotlottie/player-component) is needed.
