### ISSUE TITLE
Dynamic Value/Links, Lottie & SVG icons not working for non-Superadmins and so

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1152]
### Description:

Some blocks/extensions don't work properly for non-Super Admins in MS and non-Editors in Single Site. Patch incoming.

**Comment by mghenciu** [comment]
@irinelenache , maybe it would be a good idea to have a **Test with different type of users, and privileges, on a multisite** instance - to test future releases for bugs like this.

As the issues mentioned above are in the wild for at least 2-3 months and no user reported them (which is good and bad at the same time 🙂 ).
