### ISSUE TITLE
Typo in Google Maps > Controls

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1153]
Hi there!

While working with Google Maps I've found an option called "Streen View". Should it be "Street View" instead?
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/187876638-44e37dec-1903-47cc-884a-b21445cd062f.png">

**Comment by HardeepAsrani** [comment]
Thank you @AndreeaCristinaRadacina, I've fixed the typo.
