### ISSUE TITLE
Review Comparison Table not accessing the previously added reviews

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1172]
Hi there!

I created a Product Review on a particular page, published the page, and exit it, then came back to it and added another product review. After updating the page, I added the Review Comparison Table, but in the available reviews, only the latest one appeared. 

Is this the desired behavior?

**Comment by HardeepAsrani** [comment]
Seems to be working fine for me. Can you give me more information on exactly what you did? Was it two different posts/pages? Was it the same page? Was it published?

<img width="738" alt="Screenshot 2022-09-05 at 7 06 23 AM" src="https://user-images.githubusercontent.com/2649903/188343576-43f0fcc1-5acc-4c82-bf36-6b3c2301140b.png">

**Comment by AndreeaCristinaRadacina** [comment]
I will present the steps here:
1. I have added a product review block
2. I have published the page and exit the editor
3. Added a new product review block, for a different product, on the same page
4. Published the page again.
5. Added review comparison table

Behavior:
Only the second product review is available for the table.

Both were on the same page and the page was published.

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Seems to be working for me. Can you reproduce it somewhere like tastewp.com/ and DM me the credentials?

**Comment by HardeepAsrani** [comment]
Just a note, with the help of @AndreeaCristinaRadacina, we figured out why this was happening. Our code only checks the parent blocks without checking if the review can be inside another block (section in this case).
