### ISSUE TITLE
More space for Cons label

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1173]
The Cons label appears too close to the last pro feature listed:

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/86592992/188264434-8e657c11-f570-4d24-ba9d-13586dabb25c.png">

Can you take into consideration adding more space?

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina which theme was being used?

**Comment by AndreeaCristinaRadacina** [comment]
Neve + Neve pro

**Comment by HardeepAsrani** [comment]
Thanks, I've fixed that. Seems to be due to theme styles so I added some padding regardless to make sure this doesn't happen.
