### ISSUE TITLE
Alternating colors won't appear in WooCommerce Comparison Table

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1175]
### Description:
The alternating colors won't appear on the rows, even if a color is selected.
### How to reproduce:
1.  Add WooCommerce comparison table.
2. Select products.
3. Enable the alternating row colors.
4. Select a color and update the page.

### Expected behaviour:
The table has alternating colors of the rows.
### Current behaviour:
Nothing changed on the editor or on the front end.

### Reference:
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/86592992/188423598-97f13353-7e10-445c-905d-2876b23bb68e.png">

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.12

**Comment by HardeepAsrani** [comment]
We are removing the block anyway, so it's fine.
