### ISSUE TITLE
Responsiveness for Comparison Table if only 2 products are there

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1177]
### Description:
The comparison table has smaller width if only 2 products are selected. Can you take into consideration making the table 100% width even if we have less products?

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/86592992/188425931-0193f907-f249-41d8-8e92-25622e6507fe.png">

**Comment by AndreeaCristinaRadacina** [comment]
@HardeepAsrani I noticed that this happens for Review Comparison Table too:
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/86592992/188822466-f77677b8-0583-485b-90ad-41d93bc06420.png">

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina I tested it and seems to work fine if there's enough content. If you've no image then we only show a small table as there's no content to show. Table responsiveness is hard, sadly.
