### ISSUE TITLE
Slanted shape divider is looking broken on frontend

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1178]
### Description:

If we add a **slant** shape divider at the bottom of the section, it looks fine in the editor but broken on frontend. 

### How to reproduce:

1. Add a section
2. Add a shape divider **slant** at the bottom of the section under the Style tab
3. Check the frontend

### Expected behaviour:
The slanted shape divider should appear the same as it looks in the editor
### Current behaviour:
The slanted shape divider is looking broken
### Reference:

frontend >> https://vertis.d.pr/AIoFg2
backend >> https://vertis.d.pr/qq2FeI
### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.12

**Comment by HardeepAsrani** [comment]
@poonam279 Seems to be working fine on my end. Can you do it on your side and export it as a JSON file from the Export Block option? Thanks!

**Comment by poonam279** [comment]
@HardeepAsrani I have attached the exported JSON file here >>
[blocks-export.json.zip](https://github.com/Codeinwp/otter-blocks/files/9495438/blocks-export.json.zip)
 
I also have a test instance where you can see this issue. (valid for 24 hours only)
Page URL >> https://parsimoniousbeetle.s4-tastewp.com/slant/
 Admin area URL: https://parsimoniousbeetle.s4-tastewp.com/wp-admin 
 Username: poonam 
 Password: 2Z5mHNgNFbs

**Comment by poonam279** [comment]
Another user reported the same issue. According to him, the shape divider is flipped vertically for the following shapes.
Top: Right Curve, Curve, Cloud
Bottom: Triangle, Slant
In the editor preview, everything looks good.
Here is the exported JSON file from his site >>
[blocks-export (1).json.zip](https://github.com/Codeinwp/otter-blocks/files/9597381/blocks-export.1.json.zip)
