### ISSUE TITLE
Google Fonts not working for Mobile, Tablet in Post/Page

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/otter-blocks#1185]
### Description:

Google Fonts not working on Page/Post on Mobile/Tablet.

### How to reproduce:

1. Insert Adv Heading
2. Select a font
3. Switch to Mobile/Preview

### Expected behaviour:

The Font is working for all views.

### Current behaviour:

The Font is working only for Desktop

### Technical info
* WordPress version: 6.0.02
* Plugin version: latest

**Comment by Atharvabillore01** [comment]
@HardeepAsrani Yaa, I have checked it and now it's working fine.
