### ISSUE TITLE
Stretched image in Safari - Onboarding Modal

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1193]
### Description:

As see in the screenshot, the Otter image from the Onboarding modal - **are stretched vertically**.
![image](https://user-images.githubusercontent.com/52494172/189860114-714e2532-9541-4df5-82d8-5bfaff22b060.png)

### How to reproduce:

1. Create a clean instance or open an existing demo with Otter in **Safari**
2. Trigger the Modal the the Otter options
3. Browser through the screens

Tested on both Destkop and Macbook Pro - same result

### Expected behaviour:
![image](https://user-images.githubusercontent.com/52494172/189861167-cf63dca6-dea7-4fcd-a1fa-8bd01f92f79c.png)

### Current behaviour:

https://user-images.githubusercontent.com/52494172/189860915-73ed5e9a-73f0-42f4-b922-dcf0b64f120d.mov

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.14
* Safari version: 15.6.1

**Comment by HardeepAsrani** [comment]
I tried and it seems to work fine for my safari. I just updated to the latest version today. Can you check again? @mghenciu 

If not then can we have a third opinion from @irinelenache to confirm.

<img width="1645" alt="Screenshot 2022-09-22 at 7 02 37 AM" src="https://user-images.githubusercontent.com/2649903/191638798-69d759d2-4e9c-4574-b852-61ee80a185ef.png">

**Comment by irinelenache** [comment]
@HardeepAsrani @mghenciu I also checked on Safari and the issue is happening for me too https://vertis.d.pr/mT04Nm

I'm using **14-inch (3024 × 1964) Macbook pro** and **Safari Version 15.3 (17612.4.9.1.8)**
