### ISSUE TITLE
Add the benefits of upgrading to Otter Pro, for notices like this

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1198]
### Description:

As discussed with Hardeep on Slack, when showing single upgrade buttons for Otter Pro, we also need to include some benefits of why to upgrade to Pro; or make sure it's clear what the users are getting after upgrading.

For example in cases like this (image below), the button makes sense as it clear that it will extend the Conditions. 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/52494172/190142555-8ffecd69-577d-4fbb-81c9-f518fa677698.png">

___
### But for the Product Review block, the advantages of upgrading to Pro, are missing (it's only a panel with a Upgrade button), so my suggestion is to add some benefits of upgrading to Pro:
<img width="343" alt="Screenshot 2022-09-14 at 10 41 38" src="https://user-images.githubusercontent.com/52494172/190142842-5ed75652-2509-4e8e-98c5-1d00ec657d38.png">

___
The example from the Woocommerce builder, is the perfect example of how we can do this better, by showing some advantages: 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/52494172/190143035-97618d82-fe56-423c-857a-41a3b2a684ef.png">

**Comment by mghenciu** [comment]
> I noticed this as well while testing the review block, good catch. Do you think we should be specific to the advantages of each block? Or just mention the same generic Otter PRO advantages regardless the block?

I think it should be contextul. And we already have some general upgrade/upsell used in Otter or other products.
By contextual I mean that it should make sense in that context and **upgrading benefits be clear**. For example if we are talking about animations, it can say _unlock more animation options, like animation1, animation2, and much more._
Same thing for the Display conditions where it's clear that upgrading will unlock all conditions.


While in this case is not clear what (as a user) I get with Otter Pro. Maybe we could use a line about **Sync Product Reviews** feature, and/or something else. 
___
What other benefit upgrading to Pro for the Product Review block, users have @HardeepAsrani ? Review Comparison Table, maybe - but doesn't sounds directly related to this.

**Comment by JohnPixle** [comment]
I also agree about the benefits list being contextual, thanks for the input 👍🏻

**Comment by HardeepAsrani** [comment]
It's just Syncing and Review Comparison Table for Review Block.

**Comment by mghenciu** [comment]
> It's just Syncing and Review Comparison Table for Review Block.

Sounds better than nothing :)
We can use those.
