### ISSUE TITLE
Dynamic link added to a buttom from ACF does not work

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#1199]
### Description:
In the recent release we added possibility to add links dynamically - https://github.com/Codeinwp/otter-blocks/pull/1146

But I tried adding it to the button and it doesn't work.
I've added it this way:
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/36594177/190152833-ced0dd94-0627-4f23-9822-5a387d731e80.png">

No link in the front-end:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/36594177/190152982-741e1982-ee2c-4f75-aeab-43bc6de884f7.png">

If you **mark the text** and try to add it then (I don't think we should make it work this way and it should work on button itself):
<img width="733" alt="image" src="https://user-images.githubusercontent.com/36594177/190153250-ec7f3e25-f0bd-4603-903a-ead8e0d6aea8.png">

Then it works but result on the front-end is very bad:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/36594177/190153408-2efa9125-8ccc-4f59-9e54-ce5283b95c5a.png">

### How to reproduce:
1. Create a new button and try to add dynamic link to the button using ACF
2. Check the front-end.

### Expected behaviour:
Link from ACF value to be added as a href link to the button.

### Current behaviour:
Link is not added to the button and if added on text it's a separate <a href element out of the button container.
### Reference:
Screenshots above.
Reported that dynamic link doesn't work here - https://secure.helpscout.net/conversation/2000442981/335800
### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.14
* Otter PRO: 2.0.14

**Comment by HardeepAsrani** [comment]
Thank you @vytisbulkevicius, right now the Format doesn't work on Buttons. We will check and fix it. Thank you!
