### ISSUE TITLE
Add Table of content block 

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1200]
### Description:

A user suggested to add a Table of content block in Otter. I think it can be a good addition.

### Alternatives:

 Suggest a third-party plugin.

**Comment by HardeepAsrani** [comment]
There long has been a plan in Core to offer a ToC: https://wptavern.com/the-gutenberg-wordpress-plugin-to-introduce-a-table-of-contents-block

Besides, Yoast already offers one, so not sure if we can make something much better to offer a better value proposition to the user.

Any opinions @Codeinwp/design-team

**Comment by JohnPixle** [comment]
I also don't think there is much to do here as we better focus our efforts on optimising our current blocks and UIX.  @HardeepAsrani
