### ISSUE TITLE
Tabs/Form/Countdown/Flip block is wrapped with an extra border (editor only)

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#1201]
Hey team, There appears to be an extra border in the tabs block, which is definitely not supposed to be there. 

Please note that this happens only in the editor, and not at the frontend, but it's still confusing.

![Screenshot 2022-09-15 at 17 16 22](https://user-images.githubusercontent.com/4193672/190428518-da5b118a-5820-485a-900d-2f9b5e866981.png)

**Comment by HardeepAsrani** [comment]
- Similarly, Posts doesn't load for non-admins.
