### ISSUE TITLE
Form block is wrapped with an extra border (editor only)

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#1202]
Similar to the tabs block at #1201 there appears to be an issue with the form block and a wrapping border, when the border size is edited. This also appears only at the editor side.

Here is a [quick video](https://www.loom.com/share/107848948182483998bf0b638004c373) showing the issue in action.

![Screenshot 2022-09-15 at 19 50 21](https://user-images.githubusercontent.com/4193672/190463158-7e03f963-d6a8-4fa3-b84a-a4df66008922.png)

Let's see if we can address this one in a timely manner, since it will be present in the forms of the WP maintenance templates.

**Comment by HardeepAsrani** [comment]
Closing this in favor of https://github.com/Codeinwp/otter-blocks/issues/1201
