### ISSUE TITLE
The Section block won't refresh in the frontend

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1205]
### Description:
If I make changes to the section block, they will not be refreshed on the frontend.
### How to reproduce:
1. Add a section block
2. Add a section column and insert custom HTML block
3. Publish the page
4.  Make some changes and update the page
5. Refresh the website

### Expected behaviour:
The website will have a different appearance.
### Current behaviour:
Nothing happens.
### Reference:
https://www.loom.com/share/230a937146a44df192475ebc8c4dd85a
### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.13
* Neve version: 3.4.1
* Neve Pro version: 2.4.1

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina I tried it on my end and things are working properly. You might need to let the CSS save once you press the publish button.

**Comment by HardeepAsrani** [comment]
@irinelenache Just to confirm if that's indeed not an issue.

**Comment by irinelenache** [comment]
@HardeepAsrani @AndreeaCristinaRadacina I checked and i couldn't reproduce the issue, everything is fine on my end

**Comment by AndreeaCristinaRadacina** [comment]
okay, thank you for letting me know!
