### ISSUE TITLE
Error in Appearance -> Widgets

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1207]
### Description:

There is an error in Appearance -> Widgets with the latest version of the plugin. Rolling back to the previous version solves the issue.

![Capture](https://user-images.githubusercontent.com/86592341/191542773-69c4e6f0-b423-4755-9386-1d6851e5cc88.PNG)

The user who reported this also mentioned that the content he added in the widgets from the footer was removed. That's when he noticed this error in Appearance -> Widgets. He added the content back and it didn't disappear again after that. I couldn't replicate this behavior, I'm not sure if it's related to that error, but I can see the error as well.

### How to reproduce:

1. Make sure to use the latest version of Otter
2. Go to Appearance -> Widgets

### Expected behaviour:
No error will appear.

### Current behaviour:
An error appears.

### Reference
Reported [here](https://secure.helpscout.net/conversation/2015917923/337783/).

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.14

**Comment by HardeepAsrani** [comment]
@MarinescuLucia Thanks for reporting. We will fix it. However, I don't believe the other mentioned issue was because of this error.

**Comment by kushh23** [comment]
+1: https://wordpress.org/support/topic/the-otter-welcome-plugin-has-encountered-an-error-and-cannot-be-rendered/
