### ISSUE TITLE
Test Otter with WordPress 6.1 Beta

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1208]
Hey @irinelenache,

When you have time, can you test Otter with WordPress 6.1 Beta to see if everything works as expected?

**Comment by irinelenache** [comment]
@HardeepAsrani Did some testing and here are my findings: 

- [ ] Controls are missing for the Countdown block when the **countdown type** is set to **Evergreen** or **Interval** https://vertis.d.pr/Z2lINJ (Also there is a typo in the dropdown, the word should be Evergreen)
- [ ] There is a small visual problem for the Hide/show block feature in the countdown block https://vertis.d.pr/XQwB5j
- [ ] In the Icon block, when i'm opening the Font awesome icons dropdown, there is a strange behaviour of the dropdown https://vertis.d.pr/5tPktt
- [ ] The background control for the lottie block has some blank spaces https://vertis.d.pr/xERWx8
- [ ] For every dynamic image i'm getting an error in the editor and in frontend there is only the default image for Otter dynamic
editor: https://vertis.d.pr/iVhyCv
frontend: https://vertis.d.pr/1c1iV9
For the last issue i switched back to wp 6.0.2 and it still happens, maybe it's related to InstaWP or the Speed starter site?

**Comment by HardeepAsrani** [comment]
@irinelenache I can't reproduce the first issue. Apart from that, I've fixed the rest.

For the Dynamic Image one, it only works if the user uses pretty permalinks. If it's using the default permalink structure of `?p=12` then it doesn't work.

**Comment by irinelenache** [comment]
@HardeepAsrani The marked issues are fixed, thank you 🚀 

>  Controls are missing for the Countdown block when the countdown type is set to Evergreen or Interval https://vertis.d.pr/Z2lINJ (Also there is a typo in the dropdown, the word should be Evergreen)

^ I also couldn't reproduce it again so now everything's fine 👍

**Comment by HardeepAsrani** [comment]
@irinelenache No other issues with 6.1 apart from these. I see Popovers in many places are appearing in weird places but that is also happening with Core ones so Core should fix this issue.
