### ISSUE TITLE
Translate Posts block with Loco Translate

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1209]
### Description:

A user mentioned that the Read More tag from the Posts block can't be translated with Loco Translate. It looks like if you search for the Read More tag in Loco Translate -> Plugins -> Otter -> New Language, no results can be found.

![tempsnip](https://user-images.githubusercontent.com/86592341/191773635-f01229c9-ecc4-41e0-bd48-a12aa5f3a9cb.png)

### How to reproduce:

1. Install and Activate Loco Translate
2. Go to  Loco Translate -> Plugins -> Otter
3. Add a new language and start translating
4. Look for the Read More tag

### Expected behaviour:
The tag will appear when searching for it so it'll be possible to translate it.

### Current behaviour:
The tag doesn't appear.

### Reference:

Reported [here](https://wordpress.org/support/topic/translation-of-the-read-more-label-in-the-posts-block/#post-16024195).

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.14

**Comment by HardeepAsrani** [comment]
Closing this in favor of https://github.com/Codeinwp/otter-blocks/issues/629
