### ISSUE TITLE
Priority edits for Patterns integration

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#1210]
This is issue is about some high-priority tweaks we need to make in our blocks, in order to improve the interoperability of our Otter Patterns in multiple theme contexts (light and dark themes).

Original issue: [**Otter Pattern Library** ](https://github.com/Codeinwp/otter-blocks/issues/1203)

## 1 - Border default color should inherit body text color
**The color value in Border controls** should inherit the **theme's Body text color** across all our blocks from now on. Currently, by default, the border colors have an inline value of #000. We want this to automatically inherit the body text color, so when the pattern is inserted in a dark theme, we have the proper color contrast.

I understand that we do not want to wait to apply this change across all our blocks, so **I would prioritise at least the borders of Section Columns now,** where we use them extensively for the boxed style. Gradually we can extend this to all our blocks, as we go through the sidebar restructuring.

**This is how it looks now (with inline #000000 value) 👇🏻👇🏻👇🏻**

![Screenshot 2022-09-22 at 19 17 03](https://user-images.githubusercontent.com/4193672/191799626-7e633fd2-ad38-4c5b-996a-4257806dc6cc.png)

**This is how it will look when borders will inheriting the body text color 👇🏻👇🏻👇🏻**

![Screenshot 2022-09-22 at 19 16 54](https://user-images.githubusercontent.com/4193672/191799800-df95c796-2e43-432d-bdb8-a9b033650551.png)

## 2 - Advanced icons default color should inherit body text color

In the same spirit, we should allow the **default color of the advanced icons** to **inherit the body text color.** instead of an inline black color.

**This is how the above section will look when this happens 👇🏻👇🏻👇🏻**

![Screenshot 2022-09-22 at 19 14 1](https://user-images.githubusercontent.com/4193672/191801077-e32a6c42-8549-4909-b35d-cd92f43bcbed.png)

I should mention at this point that the icons in the icon list block already inherit the body text color, and work fine.

![Screenshot 2022-09-22 at 19 21 53](https://user-images.githubusercontent.com/4193672/191801479-53bd5d04-fdb6-426f-9b1d-abe1f3e43146.png)

## 3 - Extra border appearing on blocks

One important issue that currently affects many blocks is the extra border that appears, as mentioned in the issue below.
- [x]  https://github.com/Codeinwp/otter-blocks/issues/1201

I am not sure if solving the above issue will fix every block where the problem appears, but we need to keep an eye on the form block as well, since it is particularly visible in the pattern preview.

![Screenshot 2022-09-22 at 19 00 44](https://user-images.githubusercontent.com/4193672/191796581-20c2caba-73b9-4dc9-ba5c-1b70d510b49e.png)

Please do not hesitate to ping me for any clarifications regarding the above, or if you have any questions about the implementation. It would be great if we can have those changes live before we roll out the Otter Patterns.

@HardeepAsrani @Soare-Robert-Daniel @mghenciu

**Comment by HardeepAsrani** [comment]
> In the same spirit, we should allow the default color of the advanced icons to inherit the body text color. instead of an inline black color.

@JohnPixle I checked and the icons don't have a set color. They inherit already. Can you check again to confirm?

**Comment by HardeepAsrani** [comment]
I can see, it happens with TI icons.
