### ISSUE TITLE
Review block 'Cons' label reads 'Cros'

### ISSUE THREAD

**Issue by milicavs** [Codeinwp/otter-blocks#1220]
### Description:
The 'Cons' label in the review block says 'Cros'.

### Reference:
https://staging-finmasters.temp513.kinsta.cloud/sezzle-up-review/

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.16

**Comment by HardeepAsrani** [comment]
@milicavs Thank you! By the way, you can also change the text of Pros/Cons label now from the editor while we fix it.

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2035709164/340462?folderId=212385

Please fix it as soon as possible. This user is very angry because he is using many review blocks, and it's not a good solution to edit each block.
