### ISSUE TITLE
Vertical align on sections not working on mobile

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/otter-blocks#1223]
### Description:
If you create a section with Otter's section block and set its vertical-align to center, the content will be centered only if window width is at least 600px

### How to reproduce:
1. Add a section and set its vertical-align to center
2. Check on front-end on windows lower than 600px

### Expected behaviour:
 - Content to be centered
 
### Current behaviour:
- Content is not centered and I didn't find a way to do it.

### Reference:
https://normalsisters.s1-tastewp.com/otter-page/
Username: cungureanu  Password: jy1LME_nE8s

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.15

**Comment by mghenciu** [comment]
[May be related to this ](https://vertistudio.slack.com/archives/C02JC68P404/p1660301856918939).
Hopefully the Otter team will have the time to take another look on this, at some point.
