### ISSUE TITLE
Otter breaks "Attach to Products" modal of the PPOM Plugin

### ISSUE THREAD

**Issue by mskapusuz** [Codeinwp/otter-blocks#1237]
### Description:

[PPOM Free](https://wordpress.org/plugins/woocommerce-product-addon/) has a "Attach to Products" feature. If Otter Blocks is activated, attaching a product to a PPOM group is not possible anymore.

### How to reproduce:

1.Install WooCommerce & PPOM Free
2.Install stable Otter
3.Install WooCommerce
4.Visit WooCommerce->PPOM Fields screen and try to attaching a product to a PPOM group, you will get an error alert.
5.Deactivate the Otter
6.Try again to attaching a product to a PPOM group, you will see you can achieve it.

### Expected behaviour:
PPOM "Attach to Products" feature should work well independently from Otter.

### Current behaviour:
Otter breaks "Attach to Products" feature of the PPOM.

### Reference:

![Screen Shot 2022-10-03 at 17 07 08](https://user-images.githubusercontent.com/25361626/193598092-2e456441-df6a-4617-a568-5e6b0511ef87.png)

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.16

**Comment by mskapusuz** [comment]
I've investigated the issue. That's not specific for PPOM.

Otter removes all HTML Form Input values in the Ajax Responses. 

The issue comes from the following:

`add_filter( 'wp_kses_allowed_html', array( $this, 'used_html_properties' ), 10, 2 );`
https://github.com/Codeinwp/otter-blocks/blob/master/inc/class-main.php#L48

**If Otter is activated:**
![Screen Shot 2022-10-03 at 17 13 27](https://user-images.githubusercontent.com/25361626/193599524-8307bd11-cc62-4a79-a527-b7329540027e.png)


**If Otter is not activated:**
![Screen Shot 2022-10-03 at 17 14 30](https://user-images.githubusercontent.com/25361626/193599795-6caed95b-3f26-491b-8f89-2d51538793ba.png)


-----

So the issue affects all WP around but I'm not sure if I should create a separate issue to report it. I shared on this comment. Fyi @HardeepAsrani

**Comment by HardeepAsrani** [comment]
Closing in favor of https://github.com/Codeinwp/otter-blocks/issues/1238
