### ISSUE TITLE
Otter removes HTML Form Input values where in the AJAX responses in All WP

### ISSUE THREAD

**Issue by mskapusuz** [Codeinwp/otter-blocks#1238]
I've investigated the issue (https://github.com/Codeinwp/otter-blocks/issues/1237). That's not specific for PPOM.

Otter removes all HTML Form Input values in the Ajax Responses. 

The issue comes from the following:

`add_filter( 'wp_kses_allowed_html', array( $this, 'used_html_properties' ), 10, 2 );`
https://github.com/Codeinwp/otter-blocks/blob/master/inc/class-main.php#L48

**If Otter is activated:**
![Screen Shot 2022-10-03 at 17 13 27](https://user-images.githubusercontent.com/25361626/193599524-8307bd11-cc62-4a79-a527-b7329540027e.png)

**If Otter is not activated:**
![Screen Shot 2022-10-03 at 17 14 30](https://user-images.githubusercontent.com/25361626/193599795-6caed95b-3f26-491b-8f89-2d51538793ba.png)

-----

So the issue affects all WP around but I'm not sure if I should create a separate issue to report it. I shared on this comment. Fyi @HardeepAsrani

_Originally posted by @mskapusuz in https://github.com/Codeinwp/otter-blocks/issues/1237#issuecomment-1265511768_

**Comment by HardeepAsrani** [comment]
@mskapusuz I've fixed it in the development branch of Otter. Can you check to make sure?

**Comment by mskapusuz** [comment]
> @mskapusuz I've fixed it in the development branch of Otter. Can you check to make sure?

I've tested **Otter Free (development branch)** + **PPOM**. The bug I've referred to in https://github.com/Codeinwp/otter-blocks/issues/1237 seems fixed. Thanks!

**Comment by HardeepAsrani** [comment]
Thanks for quick testing @mskapusuz!
