### ISSUE TITLE
Section block's Global settings

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#1241]
### Description:
A customer asked about the global settings of the section block:

> 1: Is there a reason there is no 'Reset' like on the 'padding' and 'margin' settings (A reset that is just for the maximum section width)?
> 2: Is it possible to make the maximum width more than 1200?

<img width="905" alt="image" src="https://user-images.githubusercontent.com/36594177/193768831-3885bdf1-4d42-44a0-b9bb-6f35e1b782f9.png">

I think both these questions make sense as for individual Structure block we can set more than 1200px width and we have reset button:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/36594177/193769081-1ba2278e-2072-4150-b6fd-9bcc12df2fce.png">

So maybe we can do the same for the global settings?
Asked here - https://secure.helpscout.net/conversation/2026564471/339149
### Alternatives:
Leave it as it's now.

**Comment by HardeepAsrani** [comment]
Thank you, should be fixed in the next version @vytisbulkevicius
