### ISSUE TITLE
Product Review stars color

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1242]
### Description:

If you set a certain color for the stars from the Product Review block in the Global Defaults section, the stars will have that color regardless of the rating. If you set it as green, the stars will be green for a big rating, as well as for a small one, they won't change color based on the value of the rating. This happens with the latest two versions and it works properly with 2.0.14.

### How to reproduce:

1. Create a page
2. Go to the Global Default section -> Product Review block
3. Expand Colors and set a color for the Stars
4. Add the Product Review block on a page and play with the ratings of the features; the color of the stars won't change along with the general rating

### Expected behaviour:
The color of the stars will change based on the value of the rating.

### Current behaviour:
The color of the stars remains the one set in Global Defaults, regardless of the rating which isn't ideal and may be confusing because, for example, a 3/10 rating will appear green, the same as for a 10/10.

### Reference:

Observe the green color (which was previously set in Global Defaults -> Product Review) for a rating of 3/10.
![Capture2](https://user-images.githubusercontent.com/86592341/194304142-5fe207f9-684d-433c-9ed1-a17c3d6b287b.PNG)

Everything is the same here, except the version of Otter which is 2.0.14 and the color of the stars changes accordingly to the rating.
![Capture3](https://user-images.githubusercontent.com/86592341/194304320-7bb5a712-0d23-4c81-918e-e8dd0b7d2e8b.PNG)

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.16 & 2.0.15

Reported [here](https://wordpress.org/support/topic/default-settings-for-all-blocks/#post-16075097).

**Comment by HardeepAsrani** [comment]
@MarinescuLucia Yea, it was a design decision made in the last version where we allow users to customize the color but show only one color star instead of based on the rating.

Might be confusing for older users but I don't see it as a big deal. What do you think @JohnPixle

**Comment by JohnPixle** [comment]
I agree, I think it makes more sense to have a single color for the stars, regardless the value. Having many different star colors based on the value of the rating was adding some visual clutter, and it would be harder to manage them via the color settings. 

I believe we are good as we are in the latest version, but thanks for sharing the concern Lucia 👍🏻

**Comment by HardeepAsrani** [comment]
@MarinescuLucia I'll suggest that support team can maybe make a doc about how to change it with Custom CSS as I can see many people asking for this. I'll close it for now.

**Comment by AndreeaCristinaRadacina** [comment]
Hi there!

Can you please provide the archive for the 2.0.14 version? I tried 2.0.13, and it didn't work. @HardeepAsrani
