### ISSUE TITLE
Reverse columns not appearing if the section layout is configured from the modal

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1256]
### Description:
When I create a 3 columns layout, the reverse columns in mobile devices won't appear. It appears only after I change the number of columns from the Layout tab.
### How to reproduce:
1. Insert a section block.
2. Select a 3 columns layout.
3. Open the advanced tab,

### Expected behaviour:
The reverse option will appear.
### Current behaviour:
The reverse option does not appear.

### Reference:
https://www.loom.com/share/dab68b6861c5496596a7ae0319e31ce7
### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.15

**Comment by HardeepAsrani** [comment]
Hey @AndreeaCristinaRadacina, we only show that option if user has selected this for Mobile Screen, the collapsed rows layout.

<img width="273" alt="Screenshot 2022-10-10 at 6 35 29 PM" src="https://user-images.githubusercontent.com/2649903/194873050-0a5c4374-5f59-4779-bc1e-ad7d5fc278cf.png">

**Comment by AndreeaCristinaRadacina** [comment]
@HardeepAsrani okay, thank you!
The fact that the desktop was selected, but the option appeared after changing the number of columns is expected?

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina That's because once you switch to 1 column layout, the mobile style becomes collapsed so that's why it's happening.
