### ISSUE TITLE
Review Block: Add descriptions to product ratings

### ISSUE THREAD

**Issue by milicavs** [Codeinwp/otter-blocks#1260]
### Description:
It would be nice to have an option to display the reasons for the rating for each of the product features. 
Something like: https://prnt.sc/QYWb9sO-vIkD

### Alternatives:
n/a

**Comment by HardeepAsrani** [comment]
Personally, I think there were I expect the article to have that data and the review block is just for an overview at the end. What do you think @Codeinwp/design-team

**Comment by JohnPixle** [comment]
@HardeepAsrani I find it a good idea tbh, given the fact that there is also enough blank space where we can include a description without breaking the layout. The implementation of the control in the sidebar also looks easy to add. I find it like an extra positive touch, I'd say we try it. 

Also, I believe there is no need to go all-in and add more UI controls for customising the appearance of this text, we can have some good defaults and set the description font size to a default` 0.8em  and it can inherit the text color with 0.7 opacity.

It should look good by default in most cases. 

![Screenshot 2022-10-14 at 10 30 05](https://user-images.githubusercontent.com/4193672/195788611-6c3027a9-56a4-47f0-a92e-8156ef032167.png)

Let me know what you think!

**Comment by milicavs** [comment]
@HardeepAsrani Do we know that most people use the review block at the end of an article? It seems quite unlikely to me. I would assume that a majority of users would put it quite closer to the top if not right at the top of an article.

From my experience and all the data I've seen, if an article has a review box summarizing ratings, pros & cons, etc. near the top, most readers will focus on the data in it and rarely read the entire article. That's why I think that this would be a nice addition. It would allow publishers who want to do it to actually show that the ratings are not just random numbers (which too often they are) and provide additional value to the reader.

**Comment by HardeepAsrani** [comment]
@milicavs Yea, usually I've seen it at the bottom of the article as much as I've seen with our users.

@JohnPixle The design looks good, to be fair. Given it's a dynamic block, it should be easy to make the change but I'll try to see if we can somehow manage the font-size properly instead. I do agree that we have a lot of empty space there so maybe having it can make it look better.
