### ISSUE TITLE
Visibility conditions don't work for Widgets added in sidebar

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1263]
### Description:

If you set visibility conditions for the widget added in the sidebar, they will be ignored. 

### How to reproduce:

1. Add a widget in the Sidebar under Appearance > Widgets
2. Set the Visibility Conditions of that widget.
3. Save the changes
4. Reload the page
5. Check the previously added condition

### Expected behaviour:
Visibility conditions are not working for sidebar widgets

### Current behaviour:
Visibility Conditions are ignored for widgets added to show in the sidebar

### Reference:

Screencast >> https://vertis.d.pr/eUMgmP

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.16

Issue reported before: https://github.com/Codeinwp/otter-blocks/issues/999 This time, the conditions are not working only with sidebar widgets.

**Comment by Soare-Robert-Daniel** [comment]
This seems to be fixed (tested with the Neve theme on WP 6.0.3). @irinelenache, when you have time, a second confirmation will be much appreciated.

**Comment by HardeepAsrani** [comment]
I think that's fair game, we are a block plugin; those aren't blocks. I'll close it then. @poonam279
