### ISSUE TITLE
Tab removing feature doesn't work and has an error in Console

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1268]
### Description:

https://user-images.githubusercontent.com/52494172/196226242-8907bde5-e727-4fe7-a417-9cfca728f078.mov

### How to reproduce:

1. Fresh Otter instance
2. Add a Tabs Block with a few tabs
3. Try to remove some of the Tabs

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.16

**Comment by HardeepAsrani** [comment]
Should be fixed now.
