### ISSUE TITLE
More Animations for the Slider block

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1279]
### Description:
A user asks if there is a way to make the slider images fade in/out instead of sliding. 

Ref: https://www.youtube.com/watch?v=o8nEzv2tY18&t=26s
### Alternatives:
Leave it as it is.

**Comment by HardeepAsrani** [comment]
Duplicate of https://github.com/Codeinwp/otter-internals/issues/8
