### ISSUE TITLE
Dynamic value name won't change when I change Data Type

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1280]
### Description:
If I introduce a Post Time dynamic value and change the data type to Post Excerpt, the name won't change.
### How to reproduce:
1. Insert a dynamic value, with any data type.
2. Click on it and change the data type.

### Expected behaviour:
The name of the current data type will be replaced.
### Current behaviour:
The name of the dynamic value stays the same.
### Reference:
<img width="430" alt="Screenshot 2022-10-20 at 11 02 45" src="https://user-images.githubusercontent.com/86592992/196945160-0842f721-2bd3-4250-a6c6-ed9c0e382870.png">

### Technical info
* WordPress version: 6.0.3
* Plugin version:  2.0.16

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Yea, that's expected. We don't change the default, we can't make sure what the user wanted there.
