### ISSUE TITLE
Add option to disable email notifications if user has enabled subscription

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1290]
A user asked if it's possible to disable the email notifications that are sent to the admin when a person subscribes to the form from the maintenance/coming soon page. Maybe we could add an option to be able to do this.

As an alternative solution, I think we could create a doc explaining how to achieve this with custom code.

Suggested [here](https://wordpress.org/support/topic/disable-email-notifications-12/).

**Comment by HardeepAsrani** [comment]
@girishpanchal30 If needed, one can disable it site-wide using https://github.com/Codeinwp/otter-blocks/blob/master/inc/server/class-form-server.php#L110 but that's not ideal.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel We can put this on hold for now and we can approach it later when we work on the admin dashboard with mails.

**Comment by HardeepAsrani** [comment]
@arinaturcu I think you can group this in with https://github.com/Codeinwp/otter-blocks/issues/1463, maybe some option in Form Block to select if they want notification or storing (or both), with both being enabled by default.

**Comment by Soare-Robert-Daniel** [comment]
Since we now have `Database` option as a saving location, we can close this. @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel This was related to a free user who was using the form for just subscription users to newsletter and not wanting to get the alerts.

**Comment by Soare-Robert-Daniel** [comment]
So, should we add a special button for it? Like a toggle for notifications?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel One option to not save it anywhere in the drop-down, with selecting it showing a help text and explaining the situation where it can be helpful.
