### ISSUE TITLE
Simplify Dynamic Value preview

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#1292]
@HardeepAsrani 

I would suggest to keep the styling of the Dynamic values to the minimum, and have them less opinionated in order to not interfere with the overall style of the page. 

### Currently we use a double underline

I think this is too bold. Users need just a simple visual hint (if any at all). Elementor does not alter visually the dynamic values at all. They just display the dynamic value right away.

![Screenshot 2022-10-28 at 11 58 31](https://user-images.githubusercontent.com/4193672/198548957-cc663923-108d-484a-a8b3-3cc8e30319ce.png)

### Suggested style:
I would suggest we have this more subtle, by using a single dashed underline of 3px thickness.

![Screenshot 2022-10-28 at 12 01 17](https://user-images.githubusercontent.com/4193672/198549049-26f3b068-47d8-4bc1-bb54-f391be09c55c.png)

Here is the CSS I used to reach this result

```
text-decoration-color: var(--wp-admin-theme-color);
    text-decoration-line: underline;
    text-decoration-style: dashed;
    text-decoration-thickness: 3px;
```
 
### Selecting a parent Section / Column

I also noticed the following... When the Dynamic Element is inside a Section, and the section or column is selected, then the dynamic value shows up in the orange style (i don't know how to call it, sorry 😛 ). So essentially it behaves as if the Dynamic element itself is selected. Can we do something about this?

Here is a [quick loom](https://www.loom.com/share/28be4e98935b41cd952ddf3d77e3a9ff) for context.

![Screenshot 2022-10-28 at 11 42 24](https://user-images.githubusercontent.com/4193672/198550415-55cdc1b2-4153-4c42-a700-593a932d7bf6.png)

@mghenciu feel free to share your thoughts on these if you have any other suggestions about the styling.

**Comment by mghenciu** [comment]
Makes sense, John. 
Thank you for your input.

I like the idea of having it with **orange** when it's a Dynamic Value, because it makes it look more like something clickable (a button), and having the **blue underline** when the Actual Content is previewed.

Only one question here, do you think maybe it's worth adding a Toggle here for this?
something like _Highlight the Dynamic Text_
<img width="305" alt="image" src="https://user-images.githubusercontent.com/52494172/199056695-db674849-cebc-447a-8322-2a1659dfa282.png">

___
For the Implementation Phase, keep in mind that this Blue Underline should also work when the text is marked with the Red underline (signifying an gramatical error):
<img width="259" alt="image" src="https://user-images.githubusercontent.com/52494172/199057080-b3d3ddc8-6674-4c71-8ca4-f854ddee35bc.png">

**Comment by JohnPixle** [comment]
@mghenciu Thanks for the input. 

> _Only one question here, do you think maybe it's worth adding a Toggle here for this?
something like Highlight the Dynamic Text_

That's actually a good idea, it would make sense. Personally, I would definitely have the highlight disabled as I would not want any extra styling imposed on the elements. I really enjoy how Elementor handles this, where dynamic things are seamlessly integrated in the layout without any differentiation.

But I guess for other users (or in cases with a lot and mixed dynamic values) it would make sense to have a visual hint.  It's definitely a good idea to offer users this option, good catch.

@HardeepAsrani let us know if you find this a possible option!

**Comment by mghenciu** [comment]
> @mghenciu When the toggle is disabled, should both the underline and the orange background be disabled? or just the underline?

I think **both of them of them would be disabled, if the Toggle is disabled.**

But if I understand the suggested improvement correctly, the issue now is that the **outside context highlight is too strong.**
By Outside, I mean when the Dynamic element is not even selected, it's should render as an actual content and no highlight. Currently it has a double underline: 
![Screenshot 2023-01-09 at 17 47 05](https://user-images.githubusercontent.com/52494172/211349428-7e9b0e58-d17b-4620-a7dd-f9f87c5b62fb.png)

___
But in case where I go and **select that element, I think it should remain highlighted even if the toggle is disabled:**
![Screenshot 2023-01-09 at 17 49 39](https://user-images.githubusercontent.com/52494172/211349832-051b7705-eecc-4e40-8fdf-f55446ade35d.png)

Let me know @JohnPixle , if you imagined this the other way.
