### ISSUE TITLE
WordPress media library is hidden by RankMath popup

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1295]
### Description:

If Otter plugin(free) is active, the WordPress media library is hidden by a RankMath pop-up when we go to "Add/Replace Image" on my Social Media settings for a post.
### How to reproduce:

1. Install and activate RankMath Plugin along with Otter
2. Edit a page
3. Go to Social Media Preview option under Rankmath settings
4. Click Add image button
5. You will see that the WordPress media library is hidden by RankMath Popup
6. Deactivate Otter(free) and check again

### Expected behaviour:
We should be able to select an image from the WordPress media library.

### Current behaviour:
WordPress media library is hidden so you can't select any image
### Reference:

Screencast >> https://vertis.d.pr/v/ZUFtzm

### Technical info
* WordPress version: 6.0.3
* Plugin version: 2.0.16

**Comment by HardeepAsrani** [comment]
Thank you for the report. I know what's causing it.
