### ISSUE TITLE
missing consent text in otter-blocks.pot file

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1297]
### Description:

When we add a form block and Mailchimp integration is active and select the **submit and subscribe action**, a checkbox for data-sharing consent with this text - **I have read and agreed the privacy statement** appears at the bottom of the form. This string is missing in otter-blocks.pot file, so it's not possible to translate. 
### How to reproduce:

1. Add a Form block
2. Enable Mailchimp integration i
3. Select the **submit and subscribe action**
4. Check the Form, you will see this text - **I have read and agreed the privacy statement.**

### Expected behaviour:
The string should be available for translation
### Current behaviour:
String is missing in the otter-blocks.pot file

### Reference:

https://vertis.d.pr/i/u1Kvlm

### Technical info
* WordPress version: 6.0.3
* Plugin version: 2.0.17

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, I see that in the pot file we do not have this file https://github.com/Codeinwp/otter-blocks/blob/131840019a251f026cad0436c779db0ffdda638e/inc/class-registration.php

**Comment by HardeepAsrani** [comment]
Yea, it's a messy system that we need to fix.

**Comment by HardeepAsrani** [comment]
Closing in favor of https://github.com/Codeinwp/otter-blocks/issues/629
