### ISSUE TITLE
find a new name and icon for Advanced columns

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#13]
@HardeepAsrani

**Comment by HardeepAsrani** [comment]
What do you want here? Section?

**Comment by selul** [comment]
following #8 i think we should move this under layout tab too. Section indeed seems much better than advanced column in terms of naming.

**Comment by HardeepAsrani** [comment]
Okay, so as talked with both of you:

- We will rename "**Advanced Columns**" to "**Section**"
- Rename category of "**Otter Blocks**" in Inserter to "**Advanced Blocks by Otter**."

What about Advanced Heading? Should we also rename it to something like, "Title" or something, or we just leave it as Advanced Heading?

@selul @ineagu

**Comment by ineagu** [comment]
1. @selul my original idea for our "advanced" blocks as well as section was to use a small differentiator for sections with a common name, in a way that section purpose is clear, but also unique, with small o from Otter. Both Rodica and Hardeep don't like my idea, don't have another one.

oSection
oHeading
oButton 
etc

2. For Category in the inserter, I would have just Otter with a small icon.
