### ISSUE TITLE
Making use of Finmasters' Review Design

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1312]
### Description:

@JohnPixle @mghenciu I think we can take use of the design that @milicavs used for the Finmasters website: https://finmasters.com/experian-boost-review/ - What do you both think?

If yes, then we will have to see how we can make the design work wth her other suggestion that we plan on adding: https://github.com/Codeinwp/otter-blocks/issues/1260

What do you think?

**Comment by JohnPixle** [comment]
@HardeepAsrani I was about to write about that too, I definitely agree. Their implementation shows an alternative user perspective, we can see how we could have made things easier for them and potentially many other users.

One thing I liked from them was the inline approach for the inline layout for the rated features. This helps filling horizontal space, which is something we discussed on the other ticket. I think using an inline / horizontal option of the ratings, along with the descriptions, it will help a lot. And we can apply it in both column layouts. Example from[ Figma](https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=2426%3A30111).

![Screenshot 2022-11-07 at 10 31 12 AM](https://user-images.githubusercontent.com/4193672/200262551-19bfae1e-8e6c-4748-a46e-ed4d9713640f.png)


In the Inspector sidebar I think we can add a toggle to enable this alternate layout. We can add it in the settings at the root level, or **I suggest better under the Features tab.**

![Screenshot 2022-11-07 at 10 41 38 AM](https://user-images.githubusercontent.com/4193672/200264897-0ed96b15-e98c-4376-9d16-a8a8408c293a.png)


Let me know your thoughts!

**Comment by HardeepAsrani** [comment]
@JohnPixle We can put it in Column Structure too. "Default" "Two Columns" "Inline" something like that so it's easy to find and switch to make it look like this:

<img width="1118" alt="Screenshot 2022-11-07 at 5 30 11 PM" src="https://user-images.githubusercontent.com/2649903/200305131-838e9363-e583-4248-a27d-c8ec9f59092e.png">

**Comment by JohnPixle** [comment]
Indeed we could, but if we keep it as a separate toggle option, then it can be applied to any of the "Default" or "Two Columns" layouts. I think it might be a bit more flexible this way. For example a user might still want a 2 Column layout but have the features inline. Like this 👇🏻 

![Screenshot 2022-11-07 at 2 23 03 PM](https://user-images.githubusercontent.com/4193672/200309425-168363e0-7ddf-4624-af02-388b29030f34.png)

Thoughts?

**Comment by ineagu** [comment]
I am curious here, any reason why we haven't tried to keep the original design? I felt that the design was part of the product success : https://www.google.com/imgres?imgurl=https%3A%2F%2Fpagely.com%2Fwp-content%2Fuploads%2F2015%2F01%2FFist-of-Legend.png&imgrefurl=https%3A%2F%2Fpagely.com%2Fblog%2Fgive-wordpress-review-posts-makeover-wp-product-review%2F&tbnid=NuE5Tt1nRw6UxM&vet=12ahUKEwj67YiwrLD7AhUpUaQEHVK_AUMQMygPegUIARDaAQ..i&docid=KEPVQ3AsUrjelM&w=945&h=461&q=wp%20productreview&client=safari&ved=2ahUKEwj67YiwrLD7AhUpUaQEHVK_AUMQMygPegUIARDaAQ .

**Comment by JohnPixle** [comment]
@ineagu I have never seen this design before tbh 🙈 . 
Looked a bit deeper and looks like it was from [one of our plugins](https://docs.themeisle.com/category/1647-wp-product-review) that is no longer maintained?

I definitely don't recall seeing this UI in any version of the Otter blocks. 
If we stopped maintaining the WP Product Review in favor of the Otter block version then it should have been the default style. Maybe Hardeep had his reasons for that or we can always look into offering it as a style variation.

**Comment by ineagu** [comment]
I think it might have been just the limitations of the editor since this was not ages ago :D You are right that it was a older plugin of ours, it was the most popular review plugin, just that it proven a thing that not a lot of people want to pay for and prefer to enjoy it for free, but again the design for the main box/widget worked really well.

**Comment by JohnPixle** [comment]
Thanks for the insights. I'll sync with Hardeep when he returns and see what we can do.

**Comment by HardeepAsrani** [comment]
One of the reasons was that the Circular review bar can be too buggy, it also requires JavaScript.

**Comment by HardeepAsrani** [comment]
It can be done with CSS but the ones from there was JSON with the animation and everything, overall it was too buggy and the original layout was tried to keep it pretty similar to the WPPR design.
