### ISSUE TITLE
Posts Block doesn't show custom taxonomy created for a custom post type

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1324]
### Description:

When we use a Posts Block and select a custom post type, the custom taxonomies created for that custom post type don't appear under the category option. So you can can't filter the posts based on taxonomies.

### How to reproduce:

1. Create a custom post type using CPT UI Plugin
2. Create custom taxonomy for that custom post type
3. Create a page and use Posts Block
4. Select post type under Layout option >> https://vertis.d.pr/i/W7HnOK
5. Try to find your custom taxonomy under category >> https://vertis.d.pr/i/dqCRJn

### Expected behaviour:
The custom taxonomy should be available for selection 
### Current behaviour:
The custom taxonomies do not appear for selection under the category section of the posts block.
### Technical info
* WordPress version: 6.1
* Plugin version: 2.1.2

**Comment by HardeepAsrani** [comment]
It's a hard thing to do, maybe you can see if we can do it consistently @Soare-Robert-Daniel?

**Comment by HardeepAsrani** [comment]
Might be helpful here https://developer.wordpress.org/reference/functions/get_object_taxonomies/

**Comment by HardeepAsrani** [comment]
We discussed this in the meeting and decided against it as the user is looking for something very specific, and it's a Posts block and for their usecase something like Query block will be more appropriate.
