### ISSUE TITLE
Posts block doesn't show the Sticky post as a featured post. 

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/otter-blocks#1325]
### Description:
A user has asked about this on the wp.org forum that if he can use the sticky post as a featured post in Otter's posts block.

When you use the Posts block and turn on the featured post option, then the sticky post doesn't appear as a featured post. The sticky post appears at the top of the Blog/Archive page so his query is if it can be also used here and if it could appear as a featured post.

P.s  - I am not sure If I should add an enhancement tag or the bug tag.😅

### How to reproduce:

1. Create some demo posts.
2. Go to any random post and make it a sticky post by going to post settings [See attached screenshot in reference].
3. Install Otter and Create a new page.
4. Use Otter's **Posts Block** and turn on the featured post option. 
5. Go to the page and observe that the post which is featured on top is the latest post that was created by you. If you will create a new post then the new post will appear as a Featured post.
6. Now go to the Blog/Archive page and see that the sticky post appears at the top instead of the latest post.

### Expected behavior:
The posts block should show the Sticky post as a featured post. 

### Current behavior:
The posts block doesn't show the Sticky post as a featured post. 

### Reference:

![image](https://user-images.githubusercontent.com/110405452/201397469-6dfecb4c-d578-43a5-9254-8c90911dec9e.png)
![image](https://user-images.githubusercontent.com/110405452/201399366-11be7018-7aa7-4586-9a2f-fcc4fae2f1d9.png)

![image](https://user-images.githubusercontent.com/110405452/201398979-f066c956-3473-4fe9-8daf-f456668e390d.png)
![image](https://user-images.githubusercontent.com/110405452/201399183-31b22879-b5df-4372-abee-df3987ecf789.png)

The user asked here : https://wordpress.org/support/topic/can-i-keep-the-sticky-post-as-the-featured-post-in-the-posts-block/
### Technical info
* WordPress version: 6.1
* Plugin version: 2.1.3

**Comment by HardeepAsrani** [comment]
Makes sense. Sticky post should be the featured post if it exists. Thanks for the report!

**Comment by Soare-Robert-Daniel** [comment]
How do we handle the case when there are multiple Sticky posts?

Should the sticky posts be a higher priority in displaying as a rule?

**Comment by kushh23** [comment]
I checked it with the Normal blog/archive page and on that, if there are two sticky posts then the latest one should be on top then the other one .
