### ISSUE TITLE
Different button color on front end compared to the editor

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1328]
### Description:

If you add a button group directly to the page, as a main block level, the colors works correctly. When adding the button group block into the Section block, the color shown in the editor is different than the one on the front end.

### How to reproduce:

1. Use the Neve theme - didn't try with others
2. Add a **button group** with a button as the **main block**. Don't set any color
3. Add a **button group** with a button **into** a **Section block**, and don't set any color.
4. By default, you should see the button background color dark grey and the button text color white.
5. On the front end, for the button inside the Section block the text will be black not white, because it inherits the link color from the global colors.

### Expected behaviour:

![Markup on 2022-11-15 at 18:22:36](https://user-images.githubusercontent.com/26867648/201972119-f42c560d-7037-4554-bf28-0f43436ef2cf.png)

### Current behaviour:

![Markup on 2022-11-15 at 18:23:09](https://user-images.githubusercontent.com/26867648/201972127-0ab32d80-2215-47f9-af0f-00e2092621c1.png)

### Reference:

https://secure.helpscout.net/conversation/2063728156/344041/
https://secure.helpscout.net/conversation/2062492046/343885?folderId=212390
https://secure.helpscout.net/conversation/2069560681/344889?folderId=212385

### Technical info
* WordPress version: 6.1
* Plugin version: 2.1.3

**Comment by stefan-cotitosu** [comment]
The customers mentioned in the issue description said the problem appeared at the last update of the plugin.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani do we changed something on CSS pipeline loading?

The CSS is generated but is not loaded on the page.

<img width="781" alt="Screenshot 2022-11-16 at 10 42 24" src="https://user-images.githubusercontent.com/17597852/202131540-ac83fd91-c715-4e82-b210-3a5c5495be3e.png">

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel I'll take care of it, I know what's causing it. I need to refine it better to avoid inheritance every time.
