### ISSUE TITLE
Widgets section does not load with Otter enabled

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#1332]
### Description:
It can be replicated on a completely fresh instance with any theme when Otter is enabled.

If the Otter plugin is enabled in the Appearance->Widgets section nothing loads and all sections are locked (can't be expanded):
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/36594177/202227778-40c4f4c6-452f-4c91-a852-b1b1deb9ef45.png">

If you click to add something there is an error in the console:
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/36594177/202228007-fc439f80-e5eb-4ad9-8805-349350752ff1.png">

Disabling Otter plugin fixes the issue and Widgets appear as expected:
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/36594177/202228520-343c3ae2-c95f-4be0-aa13-f9f0de2875f5.png">

Screencast: https://vertis.d.pr/v/PFaLjy

Rolling back Otter plugin doesn't fix the issue so not sure how it wasn't reported before.

### How to reproduce:
1. Install Otter plugin with any theme and go to Appearance->Widgets

### Expected behaviour:
Widgets to load
### Reference:
Reported here - https://secure.helpscout.net/conversation/2068424450/344628

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.1.3

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius Seems to work for me when I try locally or on Tastewp.com, are you only having it with a particular theme or any theme at all?

**Comment by vytisbulkevicius** [comment]
@HardeepAsrani,

Can you check with Chrome browser? I double check now and it works with Safari, Firefox but not Chrome.

**Comment by HardeepAsrani** [comment]
Thanks @vytisbulkevicius, I can reproduce it now. Can you look at it @Soare-Robert-Daniel? Probably try to isolate different large chunks and see what's causing it if you're not getting anything in console to point it to something directly.

**Comment by HardeepAsrani** [comment]
It was fixed in this: https://github.com/Codeinwp/otter-blocks/commit/64b0c468e5dd28421978324cb6f2711578493e46 - thank you!
