### ISSUE TITLE
Advanced Heading Size control needs to inherit Default Size of the H tag instead of Size

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#1335]
We have a serious issue with the latest Font Size controls in the Advanced Heading Typography. Mainly happening in the frontend.

Looks like the Advanced Headings are forced to inherit one of the Theme's Font Sizes (M) and not the default size defined for the  specific Heading Tag.

So, if I use an Advanced Heading and set it's tag as H2 for example, then in the frontend it will not use the default H2 size of the theme, but instead the M size.

This currently affects all our Advanced Headings, in layouts and patterns as well.

❇️ [**Video example.**](https://www.loom.com/share/e7eecac604b34257ad811e157bceee35)

![Screenshot 2022-11-18 at 11 06 21 AM](https://user-images.githubusercontent.com/4193672/202664038-80208fa7-1e9b-4c35-b914-1d57a95b7701.png)

cc @HardeepAsrani @Soare-Robert-Daniel @mghenciu

**Comment by HardeepAsrani** [comment]
@JohnPixle The one that isn't released yet, right?

**Comment by JohnPixle** [comment]
@HardeepAsrani Thankfully yes, I spotted it when testing the last PR about the section colors.
Wanted to give you guys a heads-up before we push it live.

**Comment by Soare-Robert-Daniel** [comment]
Fix the showed value here https://github.com/Codeinwp/otter-blocks/commit/c551dd5e5d9c0a5117f643307934e4ef72eba884
