### ISSUE TITLE
Add transition timer to Section

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1338]
### Description:

Suggested by John:

Maybe it is worth exploring adding a transition control like Elementor does for sections? Elementor only applies the transition time on the bg color of the section and column though, and not the text. In our case we can have it apply in both bg and text colors, so they both change smoothly on Hover.

**Comment by JohnPixle** [comment]
Following up on this, here is an image from Elementor's implementation and a possible solution for otter

![screenshot_2022-11-18_at_12 37 28_pm](https://user-images.githubusercontent.com/4193672/203305364-528f2196-1d37-47f8-9c37-2d183a423e75.png)

However, if it's too much of work to add a transition timer, as Mihai suggested maybe we can start with a generic transition effect and add the option to adjust later.
