### ISSUE TITLE
Create a Citation block 

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1342]
### Description:
The posts can be cited sometimes by other websites, and this can be done more easily using the citation block. There, the author can type the exact citation form as a code snippet.

Other similar products - https://wptavern.com/cite-a-wordpress-plugin-to-help-readers-correctly-attribute-articles

Reference -  I found searches for cite / citation in HelpScout, and I thought it could be an addition.
### Alternatives:
We can skip this if it isn't worth it.

**Comment by HardeepAsrani** [comment]
This can be done easily if one is using FSE theme by using existing Core blocks and Dynamic Data. Don't think it's worth the effort or will be used by more than few users. Thanks for the suggestion!
