### ISSUE TITLE
Product Review Comparison Table is Not Responsive On Mobile

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/otter-blocks#1343]
### Description:
When setting up the product review comparison table block, you'll notice that no matter how many products you introduce, the table won't be responsive on mobile, rendering the columns outside of the viewport.

### How to reproduce:

1. Create a website and have Otter plus Otter PRO installed
2. Create a few reviews using the Review Block
3. Use the Product Review Comparison Block and select the above-created reviews
4. Save and Update the page
5. Visit the page on a mobile device or using the Chrome Inspector tools
6. Observe how the table is not adjusting for mobile or at least has a horizontal-scroll

### Expected behaviour:
The table becomes responsive for mobile or introduces a horizontal scroll that allows the user to see all the columns.

### Current behaviour:
The table is not responsive and the user cannot see all columns.

### Reference:
[Screencast showing the issue.](https://vertis.d.pr/v/NXiG9A)

Testing Environment: https://peacefulplate.s4-tastewp.com/
User: matei@themeisle.com
Password: HW1LRO4op0Q

### Technical info
* WordPress version: 6.1.1
* Otter version: 2.1.4
* Otter PRO version: 2.1.4

**Comment by HardeepAsrani** [comment]
It is intended that way. It's a lightweight table without any JS and there's no better way to make responsible tables. If we get more people using it or more response on Otter Pro, we might consider having a better table but for now this does the work that is required by the user.
