### ISSUE TITLE
Creating a Woocommerce template 

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1344]
### Description:

Some users asked if there is a way to make a Woocommerce template that can be applied to all products instead of having to individually edit each product.

https://secure.helpscout.net/conversation/2075774559/345827?folderId=212390
https://secure.helpscout.net/conversation/1958128121/330634/

**Comment by selul** [comment]
@abaicus can't this be achieved with Raft?

**Comment by abaicus** [comment]
@selul Yes, it can mainly be achieved with block-based themes, but I have a hunch the users don't want to switch to one 😬

**Comment by HardeepAsrani** [comment]
@selul We can do a lot with Woo Builder in Otter just the worry is that if we should do it as our work can be wiped away the day WooCommerce decides to release their own version.

Things like:

- Allow users to select one page for the whole website
- Allow more customization to individual page items, like colors, typography and such

**Comment by HardeepAsrani** [comment]
Closing in favor of https://github.com/Codeinwp/otter-internals/issues/50
