### ISSUE TITLE
Remove the visibility conditions upsell 

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#1353]
### Description:

The general idea is that the PRO upsells should not confuse users and don't let them experience the feature properly. In this case the button is too obvious, more obvious than Add a rule setting: https://vertis.d.pr/i/F6fl2m. For a first time user of the feature, our priority is that they try the feature & only after we ask for an upgrade.

Possible solutions: 

1. Simple one, remove that button: https://vertis.d.pr/i/F6fl2m. The user would open the dropdown and they would see that there are more options and which one as well, there is no better upsell than this.2. 

2. More complicated. Show a cleaner upgrade button, but only after the user added at least a rule on their site.

### Alternatives:

cc @HardeepAsrani @mghenciu

**Comment by ineagu** [comment]
> Maybe we can also check the Stats, if we have an UTM for this button.
> 
> I would prefer the second option, maybe even not show it at first use of a rule, but maybe after you've added **at least 2 rules** (based on the assumption that that type of user would need more).

Thank you for the input Mihai. We can check the stats, but they won't tell us much about this issue, here is a bit more how I am looking at it.

Since sales are pretty close to 0, I ignored for now if we lose 1 sale or not since it not that relevant, with my comments, I tried to focus on what can potentially make someone deactivate Otter.

My assumption is that the reason that people are not buying Otter is because they aren't using it enough. For e.g here if they would heavily rely on those rules and would want those "locked in", they would find a way to buy the pro, no matter of what we do.

So things like Otter tools approach, boxes in the sidebar, this red pro button are small things, but which can overall can "convince" someone to Deactivate Otter.

If we want some data, this would be how much showing that button affects retention, which is  impossible to track for now, so yes, with the risk of maybe losing some revenue, I've tried to focus on making sure people are using Otter. We solved the issue of people installing Otter, if they would also keep & use it, we should be able to convince them to buy.

So forgetting about revenue, do you think this would help with the "first impression" and retention/usage?

**Comment by HardeepAsrani** [comment]
I think we can remove it given that user already sees a list of so many options that they get with Pro version:

<img width="284" alt="Screenshot 2022-12-01 at 2 15 26 AM" src="https://user-images.githubusercontent.com/2649903/204904454-627adbee-5976-478e-ac8b-2322548e9d3c.png">
