### ISSUE TITLE
Rework global defaults & introduce visibility controls

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#1355]
### Description:

We can improve the design of the global defaults and use a similar layout as the below example to add visibility controls.

We can stick to 2 simple visibility options : 

Disable the block
Hide settings for role > X 

e.g https://vertis.d.pr/i/5iyeMK

**Comment by JohnPixle** [comment]
By visibility controls, you are referring to the user's ability to disable the block completely, or show/hide the **GD** (Global Defaults) **controls** for specific blocks? 

I am not sure if the visibility referes to the block, or the block's Global Defaults.

If I disable the visibility of the GD of the Advanced Heading, does this mean that in the settings sidebar there will be no GD controls, is this true?

In this case, what happens to the actual GD values when de-activated?

Perhaps I'd take a look at kadence and see how this works.

### Global Defaults rework.
I am a big advocate for completely re-thinking the whole GD thing, just so you know. 
There are serious issues right now with how things are communicated in the UI and I believe we should look for a more binary solution : Either a block will be synced with the GD values, or it won't. This would require a toggle at the main panel.
Providing such a deep scattered level of control as we do now, across many settings, is something we must avoid imo.

Elementor is also experimenting with default widget styles, and looks like a good different perspective. 

It will allow you to style a widget as you want, and then save the style as default. Every time you add a new widget, it will show with the new default style. For every existing block, if you reset it to default, it will then show the new default styles as well.

I don't know how of much this possible in our case, but we can talk about it for sure. I remember we had discussions about that earlier this year, and if I recall well there must had been some technical challenges.

**Comment by ineagu** [comment]
Sorry for mixing the 2 together.The visibility control idea has nothing to do with global defaults, would just use the same settings screenSent from my iPhoneOn Dec 1, 2022, at 09:48, John Fraskos ***@***.***> wrote:﻿
By visibility controls, you are referring to the user's ability to disable the block completely, or show/hide the GD (Global Defaults) controls for specific blocks?
I am not sure if the visibility referes to the block, or the block's Global Defaults.
If I disable the visibility of the GD of the Advanced Heading, does this mean that in the settings sidebar there will be no GD controls, is this true?
In this case, what happens to the actual GD values when de-activated?
Perhaps I'd take a look at kadence and see how this works.
Global Defaults rework.
I am a big advocate for completely re-thinking the whole GD thing, just so you know.
There are serious issues right now with how things are communicated in the UI and I believe we should look for a more binary solution : Either a block will be synced with the GD values, or it won't. This would require a toggle at the main panel.
Providing such a deep scattered level of control as we do now, across many settings, is something we must avoid imo.
Elementor is also experimenting with default widget styles, and looks like a good different perspective.
It will allow you to style a widget as you want, and then save the style as default. Every time you add a new widget, it will show with the new default style. For every existing block, if you reset it to default, it will then show the new default styles as well.
I don't know how of much this possible in our case, but we can talk about it for sure. I remember we had discussions about that earlier this year, and if I recall well there must had been some technical challenges.

**Comment by HardeepAsrani** [comment]
@ineagu We were discussing visibility controls for options and wonder if this is the level of customization useful for most users. We wondered if it'll make sense to, instead of allowing individual panels or settings of each block to be controls, we just do it for entire sections, as in Settings/Styles of the block, where you can control if you want to allow non-admins to access the Styles part of the block and such.

What are your thoughts?

**Comment by selul** [comment]
here not sure if the visibility has or somehow intersect the functionality with block locking from core https://fullsiteediting.com/how-to-lock-blocks-and-templates/

**Comment by HardeepAsrani** [comment]
@selul Right now it is works very differently but I saw on Matt's presentation on the changes coming: https://youtu.be/VeigCZuxnfY?t=1699

I wonder if what we're doing will be a useful addition to the settings for most users or just a very few. I do like what Core is planning on doing, to allow, by locking block areas, to simply just let your client edit the content without being able to edit the settings.

cc @mghenciu @JohnPixle

**Comment by mghenciu** [comment]
This is definitely a feature that **won't be used by a large majority of users**, as it makes sense only in an Agency/Developer -> Client context.

In our case, I think the main differentiator is the users would be able to choose between Style & Settings, which I think is useful. So for example let's say I have a site using Otter forms a lot, and I want to **Lock the Style of the forms**, but allow users to edit the Form Content. Not sure how would this work in the current FSE context.

___
I am not trying to advocate on something, as this may be just one of those times when we add something (like Masonry), and in a few months Core adds their solution, which overlaps with ours.

**Comment by HardeepAsrani** [comment]
Closing this and we can continue the discussion here in private: https://github.com/Codeinwp/otter-internals/issues/70
