### ISSUE TITLE
Show Otter Blocks first in the list of blocks

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#1356]
### Description:

Being generic enough I think Otter blocks should not appear the last ones vs the competition who place them 1st in this list : https://vertis.d.pr/i/fZxm6N

**Comment by HardeepAsrani** [comment]
@ineagu I wanted your thought about this little annoyance: https://www.loom.com/share/694b1d330964447f97088d6d6c35228e

**Comment by ineagu** [comment]
I am not worried, the small inserter that most people are using is sorted by popularity/recency. You would likely never use that big + for adding a paragraph in real life, you might use it for seeing all available blocks.I see it more like the popular plugins/themes repo tab, rarely people would go there, but when they go, is good to remind them of Otter.And again every block plugin does this and I suspect users have more than 1 plugin for blocks.Sent from my iPhoneOn Dec 1, 2022, at 09:45, Hardeep Asrani ***@***.***> wrote:﻿
@ineagu I wanted your thought about this little annoyance: https://www.loom.com/share/694b1d330964447f97088d6d6c35228e
