### ISSUE TITLE
Bump minimum compatibility

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#1358]
### Description:

@HardeepAsrani Mihai suggested that we can boost this for some improved controls, if this would give us better features and easier-to-manage code, I think we should make the change for 5.9 minimum.

Any reason you haven't done it before?

**Comment by HardeepAsrani** [comment]
@ineagu We support at least last two major versions as it's recommended and usually that's enough versions for most people to update to the latest. We were gonna upgrade after 6.1 but haven't made any changes that require the update so far, so would've happened itself the next time we make a change that requires newer components.

**Comment by ineagu** [comment]
Makes senseSent from my iPhoneOn Dec 1, 2022, at 09:36, Hardeep Asrani ***@***.***> wrote:﻿
@ineagu We support at least last two major versions as it's recommended and usually that's enough versions for most people to update to the latest. We were gonna upgrade after 6.1 but haven't made any changes that require the update so far, so would've happened itself the next time we make a change that requires newer components.
