### ISSUE TITLE
Product Review Block Structured Data Issue with 1-5 Rating Scale

### ISSUE THREAD

**Issue by milicavs** [Codeinwp/otter-blocks#1375]
### Description:
When using the 1-5 rating scale, there are some cases that generate structured data to be invalid.
When you enable a 1-5 rating scale in Otter options the scale in the editor still shows a 1-10 scale. Depending on the ratings you input this can lead to invalid structured data.

### How to reproduce:
1. Enable the 1-5 rating scale in Otter options
2. Add a review block with 4 product features 
3. Give each feature a rating of 1 star.

### Expected behaviour:
The final rating for this product should be 1 start.

### Current behaviour:
The final rating for this product is 0.5 stars.
Even though the schema is valid when I run it through the [validator](https://validator.schema.org/), this still throws and error in [Rich Results Test](https://search.google.com/test/rich-results) and shows up in GSC. The error in question is: 'Rating is outside the specified or default range.'

### Reference:
[Example](https://finmasters.com/restoration-hardware-credit-card-review/)

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.1.4

**Comment by HardeepAsrani** [comment]
Thank you @milicavs, will fix that!
