### ISSUE TITLE
Popup block hard to edit in the editor preview

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1383]
### Description:

I was testing the popup block and it seems to be very different in the editor preview compared to the front end.

### How to reproduce:

1. Open the editor
2. Use the popup to add some content to it
3. Check how it looks like in the editor vs front end

### Expected behaviour:

![Markup on 2022-12-09 at 13:08:57](https://user-images.githubusercontent.com/26867648/206689429-6bae945b-5b2a-4acb-a391-18c1aa7326e9.png)

### Current behaviour:

![Markup on 2022-12-09 at 13:09:42](https://user-images.githubusercontent.com/26867648/206689424-868a9db5-b83a-4706-a052-dfb2cb7c4ed4.png)

### Reference:

https://secure.helpscout.net/conversation/2092354979/347883/

### Technical info
* WordPress version: 6.0.3
* Plugin version: 2.1.6

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Which theme are you using? Can you send me a dummy site where this happens? I can't seem to reproduce it on Neve or Kadence theme.

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani, I can't replicate it anymore, either. I was using Neve. Maybe it got fixed at the last update of the plugin.
