### ISSUE TITLE
Dynamic Value is not aligned according to editor settings

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1385]
### Description:
The site title and tagline are not aligned to the center, as appears in the editor.
### How to reproduce:
1. Insert Site Title and Site tagline as dynamic values.
2. Align them to the center.
3. Publish and check on the frontend.

### Expected behaviour:
The information will be centered.
### Current behaviour:
It appears on the left.
### Reference:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/207041768-7880d30d-079e-4ce6-a08a-3edca9f47ed1.png">
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/86592992/207041820-6bb4e123-0003-4101-8b7a-b4cb8fd03e9c.png">

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.1.5

**Comment by HardeepAsrani** [comment]
Closing this as the reason for this and https://github.com/Codeinwp/otter-blocks/issues/1386 is the same, as we try to debug more and see if it's happening on other places as well.
