### ISSUE TITLE
Advanced Heading looks different on the frontend

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1386]
### Description:
The advanced heading appears without any customizations on the frontend.
### How to reproduce:
1. Insert an advanced heading.
2. Add a background.
3. Publish and check on the frontend.

### Expected behaviour:
The heading appears as in the editor.
### Current behaviour:
The heading appears as a basic one.
### Reference:
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/86592992/207042719-89dd5ccc-18c8-487f-9015-4ac8b78beae5.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/207042754-c7781c81-09af-437e-9ee9-3bc434597f99.png">

### Technical info
* WordPress version:6.1.1
* Plugin version: 2.1.5

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Seems to work fine on me, can you reproduce it on a test site and pass me the credentials?

**Comment by HardeepAsrani** [comment]
We weren't able to reproduce it anywhere else, and it also fixed itself in the original site hence closing it for now. Thanks @AndreeaCristinaRadacina for your help!
