### ISSUE TITLE
Popup width not responsive on mobile with On Anchor Click trigger

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1390]
### Description:

If the open trigger for a popup block is set to On Anchor Click, the popup won't be responsive on mobile. The height will adjust as expected to fit the content, but the width remains set to 500px. [Here](https://vertis.d.pr/v/XwaNUg) is a screencast showing the behaviour. There is no issue with the responsiveness if other open triggers are used.

### How to reproduce:

1. Add a button and add a link to it that will be used for the popup
2. Add a popup block and set the open trigger to On Anchor Click
3. Add the name from the button link in the Frequency & Close Settings ->Anchor field from the popup
4. Publish the page and check the behaviour on mobile

### Expected behaviour:
The popup will be responsive.

### Current behaviour:
The popup is not responsive.

### Reference:

Reported [here](https://secure.helpscout.net/conversation/2095841173/348309/).

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.1.6

**Comment by HardeepAsrani** [comment]
@MarinescuLucia I can reproduce it but for me it's happening regardless how you open the popup.

**Comment by MarinescuLucia** [comment]
@HardeepAsrani Yep, you're right. Sorry, I guess the cache tricked me :).
