### ISSUE TITLE
Popup position can't be changed

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1393]
### Description:
When I try to change the popup position, I can't select anything apart from the default position - center.
### How to reproduce:
1. Add a popup block.
2. Open the Popup Position accordion.
3. Try to select something else.

### Expected behaviour:
The chosen position gets selected. 
### Current behaviour:
The position is not clickable.
### Reference:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/208235276-9d0af0f2-fdcd-402e-8de8-2a2498e929b4.png">

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.1.5

**Comment by AndreeaCristinaRadacina** [comment]
Also, when I try to configure the position for other devices and click on another one, the whole page is reloaded, and the popup position accordion appears closed; shouldn't it just switch to the other device?

**Comment by HardeepAsrani** [comment]
Thank you @AndreeaCristinaRadacina, I've submitted a fix for it. We can't control the control closing when you change the screen but I've fix the position not being changed.
