### ISSUE TITLE
Add image and gradient background options for popup block

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1394]
### Description:
The popup block can be used in many ways, so the background can help to boost the website's appearance, such as displaying the logo as a background image or things like this.
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/86592992/208235684-f7ca1a2f-f727-4857-9417-833a82851ff3.png">

### Alternatives:
Leave it as it is.

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina One can actually still do it by using the Cover or Section block by following these steps: https://www.loom.com/share/2f37c9a77470441a95f7c49be1288c80
