### ISSUE TITLE
Visual issues with the Global Defaults popups

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1398]
### Description:

While working on the Global Defaults reorganisation, I spotted some issues in the Popups, **mainly regarding the Height of the Container** (attached images & video):
<img width="582" alt="Screenshot 2022-12-20 at 11 25 26" src="https://user-images.githubusercontent.com/52494172/208631742-98c16058-1592-4cc1-bfa7-b6191551ff36.png">

<img width="622" alt="Screenshot 2022-12-20 at 11 26 30" src="https://user-images.githubusercontent.com/52494172/208631930-d614b51f-3cb2-4608-8afd-6ea253a63e1f.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/52494172/208631990-1a008e90-55f0-4c14-9e15-c162a15911dc.png">

<img width="464" alt="Screenshot 2022-12-20 at 11 27 22" src="https://user-images.githubusercontent.com/52494172/208632090-6ac96fbc-3188-405d-9f46-546d55a50c21.png">

### How to reproduce:

1.
2.
3.

### Current behaviour:

https://user-images.githubusercontent.com/52494172/208632378-1dd76dc5-4651-4352-ba0c-16d67845a1a6.mov

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.1.6

**Comment by HardeepAsrani** [comment]
I'll close it as we will be changing the UI to a sidebar approach anyway so this won't be relevant.
