### ISSUE TITLE
Fade in or out instead of sliding [ Slider block ]

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1399]
### Description:
A user asks if there's a way to fade in or out instead of sliding. Could this be an addition?
<img width="461" alt="image" src="https://user-images.githubusercontent.com/86592992/208634772-1f196fb5-cecc-43f4-b95d-92bd26665489.png">

### Alternatives:
Leave it as it is

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina It's not possible really, we tried looking into it but fading in doesn't work nicely with the slider.

**Comment by AndreeaCristinaRadacina** [comment]
Oh, okay, thank you!

Maybe we can consider creating a new block or animations for images if it is worth it.

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Probably not given we're trying to narrow the scope for Otter and decide on a particular niche. I'll close it for now.
