### ISSUE TITLE
Visibility condition - add an option to match keyword in URL instead of only having key=value combination

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#1401]
### Description:
Client reported that he wants a block to appear using Visibility conditions if there is a matching parameter in URL but he wants to have it no matter what's the value of the parameter.

Based on current condition: 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/36594177/209004634-634bd760-ccfc-4595-a4a1-3fab59bd4a77.png">

it only works if you set the matching key=value pair, however, he wants to match URLs that only have "key" so let's say he wants to display block on all URLs that have "utm_source" in URL doesn't matter if utm_source=facebook or utm_source=twitter.
Currently, it's not possible and you need to know the value also so add a new option to match URL if there is keyword in it would be great.

### Alternatives:
No alternatives that I can think of from existing options to catch a keyword used.
 
Reported here - https://secure.helpscout.net/conversation/2099672973/348890/

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius I've been thinking about this but can't still see a good opportunity to use it. This workflow has a lot of flaws with the word in URL appearing unknowingly in many cases, and there always being some better way to do it, lets say based on the taxonomy or post type instead of targeting a particular keyword in the URL. Let me know what you two think @mghenciu @JohnPixle

**Comment by mghenciu** [comment]
Shouldn't it work based on contained in the URL?

For example if I want to catch all of them, I would something like this:
utm_source=fb
utm_source=tw
utm_source

and if any of those are in the URL -> then execute my condition.

___
Another idea could be for Query to have another option, to choose if the URL should **Contain** a key or be exact key+value.
