### ISSUE TITLE
Styles set for Icons in Customizer (header/footer builders of Neve) are ignored

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#1420]
### Description:
In Header builder or Footer builder of Customizer using Neve theme we can add Widget area component or dedicated Footer component and use Icon block of Otter but styles can't be set, so if you try to change the color or size of the icon it only reflects in the Editor but not on the page.

Example of Header builder:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/36594177/210219880-746bd581-461f-4ace-9f58-c84a64a845b9.png">
In Editor itself, changes are visible:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/36594177/210219927-39bcaef1-aa3a-4c47-891b-e8cdca4751ad.png">

Example from Footer builder:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/36594177/210220079-d289d11d-bfe2-410b-8bde-881d41a23202.png">
<img width="284" alt="image" src="https://user-images.githubusercontent.com/36594177/210220112-82d09482-f45e-447e-9b88-45e0d7ac609a.png">

### How to reproduce:
1. Add one of the Footer components into the Footer builder
2. Click to edit it and select Icon there - 
<img width="306" alt="image" src="https://user-images.githubusercontent.com/36594177/210220210-20e7ec9e-3252-4ee6-bc31-c7b0622e9246.png">
3. Edit the Icon added by clicking "show more settings":
<img width="484" alt="image" src="https://user-images.githubusercontent.com/36594177/210220250-4591ff65-e365-4037-a2b8-66934b8539ec.png">
4. Try to set color, background color, change the size of the icon. No style changes will be applied to the icon on the page, only in editor.

### Expected behaviour:
Styles to work.
### Current behaviour:
Styles don't work.
### Reference:
Ticket - https://secure.helpscout.net/conversation/2104028738/349425?

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.1.6
* Neve: 3.4.9
* Neve PRO: 2.4.8

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius I tried to reproduce it on the latest version of all of these and it seems to work fine for me. Can you reproduce it on a test instance, send me creds and also maybe make a video so I know the exact steps you took?

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius I checked and we can't do much there, you can only see the changes in the Customizer Editor and not in the preview as there as I couldn't find any hooks for that. I'll close it then.
