### ISSUE TITLE
Add Instagram icon to the Sharing Icons block

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1433]
### Description:

The Sharing Icons block has only 6 social networks but not Instagram.

![Markup on 2023-01-07 at 14:07:29](https://user-images.githubusercontent.com/26867648/211149874-b803cb26-2d6c-42c9-998f-03290eb3a8e5.png)

Can we add the Instagram network here, also?

Ticket: https://secure.helpscout.net/conversation/2117400289/351103?folderId=212385

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu You can't share a link to Instagram from a website. It allows only image shares.

**Comment by stefan-cotitosu** [comment]
I wondered if this is the reason, thank you for the clarification.
