### ISSUE TITLE
Popup block styles not loading when used in a Neve Custom Layout context 

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1436]
### Description:

As discussed before, Otter should work as expected when used in a Custom layout context, as it's opens a new - global way of building things. Just to mention two use-cases for this, one is building a Popup that will show side-wide, or building a Countdown that will show side-wide. 
___
In this case I tried building a Popup inside a Custom Layout and display it site-wide.
When the Popup is used on a single page (directly inserted in the markup) - it works as expected. But when used in a Custom Layout context, the Popup will look shrinked (attached images).

### How to reproduce:

1. I used a modified version of [Web Agency Demo](https://demosites.io/web-agency-gb/)
2. and added this Popup in a site wide Custom Layout
[popup.json.zip](https://github.com/Codeinwp/otter-blocks/files/10382450/popup.json.zip)

### Expected behaviour:
![image (1)](https://user-images.githubusercontent.com/52494172/211544262-2bd7a44d-987d-4213-92d4-9cc53708f00d.png)

### Current behaviour:
![image (2)](https://user-images.githubusercontent.com/52494172/211544300-774672ca-503d-4617-ab53-8a0c41f7d1bf.png)

### Reference:

![image (3)](https://user-images.githubusercontent.com/52494172/211544332-1ff1d71d-63f9-44c0-8c95-0bdbcb1c9a62.png)

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.1.6
* Neve: 3.4.10
* Neve Pro: 2.4.9

**Comment by selul** [comment]
hey @mghenciu,

I've noticed that you've been labeling this as both 'bug' and 'enhancement'. I just wanted to remind you that an issue can't be both a bug and an enhancement. They are two different types of issues and each one should be labeled accordingly. A bug is an error or flaw in the software that needs to be fixed, while an enhancement is a new feature or improvement that could be added. By labeling an issue as both, it makes it harder to track and prioritize. Please keep this in mind when creating or labeling issues in the future, and let me know if you have any questions.

**Comment by mghenciu** [comment]
Thanks for the suggestions, @selul .

Usually I try to use just one tag, in this case I thought about from both perspectives. 
The Bug is the fact that the Popup isn't working in the Custom Layout, and this may be an issue or it may be just how it was implemented. On the other hand, I suggest this to be treated as an enhancement and make sure Otter works as expected in any Custom Layout. Meaning that it's not enough to just fix the Popup in the Custom Layout.

In theory is more of a bug, so I will edit it to be that.

**Comment by Soare-Robert-Daniel** [comment]
After some testing, this issue is on the option `Global` for Layout. The other options like `Header`, and `Foter` work as expected like in the video below: 

https://user-images.githubusercontent.com/17597852/224712115-29285247-374e-43a8-aa6b-8a2098b0ef5d.mp4
