### ISSUE TITLE
Initialise by default the Text color on the Advanced Heading

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1440]
### Description:

**I think from an UIX point of view, it may be better to have the Text Color already initialised for the Advanced Heading block.**
At this point, when adding a new Adv. Heading or when converting a Heading to Adv. Heading, the color panel is empty, and there is just the + Icon. To change the color, right now an user would need at least **5 clicks**, and I think this add too much friction.
![Screenshot 2023-01-12 at 18 51 29](https://user-images.githubusercontent.com/52494172/212130299-29e2b25d-b650-4f95-8bed-816c16080059.png)

cc. @JohnPixle

**Comment by HardeepAsrani** [comment]
The issue with this approach is that it stops the inheriting of colors which is something we want.

**Comment by mghenciu** [comment]
Got it, Hardeep.

Using an **color=unset, like the Core Heading block**, can't make this work?
![Screenshot 2023-01-12 at 21 08 10](https://user-images.githubusercontent.com/52494172/212159298-5d25054d-c45f-442b-a6b6-78220a870524.png)

**Comment by HardeepAsrani** [comment]
@mghenciu Yea no, unset is a value for CSS so it will remove whatever the default CSS from inheritance will be. What they do, for example in Cover, they check the Background color to see if it's dark or light (with some JS logic that should work nicely in most scenarios) and based on that they switch between the default font color for the Cover. We can use a similar logic inside the Section block.

If you right now add a Paragraph, Heading & Advanced Heading in Core's Cover block and use a Dark Background, all three of them will work nicely. I tested using the latest default WP theme.
