### ISSUE TITLE
Form on frontend looks different than in the editor

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1441]
### Description:
I created the page a while ago and it looked okay at that time. I checked it again today, and the form is broken. I don't know if it's because of an update or why.
Website - https://root.stefancoti.com/2020/03/05/how-to-wash-custom-t-shirts/

### Expected behaviour:
The form looks as it was when I created it. - check here https://docs.themeisle.com/article/1674-form-blocks#contact-form
### Current behaviour:
The form is broken.
### Reference:
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/86592992/212183552-ebb2b96d-16ec-409f-a338-96afbead698b.png">

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.2.0

**Comment by mehdigrn-code** [comment]
Hi, there is a solution to this, but it's not fixing your issue exactly like the previous form style, it's close to it though. Add this CSS snippet and see the results. Let me know if it helps.
#wp-block-themeisle-blocks-form-39042afa {
	width: fit-content !important;
	padding: 5em !important;
}
