### ISSUE TITLE
Block Tools in 2 Tabs

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1442]
Hi there!

I noticed that for Otter Blocks, the Block Tools appear in multiple tabs, for example, for the Advanced Heading:
Style tab
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/212184432-6030a599-8049-4633-af2a-e23929046785.png">
Settings tab
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/212184585-1a8b906a-00ca-4f94-983c-76999fe93254.png">

Why do we have it duplicated? Is it necessary?

**Comment by Soare-Robert-Daniel** [comment]
It is not duplicated. The Tabs give a false impression of containment 🃏 , but they are just some fancy switch that allows adding more options without significantly increasing the sidebar size.

**Comment by HardeepAsrani** [comment]
As Robert said, but I'd like to ask @mghenciu & @JohnPixle if they think we should limit it only to Settings? It's a bit weird as Animations & Custom CSS are style settings, so the containment of them don't make sense in that context.

**Comment by mghenciu** [comment]
Personally I don't like the idea of having them moving around, between Tabs as it's doesn't stick to a pattern: **either it's a Style option, either a settings/advanced option.** For example the Advanced Tab can't be in both.

Now from an UIX point of view, I already got used to it... but based on how the competition does it, I think it's safe to assume that **a separation is needed.** Of course we can look into this also when/if doing the User Capabilities.

___

But I would agree that Animations should be copied when doing **Copy-Paste styles**. I'll make an issue for it.

**Comment by HardeepAsrani** [comment]
@JohnPixle I would be against removing them from Block Tools as they're used even outside our blocks too. When we experiment with visibility, we can also have an option for choosing visibility for Block Tools as a separate option.

On the other topic, we can limit the Block Tools to just the Settings panel if we want, at least in our blocks.
