### ISSUE TITLE
Sticky feature remains active if it is enabled in one of the tabs

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1443]
### Description:
Because the block tools appear in multiple tabs, if I have configured it in the Style tab and then tried to disable it from the layout tab, it will still appear on the frontend.
### How to reproduce:
1. Enable the Sticky feature inside Block Tools, in the Layout tab.
2. Configure it there, then check on the frontend.
3. Open the settings again, but disable the sticky feature from the style tab.
4. Update and check again.

### Expected behaviour:
The sticky feature will not be applied anymore.
### Current behaviour:
The sticky feature remains.
### Reference:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/212198142-21fb815d-e462-4dde-aeda-75f5a98ff7d0.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/212198186-d4d0fa53-ea3b-4148-9e23-ecd590afd894.png">

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.2.0

**Comment by HardeepAsrani** [comment]
It's same as https://github.com/Codeinwp/otter-blocks/issues/1442
