### ISSUE TITLE
PHP 8.2 issues

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#1444]
In this thread i'll add the **issues/errors** that occur in Otter blocks and Otter pro when using **PHP 8.2**

**Comment by irinelenache** [comment]
This notices appear after importing Craft Beer starter site, without making any changes in the plugin
```
Deprecated: Creation of dynamic property ThemeIsle\GutenbergBlocks\Main::$name is deprecated in /home/givudusoro3348/web/woobooster-php82.vertisite.cloud/public_html/wp-content/plugins/otter-blocks/inc/class-main.php on line 30

Deprecated: Creation of dynamic property ThemeIsle\GutenbergBlocks\Main::$description is deprecated in /home/givudusoro3348/web/woobooster-php82.vertisite.cloud/public_html/wp-content/plugins/otter-blocks/inc/class-main.php on line 31
```

**Comment by HardeepAsrani** [comment]
Hey @irinelenache, that's great. Can you let me know when you've finished the testing so I know there aren't more issues with PHP-compatibility?

**Comment by irinelenache** [comment]
@HardeepAsrani I'll leave a comment when i finish testing. For now i was focused on Neve / Neve pro / Sparks and this issue also occured 👍

**Comment by irinelenache** [comment]
@HardeepAsrani After more testing didn't find more PHP 8.2 related errors ✅
