### ISSUE TITLE
Popup behaviour when there are sticky elements

### ISSUE THREAD

**Issue by poorse02** [Codeinwp/otter-blocks#1445]
### Description:

The popup has is overshadowed when there are sticky elements on the page. In my case, the sticky element was the nav bar. @mghenciu will provide more details.

Esentially the challenge here is that Popups are centered around a page container, but with Neve - when Navs are made sticky, the Popup will use the same container, and not the new available size (main view - sticky nav height = new container height):
<img width="1722" alt="Screenshot 2023-01-13 at 14 50 19" src="https://user-images.githubusercontent.com/52494172/212356126-b6215718-c576-417d-a62f-f37311a0ce73.png">

### How to reproduce:

I encountered it when using popups on [Coding School](https://demosites.io/coding-school-gb/), so just by opening any page on that site and waiting for the popup to appear.
The sticky nav bar then covers the popup. I noticed this happening today and it didn't have this behaviour before.

### Expected behaviour:
The popup to cover the nav bar as well.

### Current behaviour:
The nav bar sticks out over the pop up, like this:
![image](https://user-images.githubusercontent.com/67728772/212322376-c3bcd3aa-9240-4310-afe8-1da7dbdb045b.png)

### Technical info
Display Resolution: 1920 x 1080
* WordPress version: 6.1.1
* Plugin version: 2.2.0

**Comment by HardeepAsrani** [comment]
Thank you @poorse02, the issue is with the Navbar using a higher z-index value than the Popup. I'll increase the z-index in Popup to fix it, thank you again!
