### ISSUE TITLE
Copy Animations with Copy-Paste style

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1446]
### Description:

As mentioned [here](https://github.com/Codeinwp/otter-blocks/issues/1442) and as Discussed with Robert, **it would be helpful to have Animations included in the Copy Paste mechanism.**

**Use-case**: I have a page with 32 different Icons, and I want to add animations to all of them. I would be much easier to add on one Icon, and then Copy-Paste the style to others.

**Comment by HardeepAsrani** [comment]
@mghenciu Do you think we should follow the same with Custom CSS?

@Soare-Robert-Daniel Just out of curiosity, do we copy/paste the CSS classes?

**Comment by mghenciu** [comment]
> @mghenciu Do you think we should follow the same with Custom CSS?

**For now I think we can leave it as it is**, Hardeep, meaning not Copy-Paste for Custom Css.

The reason being the fact that we can't control/know what users may use inside a Custom CSS and how this will work for a different block.
On the other hand, a Slide Up animation should work on an Adv. Heading the same way as it does on a Section Block.
