### ISSUE TITLE
Add bring to front option for the Shape Divider in Section block

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1456]
### Description:

The shape divider in the Section block always has the same position related to the background overlay of the section - or I didn't find an option to change it.

![Markup on 2023-01-25 at 15:36:57](https://user-images.githubusercontent.com/26867648/214578164-6a66441a-1408-4d4e-b318-edd98af84279.png)

I noticed Elementor has this, so maybe we can add such an option as well.

![Markup on 2023-01-25 at 15:37:23](https://user-images.githubusercontent.com/26867648/214578212-235549f8-d590-46f8-b98f-431a8fb879fe.png)

I found it while working on the following ticket, where the shape divider didn't behave like on my website so I adjusted it with z-index.

https://secure.helpscout.net/conversation/2133165521/353316/

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu While I get the idea and I think it's a good option, isn't it already in front in your first image?

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani, I suggested it as I saw the dividers behind the background overlay on this website - https://deutsch-polnisch-7p0aa2gsd5.live-website.com/

I didn't investigate this in detail to see if there is a combination of options influencing the position of the divider, front/back.

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu In Otter, divider is in the front of the background overlay by default. You can test this by adjusting the z-index of the overlay. Feel free to close the issue if you're satisfied or if you find something different.

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani, you are right. I've checked the customer's website again, and he added a Cover block into the Section block, therefore, the issue.


![Markup on 2023-01-31 at 10:57:07](https://user-images.githubusercontent.com/26867648/215721810-5b52f84e-055b-4193-8297-a52f980d78f0.png)
