### ISSUE TITLE
In-built spam protection in Otter Forms

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1465]
### Description:

Apart from reCaptcha, we can have some in-built spam protection in Otter forms. We can use the classic honeypot methods, like these two:

- A hidden input field is added to the form. If a value has been entered in the field when the form is submitted, then this indicates that a spam bot completed the form, and the submission is blocked.
- If the form is submitted before a specified time (5 seconds), we can assume it's not a human and can block the submission.

We need to make sure it doesn't break any pre-build forms.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, do we want to have a pop-up with questions like: '3+5=?' after pressing the submit button?

**Comment by selul** [comment]
Turnstile from Cloudflare is pretty popular right now too.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel I think that might be too much for us to do in the plugin, 2 simple steps that don't bother the UI can be good start with users can add reCaptcha if they need more.

@selul The talk I had with Ionut was about adding something in the plugin itself without using a third-party service.
