### ISSUE TITLE
Font preview in Advanced Heading

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1488]
### Description:
When changing the font family of the advanced heading, there are many options, and if I select one ( without knowing how it looks ) and I don't like it, I have to search again, select another font, then repeat until I find the suitable one.

Can we have something like a preview when hovering over an option?
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/216764523-6c79d5a5-ca3a-40f0-9482-f9895a25202c.png">

### Alternatives:
Keep it as it is.

**Comment by HardeepAsrani** [comment]
We can't just display the font, it might take a while to load them all. I'm curious to know if Neve team is using a better approach? @cristian-ungureanu

**Comment by preda-bogdan** [comment]
@HardeepAsrani You can check Neve Typography control inside Customizer it uses a font preview. You can also leverage react to only load and show the font once in view. Also when loading the font for preview you can request just the characters you need to display as to not load the whole font.

I agree with @AndreeaCristinaRadacina a way to preview the font should benefit the user experience. 

Let me know if this helps. Thank you!

**Comment by HardeepAsrani** [comment]
Thanks. I'll link the Neve's control here for reference: https://github.com/Codeinwp/neve/tree/4a108246bdb276c87104d2452a3928b7d3afa195/assets/apps/customizer-controls/src/font-family
