### ISSUE TITLE
Mailchimp integration form- get all lists

### ISSUE THREAD

**Issue by erinjholmes** [Codeinwp/otter-blocks#1489]
### Description:

The default get request for lists only retrieves 10 lists. If you have more lists than this, they won't appear or be available to connect in the dropdown contact list. 
### Alternatives:

 How to get all lists on mailchimp API for current version requires a few additional requests that return more than the default 10 lists. It will look something like, $lists = $mc->get('lists?count=100');

**Comment by HardeepAsrani** [comment]
@erinjholmes Thank you, we will include the fix in the next version.
