### ISSUE TITLE
Add Countdown Patterns in Otter

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1492]
### Description:

As discussed on Slack, I'll add at least 2 patterns in Otter.

### How to reproduce:

1.
2.
3.

### Technical info
* WordPress version: x.x.x
* Plugin version: x.x.x

-----

(Edit by Hardeep) Details for Robert here: https://github.com/Codeinwp/otter-blocks/issues/1495#issuecomment-1436981459

**Comment by mghenciu** [comment]
I've added on the Patterns page
- **3 banners**, including one with a Countdown
- and **2 Popups**
![image](https://user-images.githubusercontent.com/52494172/218572464-b9abce48-63ea-453d-971f-ebb5901a087f.png)

___
![image](https://user-images.githubusercontent.com/52494172/218572578-649f8182-4009-4f90-81b0-69af1fbf2b32.png)

___
![image](https://user-images.githubusercontent.com/52494172/218572609-b5b73a6c-9bff-41fd-b474-f2a866d55a57.png)



When you have some time @HardeepAsrani , please give them a try in a build, I am curios if we can make the Popups visible in the Pattern inserter.

**Comment by HardeepAsrani** [comment]
@mghenciu Nope, the Popup won't be visible in the Preview itself. It's hard to really show them efficiently in the Patterns.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel For the Pro Patterns, you can add the patterns here: https://github.com/Codeinwp/store-themeisle/tree/master/web/app/plugins/templates-cloud/inc/patterns

And then list them here: https://github.com/Codeinwp/store-themeisle/blob/master/web/app/plugins/templates-cloud/inc/class-patterns-factory.php

Make sure to test the minimum required version for the Pattern.
