### ISSUE TITLE
Add Templates for Popups

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1495]
### Description:

As discussed in the Meeting, in the same way as we have templates for the Form Block, it would help to also have it for the Popup block. Here's how those would look:
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/52494172/218794191-e54cfc33-2abf-4210-bec5-470f48c068b8.png">

And the corresponding Patterns can be found [here](https://demosites.io/otter/pro-patterns/).

### Options
- First template is the default one - **empty popup**
- the second one is **Text + Image**
- and the last one is a **Form**.

### Alternatives:

 

___
### [Figma](https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=2217%3A28046&t=BeUIkOn5OLMWTsSi-1)

cc. @JohnPixle

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel This is also part of https://github.com/Codeinwp/otter-blocks/issues/1492 - the Pro Patterns can be added for the Countdown & Sticky Bar thing.

And the Popup stuff can be added to Popup as variant (with Popup having a Variation Picker in the start) for free version.

**Comment by HardeepAsrani** [comment]
As mentioned in the meeting, you can use the `parse` function from `@wordpress/blocks` package to get it returned in the JSON format, and then filter out the items which aren't needed for a variation.

<img width="1227" alt="Screenshot 2023-02-22 at 12 53 55 AM" src="https://user-images.githubusercontent.com/2649903/220439413-6e0af53a-6c08-43bc-b4f6-5ade623a0a82.png">
