### ISSUE TITLE
Testing with WordPress 6.2

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1496]
### Description:

This is just here as a reminder of testing Otter with WordPress 6.2 once RC1 is out.

Test to make sure Otter works properly with WordPress 6.2 and there are no visual or functional issues.

**Comment by wpgaurav** [comment]
![Google Chrome 2023-03-08 002113](https://user-images.githubusercontent.com/3599257/223641570-df5f126a-f7bb-4df5-88fc-bf7331d4c733.jpg)
Any filter to remove `Copy Style` and `Paste Style` context menus added by Otter? These already exist in Gutenberg 15+ and are most likely to land in 6.2.

**Comment by mghenciu** [comment]
Thank you for the suggestion @wpgaurav .
@HardeepAsrani , as discussed I think we can have this under the Other Modules panel in Otter dashboard like this:
![Screenshot 2023-03-09 at 17 37 21](https://user-images.githubusercontent.com/52494172/224074759-017df4f5-2823-4658-9495-e6c80ff1945e.png)

**Comment by wpgaurav** [comment]
Yeah, this looks much better.

**Comment by irinelenache** [comment]
@HardeepAsrani Here are some more findings regarding FSE:

- [ ] Some blocks are not rendered or don't look good at all in the Style book: [Flip card](https://vertis.d.pr/i/hhvA8j), [Maps](https://vertis.d.pr/i/qhz4sE), [Popup](https://vertis.d.pr/i/w0V0mG), [Progress bar](https://vertis.d.pr/i/5UNJtM)
- [ ] In the Style book, the style variations are visible only for the Sharing icons, even if more blocks have them https://vertis.d.pr/i/xkjvIz

**Comment by HardeepAsrani** [comment]
@mghenciu Do you think we should also use the same design for Tabs as Core?

<img width="320" alt="Screenshot 2023-03-19 at 2 50 08 AM" src="https://user-images.githubusercontent.com/2649903/226140672-3ebf064d-172b-4436-b579-d3940c7012fb.png">
<img width="346" alt="Screenshot 2023-03-19 at 2 49 57 AM" src="https://user-images.githubusercontent.com/2649903/226140678-e734e927-a1e5-49c0-b42b-ae98d0e529bf.png">

**Comment by mghenciu** [comment]
> @mghenciu Do you think we should also use the same design for Tabs as Core?

**I think we can do this later.** Essentially the tabs are the same thing, but probably we'll need to review if the settings and styles structure is what Core means with this.
