### ISSUE TITLE
Frontend very different than what it is in the editor

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1508]
### Description

Context: https://github.com/Codeinwp/otter-blocks/issues/1508#issuecomment-1437487072

The patterns are not loaded as they should, which makes the block look very different on the frontend.

### Step-by-step reproduction instructions

1. Install Fork theme
2. Open a page and add a pattern
3. Publish the page and go on the frontend

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/220141574-700eb67d-b49d-45d1-8275-23465d4b421e.png">
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/86592992/220141635-32a872c7-7127-4310-895b-79972aa14faa.png">

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Seems to work fine for me: https://absorbedapparel.s2-tastewp.com/2023/02/20/5/ - maybe give it a refresh, the CSS hasn't loaded.

**Comment by AndreeaCristinaRadacina** [comment]
I have used it inside a custom template and I refreshed the page multiple times @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Would it be possible for you to share an instance where I can see the issue?

**Comment by AndreeaCristinaRadacina** [comment]
Here is the link - https://innocentwren.s2-tastewp.com
Pwd: 8QPeVoBMDdq*PT9Juml@p15S
Email: innocentwren@tastewp.com

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Which page to check this on?

**Comment by AndreeaCristinaRadacina** [comment]
services, and the template is called Advertisment Layout

**Comment by HardeepAsrani** [comment]
With the help of Andreea, we discovered the issue. In her setup, she has a Template which is using Dynamic Content for showing Post Content.

If a page uses that Template in FSE theme, anything that is rendered inside Post Content doesn't load its CSS.
