### ISSUE TITLE
Adding width option to Form Fields

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1513]
### What problem does this address?

To allow users to have forms where two fields are side by side, like this:

<img width="887" alt="Screenshot 2023-02-23 at 3 23 25 AM" src="https://user-images.githubusercontent.com/2649903/220770212-89e84d4f-bd12-4e85-9bdb-c5d21ed7ef8f.png">

Currently, this can be done using Columns or Sections within the Form but this would make the things easier for the user. I'd propose Full/Half/Third option.

### What is your proposed solution?

This can be achieved using just by adding CSS classes to the fields and flex-basis property, and the UI can either be in the sidebar or the alignment can be replaced as the current one serves no purpose for fields:

<img width="942" alt="Screenshot 2023-02-23 at 3 24 17 AM" src="https://user-images.githubusercontent.com/2649903/220770449-7d11bbb2-0e9f-4681-bb73-a05fd8e58f10.png">

Also, this should only apply to Tablet/Desktop while mobile can stay one columns.

Let me know your thoughts @mghenciu @JohnPixle

**Comment by mghenciu** [comment]
**This is 100% needed.**

We had this discussion at the beginning of the Form block, and at that point I think it was challenging to do this, dev wise.
Hopefully things changed.

We already have the logic in OrbitFox form, so I think we can just adapt some of it to Otter:
![image](https://user-images.githubusercontent.com/52494172/220836865-ba529f4f-eeb9-4257-bdb9-d9e5a2dd824e.png)

**Comment by Soare-Robert-Daniel** [comment]
Will it be not be more easier to implement more pattern/variant for the block with those layout? Form is not something that you constantly do, and you need shortcuts for quick formating the layout

The Core column is powerful.

![image](https://user-images.githubusercontent.com/17597852/220880109-8673cda2-9940-45d4-8a29-2de3bb9c2500.png)

**Comment by mghenciu** [comment]
> Will it be not be more easier to implement more pattern/variant for the block with those layout?

Maybe easier for our side. But it can also backfire later, as this will require maintenance and making sure it doesn't break on new core/otter updates.

From a users perspective it's hard to pin point the most common use cases for when users may need the custom width + it may not be very intuitive that they should use columns to build this (I didn't knew about this until this week).

**Comment by mghenciu** [comment]
ok.

 **But would it be possible to remove/handle in any way the additional spacing added by the Columns Core block?** only in the Form Block context.

Because at this point the Core columns adds some spacing, making that row different compared to other fields:
![Screenshot 2023-02-23 at 13 18 17](https://user-images.githubusercontent.com/52494172/220892717-c3066b66-533c-4472-8992-3f776cc403f8.png)

Another option would be to use the Otter Section block instead of Core Columns, but the same idea - extra attention will be needed when we change something for this blocks.

Let me know your thoughts.

**Comment by Soare-Robert-Daniel** [comment]
The spacing is not an issue. In the Form block context, the Form should handle the spacing via Fields Spacing options. You don't see the extra space in field because we override the margin from Gutenberg. We need to extend this to all direct children of the form and not just the fields.

**Comment by HardeepAsrani** [comment]
I agree that this can be done with Columns and it's really powerful but the idea of adding a Column inside Form Container isn't very easy to cross the mind for an average user, as they might not be aware that you can add other blocks inside the Form.

Since the introduction to Sidebar Management, even I've been only using that part to manage fields and not using the Inserter. This makes it easier to do things.

@mghenciu Should we have a width Select and not just a "Full/Half/OneThird/Quarter" option? I'm thinking of something of a Button Group instead of a Select field to make it easier. It will all be done using CSS classes so we can remove/add more items when needed.

**Comment by mghenciu** [comment]
Yeah, we can have either percentages (I think these are more common) or words (Full/Half/OneThird/Quarter).
And in terms of UI, **yes** it can be a selector like we have on the Button group (but with what I mentioned above, inside it):
![image](https://user-images.githubusercontent.com/52494172/220906927-b938aaf7-d9bf-469f-b606-0b973ea99cfa.png)
