### ISSUE TITLE
Add Time to Read in the Posts block

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#152]
The Posts block offers a similar layout as the one available in Neve on the blog/archive pages.
The post title/meta etc can be reordered as well. It would be nice to add the Time to Read info here.

![add-time-to-read](https://user-images.githubusercontent.com/26867648/77078577-73499300-69ff-11ea-85b6-51bba6157cf5.png)
![expected-behavior-ttr](https://user-images.githubusercontent.com/26867648/77078583-75abed00-69ff-11ea-8d07-c4dd64133865.png)

I got the idea from this conversation: https://secure.helpscout.net/mailbox/dd8c59516d047fb2/chats/59a92162-2b11-4a99-ad6a-2b6b9cfc7aac

**Comment by HardeepAsrani** [comment]
Really not looking to do this in the recent future unless more people need it. Maybe then we can have a hook or something for this.

**Comment by HardeepAsrani** [comment]
Closing as it's up for voting on nolt and we can have it when more people ask for it: https://otter.nolt.io/
