### ISSUE TITLE
Button styling problem in Neve (free) Pricing block

### ISSUE THREAD

**Issue by JessycaFrederick** [Codeinwp/otter-blocks#1520]
I'm using Neve Free. In the Pricing Block (not the Outlines one), there is a styling bug which affects the button on anything bigger than 768px. Screenshots below in Chrome (current) on Mac 12.6.

It *appears* to be related to the div which contains the buttons, and specifically to the use of the `alignfull` class. As in, if I remove that class, the buttons are the correct size.

It is not an issue on mobile or small tablet.

Please and thank you!

<img width="1271" alt="Screen Shot 2023-02-27 at 3 30 49 PM" src="https://user-images.githubusercontent.com/5640068/221714341-85a3d801-2e24-426e-9ceb-e8ed84fe2b7a.png">
<img width="1271" alt="Screen Shot 2023-02-27 at 3 37 42 PM" src="https://user-images.githubusercontent.com/5640068/221714495-db280e19-a2b2-4137-9feb-23d4e1da5c34.png">

<img width="1271" alt="Screen Shot 2023-02-27 at 3 38 22 PM" src="https://user-images.githubusercontent.com/5640068/221714366-07e2b9b4-85b0-4d47-a773-6ecfd346ad6a.png">
<img width="1271" alt="Screen Shot 2023-02-27 at 3 38 04 PM" src="https://user-images.githubusercontent.com/5640068/221714362-f2ef11d1-312e-47af-8ac2-1d62b0ace74e.png">

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani

The `Align Full` need to be set to `None`. Having `width` as `100%` seems to be enough. The buttons expand correctly.



![Image](https://user-images.githubusercontent.com/17597852/224076014-45146086-4c91-4006-a699-b9efbf8588b0.png)

**Comment by Soare-Robert-Daniel** [comment]
This is a Core pattern. The fix will come from the WordPress theme.
