### ISSUE TITLE
Popup close behaviour after opening a new tab

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1539]
### What problem does this address?

When a button that redirects to a page that will be opened in a new tab is added in a popup, the popup will stay active after the user is redirected to the desired page in a new tab. A client wanted to automatically close that popup after the button within it is clicked and the new tab is opened and I think it would be a nice detail to consider adding in the future.

For example, when the button from the popup from [this page](https://indebuurtzoeken.nl/online/alternate/) is clicked, it opens a new tab, but the popup remains open on the first page which doesn't make a lot of sense because the main action within the popup was already performed. At the moment, the user has to manually close it when he comes back to the first page.

Reported [here](https://secure.helpscout.net/conversation/2170128603/359828/).

### What is your proposed solution?

Automatically close the popup if a new tab is opened from it or add a toggle to enable this option.

**Comment by HardeepAsrani** [comment]
It's already possible to it if you're using the Pro version.

<img width="278" alt="Screenshot 2023-03-03 at 11 46 17 AM" src="https://user-images.githubusercontent.com/2649903/222645769-c9269681-07fc-4642-8b84-4550e7df1714.png">

**Comment by HardeepAsrani** [comment]
^ @MarinescuLucia

**Comment by HardeepAsrani** [comment]
Oh wait, thinking about how it works, it won't work with the anchor + link. Maybe we can have something like any button inside the popup that has `close` class trigger close.

**Comment by MarinescuLucia** [comment]
@HardeepAsrani Yes, that Close On Anchor Click option doesn't work in this particular case because you'd have to somehow add two links for the button within the popup, one for the actual page that you want to open and one for the button id so the popup will be closed when clicking on it.
