### ISSUE TITLE
Custom Delay/Speed, Animation Offset & Hover controls for Blocks Animation

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1548]
### What problem does this address?

> With the introduction of the block editor and the lack of ability to assign metadata to your markup makes adding block animations fairly difficult.
> 
> This plugin comes very close to solving this problem but after testing is missing some key features.
> 
> Custom Inputs
> 
> You don’t have the ability to add custom values for delay/speed. This is critical to chaining animations especially when content is ordered into grids/columns. If I have 3 columns each containing an image and I wish to fade in the image one after the other this is not possible using this plugin.
> This renders the animation useless for a large number of content layouts.
> 
> Animation offset
> 
> I’m surprised this is missing from the plugin but you can’t assign an offset to run the animation. Currently, the animations trigger as soon as the content enters the viewport. Although you can add a pre-defined animation delay this is not the same.
> 
> If an element is only just within the view port the delay count down will run. If you want to ensure the full element is in view before running the animation you’d need to be able to assign an offset.
> 
> Hopefully this plugin continues to be developed to better support these 2 common animation features. 

### What is your proposed solution?

Feedback for the plugin posted on WordPress.org: https://wordpress.org/support/topic/so-close-to-being-perfect-3/ - I think it's some good feedback and we can see how we can implement these features, especially the second one that seems not out of box with the library we use.

Also, we can have Hover animations as many users have asked for that over the years.

**Comment by MarinescuLucia** [comment]
Another user mentioned that this would be a nice addition to the plugin.
https://wordpress.org/support/topic/so-close-to-being-perfect-3/#post-16798059

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, regarding the animation offset, I assume he refers to screen offset (like in Sticky)?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yes, I'll go with the custom delay first as offset might not always be easy, but you can do a quick test to see if we can have that as well.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Also, as mentioned, if we can make them work on actions like hover.
