### ISSUE TITLE
Dynamic values: Post Terms is not working for custom taxonomies

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1559]
### Description

Otter Pro allows us to show the Post Terms in the posts using dynamic values features. But it's not working for custom taxonomies. User created a custom taxonomy with CPT UI Plugin and when they try to show the output using post terms tag, it doesn't show anything. Other options are working fine except this one.

### Step-by-step reproduction instructions

1. Create a custom taxonomy  using CPT UI Plugin
2. Try to show it under a custom post type or a default post type using dynamic value feature of Otter
3. check the output

### Screenshots, screen recording, code snippet or Help Scout ticket

HS Ticket >> https://secure.helpscout.net/conversation/2183329666/361728?folderId=212385

### Environment info

 Admin area URL: https://abacksilver.s1-tastewp.com/wp-admin   Username: poonam   Password: rewVRz8xYnw 

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
Thank you @poonam279. It's not a bug but this isn't supported by Otter at this point in time. We will add it to an upcoming version, seems useful.
