### ISSUE TITLE
Stripe Checkout - PHP Error when displaying the block with a different API key

### ISSUE THREAD

**Issue by milicavs** [Codeinwp/otter-blocks#1564]
### Description

A PHP error gets thrown when trying to open a page where a Stripe Checkout block is added if the products in the block do not correspond with the Stripe account we added the API key for.
The error occurs both when trying to view and edit the page.

### Step-by-step reproduction instructions

1. Open the Otter setting and add the live Stripe API key
2. Create a page and add a Stripe Checkout block. Select a product from the live environment and save the page
3. Go back to Otter settings and replace the Stripe API key with another one (test mode, for example)
4. Go back and try to view the page where we added the block
5. We get the 'There has been a critical error on this website' message

### Screenshots, screen recording, code snippet or Help Scout ticket

`2023/03/23 07:13:14 [error] 72364#72364: *480482 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /www/finmasters_407/public/wp-content/plugins/otter-blocks/inc/render/class-stripe-checkout-block.php:54
Stack trace:
#0 /www/finmasters_407/public/wp-includes/class-wp-block.php(256): ThemeIsle\GutenbergBlocks\Render\Stripe_Checkout_Block->render(Array, '', Object(WP_Block))
#1 /www/finmasters_407/public/wp-includes/class-wp-block.php(242): WP_Block->render()
#2 /www/finmasters_407/public/wp-includes/class-wp-block.php(242): WP_Block->render()
#3 /www/finmasters_407/public/wp-includes/class-wp-block.php(242): WP_Block->render()
#4 /www/finmasters_407/public/wp-includes/class-wp-block.php(242): WP_Block->render()
#5 /www/finmasters_407/public/wp-includes/blocks.php(1051): WP_Block->render()
#6 /www/finmasters_407/public/wp-includes/blocks.php(1089): render_block(Array)
#7 /www/finmasters_407/public/wp-includes/class-wp-hook.php(308): do_blocks('<!-- wp:group {...')
#8 /www/finmasters_407/public/wp-include" while reading response header from upstream, client: 87.116.134.51, server: finmasters.com, request: "GET /?page_id=205874&preview=true HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8.0-fpm-finmasters.sock:", host: "finmasters.com:39442", referrer: "https://finmasters.com/wp-admin/edit.php?ac-actions-form=1&orderby=title&order=asc&s=hedge&post_status=all&post_type=page&m=0&cat=0&ppc-select=ebff841b62&slect_opt&seo_filter&readability_filter&layout=6112195782214&action=-1&paged=1&action2=-1"`

### Environment info

https://pastebin.com/Ty95vMRs

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
At first glance, the Block is tied to the account info. Information about the product is saved like `prod_NcaZeElg7rWb1K`, just like Stripe Dashboard. Naturally, when you switch the account, the data is no longer valid, and the API tries to retrieve a product that does exist, thus emitting an Error. Since no error handling is in place, the function crash.
