### ISSUE TITLE
Product Select Component is not working

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1575]
### Description

Add to cart button block is not working anymore. There is no option to select the product and it shows "There seems to have been an error".

### Step-by-step reproduction instructions

1. Add an add to cart button block to any page.

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="824" alt="Screenshot 2023-03-29 at 10 05 43 PM" src="https://user-images.githubusercontent.com/27731529/228607759-020c7d3d-6352-4bae-a67e-b313af67eb4d.png">

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by HardeepAsrani** [comment]
@poonam279 In my memory, this hasn't happen before so removing the regression label.

**Comment by HardeepAsrani** [comment]
@arinaturcu Few things, you can make sure it works everywhere SelectProducts component is used. Also to check with the past version of Woo, where this was working properly, and make sure it keeps working with that.
