### ISSUE TITLE
Spacing between columns on mobile

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#159]
Not sure if this is how it should be supposed to work or not.
I added a new section with 5 columns, didn't change any margin/padding for the section or the columns, and from what I've seen they all have the same values.
On Desktop everything's ok but on mobile, the spacing is different for all the other columns, except the first one ( bigger left/right spacing, and between the columns )

![download (2)](https://user-images.githubusercontent.com/3266155/77235321-5e1a6300-6bbd-11ea-8d92-5f5493ee4662.png)

![FireShot Capture 022 - test – site title - localhost](https://user-images.githubusercontent.com/3266155/77235284-26132000-6bbd-11ea-9f12-82f3ac35692e.png)

**Comment by HardeepAsrani** [comment]
@rodica-andronache Can you try it with the latest version? I tried and it worked just fine.

**Comment by rodica-andronache** [comment]
it's working well 👍
