### ISSUE TITLE
Dynamic tags do not work with Neve PRO custom layouts

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#1600]
### Description

Inserting dynamic tag into Neve PRO Custom Layout is not possible, gives an error when saving:
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/36594177/230612997-17a08bbe-4892-4652-b881-e80b10f4cda5.png">

### Step-by-step reproduction instructions

- Go to layouts, create a new layout
- Choose post template
- Name the template
- Add dynamic title, content and featured image. (actually, adding any dynamic tag is enough - https://docs.themeisle.com/article/1677-dynamic-values )
- Add conditonal logic "post type is equal to something
- Try to save

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2189970724/362599

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
The client shared additional details in case you find them helpful:

> In the file wp-content/plugins/otter-blocks/inc/plugins/class-dynamic-content.php line 373 is the function get_content() that is called from the same file line 304 in get_data() which is called from apply_data() earlier in the file as a callback to the preg_replace_callback() call in apply_dynamic_content() on line 49. That regexp looks like a known problem based on the comment "// Todo: Improve this Regex, it can't go on for like this. Soon it will be longer than the available space in the universe!!!".
> Maybe some other approach could be considered, like a state machine or by using an html parsing library.
> 
> Commenting out "apply_filters()" in the function "get_content" prevents the error, but then no detail is shown on the konstnär detail so it's not a viable workaround, but more of a confirmation about the whereabouts of the problem.
> 
> public function get_content( $data ) {
> //$content = apply_filters( 'the_content', str_replace( ']]>', ']]>', get_the_content( $data['context'] ) ) );
> $content = str_replace( ']]>', ']]>', get_the_content( $data['context'] ) );
> return wp_kses_post( $content );
> }
> 
> Stack trace that shows the relevant function calls in reverse order
> 
> #226 /var/www/html/wp-content/plugins/otter-blocks/inc/plugins/class-dynamic-content.php(374): apply_filters('the_content', '<!-- wp:paragra...')
> #227 /var/www/html/wp-content/plugins/otter-blocks/inc/plugins/class-dynamic-content.php(304): ThemeIsle\GutenbergBlocks\Plugins\Dynamic_Content->get_content(Array)
> #228 /var/www/html/wp-content/plugins/otter-blocks/inc/plugins/class-dynamic-content.php(234): ThemeIsle\GutenbergBlocks\Plugins\Dynamic_Content->get_data(Array, false)
> 
> #229 [internal function]: ThemeIsle\GutenbergBlocks\Plugins\Dynamic_Content->apply_data(Array)
> #230 /var/www/html/wp-content/plugins/otter-blocks/inc/plugins/class-dynamic-content.php(49): preg_replace_callback('/<o-dynamic(?:\\...', Array, '\n<p><o-dynamic ...')

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, the problem is caused by an infinite loop in `get_content` function.

https://github.com/Codeinwp/otter-blocks/blob/ba635975b4a0ad710f8dc8d7c8e60e563e490673/inc/plugins/class-dynamic-content.php#L373-L376

When `apply_filters` is called, it triggers the infinite loop.

In the image below, left side, you see the call stack being repeated.

![Image](https://user-images.githubusercontent.com/17597852/231747733-aff89b81-d06c-4df9-b8ce-770efddc9929.png)

Any idea on the behavior?
