### ISSUE TITLE
CSS updating in editor but not on site

### ISSUE THREAD

**Issue by Decodingsand** [Codeinwp/otter-blocks#1614]
### Description

CSS feature is working in the Guttenberg block editor, but the css is not getting updated on the site.

Wordpress 6.2
Template: Twenty Twenty-Three

### Step-by-step reproduction instructions

1. Go to wordpress appearance/editor/template parts/header
2. Insert a search widget into the header
3. Custom theme the css for that search widget

.wp-block-search__inside-wrapper {
    border-width: 1px !important;
    border-style: solid !important;
    background: burlywood;
}

.wp-block-search__input has-small-font-size{
  font-size: 20px !important;
}

4. See the widget update live in the editor
5. Save the header page and refresh the browser - css does not update

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1726" alt="Screen Shot 2023-04-12 at 12 04 37 PM" src="https://user-images.githubusercontent.com/4364980/231516646-bdd2d6e8-960c-427c-89f2-de5345a1cea1.png">

<img width="1728" alt="Screen Shot 2023-04-12 at 12 06 25 PM" src="https://user-images.githubusercontent.com/4364980/231517647-2a396920-61bf-44db-a6db-2df2e36b4063.png">

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@Decodingsand Would it be possible for you to add the code and share the link to your website so we could check this?

**Comment by Decodingsand** [comment]
Unfortunately not - it is installed on a local server for development. I
have fixed this with a different solution.

This error got raised with a standard wordpress template so you should have
no problem recreating the bug.

Good luck
Thanks
