### ISSUE TITLE
Reusable Product Reviews don't appear in the Review Comparison table

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1628]
### Description

If a Product Review block is set as a Reusable block, it won't be possible to select it in the Review Comparison Table block. Is this the desired behaviour?

### Step-by-step reproduction instructions

1. Add two Product Review blocks
2. Make one or both of them Reusable
3. Add a Review Comparison Table block
4. Try to select the review and check that it's not possible to choose the reusable ones

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2220553199/366926/

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
Duplicate of https://github.com/Codeinwp/otter-blocks/issues/1622
