### ISSUE TITLE
Hide the Pro Upsell card in the onboarding modal - if user has Pro already

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1637]
### Description

As mentioned in the video, is it possible to hide the Upgrade to Pro step - **if the user already has the Otter Pro activated**?
https://youtu.be/L68FM83sxg0?t=337

### Step-by-step reproduction instructions

1. Create a fresh instance
2. Install Otter Free & Pro
3. Open a page for the first time in Gutenberg
4. Notice that in the Otter onboarding Modal, the Pro upsell appears even if Pro is active
![image](https://user-images.githubusercontent.com/52494172/235103413-83eecfe8-70ec-4cb6-a58e-864dddf415ab.png)

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@mghenciu This is meant meant to be for Users with Otter Pro. We're assuming here, given it shows in the beginning only not if you're actively using the plugin, that it's your initial use. So Learn More takes you to Otter Pro Docs, not to upsell. Let me know if it makes sense.

**Comment by mghenciu** [comment]
It makes sense, but can be a bit confusing - as the Image + Copy sound more like an upsell, and not as a suggestion to open the Docs. Same thing was pointed in the video, that it looks like an upsell to Pro.

Another direction could be to change the Headline for Pro users, and say something like: 
**You are all setup to use Otter Pro**
Text below: _With Otter PRO you have access to our advanced features, like Dynamic Content and the Premium Blocks. Learn more_

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, should we hide the Modal or change the text as @mghenciu suggested for this issue?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel we can change the text.
