### ISSUE TITLE
Dynamic tags don't work inside widgets

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#1652]
### Description

When i try to add a dynamic tag inside the sidebar, the block breaks and i'm getting a console error. I rolled back the plugin and it stopped working with Otter 2.2.4 . https://vertis.d.pr/v/g5XqrE

### Step-by-step reproduction instructions

1. Go to Appearance > Widgets > Sidebar
2. Try to add some dynamic content
3. Check the console error

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/g5XqrE

### Environment info

Otter 2.2.6 / Wordpress 6.2 / PHP 7.4

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by HardeepAsrani** [comment]
Thank you @irinelenache, seems like this was broken in https://github.com/Codeinwp/otter-blocks/pull/1554
