### ISSUE TITLE
[Rock] Upgrade project dependancy 

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/otter-blocks#1667]
### What problem does this address?

Otter dependencies are far behind Gutenberg. We need to keep up with having access to the latest tools for testing and development.

### What is your proposed solution?

Bump the dependencies and solve the related issues that might appear.

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel it's working well 👍

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel We can merge it or there are any other steps/testing needed?
