### ISSUE TITLE
In which table of the data base is the form data stored?

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1670]
### Description

A customer asked where in the database is the data from the Otter Contact form stored.

Hardeep, can you please help me with this info? Thank you!

### Step-by-step reproduction instructions

Question from the customer

``` I noticed the Otter forms. That looks quicker then the forms i use right now, but i could not find a way to see the filled in forms (database) or send a copy to the sender. And it looks like the error message is not shown in the right language (not in the builder).```

### Screenshots, screen recording, code snippet or Help Scout ticket

Asked here: https://secure.helpscout.net/conversation/2240776522/369303/

### Environment info

not relevant for this case

### Is the issue you are reporting a regression

No

**Comment by arinaturcu** [comment]
Right now, the data is not stored anywhere, but with this PR https://github.com/Codeinwp/otter-blocks/pull/1571 they will be stored in a custom post type and will be available just for pro users.
