### ISSUE TITLE
Add option to export the form submissions

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#1671]
### What problem does this address?

When the feature for saving the form submissions in the database is out, the users will probably want to be able to export the entries that are visible [here](https://vertis.d.pr/i/CN9NGn). Also, if there are multiple forms created, it should be nice to filter the submissions by the forms where they come from. 

### What is your proposed solution?

Adding a button on [this page](https://vertis.d.pr/i/CN9NGn) where the user can click and the form submissions will be downloaded in a specific format (csv/xlsx/xml) 

cc @Soare-Robert-Daniel

**Comment by HardeepAsrani** [comment]
I think we can do it just using the default WordPress exporter but will be a good to somehow implement it using the Otter UI in future.

**Comment by HardeepAsrani** [comment]
For this, you can do some research first on WordPress what will be the easiest way to prepare and export. We can look into how WP export posts and use the same functionality without coding our own.

**Comment by Soare-Robert-Daniel** [comment]
By using the WP Tools > Export. We already can export he data as XML.

An item in the XML looks like this:

```xml
<item>
		<title><![CDATA[Submission #825]]></title>
		<link>http://localhost:10007/otter_form_record/825/</link>
		<pubDate>Wed, 16 Aug 2023 10:30:17 +0000</pubDate>
		<dc:creator><![CDATA[robert]]></dc:creator>
		<guid isPermaLink="false">http://localhost:10007/otter_form_record/825/</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>825</wp:post_id>
		<wp:post_date><![CDATA[2023-08-16 10:30:17]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2023-08-16 10:30:17]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2023-08-16 10:30:17]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2023-08-16 10:30:17]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[825]]></wp:post_name>
		<wp:status><![CDATA[unread]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[otter_form_record]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:postmeta>
		    <wp:meta_key><![CDATA[otter_form_record_meta]]></wp:meta_key>
		    <wp:meta_value><![CDATA[a:4:{s:4:"form";a:2:{s:5:"label";s:4:"Form";s:5:"value";s:39:"wp-block-themeisle-blocks-form-38624739";}s:8:"post_url";a:2:{s:5:"label";s:8:"Post URL";s:5:"value";s:48:"http://localhost:10007/820/form-success-message/";}s:7:"post_id";a:2:{s:5:"label";s:7:"Post ID";s:5:"value";s:3:"820";}s:6:"inputs";a:1:{s:8:"627f6f16";a:4:{s:5:"label";s:14:"(Field 1) Name";s:5:"value";s:4:"roby";s:4:"type";s:4:"text";s:8:"metadata";a:2:{s:7:"version";s:1:"1";s:8:"position";s:1:"1";}}}}]]></wp:meta_value>
		</wp:postmeta>
</item>
```



![Image](https://github.com/Codeinwp/otter-blocks/assets/17597852/c71c06ad-bbdf-4a4d-ae33-ee79940038a0)
