### ISSUE TITLE
Form wrong default save location

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1676]
### Description

As it was discussed, the default should be database & email but I see when Pro is activated, the default is set to just database. The change was made here but seems like was later changed: https://github.com/Codeinwp/otter-blocks/pull/1571/commits/b8b76fa1742497889d70e440b1a0cc8240da9ff3

To recap,

If it is Pro, the default behavior should be Database & Email.
If it is free, the default should be Email which is the only available option.

### Step-by-step reproduction instructions

1. Add a Form with Pro activated
2. The default save location is set to Database instead of Email & Database

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="281" alt="Screenshot 2023-05-26 at 10 49 54 PM" src="https://github.com/Codeinwp/otter-blocks/assets/2649903/e3427b85-9d6c-482c-afc9-ee6e4aef922d">

### Is the issue you are reporting a regression

No

**Comment by rodica-andronache** [comment]
@arinaturcu when activating Otter Pro, the default value for me is `Database`, not `Database and Email`, as it should be

**Comment by Soare-Robert-Daniel** [comment]
@arinaturcu, it would help if you put a default value here

https://github.com/Codeinwp/otter-blocks/blob/5ab20875f1bd72ceeb46081f20026b0d73c30b71/src/pro/plugins/form/index.js#L81

If the value is `undefined`, it will how the first value as default, but now we need to show the third one.

**Comment by arinaturcu** [comment]
Thanks, @rodica-andronache 🚀
Should work as expected now.

**Comment by irinelenache** [comment]
@arinaturcu Tested and it works as it should now ✔️
