### ISSUE TITLE
Update sdk & configure the about page

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#1680]
### What problem does this address?

@HardeepAsrani would be great if we can configure the About us page & the upgrade link here : https://github.com/Codeinwp/themeisle/issues/1434 for the next release.

**Comment by HardeepAsrani** [comment]
Details on how to configure: https://github.com/Codeinwp/themeisle-sdk/blob/master/src/Modules/About_us.php#L1-L25
