### ISSUE TITLE
Posts block doesn't take into consideration Sticky posts

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1699]
### Description

I've marked one of the blog posts, not the latest one, as Sticky. When using the Posts block to display it, it's not taken into consideration, posts are listed based on the date only.

### Step-by-step reproduction instructions

1. Make sure to have at least two posts.
2. Make only one of them sticky - not the last updated/published, but the one being displayed as last on the blog page
3. Set the Posts block and enable the featured posts, choose the Sticky option there

![Markup on 2023-06-05 at 12:34:33](https://github.com/Codeinwp/otter-blocks/assets/26867648/872f71fc-6a57-41ce-9143-c73414b420d4)

5. The Featured post in the Posts block won't be the sticky one
enable

### Screenshots, screen recording, code snippet or Help Scout ticket

[Here is](https://vertis.d.pr/v/jFZEdg) a video.

Reported here: https://secure.helpscout.net/conversation/2257905909/371354/

### Environment info

https://pastebin.com/Kebeq47X

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you check how the Core block works and we can follow the same approach with this?

**Comment by HardeepAsrani** [comment]
So currently the Posts Block is consistent with how the Core one works?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani yes.
