### ISSUE TITLE
Radu's Feedback for Otter Blocks

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#17]
@HardeepAsrani, Here's my feedback for the current version:

_Warning: long post ahead!_ 😁

**Advanced Columns**

- [x] block added in previous column instead of the column where you try to add: https://www.useloom.com/share/a3a68ffea6004a0cb63d54059a6bc015
- [x] There are 2 shape dividers that don't have the "invert" option: curve and clouds
- [x] If you set the column's background to a dark color the placeholder in it is not visible and it seems hard to see that you can click inside to start typing or add a block: https://www.useloom.com/share/254d8ad925434661977ad404fc92704e
- [ ] when selecting the image it reduces its size and overlaps previous block, the reduced size also renders on the front: https://www.useloom.com/share/e67fee570a7647f4b1728d75ce690e70; http://prntscr.com/m7wu05

These 2 problems seem to be related to Gutenberg or the theme (Neve):
- [x] In a column inside the advanced columns, having a background image, when you click the background settings button it look like adding something as the scroll bar starts to shrink looking like the page is growing in length. It seems to reset when you click anywhere in the page but not in the toolbar (this happens an all the buttons, like the responsive setting button for example): https://www.useloom.com/share/9bc101a9b7184f5f9715c2fafef5a09d
- [x] The same behavior happens when hovering over the buttons and the tooltip appears, and when clicking on the button: https://www.useloom.com/share/21ec653239fa483a9ad2fd3c53f35fe6

- [x] In Advanced Columns, when setting the linked value for padding to 0, unselect the block and then select it again the padding is unlinked with the top and bottom values being empty and left-right back to default (20px). I also tried putting a random value (12px) and the only difference was that the top value was set to 12, everything else was as before (see screenshot): https://www.useloom.com/share/e54e53065b734d25903a09dadd3f8e9f; http://prntscr.com/m7xcja
- [x] When setting the linked value for margin to a certain number if you unlink you get the default values (20px), it should give you the value set when it was linked: https://www.useloom.com/share/45f1ad3a26b140a6a1cd100fd3c5c74a
- [x] We should add a hover effect for responsive options, right now there's no feedback so users can't understand, visually, if the input works: https://www.useloom.com/share/f53e530b1d574ef0bc128ae19e3606e6
- [x] _Idea_: why not have 3 buttons with the devices instead of a menu, where there is room for it and removing the menu to simplify the interface. Keep the button just for padding/margin.
- [x] We can remove the title "Responsiveness Settings" they are pretty self explanatory.
- [x] The horizontal and vertical align seems not to work  if minimum height is set to "default", we should hide the options when "default" is selected: https://www.useloom.com/share/88575735872140bfbc51b1c162d08e6f
- [x] _Idea_: make the option of vertical alignment at column level. This way you can vertically align each column as you need (e.g. maybe you want to create a cascade effect)
- [x] The control slider for content width and custom height "reset" if you exit the toolbar with the controller selected: https://www.useloom.com/share/444fb0cfb7524395952140118ba6cae3
- [x] I don't believe a "reset" button is justified here, users can delete the value and it will revert to the default: http://prntscr.com/m7y1ka
- [x] In box shadow we have "Border Shadow" and I believe it should be better called "Shadow Properties"  : http://prntscr.com/m7yj7q
- [x] If "custom height" is selected, you input a number and then want to reset it pressing _backspace_ or _delete_ keys don't work, only inputting _0_ (seems to be the case for all these type of inputs): https://www.useloom.com/share/eefbd37aff404fa288dad1ecd8b3649a

**FA Icons**
- [x] "Inner space" is better called "Padding" and "Outer Space" called "Margin. There not that descriptive as Inner/Outer Space and seems against "the standards" which might confuse people regarding their purpose.
- [x] "Icon Color" instead of "Text Color"
- [x] Options from "Icon sizes" should be moved under "Icon settings", and instead of "Text size" write just "size": http://prntscr.com/m7yvp1
- [x] We should have a menu with icon previews (similar to this one: http://prntscr.com/m7yx8b), I see that if you start writing something in the input it gives you suggestions, so it's best to add a button on the right of the input with an arrow-down so that people know there's a menu there; and/or a link to FA's[ list of free icons](https://fontawesome.com/icons?d=gallery&m=free) on their site
- [x] _Idea_: make the input the same width as the longest name from the list so it doesn't look to wide. Probably adding that arrow-down button might solve this.
- [x] I noticed in the picker input there's a placeholder "Start typing, like themeisle...". I didn't see it until I accidentally emptied the input. We should remove the default text in the input so that the placeholder is visible by default, but still have the "themeisle" icon render by default in these 2 places: http://prntscr.com/m7z227
- [x] I placed the icon inside a column and when I aligned it to the left and the text wrapped next to it(same thing for right alignment): http://prntscr.com/m7z59w; http://prntscr.com/m7z5ta; It makes sense in the content of a blog post, but I strongly believe we should have an alignment for the icon (like text align) without text wrapping next to it.

**Advanced Heading**
- [x] When I choose a font from the list a certain font weight appears as default which seems to be different depending on the font. The issue is that that default doesn't render in some cases so it should always default to "normal" regardless of the font or keep the font-weight previously selected. In my video for Poppins font the default goes to 100 but it's not actually rendered. It's not until I change it and go back to 100 that I see the 100 font-weight. So the actual issue is that the font-weight displayed is the first one in the list instead of displaying "regular" as font-weight by default is set to "normal": https://www.useloom.com/share/79c7bfa6c1254bdb8e7b5d2191c645ce
- [x] I think we can move also the padding/margin settings and remove the Advanced Tab
- [x] It seems that strong doesn't work with the defaults as font-family is set to "undefined", it should be set to "inherit": http://prntscr.com/m7zsb3

- [x] Highlight Color should be in the Style tab, under Color Settings, and write "Highlight Text Color" instead of "Highlight Color"
- [x] There's a case where you can end up selecting the heading and deactivating the menu in the top-left corner, I couldn't ascertain a pattern but it happened a couple of times: https://www.useloom.com/share/ef33cd89f7684125af22c7b94e63894f
- [x] This is related to the previous point, if we make sure 100% the menu doesn't disappear, we can remove "Font Style" from the settings as users can apply italic from the top-right menu.
- [x] Reset button and "backspace"/"delete" key don't work for: text size, line height and letter spacing: https://www.useloom.com/share/dcb63d978f924fb2a1e1b7aa3deaeeb3; IMHO why would we need a reset button for text-size? Maybe to reset to the theme's default heading size?
- [x] Text Shadow: rename the shadow properties to "shadow properties: http://prntscr.com/m80mhh
- [x] We should also make available system fonts, not only Google Fonts
- [x] When I'm searching for a font-family through the list I might not know from the first time what font I want, so if I select one and then come back to choose another one I should see the name in the search input and also see it selected in the list so I can continue searching from where I was, not having to scroll again back to where I was: http://prntscr.com/m8029j

**Button Group**
- [x] "Button to Edit" change to "Edit button:" and then put the dropdown inline, or make the list with tabs so that when you select a button it's very clear that the settings below are for that button.

- [x] Block should prefix button link with "http/https". If you write the link without prefixing with that the link will not work.
- [x] Move everything to the Style tab and remove the Group Settings
- [x] Border width & radius should be enabled to be different on hover (we could leave this one for later)
- [x] Spacing: left aligned buttons are ok, right aligned buttons should work like left aligned (but mirrored). When centered it looks like the button on the left increases space more than the right one, what I mean is that spacing seems to not be distributed equally: https://www.useloom.com/share/25fe2a6ac91c4dce8a2f5bda7b6590ca
- [x] Color: add a transition when hovering, or inherit it from the theme
- [x] Icon Settings should be under link and have an option to control the color independent of the text
- [x] Typograph: same thing for font family, weight and style as in the case of the heading.
- [x] Box Shadow should not be a separate option, should be right beneath border properties, and also change the text for the properties to "Shadow properties/ Shadow properties on hover"
- [ ] Right now there's no feedback when you select the button and might not be that obvious for less skilled users.

**Sharing Icons**
- [x] (theme related I think) in the backend the text color when using regular is in some cases the same color as the background: http://prntscr.com/m813hu; but on the front it doesn't look so great either: http://prntscr.com/m815kk

**Posts Grid**
Looks good 😃
- [x] One strange thing, the first time I added it the block became invalid (like it happened to iThemes) but after deleting and adding it again I never managed to get an error again.
One idea would be that maybe only the first time with a fresh WP the block would error and after that it would work as the info required to display posts is already recorded in the DB (might be a dumb idea but I think it's worth mentioning it.

_Originally posted by @radu-themeisle in https://github.com/Codeinwp/otter-blocks/issues/8#issuecomment-454847025_

**Comment by HardeepAsrani** [comment]
`block added in previous column instead of the column where you try to add: https://www.useloom.com/share/a3a68ffea6004a0cb63d54059a6bc015`

This is a fault with Gutenberg, reported here: https://github.com/WordPress/gutenberg/issues/13349

**Comment by HardeepAsrani** [comment]
> when selecting the image it reduces its size and overlaps previous block, the reduced size also renders on the front: https://www.useloom.com/share/e67fee570a7647f4b1728d75ce690e70; http://prntscr.com/m7wu05

Can you explain this more? I'm a little not sure about how it happens. Also, can you also see if this happens in the default Columns block too, or is an issue exclusively with Otter?

**Comment by HardeepAsrani** [comment]
> There are 2 shape dividers that don't have the "invert" option: curve and clouds

If this happens, it can either for two reasons:

- That divided doesn't need the invert setting.

- My SVG skills aren't good enough to write the same SVG in reverse. This is probably the reason with Clouds. 😄 😆

**Comment by HardeepAsrani** [comment]
> This is related to the previous point, if we make sure 100% the menu doesn't disappear, we can remove "Font Style" from the settings as users can apply italic from the top-right menu.

This thing is little confusing. I understand your point, but the weird thing is that both Italic options are for separate reasons.

- The one in toolbar is to make some particular part of the heading italic.
- The one in typography is to load Google Font with Italic property.

But you're right, we can make it better.

**Comment by HardeepAsrani** [comment]
> (theme related I think) in the backend the text color when using regular is in some cases the same color as the background: http://prntscr.com/m813hu; but on the front it doesn't look so great either: http://prntscr.com/m815kk

Theme related.

**Comment by HardeepAsrani** [comment]
> Block should prefix button link with "http/https". If you write the link without prefixing with that the link will not work.

Just didn't do it in case the person doesn't want a protocol there, like if you want a relative URL like `#anchor`, or you want something like `mailto:email@address`

Makes sense, or you have something else in mind?

**Comment by HardeepAsrani** [comment]
> I think we can move also the padding/margin settings and remove the Advanced Tab

I've kept it there for things that won't be used much often. Not just for now, but also for the options we will be adding in future.

**Comment by HardeepAsrani** [comment]
> Move everything to the Style tab and remove the Group Settings

It only has options that are set Group-wise, not per-button. Why do you think they should be kept together? Is it confusing or anything? :)

**Comment by HardeepAsrani** [comment]
> One strange thing, the first time I added it the block became invalid (like it happened to iThemes) but after deleting and adding it again I never managed to get an error again.
> One idea would be that maybe only the first time with a fresh WP the block would error and after that it would work as the info required to display posts is already recorded in the DB (might be a dumb idea but I think it's worth mentioning it.

I've figured out what was causing the issue with iThemes and fixed it already. I believe you faced the error for some other reason that we need to figure out. Can you try on a fresh install and see if this happens again? I has worked for me just fine.

**Comment by selul** [comment]
@HardeepAsrani let's try to solve the issues that make sense in the next release, please tag the fixes in commits to this issue.

**Comment by HardeepAsrani** [comment]
> Icon Settings should be under link and have an option to control the color independent of the text

Icon won't be used in the most of the situations, so that's why kept it after usual options.

> Border width & radius should be enabled to be different on hover (we could leave this one for later)

I'll mark this as checked as I don't see this being asked from users, but will keep open if more people ask for it.

**Comment by HardeepAsrani** [comment]
> Right now there's no feedback when you select the button and might not be that obvious for less skilled users.

Nice catch, should find a good UX for this.

**Comment by HardeepAsrani** [comment]
Closing this ticket and moving the feedback to their own separate tickets.
