### ISSUE TITLE
Error message does not correspond

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1705]
### Description

The error message displayed is not the same as the error message that I configured.

### Step-by-step reproduction instructions

1. Insert and configure a form block.
2. Open the Submit Messages accordion.
3. Configure a new error message.

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1676" alt="image" src="https://github.com/Codeinwp/otter-blocks/assets/86592992/cebd5bde-0790-4fa5-8719-d6b6af130955">

### Is the issue you are reporting a regression

No

**Comment by AndreeaCristinaRadacina** [comment]
Similar problem with the Success message, only that this appears well in the editor- https://www.loom.com/share/f780734fcab54664a38e9a80fed16e8f

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Correct me if I'm wrong but that error message is just there as a representation or it's supposed to update?

**Comment by Soare-Robert-Daniel** [comment]
It is as displayed. But intendent, I forgot to sync with the real message.

https://github.com/Codeinwp/otter-blocks/blob/5ab20875f1bd72ceeb46081f20026b0d73c30b71/src/blocks/blocks/form/edit.js#L986

**Comment by HardeepAsrani** [comment]
Closing in favor of https://github.com/Codeinwp/otter-blocks/issues/1804
