### ISSUE TITLE
Redirect option of Form block is not working correctly 

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/otter-blocks#1706]
### Description

Hey there, a customer has reported that the redirect form option of the Otter plugin is not working properly, it is not redirecting the users to the page configured by the user.
 
For a better understanding kindly refer to the screencast shared below.

Thank you @AndreeaCristinaRadacina for helping me in testing this bug and also for creating the screencast video 

### Step-by-step reproduction instructions

1. Install the latest version of Otter.
2. Create a page and add a form block.
3. Try to go to form settings and enable the redirection form options.
4. Now add any site or page that you want to redirect your users to after submitting the form.
5. Publish the changes and try to do some test entries and you will notice that you are not being redirected anywhere.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2261498292/371802/
https://www.loom.com/share/1e8ac3cfc84c4a829723074c2d8984d3

### Is the issue you are reporting a regression

No

**Comment by stefan-cotitosu** [comment]
https://secure.helpscout.net/conversation/2292554521/376423?folderId=212385
