### ISSUE TITLE
Compatibility warning between Otter blocks and otter pro 

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/otter-blocks#1709]
### Description

Hey there, I have spotted an error for Otter which appears to be the same as this issue for Neve and Neve pro- https://github.com/Codeinwp/neve-pro-addon/issues/2514

I see this error on the plugin's page when attempting to use otter pro with a previous version of Otter.

`Warning: This plugin has not been tested with your current version of Otter – Page Builder Blocks & Extensions for Gutenberg. Please update Otter – Page Builder Blocks & Extensions for Gutenberg plugin.`

I am not aware if this was intended so that users keep Otter and Otter Pro updated or an issue.

Thank you!

### Step-by-step reproduction instructions

1. Install otter pro's latest version.
2. Install otter block Version 2.2.7.
3. You will see a warning on the plugins page.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/i/zraH3T

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@kushh23 Yea, we can't test an old version a new version so it's normal to be this way.

**Comment by kushh23** [comment]
Okay thank you @HardeepAsrani , you can close the issue then.
