### ISSUE TITLE
Otter 2.4

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1715]
I'll be posting things for Otter 2.4 here to keep it in one place for milestone:

- https://github.com/Codeinwp/otter-internals/issues/89
- https://github.com/Codeinwp/otter-internals/issues/82
- https://github.com/Codeinwp/otter-internals/issues/95
- https://github.com/Codeinwp/otter-internals/issues/96
- https://github.com/Codeinwp/otter-internals/issues/97

**Comment by mghenciu** [comment]
Nice ideas! 🚀 

For the Stripe and Webhooks, **I think it may be important to evaluate the effort vs value**. I mean this 2 features will be Pro features, which means the user pool is already smaller; + this features are oriented to more Advanced users, which again makes the user pool even smaller.

Another thing for the Webhook I think is **having a pretty good doc about this feature** (not huge, but rather with an example so users get the idea behind it). For example in case of Kadence, I see that customers are mentioning this - [that the docs are not covering Webhooks.](https://www.kadencewp.com/support-forums/topic/documentation-for-webhooks/)

**Comment by HardeepAsrani** [comment]
@mghenciu In my Webhook article, I've pointed that before we release, we can test by creating few examples with Slack or HelpScout and put them as docs, so that should help users. This can be useful in case we want to turn them sort of pre-defined actions too in the future.

For value, if we have the options for Stripe/Webhook, it does open a possibility to promote them through articles/videos. @selul can have more insights and which features should be free/pro, and we can decide from there.

PS: We can discuss more about them in their tickets as they're private issues, and this is a public one.

**Comment by HardeepAsrani** [comment]
Closing this as we've the milestone set here: https://github.com/Codeinwp/otter-internals/milestones/1/
