### ISSUE TITLE
More info link missing for Stripe

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#1722]
### Description

The link in Otter Blocks > Settings > Stripe > More info is empty

### Step-by-step reproduction instructions

![Annotation-Annotation on 2023-06-19 at 18-42-55 png](https://github.com/Codeinwp/otter-blocks/assets/3266155/9ec747a8-93bf-4d90-b330-d872bb62cb26)

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
Thank you for noticing it, we can link it to https://docs.themeisle.com/article/1688-integrations-related-blocks#stripe-checkout
