### ISSUE TITLE
Box Shadow color doesn't change on Section Columns

### ISSUE THREAD

**Issue by RohanSharma2598** [Codeinwp/otter-blocks#1723]
### Description

The customer reported this bug. When adding a Section with let's say two columns and trying to place the Box Shadow to the column, the color of the box shadow can't be changed and no matter what color is selected in the settings, it will always show Black color on the shadow.

### Step-by-step reproduction instructions

1. Go to Edit Page and Add a section with two columns
2. Select one of the column and go to the Section Column Settings > Style > Border, Enable Box Shadow and try applying the Box Shadow with any random color and save the changes.
3. Check the shadow on the frontend and the color will show black.

### Screenshots, screen recording, code snippet or Help Scout ticket

Help Scout: https://secure.helpscout.net/conversation/2264389122/372067?folderId=212385

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
This happens when using color from the presets. The presets offer a string of a CSS variable name instead of the color value.

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/10ddc5af-aef9-4d0c-a3cd-5d13c4808d9c)

@HardeepAsrani, do you think it is better to remove the presets options?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel If I remember, we use a same workflow in some other part of Otter to fetch the variable value and use it instead?

**Comment by Soare-Robert-Daniel** [comment]
In Flip, if you have an opacity lower than 100, when you select a color with CSS `var`, we get the color from that `var`.

https://github.com/Codeinwp/otter-blocks/blob/a2ae0259796de71cb14ac07ff7adbfc80faf3767/src/blocks/blocks/flip/inspector.js#L120-L126

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yes, we can't have the same thing here?
