### ISSUE TITLE
Warning: This plugin has not been tested with your current version of Otter Pro

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#1726]
### Description

With the latest versions of Otter 2.3.1 and Otter Pro 2.3.0 there is a warning:
`Warning: This plugin has not been tested with your current version of Otter Pro. Please update Otter Pro plugin.`

### Step-by-step reproduction instructions

<img width="1289" alt="Screenshot on 2023-06-21 at 10-06-04" src="https://github.com/Codeinwp/otter-blocks/assets/3266155/cb65c443-0522-4929-b018-f6a3de164021">

### Is the issue you are reporting a regression

No

**Comment by MarinescuLucia** [comment]
+1 https://secure.helpscout.net/conversation/2284087585/374534/

**Comment by HardeepAsrani** [comment]
@MarinescuLucia Can you ask the user which version of Otter and Otter Pro they're using?

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani, I can replicate the issue as well.

Otter Blocks: 2.3.1
Otter Pro: 2.3.0

Site Info from my testing instance - https://pastebin.com/kNPyBAMc

**Comment by MarinescuLucia** [comment]
+1 https://secure.helpscout.net/conversation/2284428418/374576/

**Comment by HardeepAsrani** [comment]
Feel free to reopen if it happens again.
