### ISSUE TITLE
Regenerate CSS Files Option in Otter Settings

### ISSUE THREAD

**Issue by selul** [Codeinwp/otter-blocks#174]
We would need a way to bulk regenerate the CSS files generated by Otter.

This would be handy when somehow the regenerate all files when it has been altered by 3rd party plugins or if it has been corrupted. 

Ideally, the action should only remove the CSS folder where we save the custom css files.

**Comment by HardeepAsrani** [comment]
> Ideally, the action should only remove the CSS folder where we save the custom css files.

What do you mean by that? @selul

**Comment by selul** [comment]
We save the custom css files in a folder which we can remove it on bulk regenerate action.

**Comment by HardeepAsrani** [comment]
Alright, I'll look into it. Any idea on how to properly do it so we don't over-burden the server?

**Comment by selul** [comment]
Something like this should work: 

```
foreach ( glob( $path ) as $file_path ) {
			unlink( $file_path );
}
```

**Comment by HardeepAsrani** [comment]
Not deleting, but generating CSS for posts in bulk which won't put too much stress on the server.

**Comment by selul** [comment]
we don't need to generate it, it will be generated when someone is viewing the page. I.e if the file is not found we will generate it.

**Comment by HardeepAsrani** [comment]
Ahaa. Got it.

**Comment by HardeepAsrani** [comment]
@selul If a post has CSS + a Reusable Block (which will also have its own CSS file), I'm only generating one CSS file per page load, so not to put too much load on the server. Is that fine?

**Comment by selul** [comment]
We can regenerate it at once, won't be an issue.
