### ISSUE TITLE
Shape divider for Section block z index issue

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1751]
### Description

As seen in the Screenshot, the Shape divider is above the section content - which shouldn't be the case.

### Step-by-step reproduction instructions

1. Create a fresh instance with Otter and Neve
2. Add this Sections inside a page (attached)
3. Notice the Shape divider position 

[shape-divider-sections.json.zip](https://github.com/Codeinwp/otter-blocks/files/11949818/shape-divider-sections.json.zip)

Can also be tested here: https://demosites.io/product-launch-gb/preorder

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1703" alt="Screenshot 2023-07-04 at 16 34 15" src="https://github.com/Codeinwp/otter-blocks/assets/52494172/6df5f349-c237-41b5-8e9f-cfa4e1220382">

### Environment info

https://pastebin.com/FNmW4jB7

### Is the issue you are reporting a regression

No

**Comment by mghenciu** [comment]
Hey @HardeepAsrani @Soare-Robert-Daniel , what do you think if we prioritise this issue?

I am asking this since the issue is still in the Up Next column, and this bug is very visible and can affect the users in a more profund way, to the point where the Shape divider feature can't be used.

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu   Regarding this issue, we had some time ago a similar problem: https://github.com/Codeinwp/otter-blocks/issues/1597, which led to this PR https://github.com/Codeinwp/otter-blocks/pull/1606 in which I made the divider to be on top of the content.

I will make a version in which both dividers are behind the content.

**Comment by Soare-Robert-Daniel** [comment]
You can test this on https://github.com/Codeinwp/otter-blocks/pull/1780

**Comment by mghenciu** [comment]
> You can test this on https://github.com/Codeinwp/otter-blocks/pull/1780

Looks good in Front-end.
In Backend I think it needs some work, since the Shapes are stil above the content (attached)
![Screenshot 2023-08-01 at 09 05 25](https://github.com/Codeinwp/otter-blocks/assets/52494172/96f3c076-0e52-4afb-bd8d-42883216977b)



Test Instance:
 https://kindlyoven.s1-tastewp.com/wp-admin admin | Bn9Pt1MdqTo
