### ISSUE TITLE
Tab resets when changing viewports

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#1752]
Hey team, while working on the latest starter site I came across a weird issue which is very annoying and breaks the momentum.

When attempting to change the value for a different viewport, the style tab changes, and I need to navigate my way back to the specific control. I created a quick video to showcase what really happens.

This behaviour applies on every control.

Thanks for your time and attention!

https://www.loom.com/share/1ac28d00da6449da8f957a519d211dd5?sid=5689a965-af99-41fe-83b4-25dbd2caeb31

**Comment by Soare-Robert-Daniel** [comment]
This is happening because everything is destroyed and reinitialized when you transition from Desktop to Tablet/Mobile. If you go from Tablet to Mobile or vice versa, you will see that this effect does not happen since it is just a window resize.

This is a Gutenberg quirk.

**Comment by Soare-Robert-Daniel** [comment]
I think I have a solution similar to the trick that we did with CSS for FSE.

CC: @HardeepAsrani
