### ISSUE TITLE
Testing with WordPress 6.3 RC

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1777]
### What problem does this address?

We can test Otter with WordPress 6.3 RC and post any issues here.

### Will this feature require documentation? (Optional)

None

**Comment by irinelenache** [comment]
@HardeepAsrani Tested the plugin using WP beta tester and didn't find any problem ✅ 

Feel free to close this and we can reopen if any issues will occur 👍
