### ISSUE TITLE
Add option to hide a block depending on the device

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1800]
### What problem does this address?

A client said that it would be a nice addition to have a toggle that allows you to hide a block on a certain type of device. Moreover, he also suggested an option to add a different block on the device where the first one was hidden, so the original block would be replaced with a different one, instead of just being hidden.

Suggested [here](https://secure.helpscout.net/conversation/2308556944/378589?folderId=931544).

### What is your proposed solution?

Add a toggle for each desktop/tablet/mobile in the Visibility Conditions section of the block.

### Will this feature require documentation? (Optional)

No.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani  I see that WP has a function for this https://developer.wordpress.org/reference/functions/wp_is_mobile/

Unfortunately, it is not recommended as it is not always accurate and might have a problem with cached pages. This means the users using such kinds of plugins for caching might have a problem.

We can at this as an option along with a ⚠ warning to eliminate the belief that always works.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel I'd suggest we follow a CSS-based approach and use `hide-on-desktop` type classes on front for that.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you check with similar plugins on how they deal with it? If they do it with CSS or PHP? Personally, I like the CSS approach as it's more dynamic and at times it might only be for styling and not actually hiding content.

**Comment by Soare-Robert-Daniel** [comment]
I was researching this plugin: https://wordpress.org/plugins/block-visibility/

They use both approaches (CSS & Device): https://blockvisibilitywp.com/knowledge-base/how-to-use-the-browser-device-control/

After inspecting the code, they use the lib: https://github.com/Wolfcast/BrowserDetection

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel CSS approach is good. We don't need to target based on device, as in the company and such, just based on mobile/tablet/laptop is enough and should cover most users. 😄

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani  This will be a Free or Pro feature?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Free is fine given it's available for free in most packs, and can be useful for us to make patterns too.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and everything's fine on my end 🚀
