### ISSUE TITLE
Otter Contact Form not Saving Changes in Neve FSE Templates/Template Parts

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1802]
### Description

When you edit any template of template part in Neve FSE by going to WP Dashboard > Appearance > Editor and place the Otter Form Block, select the Contact Form, make changes to the Save Location or Success or Error Message, save the changes, and refresh the page, the changes are not saved.

When we try to make the change again, it doesn't react and the save button is not allowed to be clicked assuming that no change happened.

### Step-by-step reproduction instructions

1. Install Neve FSE theme and Otter Blocks Plugin.
2. Go to WP Dashboard > Appearance > Editor > Template > Page > Edit the template.
3. Place Otter Form Block and select contact.
4. Make changes to the Save Location setting or Success/Error Message and hit Save.
5. Refresh the page and your save will vanish.
6. Try making changes again in Form Settings and try clicking the Save button and it will not get clicked.

### Screenshots, screen recording, code snippet or Help Scout ticket

Screen Recording: https://share.getcloudapp.com/nOuL48qm

Help Scout Ticket: https://secure.helpscout.net/conversation/2323424663/380740?folderId=212385

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
⚠️ The problem is that the function for post saving from `core/editor` is unusable in the FSE Editor.

Also, the store for the editor has no function for unlocking the save. 

Snippet code to check: `await window.wp.data.dispatch('core/edit-site')`

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can we do some digging in and check if there any some ways we could trigger a save on FSE saving? Must be some way they detect things are changing?
