### ISSUE TITLE
[PRO]Fatal error in Form Submissions page by super admin users on multisite network

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#1810]
### Description

https://www.loom.com/share/ebef64bd53974499b86193006ea74bb4?sid=ed44332a-07b6-4b84-9bf7-6f4db009014f

### Step-by-step reproduction instructions

1. Install Otter Pro on a WordPress multisite installation.
2. Create multiple sites and visit one of them, while being logged in using the super admin user of the network
3. Visit Otter Blocks > Form Submissions -> There is an extra Add New button, which if you click on, it will give a fatal error

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1490" alt="Screenshot on 2023-08-11 at 14-48-12" src="https://github.com/Codeinwp/otter-blocks/assets/3266155/11210aa4-7a4d-452f-9c2d-17f7b0b3a33a">

### Is the issue you are reporting a regression

No

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel it's working well, except when Elementor is activated. In that case, the Add new button is still there, unless I add `!important` for the css line

**Comment by Soare-Robert-Daniel** [comment]
I added a special condition for the Elementor case. A very interesting case is the fact that when pressing the button no crash happens.

Also tested a few other blocks plugin to check if they add some extra CSS.

**Comment by rodica-andronache** [comment]
@rodica-andronache everything's working well now 👍
