### ISSUE TITLE
CSS for Section block only output for preview

### ISSUE THREAD

**Issue by seleborg** [Codeinwp/otter-blocks#182]
Thanks for an otherwise excellent plugin!

I'm currently experiencing differences between the preview and the published version of a page. The page features several sections blocks following each other. I recently added one section block in the middle of the page that seems to behave differently. Here's what I've found out so far:

# Padding properties correctly output to preview
I edit the padding properties of the section, hit preview and inspect the section in Chrome. When I inspect the element in Chrome, I see the padding values have changed. Works as expected.

# Padding properties "lost" after hitting "Publish"
Now I publish the page with the changed padding properties and inspect the styles in Chrome on the published page (same URL, just without the whole ?preview... parameters).
Expected: Padding values set as I specified.
Actual: No padding style info output for that block.

# Padding properties of another block work as expected after hitting "Publish"
Now I change the padding of another block, found right below the "problem" block but added to the page quite a bit earlier, hit "Publish". This works, the padding values change as I specified in the published output.

# Also changing the section element works as expected
I change the broken block's HTML element from div (default) to section. As expected, the HTML element in both preview and published output now set to SECTION.

# When I duplicate one of the previously working blocks, the duplicate breaks
I duplicate the block that worked fine above, and immediately notice that the original block looks fine but the new duplicate has lost its style output.

# My conclusions
I've ruled out caching issues and obvious user errors (like looking that the wrong page), since changing properties of another block works fine. It's just this block that acts weird. The problems persist when I duplicate it and change the duplicate.

It seems related to the generation or output of the CSS properties, since the HTML element changes as expected when I go from DIV to SECTION.

One thing that comes to mind is that this block was inserted after the latest update. I added the block on Apr 2, likely after updating to the latest version of the plugin (version 1.5.2 is installed). I also notice that I have a few post-xxx.css files lying around under .../content/uploads/themeisle-gutenberg/, the latest timestamps being from 22 March. Renaming the file related to this particular post seems to have no effect (the broken block is still broken, working blocks get their CSS from (index) instead of that .css file)

**So this looks like a recent regression to me, something to do with how new blocks are created.** A quick fix would be highly appreciated!

Wordpress 5.4 (de_DE_formal)
HTTPS enabled: yes
Caching enabled: yes (but ruled out, see above)

Active plugins:

CMP - Coming Soon & Maintenance Plugin | Version 3.7.2.1 von NiteoThemes
Duplicator | Version 1.3.28 von Snap Creek
Gutenberg Blocks and Template Library by Otter | Version 1.5.2 von ThemeIsle
Ilmenite Cookie Consent | Version 2.0.5 von Bernskiold Media
Product Video for WooCommerce | Version 1.3.1 von Addify
Redirection | Version 4.7.1 von John Godley
URL Shortener by MyThemeShop | Version 1.0.16 von MyThemeShop
WooCommerce | Version 4.0.1 von Automattic
WooCommerce Bookings | Version 1.15.15 von WooCommerce
WooCommerce Order Status Manager | Version 1.11.5 von SkyVerge
WooCommerce Stripe Gateway | Version 4.3.2 von WooCommerce
WP Mail Logging | Version 1.9.5 von MailPoet
WP Mail SMTP | Version 1.9.0 von WPForms
WP Super Cache | Version 1.7.1 von Automattic

**Comment by seleborg** [comment]
I also observe that the rendered page normally references a CSS file stored under

wp-content/uploads/themeisle-gutenberg/post-XXX.css

This file gets loaded by the browser and contains CSS rules for the other blocks, but not for the "broken" block I'm referring to.

This file has a last modified timestamp of 22.03.2020 for the particular page I'm referring to. So obviously, it hasn't been re-written in a while. When I remove the file (by renaming it), the CSS previously loaded from that file is now rendered directly into the HTML of the page, but it still doesn't contain any CSS rules for the broken block.

So it seems that there is something about this block that makes the CSS rendering code skip it.

**Comment by HardeepAsrani** [comment]
Hey @seleborg!

Thank you for the issue. Yes, one another user has reported a similar issue. Would it be able to give us access to your WordPress instance + FTP (not publicly, we will email you)?

You don't have to give access to your live instance but a staging site will do just fine. We haven't been able to reproduce this on our end.

Also, which hosting provider are you using? Thank you so much for bringing this to our attention.

**Comment by HardeepAsrani** [comment]
We run some automation to remove unused files from the released plugin, as in files that are used during development only, and our code removes a file that shouldn’t be removed.

Another user sent their FTP which helped us in solving it. We will fix it this week and release.

**Comment by seleborg** [comment]
Hi Hardeep,

OK, so you don't need access to my site, right? Happy to hear a fix is
coming quickly. Thanks for your work!

**Comment by HardeepAsrani** [comment]
You're welcome!

**Comment by HardeepAsrani** [comment]
Hey @seleborg! It should be fixed in the latest version, which is 1.5.3. Please reopen this issue if it doesn't work for you! :)

**Comment by seleborg** [comment]
Seems to work, thank you very much for the quick fix.

**Comment by HardeepAsrani** [comment]
You’re welcome & thank you for reporting the issue! @seleborg
