### ISSUE TITLE
Open AI label and link to doc

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1830]
### What problem does this address?

Under Otter Blocks > Settings > Integrations, we have the OpenAI accordion.
<img width="1079" alt="image" src="https://github.com/Codeinwp/otter-blocks/assets/86592992/ccf9fcfc-dada-4ce8-b1d9-1c4b8b2330db">

### What is your proposed solution?

I suggest renaming it from "Open AI" to "OpenAI", to remove the space.

For the More Info link, we can use this doc that explains how to generate an OpenAI API key - https://docs.themeisle.com/article/1916-how-to-generate-an-openai-api-key.

### Will this feature require documentation? (Optional)

None

**Comment by HardeepAsrani** [comment]
We can do the same for inside the AI Block when the API key field appears.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani 

The change will be a part of #1803, no need for extra testing or PR.

Commits: https://github.com/Codeinwp/otter-blocks/commit/c78424e38a12d6152f726ce04e581e142b1cad02 https://github.com/Codeinwp/otter-blocks/commit/d50772567f789795f377604dcc13e434c1bcce7a

#### Screenshot

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/5e715e6e-2cae-4e40-837b-df1b4c5e4a59)
