### ISSUE TITLE
Mailchimp API not working with the Form block

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/otter-blocks#1835]
### Description

When using the Mailchimp option under Marketing Integration when creating a form, it does not accept the API.

<img width="292" alt="Screenshot 2023-08-29 at 11 57 26 PM" src="https://github.com/Codeinwp/otter-blocks/assets/32997072/26d276b3-ffe1-4cc7-b785-457adda709db">

### Step-by-step reproduction instructions

1. Generated a Mailchimp API using this guide: https://mailchimp.com/help/about-api-keys/
2. On the WordPress Dashboard, create a new post.
3. Add the Form block > Subscribe Form.
4. Under Marketing Integration, choose Mailchimp and enter the API keys generated on Step 1.

### Screenshots, screen recording, code snippet or Help Scout ticket

Ticket: https://secure.helpscout.net/conversation/2343751503/383388?folderId=212385

### Is the issue you are reporting a regression

No

**Comment by stefan-cotitosu** [comment]
+1 https://secure.helpscout.net/conversation/2362472791/385656/
