### ISSUE TITLE
Add option to add default values to form fields

### ISSUE THREAD

**Issue by milicavs** [Codeinwp/otter-blocks#1908]
### What problem does this address?

I started designing a form with a bunch of hidden fields only to realize that there is no option to set a default value for any of the form fields. 

I think this is a pretty basic feature that all form builders have, so we should consider adding it as well.

### What is your proposed solution?

Add a 'Default Value' input field to 'Field Settings' for some input fields (text, hidden, number ...).

### Will this feature require documentation? (Optional)

I dont know.

**Comment by selul** [comment]
@HardeepAsrani I think this is more like a critical bug that should be expedited considering that the functionality is right now broken.
