### ISSUE TITLE
New Block:: Add an Image Block in Otter, Capable of Adding Dynamic Images

### ISSUE THREAD

**Issue by RohanSharma2598** [Codeinwp/otter-blocks#1920]
### What problem does this address?

There should be an Image Block in Otter Blocks as putting an image on a page is essential for every website. That Block should have a functionality that can be used to add Images Dynamically.

For example, I have a Custom Field for each post where I add an image so I should have an Image Block which I can set in my Post Template to show that Custom Field Image dynamically.

It should also have an option to open the image in a light box which can be enabled or disabled.

### What is your proposed solution?

Adding a new Image Block is my proposed solution.

### Will this feature require documentation? (Optional)

None

**Comment by HardeepAsrani** [comment]
@RohanSharma2598 Otter already has Dynamic Images feature that can be used with Core Image block. You can confirm if your use-case works with that feature. On Core Image Block, you can open the image modal and should see Dynamic Image option in Modal.

**Comment by RohanSharma2598** [comment]
@HardeepAsrani Thank you for your answer. We can close this.
