### ISSUE TITLE
Form throwing error even if the data is properly sent

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#1933]
### Description

I created a form using the AI block feature, made some changes to it and enabled **WP Mail SMTP**, **Mailchimp integration** and saving the data to **database**. After clicking submit, i'm getting a server error and also a console error, but the data is correctly saved to the database, sent to my email and added to the Mailchimp's contact list.

Here is a video with the issue https://vertis.d.pr/v/vW5Gze
Here is the form block https://pastebin.com/3JALFMwH

### Step-by-step reproduction instructions

1. Use the form from the link
2. Connect WP Mail SMTP and Mailchimp
3. Try to submit the form with some data

### Screenshots, screen recording, code snippet or Help Scout ticket

Here is a video with the issue https://vertis.d.pr/v/vW5Gze
Here is the form block https://pastebin.com/3JALFMwH

### Environment info

WordPress 6.3.2 / PHP 8.0 / Otter, Otter Pro 2.4.1

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache please give the test instance on Slack if you still have it 🙏

**Comment by Soare-Robert-Daniel** [comment]
The response from the server is:

```
<br/><b>Warning</b>:  Undefined array key 1 in <b>/home/jakefogaxu1337/web/otter-wp64.vertisite.cloud/public_html/wp-content/plugins/otter-blocks/inc/integrations/class-form-utils.php</b> on line <b>154</b><br/>{
    "success": true,
    "reasons": [
        "Expected error whatever message"
    ],
    "code": "0",
    "displayError": "Error. Please try again.",
    "submitMessage": null
}
```
