### ISSUE TITLE
RankMath not working with latest Otter

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1955]
### Description

Since the last version, RankMath has stopped working nicely with Otter as it used to. I suspect it was introduced in https://github.com/Codeinwp/otter-blocks/pull/1874 but not 100% sure.

We can investigate what caused this.

### Step-by-step reproduction instructions

1. Install Otter & RankMath
2. Create a dummy article with title and content
3. Enter the keyword and the RankMath stats related to content won't update.
4. It must be noted, it happens only if you add a new keyword. If you add a keyword, save the page and refresh the page, the stats will appear.

### Screenshots, screen recording, code snippet or Help Scout ticket

Same article & keyword with and without Otter

<img width="299" alt="Screenshot 2023-11-02 at 12 30 53 PM" src="https://github.com/Codeinwp/otter-blocks/assets/2649903/1c17c185-bdf3-4a0e-ab05-ce5f0dd39140">

<img width="300" alt="Screenshot 2023-11-02 at 12 30 59 PM" src="https://github.com/Codeinwp/otter-blocks/assets/2649903/282baa01-0a6a-458c-a196-12d063016cf2">

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2408392372/391382/

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2403281571/390680/

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel We can prioritize this as we're getting many reports, including some on RankMath support.

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2410084170/391618/
