### ISSUE TITLE
Notice appears even if configuration is correct

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1966]
### Description

There is a notice under the Action accordion that mentions the necessity of adding an Email input, even if I already have it. 

### Step-by-step reproduction instructions

1. Go to a post and add a form block
2. Expand marketing settings
3. Make the configurations (provider, API key)
4. Observe the notice under the default action

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1680" alt="image" src="https://github.com/Codeinwp/otter-blocks/assets/86592992/45037e74-93b4-4d05-a295-32ee1ed3fa58">

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
Hey @AndreeaCristinaRadacina,

I tried to reproduce it but wasn't able to. Can you send steps or create an instawp site where I can try it?

**Comment by AndreeaCristinaRadacina** [comment]
It doesn't happen anymore. Thank you for checking and sorry for the delay!
