### ISSUE TITLE
AI Block Not Functioning, Quota Exceeded Error

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#1981]
### Description

The AI block feature in the Otter Plugin is not functioning as expected, and users are encountering an error message when attempting to use it with a fresh API key. The error message states: "You exceeded your current quota, please check your plan and billing details."

### Step-by-step reproduction instructions

1. Install and activate the Otter Plugin.
2. Obtain a fresh API key for the AI block.
3. Insert the AI block into a page or post.
4. Encounter the error message: "You exceeded your current quota, please check your plan and billing details."

### Screenshots, screen recording, code snippet or Help Scout ticket

HS: https://secure.helpscout.net/conversation/2436697105/394917?folderId=212385

Screenshot: https://vertis.d.pr/i/aYPOji

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@poonam279 That's not an issue, the user needs to add some payment method to their OpenAI account for their API key to work. 😄
