### ISSUE TITLE
Display multiple authors in Posts block

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#2002]
### What problem does this address?

A user asked if it's possible to display multiple authors in the Posts Block, which is not currently available.

ref: https://secure.helpscout.net/conversation/2447044364/396163?viewId=212385

I am not sure if it's a bug or a feature request.

### What is your proposed solution?

Provide the possibility to display all authors of a post.

<img width="1676" alt="image" src="https://github.com/Codeinwp/otter-blocks/assets/86592992/02373963-24d5-4f56-bc4b-2b8e9366fe1c">
<img width="1680" alt="image" src="https://github.com/Codeinwp/otter-blocks/assets/86592992/eadde68c-c75c-4f70-ace3-125523443dc1">

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

**Comment by HardeepAsrani** [comment]
Hey @AndreeaCristinaRadacina,

I've added a filter to the plugin and created a documentation here for this: https://secure.helpscout.net/docs/6286701e68d51e7794442014/article/65c1f97102edbb142345057c

I will publish it once the plugin update is out.
