### ISSUE TITLE
Unnecessary file

### ISSUE THREAD

**Issue by DannyCooper** [Codeinwp/otter-blocks#2003]
### Description

I believe this file isn't needed as the block is "dynamic" - https://github.com/Codeinwp/otter-blocks/blob/master/src/blocks/blocks/form/multiple-choice/save.js

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@DannyCooper Yea, you are right. It was used at some point and then we reverted to it being a SSR-block. Thanks for the report.

**Comment by HardeepAsrani** [comment]
It was deleted in the last version.
