### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by Andreslav** [Codeinwp/otter-blocks#2047]
### Description

Hi, the problem is described here: https://wordpress.org/support/topic/console-errors-31/

### Step-by-step reproduction instructions

Check out the link.

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
Hey @Andreslav,

Can you let me know which version of PHP you are currently running? Also, what other plugins are you using besides Otter? And lastly, where and when exactly are you getting this error message? Does it happen in the Page Editor? Or does it happen on load or when you perform a particular action? Thank you!

**Comment by Andreslav** [comment]
Hey  @HardeepAsrani,

PHP: 8.1.23 64bit

There's only one plugin: Otter. I wrote the sequence of actions to reproduce the problem here: https://wordpress.org/support/topic/console-errors-31/

Duplicating.

>     1. Disabled all plugins except Otter.
>     2. Enabled the Twenty Twenty-Four theme.
>     3. Opened the page editor.
>     4. Opened the console.
>     
>     Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it’s running React 17.
>     
>     5. Focused on the text block. In the console:
>     
>     Warning: Invalid DOM property stroke-width. Did you mean strokeWidth…
> 
>     WP: 6.4.2, browser: Edge.

![изображение](https://github.com/Codeinwp/otter-blocks/assets/39444579/62910f58-0f71-44d2-81d6-8a1075114b53)

![изображение](https://github.com/Codeinwp/otter-blocks/assets/39444579/e8eb7ee8-8e9c-4c8c-92c7-4e8c2f2b8df8)

**Comment by HardeepAsrani** [comment]
Hey @Andreslav I'm not able to reproduce this issue on my side. Are you able to reproduce the issue here on https://tastewp.com/? You can create a temporary website there without any signups and see if you can reproduce the same issue.

Thank you!

**Comment by Andreslav** [comment]
Hey @HardeepAsrani 

1. I was unable to reproduce the problem on tastewp.com. Thanks for the link, cool tool!
2. I realized what the problem is. The problem exists if `define( 'SCRIPT_DEBUG', true );` is specified in wp-config. On tastewp.com I probably can't modify wp-config to check.

**Comment by Andreslav** [comment]
Hey @HardeepAsrani! Now there's a new error :(
Reproduced on tastewp.com

![изображение](https://github.com/Codeinwp/otter-blocks/assets/39444579/a2aa51bc-7018-4763-bdaf-05e566534b7e)

**Comment by HardeepAsrani** [comment]
Hey @Andreslav 

This is an unrelated error that we are aware of already: https://github.com/Codeinwp/otter-internals/issues/92

This happens due to translations and here I'm assuming it happens because a Form Block is part of the Patterns. If you add it to your site, you can fix it by clicking on Resolve Block and it should work as before.

Hope that helps!
