### ISSUE TITLE
Accordian FAQ schema needs name in "mainEntity"

### ISSUE THREAD

**Issue by theflyingjay** [Codeinwp/otter-blocks#2049]
### Description

Here is an example of the existing payload produced by Accordian item when you have FAQ schema enabled.
![image](https://github.com/Codeinwp/otter-blocks/assets/109875920/296c422b-d603-4f72-a79c-3c11f5e87743)

Here is the raw output from Google's rich text tester. Test URL: https://search.google.com/test/rich-results/result?id=QSt8pyVGDI7fF3CeYBkhUA
![image](https://github.com/Codeinwp/otter-blocks/assets/109875920/fa5706ad-f1de-4215-b52a-f89032b0b323)

Google Search console is reporting the issue as well.

![image](https://github.com/Codeinwp/otter-blocks/assets/109875920/c2e96b63-e0b7-4876-b927-0b34cd173a0e)

{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"","acceptedAnswer":{"@type":"Answer","text":"In Arizona’s sun-drenched climate, protecting your roof from heat and sun damage is crucial. For instance, metal roofing can reflect the sun’s rays, helping to keep your home cooler. Regular maintenance and inspections by a professional Arizona roofer can also help detect and prevent sun and heat damage before it becomes a major issue."}},

### Step-by-step reproduction instructions

To reproduce simply create a page in wordpress. Add an accordian item for FAQ. Enable FAQ schema on the right hand side. Use Googles Rich text tester to verify.

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
Hey @theflyingjay,

Would it possible for you export the Accordion Block from your website and share it with us here so we can try to reproduce it on our end? I tried to reproduce on our test site and it seems to work fine for us:

Here's how you can export the block: https://ps.w.org/blocks-export-import/assets/screenshot-1.png?rev=2632131 - make sure to do it for the primary Accordion Block and not its child blocks.

Another test, is it working for you if you remove the bold styling from the FAQ questions? Thank you!

**Comment by theflyingjay** [comment]
Removing the bold styling did not correct the FAQ schema output.
[blocks-export.json](https://github.com/Codeinwp/otter-blocks/files/13923136/blocks-export.json)

**Comment by HardeepAsrani** [comment]
Hey @theflyingjay,

Thanks for helping us troubleshoot this issue. I imported your block on my site and it still seems to work properly: https://search.google.com/test/rich-results/result?id=fGir9ug8cOO7-rJiXpegyg

Can you try two things?

- Make sure your site isn't being cached, so try to flush any cache you have and try to check again.
- Remove your FAQ block, save the page and refresh and then import the block from this json file and see if that works. You can either use Blocks Importer block to import the file or just drag & drop the file to your editor and it will import the block on that spot.

Let me know if that works.

**Comment by theflyingjay** [comment]
I tried both of your suggestions and got the same result. I noticed that you're using the default theme from Wordpress. I want to clarify I'm using NEVE 3.7.5 and Wordpress 6.4.2

**Comment by HardeepAsrani** [comment]
Hey @theflyingjay,

I've tried doing the same and it still works properly: https://search.google.com/test/rich-results/result/r%2Ffaq?id=ooO9Q-cCYpbsZVd599V6NA

Would it be possible for you to share a list of all the plugins you're using on your website so we can test with them installed?

**Comment by theflyingjay** [comment]
@HardeepAsrani I appologize. I discovered the issue is related to NEVE pro performance setting. See screenshot. Thank you for your help.

![image](https://github.com/Codeinwp/otter-blocks/assets/109875920/04e2a719-6a01-4978-9cd4-69aabab95a24)
