### ISSUE TITLE
Accordion block (suggestion)

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#217]
Hi team. I did a bit of research regarding some suggestions I might have for some useful blocks. An accordion block is one of them that I'd find very handy, especially since we are focusing on Gutenberg-first starter sites. I would not see these as a high priority but it would be great if we can include them in Otter at some point.

I am pasting below some links for inspiration.

- In [Gutenberg Hub](https://gutenberghub.com/blocks/accordion-block/) you can see an overview of the Accordion block execution of [CoBlocks](https://wordpress.org/plugins/coblocks/).
- [Accordion Blocks](https://wordpress.org/plugins/accordion-blocks/) plugin

Let me know your feedback or any questions.  ✌🏻

**Comment by HardeepAsrani** [comment]
Closing in favor of: https://github.com/Codeinwp/gutenberg-blocks/issues/267
