### ISSUE TITLE
Block Animation: fade-out, slide-out – all ‘outs’ are missing

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#2175]
### Description

In the animation options, you can find all the "in" options like fade-in. slide-in, roatate-in but fade-out, slide-out – all ‘outs’ are missing.  A user mentioned that JS file in the plugin includes slide-out-left, slide-out-right, slide-out-down, fade-out, …
but none of them are in the toolbar on gutenberg-blocks. I have checked the frontend.js file and it has all the options. 

### Step-by-step reproduction instructions

1. Try to add the animation on a block
2. Search for something like fade-out, slide-out or rotate out. rotate-out

### Screenshots, screen recording, code snippet or Help Scout ticket

https://wordpress.org/support/topic/fade-out-slide-out-all-outs-are-missing/

### Is the issue you are reporting a regression

No

**Comment by ineagu** [comment]
not a priority for now.
