### ISSUE TITLE
Tabbed content block (suggestion)

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#218]
A Tabs block would also be very useful for presenting tabbed content. 

Examples are included below.

- [Gutenberg Hub](https://gutenberghub.com/blocks/tabs-block/) highlights how the Tabs block works by Kadence. Very good reference.
- An execution by [Kioken blocks](https://kiokengutenberg.com/blocks/tabs-block/)

Thanks! ✌🏻

**Comment by HardeepAsrani** [comment]
Closing in favor of: https://github.com/Codeinwp/gutenberg-blocks/issues/268
