### ISSUE TITLE
Allow visitors to add reviews in the Product Review block

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#2180]
### What problem does this address?

A user asked if it's possible to allow visitors to input their reviews instead of restricting this to the editors only.

ref: https://wordpress.org/support/topic/visitors-kan-not-add-reviews-in-otter-review-block/

### What is your proposed solution?

Allow visitors to submit reviews and dynamically adjust the ratings. 

This can be done either by changing the current block or by creating a new one.

### Will this feature require documentation? (Optional)

None

**Comment by ineagu** [comment]
we don't plan to add this for now.
