### ISSUE TITLE
Warning after updating

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#2181]
### Description

A user reported a warning appearing on the free version after updating the plugin.

### Step-by-step reproduction instructions

1. Go to plugins
2. Update Otter Free while having Otter Pro installed

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1534" alt="image" src="https://github.com/Codeinwp/otter-blocks/assets/86592992/ab94af11-8bdf-4d70-931d-15b54b247c2e">

ref: https://secure.helpscout.net/conversation/2571558080/413982?viewId=212385

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina,

It should be fixed, the user should make sure that has Otter PRO updated to the latest version (2.6.10).

Thanks!
