### ISSUE TITLE
Button Group block: colors and spacing not working

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/otter-blocks#220]
Issue: When adding a button group block, the selected colors and the spacing set is not reflected on the frontpage.

Steps to replicate.
1. Created a custom layout for footer.
2. Selected the button group block.
3. Created 3 buttons as seen here -->> https://snipboard.io/3qLAr7.jpg
4. This is how it looks like on the frontpage -->> https://snipboard.io/7yBOdT.jpg

**Comment by HardeepAsrani** [comment]
Hey @purplecodes, which theme was the website using?

**Comment by purplecodes** [comment]
@HardeepAsrani this was tested on Neve Pro.

**Comment by HardeepAsrani** [comment]
@purplecodes Tried it on my end and it works fine. Can you reproduce it and export the block using https://wordpress.org/plugins/blocks-export-import/ plugin?

**Comment by purplecodes** [comment]
@HardeepAsrani 
Installed and activated the Blocks Export Import plugin, 
Tested again with the Button Group, it works when using Gutenberg in a page or post.
When tested in Gutenberg using the Neve Custom Layout option, the issue is still the same. The button colors and spacing are not displayed as expected.

**Comment by HardeepAsrani** [comment]
Can you export the blocks using that plugin and share the JSON with me? @purplecodes

**Comment by purplecodes** [comment]
I tested again using the latest version of Otter (v1.5.5) and it appears to be resolved.
When I rolled back to v1.5.4, I can see the issue there.

v1.5.4 https://snipboard.io/DRAvjZ.jpg
v1.5.5 https://snipboard.io/7HuA69.jpg

Here is the JSON file: https://www.dropbox.com/s/cukhql7yr019tdr/blocks-export%20%284%29.json?dl=0

**Comment by HardeepAsrani** [comment]
It's fine if it doesn't exist in 1.5.5. Thanks for the finding, let me know if you find this again!
