### ISSUE TITLE
small grammar error on the consent checkbox

### ISSUE THREAD

**Issue by selul** [Codeinwp/otter-blocks#2212]
### Description

There is a small grammar error on the default label of the consent checkbox https://github.com/Codeinwp/otter-blocks/blob/e34a2a404050e530a20b95eb5cca5025e363bdcf/src/blocks/frontend/form/index.js#L538
https://secure.helpscout.net/conversation/2604044839/419650?viewId=931549

### Step-by-step reproduction instructions

You can add a form and you will see it. 

### Is the issue you are reporting a regression

No

**Comment by hunxjunedo** [comment]
requesting assignment if open to external contributions, would love to contribute.

**Comment by vytisbulkevicius** [comment]
Let's change it to:

> I have read and agree to the privacy statement

@Soare-Robert-Daniel
