### ISSUE TITLE
Add different animations for the transition between slides

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#2253]
### What problem does this address?

A user asked about animations/transitions for the Slider block. He would like to have different traditions between the slides.

ref: https://wordpress.org/support/topic/slider-fx-fade/#post-17842080

### What is your proposed solution?

Add a section for transitions between the slides.

### Will this feature require documentation? (Optional)

None

**Comment by ineagu** [comment]
Don't plan to add this in the near future.
