### ISSUE TITLE
Blocks CSS does not insert custom CSS for non-posts

### ISSUE THREAD

**Issue by zbrachinara** [Codeinwp/otter-blocks#2324]
### Description

I observed this issue when editing a category template. Custom CSS shows up in the editor, but on the frontend, because the value of `get_the_ID()` is false, the plugin does not actually insert the custom CSS.

### Step-by-step reproduction instructions

1. Create a category template in the block editor
2. Create a block in the category template and assign it CSS (I chose `background: blue;`)
3. Save the template and navigate to the category page

### Screenshots, screen recording, code snippet or Help Scout ticket

![image](https://github.com/user-attachments/assets/2836a3dd-17f4-47c1-9cbf-0e60013a6ffe)
![image](https://github.com/user-attachments/assets/01b5eaa3-8c24-4232-ad87-daca06f14e21)

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@zbrachinara This is a known issue, and to fix it you need to use Otter Blocks plugin: https://wordpress.org/plugins/otter-blocks/ 

Making Blocks CSS work with FSE themes requires us additional features which don't make sense for a small utility plugin, so you can use it as part of Otter Blocks.
