### ISSUE TITLE
Update plugin's page

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#2327]
The plugin's page contains information that may confuse the users. For example, some of the blocks are no longer available as standalone blocks but rather as patterns:
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/f9a11799-c9a2-4ad4-9c6a-55eca74ddcd2">

A user asked about the Pricing table block, for example.

**Comment by ineagu** [comment]
@harshitarora-in this is about the plugin w.org page, for clarity.
