### ISSUE TITLE
 Two-column sections not displaying properly on mobile since 3.0.0

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#2331]
Details: https://wordpress.org/support/topic/two-column-sections-not-displaying-properly-on-mobile-since-3-0-0/

If you have a stacked layout, the full content is hidden because the slider block's overflow condition is added to make it work.

**Comment by rodica-andronache** [comment]
+1 https://secure.helpscout.net/conversation/2681232065/430288

**Comment by rodica-andronache** [comment]
+1 https://secure.helpscout.net/conversation/2680981282/430261?viewId=212385
