### ISSUE TITLE
2 columns section doesn't appear well in the Modal

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#2340]
### Description

When trying to use the two-column section, I noticed it is not correctly displayed in the modal block.

### Step-by-step reproduction instructions

1. Go to a page
2. Add the modal block
3. Inside of it, add a section block with 2 columns layout

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="911" alt="image" src="https://github.com/user-attachments/assets/6bca463b-1617-4a38-b2b8-76774c06dee1">
<img width="892" alt="image" src="https://github.com/user-attachments/assets/521f2d0f-4bbb-4026-b82c-86649cc26267">

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I've tested with the `development` branch and I can't replicate this issue.
Ref: https://tinyurl.com/2yu8mlrn, https://tinyurl.com/24xuzu2g

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30, I checked again today but couldn't replicate the issue either.
