### ISSUE TITLE
Image gets cut off on mobile when using Scale = Contain

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#2341]
### Description

Image gets cut off on mobile when using the steps below:

### Step-by-step reproduction instructions

1. Add a Section block with two columns
2. In one column add an Image block
3. For the image, choose Aspect ration = Square 1:1 and Scale = Contain
4. Check the page on Desktop -> everything is ok
5. Check the page on Mobile -> the image is cut off
This happens just with the latest version of Otter 3.0.0

### Screenshots, screen recording, code snippet or Help Scout ticket

https://github.com/user-attachments/assets/29994e4e-13a5-48a7-bbe1-0c663863ddd3

https://secure.helpscout.net/conversation/2679584211/430107?viewId=212385

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by vytisbulkevicius** [comment]
@HardeepAsrani, I think maybe you worked on this. Would you like to check, or should I ask Girish?

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius Yes but that option was for Posts Block not the Image Block. We can first confirm if this is indeed an issue with Otter and works inside the default Columns.

**Comment by HardeepAsrani** [comment]
Could be related to this too: https://github.com/Codeinwp/otter-blocks/issues/2331

**Comment by ineagu** [comment]
@HardeepAsrani yes, this is a bug related to Otter, works for Columns block and it's fixed if overflow:hidden is removed.
