### ISSUE TITLE
All blocks disappear as "Not supported" in latest version

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#2349]
### Description

I wasn't able to replicate this so far, but multiple users report something similar, so I think it's worth investigating:

- https://wordpress.org/support/topic/all-blocks/
- https://secure.helpscout.net/conversation/2685855636/430944?viewId=212385
- https://wordpress.org/support/topic/options-blocks-no-longer-appearing-in-wp-admin-setting-page-loads-empty/
- https://wordpress.org/support/topic/qtags-is-not-defined-2/

Seams to be a regression.

### Step-by-step reproduction instructions

What users are experiencing:
- The error: Your site doesn't include support for the "themeisle-blocks/advanced-columns" block. You can leave this block intact, convert its content to a Custom HTML block, or remove it entirely.
- In the WordPress dashboard, clicking on the “Otter blocks” link in the menu only a gray page without writing appears, and the same happens when clicking the “Settings”, “Blocks”, and “About us” links instead, even if for a second you see the regular page and the “redirecting…” indication and then everything disappears immediately. The “Submission Pro” and “Get otter Pro” links work regularly.

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by rodica-andronache** [comment]
+1 https://secure.helpscout.net/conversation/2686101851/430961/

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/all-blocks/

**Comment by Soare-Robert-Daniel** [comment]
> +1 https://secure.helpscout.net/conversation/2686101851/430961/

Our main JS scripts are not loaded for this user on the page. Thus, neither the blocks or the Otter dashboard is working.

**Comment by selul** [comment]
@Soare-Robert-Daniel, the problem is consistent on WP 6.5.5; I tried on an empty instance, and the Otter page is not loading.
