### ISSUE TITLE
Some user gets a fatal error

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#2371]
### Description

! I'm not able to replicate this.

The user [here](https://secure.helpscout.net/conversation/2694468020/432139?viewId=212385) reported that he got a fatal error from Otter

PHP Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /home/customer/www/joyeriaoliva.com/public_html/wp-content/plugins/otter-blocks/inc/class-main.php:185

From here https://github.com/Codeinwp/otter-blocks/blob/fd54bc2cfb4c32ba3b763af4383ca2429a4307db/inc/class-main.php#L179

And he said that checking if $attr is array, fixes the issue. I'm not sure if this is something needed to do or not, on our side.
It's possible that this can be a plugin conflict on his site, he didn't want to check it with the HealthCheck plugin.

### Step-by-step reproduction instructions

I'm not able to replicate this, to provide steps

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2694468020/432139?viewId=212385

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
I think we can add a check to ensure that the $attr variable is an array before calling array_merge to prevent this issue even if it's an edge case.

**Comment by girishpanchal30** [comment]
I've reviewed this issue and fixed it here - https://github.com/Codeinwp/otter-blocks/pull/2372
