### ISSUE TITLE
Border width and border radius not working for Button Group block

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#2373]
### Description

Border width and border radius not working for Button Group block

### Step-by-step reproduction instructions

1. Add a Button Group block
2. For one of the buttons try to add Border width and Border radius
3. Check on the frontend -> the settings don't apply

### Screenshots, screen recording, code snippet or Help Scout ticket

![Annotation on 2024-09-04 at 12-10-52](https://github.com/user-attachments/assets/f8dca39e-75d4-4cab-8c85-f29507ee67d6)
![Annotation on 2024-09-04 at 12-10-13](https://github.com/user-attachments/assets/40760656-1bf3-4fd7-a78e-4e2b55396b2f)

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@rodica-andronache I've checked this issue and I'm unable to replicate it
![image](https://github.com/user-attachments/assets/01c95c11-fa90-4d42-9b05-b79d44fe004d)

Could you please share your test instance details here?

**Comment by rodica-andronache** [comment]
@girishpanchal30 here it is:

```
https://supreme-puffin-323ece.vertisite.cloud/
user: admin
pass: admin

```

https://vertis.d.pr/v/F6xNBf

**Comment by HardeepAsrani** [comment]
@girishpanchal30 It might be an issue but normally it should be possible for it to return the units. But even if that's the not the case, we can do it while saving the attribute from the save func.

**Comment by girishpanchal30** [comment]
@rodica-andronache I've fixed the `BoxControl` component units issue with this [PR](https://github.com/Codeinwp/otter-blocks/pull/2377), Please check with the build zip and let me know if you have any issues.

**Comment by rodica-andronache** [comment]
tested and it's working well 👍

**Comment by HardeepAsrani** [comment]
@rodica-andronache It didn't cause any console errors or invalidating when updating plugin on a website which was using these settings already, right?

**Comment by rodica-andronache** [comment]
@HardeepAsrani sorry for the late reply. Yes, everything worked well when updating the plugin on a website that was using these settings already
