### ISSUE TITLE
Can't input a space in Form's submit button

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#2429]
### Description

It looks like you can't add a space directly in the Submit button of the Form block. You can only add it by copy/pasting it as typing a space is stripping it away.

### Step-by-step reproduction instructions

1. Add a form block.
2. Try to modify the submit message with something like "Send Now"
3. You will notice the space isn't inputted.

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
@HardeepAsrani I've reviewed it and found that the issue appears to be with `multiline={false}`. If we set it to `{true}`, it also allows typing whitespace.

This issue might have started from [here](https://github.com/Codeinwp/otter-blocks/pull/2028).

Do you have any suggestions on how to fix this issue?

Thanks

**Comment by HardeepAsrani** [comment]
@girishpanchal30 RichText's behavior has changed with time, and you can review the props to see which one work the best to disallow line breaks but allow white spaces: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/index.js#L80

**Comment by girishpanchal30** [comment]
@HardeepAsrani Thank you! I've resolved the whitespace issue with this [PR](https://github.com/Codeinwp/otter-blocks/pull/2440). Please review it when you have a chance. Thanks

**Comment by rodica-andronache** [comment]
@girishpanchal30 it's working well 👍 It's also fixing this https://github.com/Codeinwp/otter-blocks/issues/1977
