### ISSUE TITLE
Using up/down keyboard keys to update the number of items in Posts in Safari

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#258]
This happens just in `Safari`. In Chrome it looks ok.
1. Add a `Posts` block in a page.
2. Use the `up/down keyboard keys` to increase/decrease the `Number of Items`
3. For the up key, everything is ok
4. For the down key, the focus goes off the block, and into the title of the page
https://www.loom.com/share/0c76385c1bd147f7ace2935b4493dc4f

**Comment by HardeepAsrani** [comment]
@rodica-andronache Can't do anything. It's Gutenberg control and nothing custom. Can you see if this happens with rest of the non-Otter blocks too?

**Comment by rodica-andronache** [comment]
@HardeepAsrani yes, it happens with non-Otter blocks as well

**Comment by HardeepAsrani** [comment]
Closing it as it's not an issue with our plugin.
