### ISSUE TITLE
Trying to clear out the Offset option in the Posts block deletes the entire block

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#259]
1. Add a `Posts` block in a page.
2. Use the `backspace` keyboard key to delete the `Number of Items` option -> Everything is ok
3. Use the `backspace` keyboard key to delete the `Offset` option -> The block breaks
https://www.loom.com/share/e597c12706f245e0a11f4036b62b6d7b

**Comment by HardeepAsrani** [comment]
@rodica-andronache Can you try to the development branch and see if that happens? I fixed a related bug that should've fixed it.

**Comment by rodica-andronache** [comment]
@HardeepAsrani I've used this to get the version on development
`git clone https://github.com/Codeinwp/otter-blocks.git && cd otter-blocks && git checkout development && npm install && composer install && npm run build && cd vendor/codeinwp/ && rm -rf gutenberg-blocks && git clone https://github.com/Codeinwp/gutenberg-blocks.git && cd gutenberg-blocks && git checkout development && npm install && composer install && npm run build`

and in the editor the issue doesn't happen anymore, but on frontend I get this 
![q](https://user-images.githubusercontent.com/3266155/88527231-aaf7c580-d005-11ea-8c48-471867f6fc61.png)

Not sure if I tested properly or not

**Comment by HardeepAsrani** [comment]
That's because we've added a new file and the autoloader is in Otter. It's a weird situation. :(

**Comment by HardeepAsrani** [comment]
@rodica-andronache Was it happening after solving that debugging issue?

**Comment by rodica-andronache** [comment]
@HardeepAsrani it's ok, it's fixed in the latest version

**Comment by HardeepAsrani** [comment]
Okay, thanks! @rodica-andronache
