### ISSUE TITLE
Can't properly type from keyboard the value for 'Border Radius' and 'Border Width'  settings

### ISSUE THREAD

**Issue by StellaTI** [Codeinwp/otter-blocks#284]
We have a clean import of Web Agency starter site with Gutenberg. 
We go from Home page to Edit page > click on the first 'Learn more' button and in Block > Buttons > Border&Box Shadow and try to set the Border Radius to 40.

**Expected result:** we expect to set the value for 'Border Radius' without any difficulties

**Actual result:** when we type the value in figures from the keyboard, it might happen that instead of the typed 4 we will see figure 5, or : 0; even double zero '00' or it will be deleted. Same happens with  'Border Width'  setting.

See more details in video: 
https://www.loom.com/share/951999aaba104cf2be23e6380870aa4a
pasword: round

**Comment by HardeepAsrani** [comment]
Hey @StellaTI,

This seems to be an issue with Gutenberg itself as we are using the Core components for those settings, without adding any custom code. And this seems to also happen with Gutenberg's own controls, sadly.

Let us know what you think. 👍

**Comment by StellaTI** [comment]
hi @HardeepAsrani !
considering your comment I have tested the same settings with Elementor and Brizy and ideed, it looks like an issue on Gutenberg side. That means we can use a workaround for Gutenberg until it's not improved and close the ticket for now.

**Comment by StellaTI** [comment]
issue on Gutenberg side, not reproducible with Elementor, Brizy starter sites.
