### ISSUE TITLE
Can't open editor for new post/page with Otter blocks and Gutenberg installed

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#329]
When i try to open `New post` / `New page` with both Otter blocks and Gutenberg installed, the page remains white and i get this errors in console -> https://prnt.sc/v8m84e . This happens with any theme activated.
Can be tested here:
https://generous-coyote.jurassic.ninja
user: demo
pass: BnPSqwkwTj2R

**Comment by HardeepAsrani** [comment]
@irinelenache I fixed it few days back, you can test to make sure: https://github.com/Codeinwp/gutenberg-blocks/pull/482

**Comment by HardeepAsrani** [comment]
related issue: https://github.com/Codeinwp/gutenberg-blocks/issues/483
