### ISSUE TITLE
Progress bar and circle counter in a post give console errors on the frontend which break the proper block rendering

### ISSUE THREAD

**Issue by kmgalanakis** [Codeinwp/otter-blocks#351]
In a clean WP installation, with just 2020 and your plugin, when I put a `Progress bar` or a `Circle counter` block, when I load the frontend I get the following errors.

![image](https://user-images.githubusercontent.com/1268089/99798753-34458180-2b3a-11eb-9f1b-bfe45f6e75cc.png)

Debugging this further I see that the error comes from this line here

![image](https://user-images.githubusercontent.com/1268089/99798803-49baab80-2b3a-11eb-9575-a681306ebae3.png)

Here is how the frontend looks

![image](https://user-images.githubusercontent.com/1268089/99798856-62c35c80-2b3a-11eb-8a86-f67ecb0b0e69.png)

The issue is reproducible with the released version of the plugin and with the `master` but **NOT with** the `development` branch of https://github.com/Codeinwp/gutenberg-blocks

**Comment by HardeepAsrani** [comment]
Hey @kmgalanakis,

We fixed this issue a few days back in development and will be releasing it soon: https://github.com/Codeinwp/gutenberg-blocks/pull/520/commits/aca1360083a98ad2e1f276cf61a8255e5b2cdd9b - thank you!
