### ISSUE TITLE
FA loaded from theme instead of plugin

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/otter-blocks#36]
I used the button block with 4 buttons to recreate the social icons but the FB one was style by the theme (which uses FA v 4.7) instead of the plugin: http://prntscr.com/mdqypd

**Comment by HardeepAsrani** [comment]
Can't do anything about it. The theme should follow the same naming convention for the `font-awesome` naming. That won't cause any issues.

**Comment by radu-themeisle** [comment]
It will if you have a theme using a section with FA 4.7 icons. For example Hestia's Contact Section, we had this issue when we tried implementinng FA5 into it as some icons have completely different UTF-8 code or class name and the shivs file didn'thandle all the icons.

**Comment by HardeepAsrani** [comment]
This shouldn't happen ideally but maybe this happen with Hestia. Regardless, we can't do anything to fix it. Theme will have to handle it from its end.

**Comment by HardeepAsrani** [comment]
@rodica-andronache How do you want to solve it? Do you want me to take a look and see how we can work with the FA 5, or just provide a way to unhook FA5 for our themes?

**Comment by rodica-andronache** [comment]
@HardeepAsrani using v4 shims doesn't help?

**Comment by HardeepAsrani** [comment]
@rodica-andronache I'm gonna be honest and say I'm very confused about what's happening with FA and so many versions and shims. 😄

**Comment by rodica-andronache** [comment]
@HardeepAsrani I'm not very good at this either :D I was thinking that these shim files would do the work https://github.com/Codeinwp/hestia-pro/tree/v2.0.17/assets/font-awesome/css Maybe @radu-themeisle can help more? 💃

**Comment by radu-themeisle** [comment]
You can't have FA4 and FA5 in the same time.
The shims CSS file is just a tool to help transition to the new version and it's not recommended by FA for long-term use.
The biggest issue is that FA5 uses different font-family(ies) than FA4 and also changed some UTF-8 codes for some icons and there's no match with the old, FA4, codes.
My best bet, if you really, really still want to go head with implementing FA5 but keep backwards compatibility, would be to create a plugin that searches for the old UTF-8 codes that don't match with the new FA5 codes and replace them.
