### ISSUE TITLE
Library preview and screenshot

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#41]
@HardeepAsrani I see there is a preview button on the block/template thumbnail in the library.
Nice change 👍 

What should I do so that preview work for the blocks within the theme? 
<img width="971" alt="otter-library-preview" src="https://user-images.githubusercontent.com/26867648/52121877-c01ab080-2629-11e9-8737-2efe5f8357dc.png">

Do you recommend a screenshot size for the thumbnail? I want to avoid that whitespace on sections with less height. 😄 

<img width="938" alt="otter-screenshot-whitespace" src="https://user-images.githubusercontent.com/26867648/52121892-c6a92800-2629-11e9-8475-43e5ec127dfa.png">

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu This is a work in progress and was commited to github by default (because build process is pretty sick right now). Once ready, the previews will be generated automatically (if the current solution works out), so nothing needed to be done on your side for the preview to appear. :)
