### ISSUE TITLE
scroll in scroll issue

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#42]
@HardeepAsrani when I import blocks on veganos theme I see this weird effect when a part of the blog is hidden somehow.

https://www.dropbox.com/s/ndg26yk2znkjdxd/Screenshot%202019-02-01%2017.49.31.png?dl=0

**Comment by HardeepAsrani** [comment]
@ineagu Can't reproduce. I guess it's poopy.life. Can you try someplace else?
