### ISSUE TITLE
template directory as block

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#43]
@selul @HardeepAsrani I think it would be useful to have a direct access to templates under the +, so if I click the shortcode to add a new block, considering that I want block templates, I need now to do 2 actions, would love to have a block called section templates, when clicked it would directly open the popup to insert.

#suggestion

**Comment by ineagu** [comment]
ok, can be enough, if you don't like the idea :D

**Comment by HardeepAsrani** [comment]
@ineagu By the way, post suggestions under `otter-blocks` repo as I'm keeping `gutenberg-blocks` for just as issue tracker so I can see all the things to work on immediately while having discussions on this repo about things which needs discussion or aren't confirmed.
