### ISSUE TITLE
Progress bar throws an error in the browser console and doesn't load on front end

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#438]
The progress bar block doesn't work properly, meaning that the background(percentage) of the bar doesn't load on the front-end. It works properly in the editor preview.

![progress-bar-editor-preview](https://user-images.githubusercontent.com/26867648/112815962-89b21200-9089-11eb-98fc-8e197c6e5cdf.png)
![progress-bar-issue](https://user-images.githubusercontent.com/26867648/112815969-8c146c00-9089-11eb-8599-ea19b4894a6e.png)

Ticket: https://secure.helpscout.net/conversation/1466315940/272649?folderId=212385

Otter Blocks version: 1.6.2 (it works with 1.6.1)

**Comment by stefan-cotitosu** [comment]
We can notify this customer that he can update the plugin once the issue is fixed - https://secure.helpscout.net/conversation/1465365988/272528/

**Comment by HardeepAsrani** [comment]
Should be fixed. Can you notify the user to update? Thank you for reporting! @stefan-cotitosu

**Comment by stefan-cotitosu** [comment]
Yes, I will update both tickets.
