### ISSUE TITLE
Columns margin override section's column gap

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/otter-blocks#45]
If I want to use column gap option the margin must not be set on the section's column.
I used backspace to get rid of the value from the margin input but when you view the page and come back to the editor the margin gets a default value of 20. If you update the page and view it you'll have margin top/bottom set to 20, and left/right set to the option from the section column gap.
If I set the column margin to 0 than the section column gap option doesn't work anymore, and the column margin disappears although you set the column gap from the section.
If I set the column margin to 30 (this value is the one used in Hestia's design) it also overrides margin left-right (which should be controlled by the section column gap option).

**Comment by HardeepAsrani** [comment]
Duplicate https://github.com/Codeinwp/gutenberg-blocks/issues/53
