### ISSUE TITLE
change the video in readme 

### ISSUE THREAD

**Issue by dascalescuro** [Codeinwp/otter-blocks#46]
@HardeepAsrani I added the video on TI channel after downloading it from your channel: https://www.youtube.com/watch?v=d8fRY4Xa7Vc

could you please embed it on the readme file on wp.org page?

thanks

**Comment by HardeepAsrani** [comment]
@dascalescuro Updated. Can you change video title to `Gutenberg Blocks and Template Library by Otter` instead?

**Comment by HardeepAsrani** [comment]
And should I remove the one from my YouTube?

**Comment by dascalescuro** [comment]
Title updated.

Your decision if you want to remove it. Thanks for making the change and for the video :)

**Comment by HardeepAsrani** [comment]
Just a note for myself: This issue is open as we haven't changed the links in Github which we need to do before we rerelease Otter.
