### ISSUE TITLE
Blocks fail when user doesn't have unfiltered_html capability

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#49]
Multi-site user can't use blocks from Otter if he/she isn't super admin. 

The following situation is happening on our demo where I can manage just some of the sites. So my role is administrator not Super Admin.

1. Create a page, add a block from Otter and click publish/update.
This is the Big Title section from Neve demo, on front-end.
![image](https://user-images.githubusercontent.com/26867648/52563322-b94e2380-2e09-11e9-96d3-2f10fa8c6739.png)

2. Click edit page. This is happening in the editor.
![image](https://user-images.githubusercontent.com/26867648/52563342-c703a900-2e09-11e9-8d9d-9c79ad4f4df3.png)

@HardeepAsrani Can you please take a look at this? 

Details on how to replicate this.
1. Create a multi-site on your local server
2. Add a new user that can manage only one site for example, as administrator, which is not super admin over the network.
3. Login as the new user
4. Create a page and add a block from Otter, click publish
5. Try to edit the page created at point 4. The block contains unexpected behavior.

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Thanks for the find. I'll take a look.

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu This issue happens on Multisite and on normal WordPress site too if the user doesn't have `unfiltered_html` capability, in multisite that is everyone but Super Admin, and in normal WP it's anyone below Editor level.

It's the same issue as https://github.com/WordPress/gutenberg/issues/2539

WordPress fixed it according to Gutenberg needs but I guess custom blocks will still have such issues. Really don't know what we can do about it. It's something that Core should fix for Gutenberg.

**Comment by HardeepAsrani** [comment]
cc @ineagu @selul

**Comment by HardeepAsrani** [comment]
I've sent a zip to @stefan-cotitosu for testing.

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani I've tried using the blocks (Neve & Otter both from org) with a non-administrator user. When you click the library button in the section block, the templates are not loaded. 

The issue is fixed in the zip that you sent to me. Not sure where the code is on Github. Hope that the right code will be released even if we tested using a zip now. There is something weird regarding the background overlay. It happens only on the front-end, in editor everything looks normal.

Editor
![image](https://user-images.githubusercontent.com/26867648/52696274-49f64200-2f77-11e9-8fd8-b3fff4031c83.png)

Front-end
![image](https://user-images.githubusercontent.com/26867648/52696266-42369d80-2f77-11e9-8f5a-bedf23f92170.png)

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu The code is in github but for that you'll have to change few things and do composer install, so I just send the zip so you don't have to do all that and can just test quickly without a big setup. Closing this as it's fixed.
