### ISSUE TITLE
Columns Gap option makes no change

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#500]
In the Section block there is an option to chose Gap between the columns from the dropdown:
![image](https://user-images.githubusercontent.com/36594177/128780201-d3fb4301-fcb7-4c2c-b5e2-c06628cca397.png)

No matter which is the option selected it makes no change to the gap/space between the columns:
![image](https://user-images.githubusercontent.com/36594177/128780244-a76b83c3-a58b-447f-a679-d36d6d6c68f2.png)

Screencast - https://vertis.d.pr/1qpXtT

Reported here - https://secure.helpscout.net/conversation/1594375781/288112

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius, yea, we added padding/margin options so they override these. We will remove them sometime in future.
