### ISSUE TITLE
Product Review Block: cannot remove the price once added

### ISSUE THREAD

**Issue by milicavs** [Codeinwp/otter-blocks#503]
In the Product Review Block, once you enter either price or the discounted price, you cannot remove it. When you try to delete it, it just resets to zero and is still displayed. 
This might be an issue with someone trying to display a temporary discount on a product.

**Comment by HardeepAsrani** [comment]
@milicavs It was fixed two days back in development: https://github.com/Codeinwp/gutenberg-blocks/commit/3e2deaa0f8f4b07bae81b0e21b283218189771f1 - I'm closing it for now.
