### ISSUE TITLE
Release zip files contains some dev files such as phpunit.xml, unit test files

### ISSUE THREAD

**Issue by mskapusuz** [Codeinwp/otter-blocks#507]
I see some dev files in the stable zip

example: in the /otter-blocks/packages/codeinwp/gutenberg-blocks

ss:
https://vertis.d.pr/vnQLEk
https://vertis.d.pr/bgdo4S

**Comment by HardeepAsrani** [comment]
Solved here https://github.com/Codeinwp/otter-blocks/pull/519
