### ISSUE TITLE
Icon Block style inheritance

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#509]
By default the Icon Block from Otter Blocks is nested inside a `<p>` element. This causes (may cause in future) some style issues, meaning that themes & wordpress add by default some margin or/and padding to` <p>` elements, which translates in a different spacing then intended.

For example on [this demo](https://demosites.io/architecture-gb/), the added bottom-padding is quite visible:
![image](https://user-images.githubusercontent.com/52494172/133992419-967b3931-3c8f-4d95-a3a1-96b34bb87579.png)
  
I checked other Plugins with Icon Blocks (Ultimate Addons for Gutenberg & Qubely) and both of them use `<div>` as Icon wrappers. But, as discussed with @Soare-Robert-Daniel on Slack, changing the HTML from p to div doesn't sound like a good idea, but we definitely need to address this and check if we have other instances of` <p>` (in other blocks) that are affected.

cc. @HardeepAsrani

**Comment by HardeepAsrani** [comment]
We can change it actually, not a big deal. It's not a nice change to make for us but if it's more semantic than we should go ahead with it.
