### ISSUE TITLE
Help in reproducing issue with Jetpack

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#51]
A couple of users reported an issue with Otter not working with Jetpack installed: https://wordpress.org/support/topic/the-editor-has-encountered-an-unexpected-error-attempt-recovery-copy-post-text/#post-11204210

Can someone help me in reproducing this issue? I've tried hard and wasn't able to reproduce. :(

**Comment by HardeepAsrani** [comment]
@radu-themeisle Can you try this? I guess this isn't an issue but maybe someone can double check with me so we could close this. 😄

**Comment by radu-themeisle** [comment]
I teste in Local and had no issue using Otter & Jetpack, everything works fine.

**Comment by HardeepAsrani** [comment]
Thanks @radu-themeisle!
