### ISSUE TITLE
Rephrasing the content of the Responsive options in Section block

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#521]
Hi there!
I noticed that there is a typo / different than usual expression while exploring the Global Defaults of Otter.
In the Section block, in the Responsive accordion are three questions with the same approach:

- Hide this section in Desktop devices?

- Hide this section in Tablet devices?

- Hide this section in Mobile devices?
Do you consider it would be more helpful to write "on" instead of "in"?

**Comment by Soare-Robert-Daniel** [comment]
From the internet, I see it goes with the `on` variant.
