### ISSUE TITLE
Otter 2.x

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/otter-blocks#523]
### New Blocks
- [x] #535
- [x] #558
  - [x] Counting Animations
  - [x] Typing Animations
- [x] #560
- [x] #699
- [x] #617

### Enhancements
- Block Conditions
  - [x] #561
  - [x] #604
- Global Defaults
  - [x] #710
- Posts Block
  - [x] #655
  - [x] Integrate with ACF (reference: [link](https://creativethemes.com/blocksy/docs/extensions/post-types-extra/))
- [x] #563

### Development
- [x] #518
- [ ] #527
- [ ]  #528
- [x] #557
  - [x] #532
- Performance
  - [x] #526
  - [x] #539
  - [x] #525
  - [x] #524
  - [x] #649
- Refactoring
  - [x] More robust design on the `class-main.php`
  - [x] Creating a good foundation on the backend for future features
  - [x] #559
### Research
- #679 [Postponed]
- Remove templates, better integrate with TC
- Presets (reference: [youtube clip](https://www.youtube.com/watch?v=I2VqPBfMA5Y))
  - After doing some research, don't think we can really make it work in much meaningful way with the block editor.

### Pushed to 2.x
- Copy/Paste Styles from one block to another, should be available for Otter + Core blocks, import media items on paste

@selul. @HardeepAsrani If I miss something **please edit this comment** to keep things more teddy and ideas not to be scattered around the issue.

The reference of the issues will be added here.

**Comment by HardeepAsrani** [comment]
I'll close this now. I've moved left out issues to their own separate issues.
