### ISSUE TITLE
Enhance the Icon (List block)

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#530]
It would be nice nice to have a few more options for the Icon List block. Basically the options to have the Icon boxed, framed. Check [Elementor Icon Box for inspiration](https://www.youtube.com/watch?v=VoMGDZ3Txpc). We don't need all the options from there, but in the end, the user should be able to achieve something like this:
![image](https://user-images.githubusercontent.com/52494172/138232162-e0849486-5900-4548-8d53-e0c0af7fa252.png)

Long term, maybe even this (having Title & Body for Icon List,  option to position the icon top, on the left-side, right side):
![image](https://user-images.githubusercontent.com/52494172/138232406-20c2b377-2a5c-4743-8b0c-fc1083e536ac.png)

**Comment by HardeepAsrani** [comment]
@mghenciu So far @Soare-Robert-Daniel has added the alignment option. For the boxed style, I think it might be worth doing that with Icon + Section as people can add whatever data they want, while the list will only have an icon and one paragraph but not something like: https://user-images.githubusercontent.com/52494172/138232406-20c2b377-2a5c-4743-8b0c-fc1083e536ac.png

What do you think? Or do you think we should add Description & Boxed layout too?

**Comment by mghenciu** [comment]
> @mghenciu So far @Soare-Robert-Daniel has added the alignment option. For the boxed style, I think it might be worth doing that with Icon + Section as people can add whatever data they want, while the list will only have an icon and one paragraph but not something like: https://user-images.githubusercontent.com/52494172/138232406-20c2b377-2a5c-4743-8b0c-fc1083e536ac.png
> 
> What do you think? Or do you think we should add Description & Boxed layout too?

The current changes should be fine. I think I just thought about it as a Icon list, but in production we actually use a separate Icon/Content box for each item.
Even in [Elementor demos](https://demosites.io/food-magazine/food-magazine-subscribe/) those items are a separate Icon Box. So we can add something like that on another block, not here.

Thank you!
