### ISSUE TITLE
 Make blocks pluggable by separating build files.

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/otter-blocks#532]
Approaches:
1. Create a pipeline for loading independent CSS files similar to what we do in JS.
2. Create a pipeline for merging the CSS files of the present blocks, then load only a single file.
3. Hybrid, group the CSS files based on importance. E.g.: `high` - append in header, `low` - append in footer.

Ref: #525

@HardeepAsrani, what do you think?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel There's one issue here. We will still have to upgrade to the new block.json format which is needed for WP 5.9...but it's not possible to make pluggable files as support for that doesn't fully exist until WP 5.8.

What do you think? Should we drop the pluggable files or use our own loader for the enqueue part? I've some ideas on how to do it and make it easier to migrate in future.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani  One of my initial ideas was to make the CSS separate and then in PHP to combine them all into a single file with PHP when requested (it can work separately, but I do not know which is faster - we can do some testing in this part. From my experience with Web Core, https/2 is the key with multiple files).

We can have a condition for checking the WP version. If it is `< 5.9`, we load the files via PHP with our solution, separate or combined.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yea, but the check won't be much simple. Anyway, we will get to it when we get to it.
