### ISSUE TITLE
SVG Icons

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#539]
We should allow users to use FA's SVG icons to optimize performance. We can just give them a field where they can copy/paste the SVG icon.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel This needs to be done to close the web vitals ticket.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, should we give the user a text field to paste the SVG code, or should we get the SVG via media files and the [SVG is loaded separately](https://www.wpbeginner.com/wp-tutorials/how-to-add-svg-in-wordpress/https://www.wpbeginner.com/wp-tutorials/how-to-add-svg-in-wordpress/)?

**Comment by HardeepAsrani** [comment]
We can allow them to upload it and use it there as an image. This way it can also be cached.

**Comment by HardeepAsrani** [comment]
Just make sure that if that way we can use fill to change the color.
