### ISSUE TITLE
Button Group block invalid after save

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/otter-blocks#54]
@HardeepAsrani 

WordPress automatically adds `rel="noopener noreferrer"` to links upon post save. 

I've managed to avoid this by stripping the `rel` attributes from content upon importing in the onboarding. This way at first sight everything looks ok after the import. However, after save and refresh, the block markup is invalidated and this renders an invalid markup for the button group block. 

A fix for this would be to add `rel="noopener noreferrer"` by default to the button markup as I don't really think there's a workaround. 

![image](https://user-images.githubusercontent.com/15010186/53961871-61e26100-40f2-11e9-9eb9-49da86286c55.png)

![image](https://user-images.githubusercontent.com/15010186/53961917-758dc780-40f2-11e9-9a3c-b1625fa3cc03.png)

cc:@selul

**Comment by abaicus** [comment]
After reading a bit more on the issue, I understand that this is really bad for SEO and used to avoid **Reverse Tabnabbing** - open a link in a new tab and redirect the previous tab to something else. 

Maybe @ineagu and @dascalescuro have an idea about how this affects SEO more in depth.

**Comment by HardeepAsrani** [comment]
@abaicus This was added to gutenberg in WP 5.1, and we’ve already fixed it in development. 😀

**Comment by rodica-andronache** [comment]
@HardeepAsrani do you have this planned for a specific release? :) We wanted to add the Gutenberg starter site in Neve, and we would need this for it

**Comment by HardeepAsrani** [comment]
Very soon, perhaps by Monday. Just being tested heavily just to make sure we don’t break anything.

I’m not sure if there are any SEO a disadvantages of that rel tag so I’ve left it there by default. If there are any, then let me know and we can fix that in future.

**Comment by ineagu** [comment]
avoiding those tags is more of a security issue as far as I know, nothing to do with SEO

**Comment by HardeepAsrani** [comment]
@abaicus It's fixed in 1.1.5 version. 😄
