### ISSUE TITLE
Posts Block Improvements

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#543]
Card effects, Ability to use Products ( enable add to cart/comparison/wishlist inside). More details will be added soon. Part of #1451

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel can you take care of this? The details on the changes is here: https://github.com/Codeinwp/otter-blocks/issues/655#issue-1080946773

**Comment by Soare-Robert-Daniel** [comment]
@JohnPixle, no problem with it for me 👍 . That issue will only for Post Block. In this I see other mentions for features. We will keep them both, but for Posts we will the otter issue #655

**Comment by HardeepAsrani** [comment]
Will close this in favor of https://github.com/Codeinwp/otter-blocks/issues/655
