### ISSUE TITLE
Add video background to Section

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#545]
Add video background support to Section block.

**Comment by HardeepAsrani** [comment]
@JohnPixle @mghenciu Do you all think it's something we should have? Personally, not a big fan of background videos, they never look right and make the page slow.

**Comment by mghenciu** [comment]
As mentioned [here](https://github.com/Codeinwp/otter-blocks/issues/803), and based on features that the competition has, **I think this is a nice to have**. Even if we don't use it, customers may need it.

For example even the Cover Block from Core, has a video background option.

**Comment by JohnPixle** [comment]
I also vote for including it. I am not a big fan either, but it might be useful for users in many cases.
