### ISSUE TITLE
Fatal error when not in ‘direct’ file system mode

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#546]
More details soon, just a note for later. Context :https://wordpress.org/support/topic/fatal-error-when-not-in-direct-file-system-mode/

**Comment by HardeepAsrani** [comment]
I've never experienced this nor can I get my setup to work in such a way. Any ideas @selul?

**Comment by selul** [comment]
@HardeepAsrani have you tried to change the FS_METHOD to something like `ftp` ?
