### ISSUE TITLE
Section padding/margin

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#547]
@HardeepAsrani I think this was discussed before, I couldn't find the issue here. The fact that by default the section is adding padding + columns are adding padding, makes theme unusable for me, since every time I would need to bring those to 0.

I guess this makes sense in a full-width context, while when you're just writing a post, is really annoying.

Maybe have some context-based settings along with some defaults that you can set from the options page?

cc @selul

**Comment by HardeepAsrani** [comment]
Should be fixed in with: https://github.com/Codeinwp/otter-blocks/issues/563
