### ISSUE TITLE
Update Block Default fields

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#548]
We should update and add more settings to Block Defaults, including adding new blocks to the list.

Also: Shadow option for Heading.

**Comment by Soare-Robert-Daniel** [comment]
## Testing

Activate the sticky vie block menu.
![image](https://user-images.githubusercontent.com/17597852/147083868-a367ccb7-628f-4e02-8471-3f748cb7ce68.png)

It removes in the same way.

![image](https://user-images.githubusercontent.com/17597852/147083790-7b63c6b7-8f65-4753-8d72-079dbadebf52.png)


### Option: Stick To
| Value | Action |
| --- | ---- |
| Default | Stick to the top section of the List View |
| Column/Group | Stick to the column/group section from which has the sticky block |
| Section | Stick to the first section in which the block is |
| Screen | Stick to the screen |

⚠️  Core blocks like Group and Columns are valid containers; they are alternatives to Section Block.

![stick-heir](https://user-images.githubusercontent.com/17597852/147081834-ce9e90a2-0ed4-443a-9c84-6d5f9f4199b4.jpg)

### Option: Position
| Value | Action |
| --- | ---- |
| Top | Stick to the top of the screen |
| Bottom | Stick to the bottom of the screen |

### Option: Offset

Set the distance from the screen.

### Option: Behaviour 
⚠️ This is used to solve the conflict between overlapping sticky elements

| Value | Action |
| -- | -- |
| Default | The stick element goes behind |
| Hide | The sticky element fade out |
| Stack |  The sticky element is kept, and the next one is below |

⚠️ For the `stack` option to take effect, the sticky elements must have the same container and same `stack` option. To see this effect, make a section, puts some elements, mark them as `sticky`, then choose `stack`, preview it.

## Templates

Those are some templates for testing.
 
[template2-stack-option.txt](https://github.com/Codeinwp/otter-blocks/files/7762245/template2-stack-option.txt)
[template3-ads.txt](https://github.com/Codeinwp/otter-blocks/files/7762248/template3-ads.txt)
[template4-sidebar.txt](https://github.com/Codeinwp/otter-blocks/files/7762249/template4-sidebar.txt)
[template5-subscribe.txt](https://github.com/Codeinwp/otter-blocks/files/7762250/template5-subscribe.txt)
[template6-multiple-section.txt](https://github.com/Codeinwp/otter-blocks/files/7762251/template6-multiple-section.txt)
