### ISSUE TITLE
Accesibility Audit

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#553]
I want to do an accessibility audit of Otter and find the issues with it and then fix them. It's better to think of accessibility of the plugin from the beginning so we don't have to "hack" things into it later.

If we do it now:

- The code will be better
- Will be really helpful to people suffering disabilities
- A good way to promote
- I will also learn about a11y which will help us in the future
- It will be harder in future and easier when the plugin is new

So far the plugin is accessible in terms of keyboard navigation but not in terms of accessible HTML code.

The idea is to first learn accessibility guidelines (maybe a course or reading articles, or maybe a book or docs) and then implement. I suspect it to take around two weeks of time (could be way more or less but that's my current estimate).

And once we are done we can maybe hire someone from Upwork to do a small audit?

I personally find accesibility to be a priority and would like to get your perspectives. @selul

**Comment by mghenciu** [comment]
I've done a first round of Accessibility review, for Otter back-end.
Even though I found a considerate amount of things we can improve (based on my limited knowledge and things I learned in this period), long term I think it wold make sense to also to an audit/hire someone to test, someone who uses screen-readers (and other accessibility features) everyday.

https://www.notion.so/themeisle/Potential-Issues-e92b17bdbb744d099479dfc818e59967
