### ISSUE TITLE
Update animate.css to latest version

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#556]
We should update to the latest version of animate.css and use all the latest animations: https://animate.style/

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Okay so I was looking into this and I remember we didn't do it then because of the animate_ prefix issue.

And I found this out today: https://animate.style/#migration - so it's a note for the future, they do provide a backward-compatible CSS version too.

**Comment by HardeepAsrani** [comment]
@arinaturcu This can be your getting starting ticket for Otter. You can make a fork out of development branch and try this. I'll get you started with here and you can ask if you have any questions. The file structure can be confusing at first but feel free to ask questions here or on Slack.

**Comment by Soare-Robert-Daniel** [comment]
@arinaturcu beware that the code hsa underwent some trastic change in tooling. So `npm run start` might not work as expected every time you change some code. If you have some weird problem, terminate the process and run it again. It some cases you will might one to delete the `build/` folder.
