### ISSUE TITLE
Block Ideas

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#57]
@HardeepAsrani this can be ignored, just noted down here some things on which we can look at some point in case we wanna explore a multiple blocks solution :

1. Ads block
2. Stripe,Paypal (payment) & MailChimp blocks ( newsletter )
3. Nivo Slider block (free)

**Comment by HardeepAsrani** [comment]
@ineagu Just putting out there for future reference: we can probably turn Section into a Slider, like this:

![Slider](https://user-images.githubusercontent.com/2649903/57007450-5ef18180-6c06-11e9-838e-98807735873b.gif)
