### ISSUE TITLE
Image Grid Extension not working with new Gallery Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#572]
The options for Image Grid extensions don't show up in the new experimental Gallery Block that comes with the Gutenberg plugin.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, Gallery now uses `innerBlocks` for insertion. The `images` attribute is empty, the plugin is not working because there are no images in attr.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yea, I checked it then and the same reason why the our Image Reordering extension wasn't working.

**Comment by Soare-Robert-Daniel** [comment]
In #688, this will be disabled for ^5.9.
