### ISSUE TITLE
Move options page to a dedicated menu item

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#575]
@HardeepAsrani as the plugin grows and we might wanna have sub-pages as well, we might wanna have a dedicated menu page for otter, it would give better exposure and more freedom to structure the content in sub-pages. For e.g we can have a dedicated page where we list the PRO blocks if the user have neve :D

**Comment by ineagu** [comment]
@HardeepAsrani I think is time for this, we move more and more things there, we want to add the notification system, potentially an about page & upgrade link.

**Comment by HardeepAsrani** [comment]
We can take an Elementor like approach and we have the User Role editor that you talked about, settings based on User Role, Email Submissions and things here.

<img width="363" alt="Screenshot 2022-12-01 at 6 59 43 PM" src="https://user-images.githubusercontent.com/2649903/205065239-a217cfbf-546e-4064-9ff0-7268d5e8380d.png">

**Comment by ineagu** [comment]
yes, exactly, good place for form submissions as well
