### ISSUE TITLE
section as default block for pages

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#58]
@HardeepAsrani I am not sure if the current implementation is helpful for what I had in mind, here is what makes more sense for me 👍 

1. Show the section by default on pages, along with a x button, which on-click hide the section
2. If you wanna be less annoying, after the user do this 3 times, we can ask them on 3rd x click if they wanna remove the section block as default block on pages.

We get more usage, it isn't annoying and we can iterate later on it. cc @selul

**Comment by HardeepAsrani** [comment]
@ineagu The current implementation is just an early shipped feature as we had to release this version quickly to fix some major releases. The 2.0 will have an inboarding and welcome page that will handle all of this in the admin panel.

**Comment by selul** [comment]
@HardeepAsrani I'm not sure what @ineagu's reply has to do with the welcome page or onboarding. We can do those indifferent of what will provide the 2.0 release.

**Comment by HardeepAsrani** [comment]
Sorry, I meant 1.2, not 2.0. @selul

**Comment by HardeepAsrani** [comment]
Part of: https://github.com/Codeinwp/otter-blocks/issues/28
