### ISSUE TITLE
Pros/Cons in Review Block losing focus

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#597]
Ref: https://wordpress.org/support/topic/review-block-ver-1-7-1-breaks-pros-and-cons-editing/#post-15041842

**Comment by Soare-Robert-Daniel** [comment]
The issue is there. Pros, Const, Features still lose focus on the `development` branch.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel I had fixed it for the Review block's edit part, forgot that these values could also be edited from the inspector. Fixed it.
