### ISSUE TITLE
Function called with wrong parameters

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/otter-blocks#600]
According to the [documentation](https://developer.wordpress.org/reference/functions/get_the_content/), the `get_the_content` function has 3 parameters: `$more_link_text`, `$strip_teaser` and `$post`.

In https://github.com/Codeinwp/otter-blocks/blob/master/inc/class-main.php#L492 the function is called just with the `$post` parameter. Not giving the default values for `$more_link_text` and `$strip_teaser` will call the function with `$post` parameter in `$more_link_text` position.

**Comment by HardeepAsrani** [comment]
Thanks, @Soare-Robert-Daniel for the quick PR!
