### ISSUE TITLE
separator overriding other elements

### ISSUE THREAD

**Issue by cosmin-serbanescu** [Codeinwp/otter-blocks#61]
http://prntscr.com/mvwww9 
probably just a z-index issue @HardeepAsrani

**Comment by HardeepAsrani** [comment]
I don't understand. Can you please explain? 😄

**Comment by cosmin-serbanescu** [comment]
the blue columns separator is overriding the other elements from the editor, normally it should stay within the section itself, right?

**Comment by HardeepAsrani** [comment]
Fixed in https://github.com/HardeepAsrani/gutenberg-blocks/commit/e822e1a4dcb262f730ecfc99fd0f8c3224fef350
