### ISSUE TITLE
Form Block Changes

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#615]
- [x] Add an option for post-submit action:
  - Show custom message
  - Redirect to a page
  - Send user an email
  - Also a hook

- [x] Wrap form with a `<form>` tag to make sure theme styling works.

- [x] Allow Submit button text to be changed.

- [ ] Test to make sure form works properly without SMTP details in instances where other form plugins work.

- [x] Add doc link for SMTP option

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel I had made this back in November. Can you move your form ideas here so we can have them in one place?

**Comment by JohnPixle** [comment]
I think there is some design input from @mghenciu about the form as well at #725, and I will add some of my thoughts here to consider as well.

- As Mihai pointed, there needs to be some padding at the input fields
- please note that currently the "required" text is in bold for the message (text area) field.
![Screenshot 2022-02-23 at 09 20 51](https://user-images.githubusercontent.com/4193672/155276712-81caf20a-49de-4e60-a6dd-75d53b7aca31.png)
- please also note that the border color of the text area is different than the input fields. It would be great to be able to customise the width, radius and color of the border of input fields.
- Like we do for columns, it would be super useful if we add a dropdown that defines the width of a field (100 / 50 / 33). rough mockup below.
![Screenshot 2022-02-23 at 09 32 13](https://user-images.githubusercontent.com/4193672/155277386-793994af-1612-46a0-8856-4474b088e55a.png)
- at some point we will need to think about styling error and validation messages / notices.

**Comment by mghenciu** [comment]
@HardeepAsrani , for the post submit actions please keep in mind the aspects [I mentioned here](https://www.notion.so/themeisle/Pro-Features-702a100059c146c48079e9ab5591c28f#84056b0971764319a1351c6bcc68548d).
We can add those later.
