### ISSUE TITLE
Weird errors on Widget Screen

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#626]
Robert & I found some errors on the Widgets screen with Otter blocks which are not consistent. Sometimes they happen, sometimes they don't. We need @irinelenache your QA eyes to help us find what actions are causing these errors and how to reproduce them consistently.

Here are a few ways that we get an error:

- Add a Section block to the widget page. Click on it. Press the Delete button on your Mac (or Backspace in Windows) and you see an error in the console. Make sure Section is still in placeholder with no layout selected.
- Add a Section block, select all the widgets, and press delete. The entire page breaks down then but it is no consistent.

It will be good to find out:

- What errors are appearing and how to reproduce them?
- If they are from Otter or you can also reproduce them with Otter?
- And if they're from Otter, can you reproduce them with blocks other than Section too?
- And if you find a pattern, does it happen on post editor too?

You can test them with the latest Otter from WordPress.org.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, @irinelenache one error appears if you have `Disable Cache` activated in the Network Tab. Insert some blocks in the widget, save, activate `Disable Cache` and the reload, something like [this will appear in the console](https://gist.github.com/Soare-Robert-Daniel/d5576d769f9ffdcf4519c8da852ce116) - I have unminified version with `define( 'SCRIPT_DEBUG', true );` .

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani some code is deprecated. [`Button` has no longer props like `isPrimary`, `isSecondary` ](https://github.com/WordPress/gutenberg/pull/31713/files#diff-67ab236c71ce64ad2b69b520e436360298871296da9edc93901033e9519193bf)

A weird error about `key` in `DisplayTimeComponent` is displaying withe inserting a Countdown Block

**Comment by HardeepAsrani** [comment]
@irinelenache We think we figured things out. You should have things here: https://github.com/Codeinwp/otter-blocks/pull/630

Can you use that PR and make sure all blocks work properly in the Widgets without throwing any errors in the browser console?
