### ISSUE TITLE
Making Otter i18n Compatible

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#629]
We need to make sure the child plugins use their own text domains instead of using otter-blocks as it's making them untranslatable.

**Comment by MarinescuLucia** [comment]
@HardeepAsrani Is there any update on this? There is another user on the [forum](https://wordpress.org/support/topic/translation-of-the-posts-block/) reporting that the Read More button can't be translated with Loco Translate.

**Comment by HardeepAsrani** [comment]
@MarinescuLucia not yet but will try it will be out by the end of Jan.
