### ISSUE TITLE
Custom CSS not working on Section Block

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/otter-blocks#631]
When CSS is applied in a section block, it's not taking the changes when in the latest version (v1.7.3).
This is working fine in v.1.6.9 of Otter.

See this screencast for reference: https://vertis.d.pr/Eem0UH

Ticket: https://secure.helpscout.net/conversation/1701105873/299927?folderId=212385

**Comment by Skystream96** [comment]
It is also not working on the Advanced Header block. No errors are shown in the console.

**Comment by HardeepAsrani** [comment]
It pretty much doesn't work with any blocks coming from Otter. Thanks, I'll take care of it.

**Comment by purplecodes** [comment]
@HardeepAsrani this is in relation to custom CSS but let me know if I need to raise this separately.
The same customer is reporting that all custom CSS disappears when he made the latest update (v1.7.3)

https://www.loom.com/share/305ddf7f0581417d85cd52d12d5da8d9

**Comment by HardeepAsrani** [comment]
@purplecodes It's the same thing. We will release an update soon.
