### ISSUE TITLE
Accordion title automatically centers when an image/icon is placed before it.

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/otter-blocks#632]
When the accordion title is all text, it's aligned to the left. However, if there is an icon before the title, it centers as seen on the screenshot.

https://vertis.d.pr/JV8O48
https://vertis.d.pr/3IfSCG

Ticket: https://wordpress.org/support/topic/accordions-items-image-emoji-issue/

**Comment by HardeepAsrani** [comment]
Hey @purplecodes,

I tried to reproduce it but wasn't able to. I tried it on Firefox, Chrome & Safari. I tested it with the default WP theme, Neve & Hestia.

Can you help me in reproducing?

**Comment by purplecodes** [comment]
I created a screencast @HardeepAsrani 
Please see it here: https://vertis.d.pr/90pKYt

Is this the expected behavior?

**Comment by HardeepAsrani** [comment]
@purplecodes Got it, thanks.

@Soare-Robert-Daniel I'll need your help here as it seems to only happen on Windows (with Chrome at least).

**Comment by Soare-Robert-Daniel** [comment]
This is the problem: https://wordpress.org/support/topic/ios-emoji/#post-10787822

I found no CSS solution to this. I think we will need an extra container for this:

https://github.com/Codeinwp/otter-blocks/blob/2cba899951d9906e55e995d978a8422108381336/src/blocks/blocks/accordion/item/save.js#L15-L20
