### ISSUE TITLE
Uncaught ReferenceError: L is not defined

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#640]
@HardeepAsrani 
When we use the Maps block to display Open Street Maps, it gives the following error in the console. 

```
 ReferenceError: L is not defined
    at leaflet-gesture-handling.min.js?ver=1.7.0:1
    at leaflet-gesture-handling.min.js?ver=1.7.0:1
    at leaflet-gesture-handling.min.js?ver=1.7.0:1
(anonymous) @ leaflet-gesture-handling.min.js?ver=1.7.0:1
(anonymous) @ leaflet-gesture-handling.min.js?ver=1.7.0:1
(anonymous) @ leaflet-gesture-handling.min.js?ver=1.7.0:1
```
Also, there is a lot of mixed content errors.

Test instance:

URL: https://rotspace.tastewp.com
Username: poonam
Password: Xgd6ISVdjOA

Screenshot >> https://vertis.d.pr/TDGWGn

**Comment by Soare-Robert-Daniel** [comment]
The fix will be in the next release.
