### ISSUE TITLE
Increase Section max-width limit

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#648]
We can double it to 1200px.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, are you sure is the section? The section has a limit of 1800. Also found a bug when I checked out #651

**Comment by HardeepAsrani** [comment]
Yea, I meant 2400px, sorry for the error. @Soare-Robert-Daniel

**Comment by HardeepAsrani** [comment]
Can you bump the max to 2400 instead?
