### ISSUE TITLE
Generate translation files

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#66]
Ref: https://www.npmjs.com/package/@wordpress/babel-plugin-makepot

**Comment by HardeepAsrani** [comment]
https://developer.wordpress.org/block-editor/developers/internationalization/

**Comment by HardeepAsrani** [comment]
Another update here:

One of the reasons why WP CLI wasn't working properly was because, sadly, WP-CLI can't include vendor folder for translations.

There are two solutions. Either we can make composer to hold `codeinwp` deps in folder different than vendor.

Or we can use this custom WP-CLI comment: https://github.com/pronamic/wp-pronamic-ideal/blob/develop/src/i18n-make-pot.php

What do you think is better? @selul

**Comment by HardeepAsrani** [comment]
Don't know why WP-CLI can't fetch translations from the build files of the plugin.

**Comment by selul** [comment]
Yes, let's go with the 2nd option.

**Comment by HardeepAsrani** [comment]
I've tried many times and never been able to get this to work properly. Can you help @abaicus as I seen you've done it for Neve.

**Comment by selul** [comment]
I can help with this.

**Comment by HardeepAsrani** [comment]
Sure, sure. Happy to get this off my plate.
