### ISSUE TITLE
[Feature-request] Testimonial Slider Block

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#681]
A user suggested we should add a testimonial slider block to our collection. It can be helpful for Hestia users who want to replace the in-built testimonial section with a testimonial slider. 

https://secure.helpscout.net/conversation/1755447906/305921?folderId=212390

**Comment by Soare-Robert-Daniel** [comment]
One idea is to make a General Slider Block. It won't have much customization like a dedicated one, but it can serve as a simple solution for some designs.

**Comment by HardeepAsrani** [comment]
I had an idea about this in past, will share in details on how we can make a general slider which can work with anything after we're done with this release,

**Comment by HardeepAsrani** [comment]
Closing in favor of https://github.com/Codeinwp/otter-blocks/issues/1313
