### ISSUE TITLE
Section Block: Cannot vertically align column contents

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#685]
While working on a starter site, I noticed that I cannot vertically align the contents of the section columns.
The control seems to be stuck with the top alignment.

WP Version 5.8.3, and latest versions of Neve and Neve PRO.
I tried with the default WP theme as well, and had the same results.

Thanks for your consideration @HardeepAsrani 

![Screenshot 2022-01-17 at 09 57 28](https://user-images.githubusercontent.com/4193672/149740480-f02e5adb-d479-42e0-812e-b0883c5c670c.png)

**Comment by Soare-Robert-Daniel** [comment]
Hi @JohnPixle,

Can you give us the block code for that section to analyze it?

**Comment by JohnPixle** [comment]
@Soare-Robert-Daniel thanks for following up!
I created a new page that uses only a section block: https://demosites.io/recipes-blog-gb/test-otter/

Here is the code for the section block

```
<!-- wp:themeisle-blocks/advanced-columns {"id":"wp-block-themeisle-blocks-advanced-columns-1b58bab3","columns":2,"layout":"equal","layoutMobile":"collapsedRows","paddingType":"unlinked","paddingTypeMobile":"unlinked","paddingTop":0,"paddingTopMobile":20,"paddingRightMobile":20,"paddingBottom":80,"paddingBottomMobile":20,"paddingLeftMobile":20,"marginTop":0,"marginBottom":0,"columnsWidth":1170,"horizontalAlign":"center","verticalAlign":"flex-start","align":"full","hasCustomCSS":true} -->
<div class="wp-block-themeisle-blocks-advanced-columns alignfull has-2-columns has-desktop-equal-layout has-tablet-equal-layout has-mobile-collapsedRows-layout has-default-gap has-vertical-flex-start" id="wp-block-themeisle-blocks-advanced-columns-1b58bab3"><div class="wp-block-themeisle-blocks-advanced-columns-overlay"></div><div class="innerblocks-wrap"><!-- wp:themeisle-blocks/advanced-column {"id":"wp-block-themeisle-blocks-advanced-column-ba04570b","columnWidth":"50"} -->
<div class="wp-block-themeisle-blocks-advanced-column" id="wp-block-themeisle-blocks-advanced-column-ba04570b"><!-- wp:heading -->
<h2>This is a heading inside the column</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>This is text. Paragraph text.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:themeisle-blocks/advanced-column -->

<!-- wp:themeisle-blocks/advanced-column {"id":"wp-block-themeisle-blocks-advanced-column-5279f151","columnWidth":"50"} -->
<div class="wp-block-themeisle-blocks-advanced-column" id="wp-block-themeisle-blocks-advanced-column-5279f151"><!-- wp:image {"id":454,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="https://demosites.io/recipes-blog-gb/wp-content/uploads/sites/650/2022/01/neve-recipes-f-03.png" alt="" class="wp-image-454"/></figure>
<!-- /wp:image --></div>
<!-- /wp:themeisle-blocks/advanced-column --></div></div>
<!-- /wp:themeisle-blocks/advanced-columns -->
```


Let me know if you guys need any more info!

**Comment by Soare-Robert-Daniel** [comment]
@JohnPixle, I check it on my end, and it is working: 
![image](https://user-images.githubusercontent.com/17597852/149761924-8ed63534-3b64-4345-bb27-360e9205a749.png)

I do not know if this might be some page problems. If you refresh the page, is it the same behavior?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Are you using the version available on WordPress.org?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, you are right. I was on the `development` branch. We can say that this issue is fixed for the next release.

**Comment by JohnPixle** [comment]
Thanks for the help!
