### ISSUE TITLE
Add more Visibility conditions for Blocks, maybe we can get some of them from Neve Custom Layouts

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#686]
I know that there are plans for some improvements around Visibility conditions and Woocommerce, but I also think we could also add more generic conditions, maybe get inspiration from Neve Custom layout conditions, if possible (attached screenshot).
![image](https://user-images.githubusercontent.com/52494172/149977914-9af5d71b-13f5-4a9f-961b-0e02234b4456.png)

For example one usecase where I needed this was the Real Estate site. Where I wanted to add in the Sidebar, a block with the real estate agent for each property. The problem here was that it was showing on both Archive and Single Property page, so some conditions would've help. 

Another example could be for Marketing purposes, let's say if an an user has a Store and wants to display a banner for each Product Category.

**Comment by HardeepAsrani** [comment]
@mghenciu We've already added many for WooCommerce & LifterLMS which will be out soon. For the rest, you can make a list of all the possible ones and we can see which makes sense.

**Comment by mghenciu** [comment]
I guess you are referring to this ones >> https://github.com/Codeinwp/otter-blocks/issues/561

I'll trow some ideas, but feel free to comment (when you have time) if this makes sense from a technical point of view:
- Post or Page type. Meaning that if I add a Real Estate plugin, or any other plugin that creates specific single pages, it would be nice to show something conditionally only on those type of pages.
- Category/Taxonomy based. We have  Categories for Post & for Products. So let's say we have a Finance blog, I would want to display on the sidebar blog - a calculator. If the user reads an article from the Home ownership category - I would display a Mortgage calculator, but if he reads an article about investing - I would display an Investment Calculator.

**Comment by HardeepAsrani** [comment]
I've made a separate issue for these two:

- https://github.com/Codeinwp/otter-blocks/issues/750
- https://github.com/Codeinwp/otter-blocks/issues/752

If you're satisfied then feel free to close it or let us know if you have more ideas. Thanks!
