### ISSUE TITLE
Otter Pro

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#687]
@HardeepAsrani @Soare-Robert-Daniel I add this here as a placeholder to brainstore over some functionality for otter pro. I guess some of them would be the things from neve pro plugin that would work for all themes.

Ideally we want features to work individually as a freemium, the best example is block conditions, where we do have some in free and more in pro. So instead of upselling new blocks and new features only, we'll also offer "upgraded" blocks/features.

For the templates part, we can digg more into how Kadence/generate are approaching this to make sure they work with any theme and then decide if we want to have them in otter or require the install of the starter sites plugin.

**Comment by HardeepAsrani** [comment]
@ineagu We also have Popup as a freemium product that has both free and pro versions, while Review Block also comes with Woo + Comparison table extension when using with Neve Pro.

**Comment by HardeepAsrani** [comment]
@ineagu Soon we will also have a WooCommerce Builder for Neve Pro users so that can also be something useful. It's a pretty sick feature and should be useful as long as WooCommerce doesn't come up with their own. :)

**Comment by ineagu** [comment]
right, the idea is that likely we'll want those to be theme agnostic in the next iteration.
