### ISSUE TITLE
Please add YouTube and Instagram Icons in Sharing block 

### ISSUE THREAD

**Issue by mjza** [Codeinwp/otter-blocks#69]
In your sharing block I cannot find the YouTube and Instagram icons. Could you please add them?

**Comment by HardeepAsrani** [comment]
@mjza It's sharing icons so you can't really share links to Instagram. It's not "Follow" icons but "Share this page on your XYZ."

Let me know if that sounds right, or if I'm missing something? 😄

**Comment by mjza** [comment]
@HardeepAsrani Hi. Yes you are right. I missed up with following link. Thanks.

**Comment by HardeepAsrani** [comment]
@mjza Happens. I've received this same request from many of my colleagues too. 😄
