### ISSUE TITLE
Section transition between Fixed to Full-width and backwards

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#693]
When a new Section is added with Otter, by default the content width is set to **100% width**:
<img width="1725" alt="Screenshot 2022-01-28 at 12 21 56" src="https://user-images.githubusercontent.com/52494172/151530294-0ddb0796-21ec-4981-96a3-8709e9a18f18.png">

everything good so far, but if I change that value to 1200px (can be any number) -> the Content width will become fixed, and there is no way back to **100% full width** (not even after removing the value or making the value equal to 0):
<img width="1709" alt="Screenshot 2022-01-28 at 12 53 43" src="https://user-images.githubusercontent.com/52494172/151535397-b05702d6-0bbf-4541-a5f6-949d0d0806f1.png">

My suggestion would be to add a Reset Button (like we have on the Advanced Heading size) or if the field is empty -> that would make the section 100% width, as it is by default:
<img width="282" alt="Screenshot 2022-01-28 at 12 57 01" src="https://user-images.githubusercontent.com/52494172/151535341-8f8eef77-0279-49ad-ba02-accd1415d548.png">

Otter version: 1.7.4

**Comment by HardeepAsrani** [comment]
Can you also take care of this? @arinaturcu - thank you!
