### ISSUE TITLE
Cannot translate some strings

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#697]
I think it might be related to changes made here - https://github.com/Codeinwp/otter-blocks/issues/66
We're not able to translate strings of the contact form block:
![image](https://user-images.githubusercontent.com/36594177/151870124-744f1761-cedd-4935-a884-8046aca89071.png)

We want to translate strings "Subscribe" and "(required):
![image](https://user-images.githubusercontent.com/36594177/151870284-45fb262b-c3c8-4dce-a26b-1320b3471f08.png)

I'm not able to do so.
The client is using the plugin **_Say What?_** https://wordpress.org/plugins/say-what/ and not able to translate it.
I can't translate it neither with this plugin nor manually.
![image](https://user-images.githubusercontent.com/36594177/151870951-c66f9367-1ebf-4ed7-a3c2-ba2f93e90f27.png)

I think the strings are coming from the build/blocks/blocks.js

I see that both strings exist in /languages/otter-blocks.pot file, however, I can't translate it.

The block remains present (just loses some styles) even if I disable the Otter blocks plugin and change to a default WordPress theme like TwentyTwentyOne:
![image](https://user-images.githubusercontent.com/36594177/151870746-5b54c11f-4dc1-41a4-84d8-077008d60f23.png)
So I don't fully understand how it's cached and where to translate these strings.

Ticket for reference - https://secure.helpscout.net/conversation/1762628434/306866

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius First of all, nice plugin Say What. Works so well.

Second, it's happening because in Gutenberg, the HTML is saved into the post. It's a static string that the person can't translate using the plugin.

The only way for him to translate is to delete the form and add it back again.

**Comment by vytisbulkevicius** [comment]
@HardeepAsrani,

Thanks for the explanation, I confirm that it works if you re-create the form. Closing this issue then.
