### ISSUE TITLE
[Feature Request] Create a switch to choose which tabs to open at first sight

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/otter-blocks#698]
One user suggested that we could implement a switch for our Tabs Block which would allow the developer of the website to choose the tab that will automatically open when the user visits the page.

We could implement it as a dropdown setting in the settings sidebar or maybe there is already a filter that we can use to achieve that?

[User reference here.](https://secure.helpscout.net/conversation/1772945324/0/?folderId=212385)

What do you think about this?

**Comment by Soare-Robert-Daniel** [comment]
The first tab is *always* open. If you want a particular Tab to open first, you need to move it to the first position using the Tabs Management panel in the Inspector using hold and drag on the three horizontal bars.

![image](https://user-images.githubusercontent.com/17597852/152111797-52cbf56a-ef17-43fc-8ab6-c4bd03a4f295.png)

**Comment by HardeepAsrani** [comment]
@Skystream96 @Soare-Robert-Daniel Yea, it makes sense for Accordions but don't know why one would want this for Tabs. We can keep this open and add +1 if more users request.

**Comment by HardeepAsrani** [comment]
@mghenciu Do you think this option makes sense for the tabs like we have for the accordion?

**Comment by mghenciu** [comment]
> @mghenciu Do you think this option makes sense for the tabs like we have for the accordion?

For the use-case mentioned in Helpscout, that's more of a snowflake (something that is rarely needed/used).
But after checking 4 other Block providers, 2 of them (the ones with the most downloads) have this option.

So I guess we can add that toggle here, but keep in mind that for this case we'll need just one tab opened/selected at at time.
Compared to the Accordion block where users can mark open as many Accordion items, as they want.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel When you come to this, make sure to also fix the issue on Accordion so people can only keep one tab as the default.

**Comment by HardeepAsrani** [comment]
I'll leave this decision to @mghenciu. My original idea would've been to have this as a button on BlockControls toolbar. Mihai can decide what he thinks is better and we can use the same design here and in Accordion.

**Comment by mghenciu** [comment]
Thanks for the idea, @arinaturcu .

Essentially, as Hardeep mentioned, the Tabs & Accordion block (can) have some common controls.

___
Now related to your suggestion, I think this approach would make a lot of sense if the option would be really common and be used often, by a lot of users. And the point of having it there, is to make the interaction as frictionless as possible. 
**But** in our case (at least for the Tabs block) I think most people will leave it to default state, meaning that the first Tab will be opened by default, and they wouldn't touch this controls.

___
I am suggesting to use one Global control when the main Tabs block is selected, and from there users can select the starting tab (the one that will be opened). By default, first tab will be assigned here.
In terms of UI, it should be a Dropdown with the name: Initial Open Tab, and in the dropdown are all the Tabs.
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/52494172/157851061-5268b789-3009-4829-bb55-71cbf4b23fbd.png">

Let me know your thoughts, if it makes sense UX wise - and also how this sounds from a technical point of view.

And we can reuse the same controls for the Accordion. Even if at this point users can define multiple accordion items, to be opened by default, adding the limit of 1 - I don't think should be the problem. But there we'll have the option to open more of them at the same time, only in Front-end.

**Comment by arinaturcu** [comment]
@mghenciu The dropdown sounds good but the issue is that initilly, all the tabs have the same name, and also later the user can set the same name for 2 or more tabs and nothing stops them.

So, it would be confusing because the user won't know which tab they are selecting.

**Comment by arinaturcu** [comment]
I could make a validation on the name and not let users set identical names for different tabs and then make the dropdown @mghenciu mentioned.

How does this sound to you @HardeepAsrani?

**Comment by mghenciu** [comment]
> @mghenciu The dropdown sounds good but the issue is that initially, all the tabs have the same name, and also later the user can set the same name for 2 or more tabs and nothing stops them.
> 
> So, it would be confusing because the user won't know which tab they are selecting.

Very good point!
Did a bit of research, and one solution could be to use numbers, basically the dropdown will be Tab 1, Tab 2, Tab 3, etc. (no matter what names you have for tabs). And also change the default insertion we do. 

What this means is that by default when we add a Tabs Block, the first tab name is **Untitled Tab**, and if I add another one, it will have the same name -> **Untitled Tab**, and so on - making untitled duplicates. So in a way, we're already starting this duplication issue from the beginning. What I am suggesting here is to add by default names to Tabs, so when added - first tab will have name: Tab 1, when adding another one Tab 2, and so on, incrementing them.

___
Another thing we should consider is the drag/reordering functionality that is currently in the block.
So for example a have 4 Tabs (T1, T2, T3, T4), and by default First Tab (T1) is set to open first. Now if I change the Order, to this T2, T3, T4, T1, should the T1 be open by default, or T2 (which now has the first position). - my suggestion for this would be to use the approach that's easier from a tech. point of view, as it already feels like we are investing too much for a feature that may be a snowflake.

**Comment by Soare-Robert-Daniel** [comment]
What about instead of selecting a tab, we choose the position? Open the first tab, second tab, etc. This functionality is to be tied to the position instead of a tab.

**Comment by mghenciu** [comment]
> What about instead of selecting a tab, we choose the position? Open the first tab, second tab, etc. This functionality is to be tied to the position instead of a tab.

That's one of the potential ways to do it. But you mean to do it like this from a technical point of view?
or/and you are thinking about a different UI selector.

**Comment by Soare-Robert-Daniel** [comment]
It is both. We have a dropdown with the available position and the user will choose one.

**Comment by HardeepAsrani** [comment]
I think we can just have the way Mihai posted here: https://github.com/Codeinwp/otter-blocks/issues/698#issuecomment-1064994002

We can just prefix the tab title with a number for making it easier for the user to select.

1. My Awesome Tab
2. Tab
3. Tab

And user can select the tab and the attribute will be added to the tab itself, not the parent block, this way making sure things don't break when people add/remove new block.

If the attribute doesn't exist (by default it won't) we just show the first tab. This way we make sure we don't have to deprecate anything to make this work.

**Comment by HardeepAsrani** [comment]
> When you come to this, make sure to also fix the issue on Accordion so people can only keep one tab as the default.

Also, bad idea from my side. People might want to have multiple open so better to not change that with Accordion.
