### ISSUE TITLE
Pricing Section for Otter Pro

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#699]

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, Is this related to https://github.com/Codeinwp/otter-blocks/issues/564?

**Comment by mghenciu** [comment]
> @mghenciu, Is this related to #564?

Not sure. I think the one you mentioned is a Block.
This one is a Design/Build task with something [similar to this](https://themeisle.com/pricing/), but for Otter Blocks.

**Comment by mghenciu** [comment]
Attached the Pricing section:
![image](https://user-images.githubusercontent.com/52494172/152360476-39d204fb-15ab-478f-98dc-9b88255f30d1.png)


Keep in mind that:
- it uses both Otter & Core blocks (for example the buttons are core blocks)
- every element color is tied to a Global Color, except this one:
<img width="1324" alt="Screenshot 2022-02-03 at 16 17 26" src="https://user-images.githubusercontent.com/52494172/152360419-76469e39-93c9-4c98-8269-15cdcb380787.png">


[blocks-export.json.zip](https://github.com/Codeinwp/otter-blocks/files/7995233/blocks-export.json.zip)
