### ISSUE TITLE
Typo into the API settings

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#709]
Hi there!
While working at the Otter doc, I have noticed a typo within the API Keys section:
![151669319-523adec7-bccd-44a3-9235-98b4abf24051](https://user-images.githubusercontent.com/86592992/152366129-d5559410-0447-4f93-9480-2e7f7da215fc.png)

There are two words that contain "Captcha", spelled differently.

**Comment by HardeepAsrani** [comment]
Fixed in https://github.com/Codeinwp/otter-blocks/commit/58f18145ac7d82a8e58be3fadaccd283c4bb9512 - thanks!
