### ISSUE TITLE
Allow sync option for Global Defaults

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#710]
Allow users to sync Global Default options and force their use.

**Comment by HardeepAsrani** [comment]
@JohnPixle I needed some UI/UX help here, not sure what will be the best way to move forward with this: https://www.loom.com/share/8353db23bd944c75a589ba80bb619f8e - I've explained what we want to do and wanted to ask you if you have any ideas on how we can proceed with this.

Let me know what you think. Thanks!

**Comment by JohnPixle** [comment]
Hey @HardeepAsrani thanks for the video.
How about simply using a toggle as the first element in the panel?
IF the toggle is on, we could hide the padding and margin fields (because the globals will apply)

![Screenshot 2022-02-04 at 12 41 07](https://user-images.githubusercontent.com/4193672/152516433-41a81939-101b-4f68-b988-ec5bf0bc9135.png)

Let me know your thoughts.

**Comment by HardeepAsrani** [comment]
@JohnPixle Where exactly? Because no all options are supported in Global Defaults. Do you mean one toggle in each tab? Might look weird.

**Comment by JohnPixle** [comment]
@HardeepAsrani indeed, you are right. But on a second thought, when the user is clicking "reset" in any of these fields, then the value should automatically be inherited by the global defaults, correct?

For example, if I set the global defaults for a section, I expect that wherever I add a section block, it should come with these as default.

**Comment by HardeepAsrani** [comment]
@JohnPixle Yes, if you set a global default and then you add a new block, the default values will be taken from the global defaults. But the reset usually sets it back to 0 or null value.

What we want to do is to make this global defaults dynamic. That people can also just sync the value and make it dynamic. Right now the global defaults just work as the default. If you change the global defaults, the existing blocks don't change. We also want to give users an option where their values will become dynamic for a better control of styling over the entire website.

**Comment by JohnPixle** [comment]
@HardeepAsrani I understand. This sounds really good actually. 
I believe this UX must be as a button / icon from what I understand. Something that "pulls" dynamically the values from the Global defaults, and replaces any custom values that the user has entered in those fields on the block. The "toggle" I suggested above will not work.

Please correct me if I am wrong in any of the above.

I will come up with a mockup for this soon, but I believe that we could provide an icon somewhere near these controls. Something similar to the "link" icon that is used for the padding etc.

High risk of getting overly crowded, but we'll see. 
Alternatively we could use a button for the entire block, that shifts ALL the values for the block to the global defaults.

I'll follow up and keep you posted.

**Comment by HardeepAsrani** [comment]
@JohnPixle This seems better. I'm still confused if the `Sync` button is a toggle or it opens the popup?

**Comment by JohnPixle** [comment]
@HardeepAsrani I was envisioning that when you click the "sync" button, then the global default values for this block would populate the fields automatically.

So, let's say the global default padding for a section block is 20px on all sides.
The user is using a section block in a page and has customised the padding to 40px.
Hitting the "sync" button would apply the 20px padding, which is set at the global defaults (along with any other values defined in the GD)

Why you say to open a popup, what you have in mind that this popup would have? I am not against using a popup, just want to clarify the content.

**Comment by HardeepAsrani** [comment]
Note for self:

- Have an extension for adding the Sync with Defaults which adds the attribute `isSynced` to the block attributes.
- If it is enabled, disable the fields that we want to sync. There can be a notice about it to make sure aware.
- For the CSS, add a `hasSync` to the properties that we can sync by adding some sort of checks in CSS utilities for making sure static CSS isn't generated for those.
- Add inline CSS for synced blocks.
- We can also use browser storage to sync by default for new blocks added if the last block added has the syncing enabled.

**Comment by JohnPixle** [comment]
@HardeepAsrani What are the chances that we can extend the global defaults to include core blocks as well?

For example being able to set a global spacing styles (padding / margin) for "container" or "group" blocks.  

I am mentioning this because it could create a flexible environment for global styling for the user, that would extend to core blocks as well.

**Comment by HardeepAsrani** [comment]
@JohnPixle that might be quite hard. But we can start with some of our blocks and then see how far we can take it.

**Comment by HardeepAsrani** [comment]
Also @JohnPixle That will be a part of Core with the Full-Site Editing for Core blocks.

**Comment by JohnPixle** [comment]
> That will be a part of Core with the Full-Site Editing for Core blocks.

@HardeepAsrani Yeah I know, already played with it. Just exploring potential ideas to achieve consistency with the core UI/UX. 

What you say makes sense, at this point messing with it might be nothing but a headache. Thanks!

**Comment by JohnPixle** [comment]
@HardeepAsrani Following up from our discussion in Slack, here is a suggestion for the "sync / unsync" functionality on the individual controls.

![Screenshot 2022-02-22 at 14 50 36](https://user-images.githubusercontent.com/4193672/155135901-c8fff935-f24c-4972-b8a3-b52e4e388286.png)

This is similar to how elementor is managing global colors on individual elements. When clicked, the globe is active. In order use a custom value, the user de-activates the globe.

![Screenshot 2022-02-22 at 14 51 48](https://user-images.githubusercontent.com/4193672/155136255-1db6f8ed-8d98-4ce2-aeaa-3c7b66eb610c.png)

I am also attaching a side by side view with the original UI, for further evaluation.

![Screenshot 2022-02-22 at 14 54 48](https://user-images.githubusercontent.com/4193672/155136530-fe83d761-545d-4c66-b943-1419da4e4968.png)
 
 
 @mghenciu feel free to take a look into this when / if you have the time. Please note that we cannot edit the core components, so this is why we use a wrapper element, and we add a border and the globe icon there. Ping me for any clarifications!

**Comment by JohnPixle** [comment]
@HardeepAsrani Mihai mentioned something worth noting, that there is a similar UX in core, specifically for the Group block. They use a toggle, to "inherit default layout".
![Screenshot 2022-02-22 at 18 25 48](https://user-images.githubusercontent.com/4193672/155175075-26b81315-88e6-4239-b644-2a6f4e8669b5.png)

I am doing a quick mockup based on this as well, let me know what you think.  I am not a big fan of it

![Frame 13](https://user-images.githubusercontent.com/4193672/155179190-6db5ea41-2376-44e9-9a1c-a5b5dcbb9ce4.png)


### Question.
One thing I wanted to confirm with you is the behaviour of the "reset" buttons. In your earlier comment you mention that _"...the reset usually sets it back to 0 or null value."_ So, if global default for padding is 10px, and the user clicks the reset button for the padding, then the value will be 0 or null, correct?

**Comment by HardeepAsrani** [comment]
@JohnPixle Perfect, it looks what we needed. Thanks both!

> One thing I wanted to confirm with you is the behaviour of the "reset" buttons. In your earlier comment you mention that "...the reset usually sets it back to 0 or null value." So, if global default for padding is 10px, and the user clicks the reset button for the padding, then the value will be 0 or null, correct?

The reset, usually, sets to undefined. Sometimes it also gives you the default value but mostly undefined. If you've synced with defaults, the reset button is also disabled.

**Comment by HardeepAsrani** [comment]
Looks perfect!

<img width="512" alt="Screenshot 2022-02-23 at 3 27 45 AM" src="https://user-images.githubusercontent.com/2649903/155226442-e4faa913-7a3c-49ec-aa8c-60b0ce63d546.png">

**Comment by HardeepAsrani** [comment]
@mghenciu Can you go through the blocks and let me know which fields should be part of the Global Defaults Syncing? Keep in mind, it can only be a CSS.

For example, we can't change the Section tag type dynamically. Also, it should only be things that user would like to keep globally sync like Sizing and Color and such. I'm sure you're well aware of these but still a note to keep that in mind.

Let me know and I'll add that. Make sure you download the zip from here: https://github.com/Codeinwp/otter-blocks/pull/741

**Comment by mghenciu** [comment]
Let's add them here first, as it's easier to edit them collaboratively:
https://www.notion.so/themeisle/Global-Defaults-Sync-f834a709bd3547f6bd87cb82b00d6dc9

And I have one more question about this @HardeepAsrani . Is it safe to say that if at some point we decide to drop this and use the core approach with Toggle and Reset all panel (plus icon), everything would be fine with the existing sites that use this feature?
![image](https://user-images.githubusercontent.com/52494172/155271949-497f92de-f4ed-4d04-9a59-4f37f2ff57ba.png)

**Comment by mghenciu** [comment]
I've added my suggestion about what [setting we should sync globally](https://www.notion.so/themeisle/Global-Defaults-Sync-f834a709bd3547f6bd87cb82b00d6dc9).

Note that, the settings I selected are made having in mind an environment where Customizer is present, as a lot of things can be configured and are coming from Customizer.

But if we think about this from a FSE perspective, where Customizer pretty much will disappear - then things change a lot.
We can talk more about this in the meeting.

**Comment by HardeepAsrani** [comment]
One issue that we get for some blocks, Review in this case, is that we can't out the Sync All button on the very top as the Styles panel is added by Gutenberg for the block, so we can't have anything above it.

What do you think we should do @JohnPixle @mghenciu?

<img width="488" alt="Screenshot 2022-02-26 at 5 21 42 AM" src="https://user-images.githubusercontent.com/2649903/155818522-4b61f7bb-f521-4e0d-93f6-27c724ec41c8.png">

**Comment by JohnPixle** [comment]
@HardeepAsrani I am not sure I got what the issue is here. I assume we can't have the button nested somewhere in the Block description area like it was in the mockup?

Essentially what this button does is to Sync all the sync-able settings of the block at once. 
Perhaps we can re-locate it at the bottom of the sidebar? And use the toggle UI?

Let me know your thoughts


![Screenshot 2022-02-28 at 10 04 51](https://user-images.githubusercontent.com/4193672/155952235-690f2332-9c98-41f2-a537-1db5198226af.png)

cc @mghenciu

**Comment by HardeepAsrani** [comment]
We also can't put anything below the Advanced option. Maybe we can put it inside the advanced tab instead?

**Comment by HardeepAsrani** [comment]
^ @JohnPixle

**Comment by JohnPixle** [comment]
@HardeepAsrani Yes, although not the best solution, we can try that. Perhaps we can also go for a more core-friendly style
![Screenshot 2022-03-01 at 11 34 17](https://user-images.githubusercontent.com/4193672/156143314-3808d822-efec-4a36-842f-3b0f5b7db7a7.png)

**Comment by HardeepAsrani** [comment]
@JohnPixle Yea, that will do. Just one question, does this option make sense at all if we put it somewhere so hidden? When people can just put the sync option on values they want.

**Comment by JohnPixle** [comment]
@HardeepAsrani  Makes sense, because if a block has only a couple of sync-able settings, then the user will probably just toggle the individual ones.
However, I think we can still use this "sync / unsync all" functionality, perhaps even in the future. I would suggest that we keep it downplayed in advanced tab, until we find a better way to communicate it. If you feel that removing it completely makes more sense, I am fine with this as well.

**Comment by HardeepAsrani** [comment]
@JohnPixle For now I think let's just remove it. In future, we can just put an option in Global Defaults popup thingy about "Enable Sync by default" which just enables syncing by default on the newly inserted blocks. Makes sense?

**Comment by JohnPixle** [comment]
@HardeepAsrani Makes sense, agreed 👍🏻
