### ISSUE TITLE
Form submit message

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#718]
@HardeepAsrani by default the contact form block uses "submit" as button text, I can't change that, then on frontend I see Subscribe : https://domainwheel.com/contact/ .

I would rather have Send as default + allow me to change.

**Comment by HardeepAsrani** [comment]
@ineagu Subscribe should be if it's an email subscription form. @Soare-Robert-Daniel can you check if somehow it's adding Subscribe on Contact forms too?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani we have a problem with this line:

https://cs.github.com/Codeinwp/otter-blocks/blob/09a80537db8a5232f1bfcfa3e05d8c1793a1e613/src/blocks/blocks/form/save.js#L40

which is influenced by this https://cs.github.com/Codeinwp/otter-blocks/blob/09a80537db8a5232f1bfcfa3e05d8c1793a1e613/src/blocks/blocks/form/attributes.js#L29

By default the action is set to `subscribe` but Subscribe is meant for Integration, and we have no way to change in the Inspector.

**Comment by HardeepAsrani** [comment]
I can't see the first link. @Soare-Robert-Daniel

**Comment by Soare-Robert-Daniel** [comment]
https://github.com/Codeinwp/otter-blocks/blob/09a80537db8a5232f1bfcfa3e05d8c1793a1e613/src/blocks/blocks/form/save.js#L40

**Comment by HardeepAsrani** [comment]
We can change that when we change the div to a form.

**Comment by HardeepAsrani** [comment]
Closing this in favor of https://github.com/Codeinwp/otter-blocks/issues/615 - we can discuss the ideas there to have them in one place.
