### ISSUE TITLE
Form design looks weird

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#719]
@HardeepAsrani any reason we don't wrap the form in a <form> tag? Due to this the form looks weird on Neve, since we apply the style for inputs only when they are inside a form.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yea, but let's finish the 2.0 tasks first as they're more important.

**Comment by HardeepAsrani** [comment]
Closing this in favor of https://github.com/Codeinwp/otter-blocks/issues/615 - we can discuss the ideas there to have them in one place.
