### ISSUE TITLE
[ Development ] Add dev build link for Bot.

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/otter-blocks#721]
The zip created by the bot is used mainly for testing. A dev builds with the source map is very helpful when testing because it shows clearly where the error was produced.   

Also, we will have a handy way to give other people this zip to check the error on their site when debugging.

**Comment by HardeepAsrani** [comment]
Good idea. I had to do it just yesterday.

**Comment by Soare-Robert-Daniel** [comment]
Also, can the dev and production build ZIP be posted in the release for easy access? Navigating through closed PR might not be a funny experience.

**Comment by HardeepAsrani** [comment]
> Also, can the dev and production build ZIP be posted in the release for easy access? Navigating through closed PR might not be a funny experience.

@Soare-Robert-Daniel I checked and it's not possible as the release is made automatically by Semantic Release.

Dev link in comment is added, you can check an example here: https://github.com/Codeinwp/otter-blocks/pull/755
