### ISSUE TITLE
[ Refactor ] Form Block

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/otter-blocks#725]
@HardeepAsrani, It seems that the idea of a barebone Form block is not very reliable.

This will be more like a compilation of complaints on this.

 Things we should change:
 - Wrap the block in a `form` tag #719
 - Allow the user to change the text of the Submit button #718 . Trying to enforce the name based on the situation is error-prone and might not fit the needs.
 
Things to add:
- Docs link for setting up an SMTP feature. Since we do not have any indication about this, some users might this is a plug-and-play form #712
- Custom text color. A possible situation #694 
- Open link on success. When submitting the form succeeds, we can redirect the user to the given link.

**Comment by Soare-Robert-Daniel** [comment]
@ineagu For sending the email, we use the `wp_email` function. All the problem with sending emails is related to this function.
And this function is well not viewed: [1](https://bobcares.com/blog/wp_mail-function-not-working), [2](https://wpmailsmtp.com/why-wp_mail-is-not-working)

As @HardeepAsrani, it depends on everybody's setups. WPForm plugin will work well because they have their own STMP plugin/function integrated (which we also used when testing).

The Form block takes the data and uses the WP built-in function for processing.

**Comment by ineagu** [comment]
That is an edge case, wp mail should work in 99% of the cases. i would assume you’re missing something there.

I didn’t looked in depth but I am quite confident that wp mail works out of the box

**Comment by mghenciu** [comment]
Make sure to also add some padding to the input fields.
If it uses the form styles from Neve Customizer - it's good, but still - it should have some default padding.
![Screenshot 2022-02-11 at 16 46 18](https://user-images.githubusercontent.com/52494172/153612905-b447cb7c-1cd4-40f5-931b-2b0c8454b87f.png)

**Comment by ineagu** [comment]
@HardeepAsrani btw I consider the form block pretty important, so should cover the needs of 90% of people and work flawlesly, since every website need a form, would be good to avoid recommending 3rd party tools and use otter block instead

**Comment by HardeepAsrani** [comment]
Closing this in favor of https://github.com/Codeinwp/otter-blocks/issues/615 - we can discuss the ideas there to have them in one place.
