### ISSUE TITLE
Inputs are looking bad

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#729]
### Description:
I can see here on the form added by Otter that inputs are looking bad: https://domainwheel.com/contact/. It seems to be due to the fact that there is no <form> parent.

### How to reproduce:

1.Visit : https://domainwheel.com/contact/

### Expected behaviour:

Input looks good even if outside form element

### Current behaviour:

They look unstyled.

### Technical info
* WordPress version: 5.8.3
* Theme version: 3.1.5

**Comment by HardeepAsrani** [comment]
Closing this in favor of https://github.com/Codeinwp/otter-blocks/issues/615 - we can discuss the ideas there to have them in one place.
