### ISSUE TITLE
Background Overlay image is not loaded in the front-end

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#732]
If I create a section and select an image as a Background Overlay - it is only visible in the dashboard but not in the front-end.
Image attached - https://vertis.d.pr/zR6qZt

Front-end - https://vertis.d.pr/0MPGC2

Screencast - https://vertis.d.pr/HUZWnA (to show that image is not loaded in the front-end).

Plugin version:  1.7.5  (tried with different themes)

Client reported here - https://secure.helpscout.net/conversation/1763793072/307000/

**Comment by HardeepAsrani** [comment]
This was fixed in development and will be released in the next version. @vytisbulkevicius
