### ISSUE TITLE
Section and other block types broken in 1.7.5 (Previously Reported) Reproduced

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/otter-blocks#739]
There was a previous issue that was reported about section blocks and others that were rendering an error in the editor stating "type "themeisle-blocks/advanced-columns" is not supported".

That initial issue was solved by clearing the browser cache however, now we have new users reporting the same issue that cannot be fixed in the same way.

I managed to reproduce it on a test instance using previously downloaded versions.

Note: You can "fix" the issue by rolling back to version 1.7.4.

Steps to recreate:
1) Install Otter v 1.7.4 (You can download it from [here](https://wordpress.org/plugins/otter-blocks/advanced/))
2) Insert a few Otter Blocks (in my example I used a 2 column layout with an accordion and paragraph)
3) Update page/Save Settings
4) Update the plugin to v 1.7.5
5) Edit the page again and observe the error.

Reference:

[Here is a screencast reproducing the error.](https://vertis.d.pr/0o54Gr)
[Screenshot of the console log.](https://d.pr/AM3zme)
Might be related to this issue #720 

Users Reported Here:
1) https://wordpress.org/support/topic/themeisle-blocks-advanced-columns-broken-after-otter-update-version-1-7-5/page/2/#post-15383937
2) https://secure.helpscout.net/conversation/1791383250/310512?folderId=212385

**Comment by HardeepAsrani** [comment]
@Skystream96 Can you reproduce it on tastewp.com and share the credentials with me? It doesn't happen when I try to reproduce.

**Comment by Skystream96** [comment]
Hello @HardeepAsrani ,

Sorry for the late reply. Here is a tastewp instance with the issue reproduced.
Website URL: https://pinkminute.tastewp.com
User: matei@themeisle.com
Pass: H&^lLxfKVA4RU^HQdVQESQr3

**Comment by Skystream96** [comment]
+1 https://secure.helpscout.net/conversation/1796821380/311349?folderId=212385

**Comment by HardeepAsrani** [comment]
@Skystream96 It's 100% an issue caused by cache. You can ask the user to follow this tutorial: https://www.fvsu.edu/how-to-clear-your-browser-cache/ - they need to clear browser cache/data completely in order to make sure the cached version isn't loaded.

**Comment by HardeepAsrani** [comment]
Any update on this @Skystream96?

**Comment by Skystream96** [comment]
> Any update on this @Skystream96?

Hello @HardeepAsrani ,

Sorry for the late reply, I had days off. I went back to the users and suggested your approach now. I'll update this once they come back with an answer!

Thank you!
