### ISSUE TITLE
Remove useless Posts Type from Posts Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#745]
In the Posts Type picker of Posts Block, can we filter out the useless post types such as wp_template, wp_template_part, wp_navigation, nav_menu_item?

They're part of WordPress' but aren't really useful to show there. We can also filter out the Neve ones.

<img width="412" alt="Screenshot 2022-02-23 at 12 48 01 AM" src="https://user-images.githubusercontent.com/2649903/155204778-a353ad56-8d45-494a-8408-37a515c6e81e.png">

**Comment by ineagu** [comment]
can't we find a solution to filter out most of useless cpts based on how they are defined? Users would likely have a lot more of others

**Comment by HardeepAsrani** [comment]
@ineagu @arinaturcu Might be worth trying to see if we can use this show_ui parameter to filter out the ones: https://developer.wordpress.org/reference/functions/register_post_type/#show_ui - it might have some exceptions but should work for most.

**Comment by selul** [comment]
@HardeepAsrani I've added here a list that could be a good start https://github.com/Codeinwp/neve-pro-addon/issues/1018#issuecomment-914377196 and could be used as a base point.

**Comment by HardeepAsrani** [comment]
@selul Regarding that list, that is for us to include or exclude? I see few that the users might want to add, like product or courses?

**Comment by selul** [comment]
yep, sure, it was just a starting point.

**Comment by HardeepAsrani** [comment]
All yours @arinaturcu.

**Comment by HardeepAsrani** [comment]
Merged to v2, thanks @arinaturcu!
