### ISSUE TITLE
Color Selector not closing when clicking outside the box - in Global Defaults

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#747]
When using the Global Defaults panel, and trying to add a Custom color - if the color panel is opened, you can't close it unless you click again the **Custom color** button:
![Screenshot 2022-02-23 at 08 22 13](https://user-images.githubusercontent.com/52494172/155270720-8ff184ee-133a-46d1-9e9c-d4683cb23657.png)

While not a huge issue, this restricts other panels visibility making it harder to use those options.

### Suggestion
The Custom color selection panel should close itself when clicking outside, the same way it does this when in a 'Normal' context (when editing the color of a block in the page and not in the Global Defaults).

**Comment by HardeepAsrani** [comment]
@mghenciu It's a core component. We have no control over that part. It's a known issue.

**Comment by mghenciu** [comment]
Got it!

I thought if it's possible in other instances, when should be possible there also.
