### ISSUE TITLE
Visibility Conditions based on Post Type

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#750]
@HardeepAsrani I am trying to use visibility conditions on bloggingpro and an interesting use case is to use it for the widgets.

I am trying to display a widget only on posts, not on pages or other post types.

I would want to display a widget only on a certain page.

Since widgets are not blocks, I thought Otter can help.

**Comment by HardeepAsrani** [comment]
@ineagu If you're using WP 5.9, even widgets are blocks. Or are you trying to use it on legacy widget UI?

**Comment by ineagu** [comment]
yes, they are. But still I can't find those conditions in otter

**Comment by HardeepAsrani** [comment]
Got it, just wanted to confirm it wasn't about it being used on legacy widgets. Thanks, makes sense.

**Comment by ineagu** [comment]
no, I was trying to use them on the Otter posts block for e.g
