### ISSUE TITLE
Submit button's label becomes Subscribe in the front-end [Contact Form]

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#768]
With Contact Form added there is a default button that says Submit:
https://vertis.d.pr/tQhA41

In the front-end it shows as Subscribe:
https://vertis.d.pr/6dITVd

This happens on a completely fresh instance, with no other plugins, any theme. (Neve, twentytwenty*)

Reported here - https://secure.helpscout.net/conversation/1804302823/312254/

**Comment by HardeepAsrani** [comment]
Closing it as it's a known issue and is part of: https://github.com/Codeinwp/otter-blocks/issues/615
