### ISSUE TITLE
Otter blocks plugin slows down pages if Cookies policy is activated on website

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/otter-blocks#770]
This happens with multiple cookies policy plugins/features and it only depends how much a website is slowed down.
A client reported that some of his pages timeout if the Otter plugin is activated together with the GDPR cookies plugin - https://wordpress.org/plugins/cookie-law-info/

I was able to replicate the issue and even using OrbitFox plugin (Policy notice feature) the website is slowed down significantly - https://docs.themeisle.com/article/1296-policy-notice-orbit-fox-module
It doesn't timeout in my case but takes a lot to load compared to when one of these plugins is disabled.

I didn't find anything specifically added to the page that could be causing it, based on my tests it only matters how many resources are added to the page so more content and images to have - more time it takes to load with these plugins activated and ultimately it causes timeout.

Here is the network tab with both Otter and OrbitFox plugins activated (sorted by resources taking most time): https://vertis.d.pr/f79XK1

Here is the network tab with the Policy notice of OrbitFox disabled: https://vertis.d.pr/b0y5td

The website has only these 2 plugins enabled: https://vertis.d.pr/quLL09

Content of the page that could be copied to face this issue (it has a lot of content so hard to replicate with only a few images but the more content you add the slower page becomes as every resource seems to be delayed):
https://pastebin.com/nZgpjE0F

Also, here is a test instance where you can check it (valid for 7 days):
https://loseyarn.s4-tastewp.com/2022/03/07/3commas-dca-bot-indicator-strategy-v1/

 Admin area URL: https://loseyarn.s4-tastewp.com/wp-admin
 Username: bvytis  
 Password: d-cRizrcmhE

Reported here - https://secure.helpscout.net/conversation/1793320837/310815

cc @HardeepAsrani this is the case we discussed about. Thanks!

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu You might have some insights on this. Do these Privacy Policy modules block rendering of scripts or anything that could be causing this?

**Comment by cristian-ungureanu** [comment]
@HardeepAsrani the issue is fixed in the latest version of Otter.

It was indeed a problem with the previous version. Don't exactly know why but when OrbitFox tried to execute "wp_kses" function from here https://github.com/Codeinwp/themeisle-companion/blob/master/obfx_modules/policy-notice/init.php#L202, everything was so slow. After deactivating Otter 1.7.5, everything was fine.

Now I updated Otter to 2.0 and everything works great!

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius Is it same for you?

**Comment by vytisbulkevicius** [comment]
Yes, everything looks great with Otter 2.0, and the page loads instantly 👌
Thank you both! 

Closing this issue.
