### ISSUE TITLE
Blocks Animation: Nothing shows when printing page

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#780]
More details: https://wordpress.org/support/topic/nothing-shows-when-printing-page-or-making-a-pdf-unless-the-page-is-scrolled/#post-15437212

Can you test @arinaturcu? I was able to reproduce it but normally it shouldn't happen as the library has the code to prevent animation in print.

Let me know your findings.

**Comment by arinaturcu** [comment]
@HardeepAsrani I looked into it and it seems that the problem comes from the `.hidden-animated` class that is added by us.

Why do we use this class? It seems to me that everything works just fine without it. What am I missing?

**Comment by HardeepAsrani** [comment]
@arinaturcu We hide everything on load and then show it with the animations. You can add some CSS to make sure the .hidden-animation doesn't affect on @media print: https://www.tutorialspoint.com/css/css_printing.htm
