### ISSUE TITLE
The strings within the Countdown block can't be translated

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#783]
The following strings can't be translated.

I've tried with Loco Translate and by replacing the string with the [Say What?](https://wordpress.org/plugins/say-what/) plugin and it didn't work.

### Reference

![Markup on 2022-03-09 at 13:06:19](https://user-images.githubusercontent.com/26867648/157429615-f1154d3d-f7ab-41a8-b920-1944b13b116c.png)

Ticket: https://secure.helpscout.net/conversation/1810411010/313002?folderId=212385

**Comment by HardeepAsrani** [comment]
How are they values appened? Are they static or added from front-end scripts? @Soare-Robert-Daniel

**Comment by Soare-Robert-Daniel** [comment]
They static, but with not `__`

https://github.com/Codeinwp/otter-blocks/blob/466e2126f77c521e05b736588ea9db21887abf1f/src/blocks/helpers/helper-functions.js#L217-L248

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel you should use `__` there.
