### ISSUE TITLE
Masonry Block Styles & Responsiveness

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#784]
- [ ] right now, there seem to be a small delay until the Styling of the Masonry is applied. Basically the Gallery is initially loaded with one style (for example 2 col grid), and after 1 second - the layout changes to something else (for example 3 col grid).
I guess it may be related to the fact that we are using the Core Gallery block, but still it doesn't look good.
- [x] Masonry isn't responsive on mobile devices. Meaning that the gallery will look the same on mobile as on desktop. We should at least make sure on mobile the columns are equal to 1-2, or/and add controls for the number of columns depending on the device.
![image](https://user-images.githubusercontent.com/52494172/157445805-149d9608-bd28-4785-8c96-45ab58d9964a.png)

**Comment by HardeepAsrani** [comment]
Seems like Masonry has other issues where the new version of it (on 5.9 or later) doesn't work as expected. The columns don't work, reorder doesn't work. It happened after they switched from a normal gallery block to a gallery block that uses Images as child blocks.

For now, I'm making Masonry work only in the frontend and adding a notice saying it works only in the front. We can take care of these issues together.

**Comment by HardeepAsrani** [comment]
Closing this as the issue here has been fixed. We might have to rethink about the masonry feature as the changes with Gallery blocks have made it harder for us to maintain it. We will give it another go and see if we can do something, I'll make another issue for that.
