### ISSUE TITLE
Maps - Enhancements

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#785]
- [x] Loading State, as mentioned on the [Google Maps block](https://github.com/Codeinwp/otter-internals/issues/5)
- [x] (NAD) Have the same tab order for the Google Maps Block. Right now there are some differences, when adding the G Maps block first time, for example the position of the Custom CSS tab:
![image](https://user-images.githubusercontent.com/52494172/157508370-9d82b45f-ece7-4b20-976f-1b23b5116432.png)

**Comment by HardeepAsrani** [comment]
@mghenciu It's actually the same order. Custom CSS/Animation are added from an extension so they appear on the bottom by default. If you de-select and re-select the Google Maps, you will see Custom CSS and Animations appear on bottom.

We can't control where they appear.

**Comment by mghenciu** [comment]
ok. I thought if it's possible with the Maps Block(Leaflet) - to have the right order from the beginning, then it should be also possible with the Google Maps block.

**Comment by HardeepAsrani** [comment]
@mghenciu I made this little video to explain why this behavior happens: https://www.loom.com/share/b97771062e644da9ba6637861c3e1c1f

**Comment by mghenciu** [comment]
> @mghenciu I made this little video to explain why this behavior happens: https://www.loom.com/share/b97771062e644da9ba6637861c3e1c1f

Thanks for video Hardeep. I've edited the tasks, marking the 2nd one as a NAD (not a defect).
And I guess we can still keep the first one.

**Comment by HardeepAsrani** [comment]
@mghenciu Should we close this now or implement some loading state?

**Comment by mghenciu** [comment]
> @mghenciu Should we close this now or implement some loading state?

That's up to you.

If you already implemented what you've mentioned [here](https://github.com/Codeinwp/otter-internals/issues/5#event-6317911077), then I guess yes -> we can close it.
Otherwise, I will keep it open until the loading enhancement is implemented.

**Comment by HardeepAsrani** [comment]
@arinaturcu When you are done with current issues, we can add some sort of loading state to Maps.
