### ISSUE TITLE
Accordion - Enhancements

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#787]
We should add the following controls for the Accordion block (Global element):
- [x]  border controls including size & style (dashed, etc)
- [x]  Typography controls for content and title
- [x] if we don't add Typography controls for the Title, we should at least make it a bit bigger by default. Right now it's 16px, same as the body text. From a Information Architecture point of view, those should be different.
- [x]  spacing (padding) that should apply to title and content.
- [x] Globally for the Accordion Block - have the option to enable Closing of other Accordion Items when one is open (this will be the default). When this is **disabled**, multiple accordion items can be opened at the same time. Example of toggle: https://www.notion.so/themeisle/Accordion-71df8651501e47ee83684ec3158ac841#1a4811d9e2c0424f987d8333279876fe

___
### Nice to have:
- [x] shadow options for the Items
- [x] option to change the Icon to another Icon, maybe integrate it with Font Awesome
- [x] Option to change the Icon position, to left/ride side (basically start end of the Accordion Item)
- [x] Option to change the Title HTML tag (from H1 to H6, and 'div')
- [x]  Active State styling (when a tab is opened). Basically have the option to style the opened items including bg-color of the Title 'div', icon and title color; choose a different Icon for the open State. By default all this options should work ok without even defining the active state.
An example with the Active state from Bootstrap: 
<img width="837" alt="image" src="https://user-images.githubusercontent.com/52494172/157631953-b18edee5-6c23-4771-ad9f-4c59dee95156.png">

- [x] Icon color should also work in Dark Mode.
Here's is a section in Light Mode with Neve:
![image](https://user-images.githubusercontent.com/52494172/162433765-db6d23db-1a71-4a54-bb6a-2ba768166768.png)
and the same section in Dark Mode; where the icons are barely visible:
![Screenshot 2022-04-08 at 15 16 39](https://user-images.githubusercontent.com/52494172/162433890-234a63d2-bd99-492e-90a7-dafca343e60e.png)

Maybe we could sync the Icon color with the Text color (`currentColor`); I know right now it's synced with the border color.

**Comment by HardeepAsrani** [comment]
> option to change the Icon to another Icon, maybe integrate it with Font Awesome

I'm little confused here. Why would one change it to something else?

>  Active State styling (when a tab is opened). Basically have the option to style the opened items including bg-color of the Title 'div', icon and title color; choose a different Icon for the open State. By default all this options should work ok without even defining the active state. An example with the Active state from Bootstrap:

Can you explain that? I'm little confused.

**Comment by mghenciu** [comment]
@HardeepAsrani,
### Active State
Here are 2 things. One of them is the aesthetic part, meaning that it's looks better to have a different look(state) for the opened accordion item.
The other thing (less subjective) is that having at least a focus state on the accordion items, is very recommended from an accessibility point of view. Because some users don't use a mouse, so there is no hover state there.
And we are not reinventing anything, there are plenty of Design System that use this approach (at least having a keyboard focusable state). But sure, there are also some of them that don't use this approach.
[Accessibility things to keep in mind with the Accordion](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html).

Examples from other Design Systems:
https://getbootstrap.com/docs/5.0/components/accordion/
https://www.carbondesignsystem.com/components/accordion/code/
https://catho.github.io/quantum/?path=/story/accordion--accordion-story

____
### Different Icon
While the chevron icon is the most common icon used with an accordion item, there are cases where there could be a different icon.
Like + and - https://www.w3schools.com/howto/howto_js_accordion.asp
Or using specific content Icons, mentioned in [Notion](https://www.notion.so/themeisle/Accordion-71df8651501e47ee83684ec3158ac841#57c83f1426ff4d3bb9da8e398cc2a9a8).
We could also go for just 2-3 icons users can choose from, instead of the whole FA font.

**Comment by mghenciu** [comment]
Here's an example of [a FAQ section from Lyft](https://www.lyft.com/expressdrive), where it's visible how import the Typography & Spacing settings are:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/52494172/161908096-5498200b-1bdd-4416-99aa-bb4f7f88206d.png">

Ideally, we should be able to achieve something like this, using Otter Accordion block.

**Comment by HardeepAsrani** [comment]
Hey @arinaturcu, you can take over this when you get time.

You can do these things mentioned in the list one by one. Do as much of it is possible *without* changing the HTML of the save file. If something requires changing the HTML (like option to change icon) then you can leave it for now and mention in the end.

>  Option to change the Icon position, to left/ride side (basically start end of the Accordion Item)

This can probably be done using CSS, but if something requires changing HTML, we can leave it for now. All the things that can be done using CSS will be good. 

This is how we manage CSS for the front: https://github.com/Codeinwp/otter-blocks/blob/master/inc/css/blocks/class-accordion-css.php

Let me know if you have any questions!

**Comment by mghenciu** [comment]
I found an edge case, meaning that's it looks to be an issue, but I am pretty sure not a lot of people will use Accordion with Flip Card.

___
While testing the Flip Card, I noticed something strange with the Accordion block.
Basically it acts different in front-end vs Backend (being full-width).

**Backend**:
![Screenshot 2022-06-22 at 13 14 41](https://user-images.githubusercontent.com/52494172/175005153-b2587570-a5fe-4e1c-a714-892e399685df.png)

**Frontend**
![Screenshot 2022-06-22 at 13 15 02](https://user-images.githubusercontent.com/52494172/175005181-f2d8e2f3-23ac-4763-94a2-44941f8dfbe5.png)

___
**Repro, v 2.0.5**
- add a Flip Card
- add a Accordion Block inside the flip card.

**Comment by arinaturcu** [comment]
> * [ ]  Option to change the Title HTML tag (from H1 to H6, and 'div')

Is this still useful even if we add typography settings that include font size and weight?

**Comment by arinaturcu** [comment]
Since this requires changes in the HTML of the `save` file, we leave it for later
> - [ ] option to change the Icon to another Icon, maybe integrate it with Font Awesome

**Comment by HardeepAsrani** [comment]
@arinaturcu You should be able to do it using CSS. We can have an attribute to choose Font Awesome icons and use that value to add the unicode by getting it from the fa-icons.json in PHP.

It's not the easiest way of doing it but we don't need to update the HTML structure for it.

<img width="2550" alt="Screenshot 2022-07-07 at 9 42 50 AM" src="https://user-images.githubusercontent.com/2649903/177689235-3822cd37-b7fe-46e5-878e-732ec9489ccb.png">

**Comment by irinelenache** [comment]
@arinaturcu Good job 🚀 Tested the enhancements and here are my findings:

- [ ] The icon is not aligned with the accordion title in the editor https://vertis.d.pr/1cLxVt (It happens when the title is set to be a heading)
- [ ] If the title is set to be a heading, the selected font family won't have any effect https://vertis.d.pr/3GcoTK
- [ ] If i set an icon only for the closed accordion item, it won't be aligned with the title (https://vertis.d.pr/XCPQHK). After i set an icon for the open item too, it will be correctly aligned (https://vertis.d.pr/hsckcI)
