### ISSUE TITLE
About Author - enhancements 

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#788]
Please make sure to read the [first paragraph from Notion](https://www.notion.so/themeisle/About-Author-1472c57bcf664974815744b1ae846f53#c2ba66cc795346e38a2c443fcc2cc4cb).

___

### The block should have
- [ ]  options and styling for the avatar image, including Toggle for shadow with options; if the image is using the cover approach, we can add a Border radius slider. Otherwise, we need to variations: Round & Square.
- [ ] vertical layout option. Example of a vertical layout:
![image](https://user-images.githubusercontent.com/52494172/157708412-0dd5cde2-1920-482c-8443-671adb12b4f1.png)

- [ ] alignment options for the whole block: left, center, right.
- [ ] typographic control sizes UI for text elements
- [ ] Add text color picker (applies to title and bio)
- [ ] Adjust the excerpt size. At the moment the block gets all the text from Author Bio description.
- [ ] Add padding controls for the block, based on the core padding UI controls. 
- [ ] add border option and background color picker. Basically this should allow us to create a Boxed layout. Example of a Boxed layout: 
![image](https://user-images.githubusercontent.com/52494172/157707831-e8a9f2ba-9008-41fa-b453-e48253b8d1c4.png)

- [ ] Increase the space between the Avatar Image & the name, when on **Mobile**. Can be 16 or 24px. Right now the image looks too close to the Author name:
<img width="430" alt="Screenshot 2022-03-21 at 14 24 27" src="https://user-images.githubusercontent.com/52494172/159260378-3c958e65-6037-436a-8bb7-00140d49bcc1.png">

___
### Nice to have:

- [ ] Add the option to write a custom Author name and bio in the editor, for this block only. Meaning that there will be 2 options, one is inheriting the author from the post, and the other one is to Custom - allowing to use an editable name, biography.
- [ ] Option to Enable or disable more Author metadata, like the number of posts published, bio, Author image, etc. Example here with the number of posts: 
![image](https://user-images.githubusercontent.com/52494172/157706989-e4ca2558-550b-417f-a0b5-893a4c559b35.png)
- [ ] Add option for Social media icons
- [ ] have the option to hide the image

**Comment by ineagu** [comment]
@mghenciu I would say this is more suitable to be a pattern, there is not complex enough, nor simple enough to be a block. ( Feel free to ignore, I am just building up on the logic that I described in the services block issue).

**Comment by HardeepAsrani** [comment]
@ineagu It can't be a pattern because it's dynamic data, like Post Author's name/image/description which comes automatically from the post author.

**Comment by HardeepAsrani** [comment]
It's a simple block so in this case instead of giving many options we can just have 3-4 different styles for them that look good? The idea is to inherit styles from the theme as much as possible, but if we add 3-4 different styles for them do you think that would be good enough?

And yes, we can add a list to enable disable different fields (like the image you added) that makes it look good.

**Comment by ineagu** [comment]
@HardeepAsrani thanks for the clarification, is a great point on when we should have or not a pattern vs block.

I would say from an ux perspective if we can cover with 2-3 design variations 90% of the needs, we can just offer that and don't worry about the options too much. It's 1 click to change the variations vs 10 to change the settings that you might not understand.

**Comment by HardeepAsrani** [comment]
@JohnPixle @mghenciu Can we get a couple of designs for Author Block? Let's keep the same options without giving the user much choice just some good designs.

**Comment by mghenciu** [comment]
I can start working on this, after I get close to the finish line with Otter Sales pages.
@JohnPixle , hope that's ok with you - and you didn't started working on this.

**Comment by JohnPixle** [comment]
@mghenciu sure thing, I haven't worked on it 👍🏻 
Thanks for checking-in.

**Comment by mghenciu** [comment]
For now, I've made 3 simple Design Styles for the block, @HardeepAsrani .
This should not require a lot of new controls, only the Text Color. And in later releases we can add more features.

[Figma file](https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=964%3A7473)

![image](https://user-images.githubusercontent.com/52494172/166939224-161875ce-fb78-4f38-9cdd-c0369891ae07.png)

- the Avatar size should remain the same on all Devices. Right now on mobile is 130px, and on Desktop is 91px.
- on Tablet & Mobile, the content in the Card Style -> will be centered
- the Biography will go on **4 lines max**. If the text is longer, then we use the ...
- the issue with the spacing between Avatar Image & Title on Mobile, still needs to be fixed
- the Title (name) should also act as a link, not only the image
- for now (until we add more shadow controls), let's use a more soft shadow for the Avatar Image: 0 1px 2px 0 rgba(0,0,0,0.10);
- spacing should use the 8pt grid. See in Figma.
- the bg-color on the Centered Style is just for presentation purposes, so don't add it in the block.
