### ISSUE TITLE
About Author - Issues

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#789]
- [x] Text color controls needed, as the text doesn't work properly in Dark Mode. this is specific to Neve and Palette Switcher.
Example of how About Author text looks in Dark Mode:
<img width="1377" alt="Screenshot 2022-03-10 at 18 42 24" src="https://user-images.githubusercontent.com/52494172/157711992-67e7d5a6-c131-4ffc-bb0b-5ece5784b35f.png">

- [x] There looks to be a difference between how the content is vertically aligned in the box. This is how it looks in Front-end vs backend; notice the vertical alignment differences:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/52494172/157712197-9112f681-4f51-4110-b24b-53233f956a15.png">
When the Bio is absent, I think the Image and name should vertically align center.

**Comment by HardeepAsrani** [comment]
> Text color controls needed, as the text doesn't work properly in Dark Mode. this is specific to Neve and Palette Switcher.

For now you can remove the CSS we have for the text color and then test if it works with Neve's Dark mode. @arinaturcu 

We can discuss the color controls and what to add or not in the other issue, will be easier to do it once we've decided on all the options.

**Comment by HardeepAsrani** [comment]
@mghenciu I've merged the PR to development. You can test to make sure nothing else is left. From next time I'll also take your review before merging ths PRs for issues reported by you. Thanks!

**Comment by mghenciu** [comment]
> @mghenciu I've merged the PR to development. You can test to make sure nothing else is left. From next time I'll also take your review before merging ths PRs for issues reported by you. Thanks!

All good! ✅ 
The 2 issues reported initially (text color & vertical alignment) are fixed.

Thank you.
