### ISSUE TITLE
Container issue

### ISSUE THREAD

**Issue by cosmin-serbanescu** [Codeinwp/otter-blocks#79]
On WP 5.2, otterblocks 1.2.2 I have this container issue: https://prnt.sc/nmpqxn due to this thing here: https://prnt.sc/nmpr9h
It was working fine on the previous version of WP - expanding to full width.

cc @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@cosmin-serbanescu What's the issue there? I don't understand.

Is it working fine on https://jurassic.ninja/create/?

**Comment by cosmin-serbanescu** [comment]
on WP 5.1.1 the Gutenberg editor was expanding to 100%, in 5.2 apparently it's being restricted by that width set to 610px

**Comment by HardeepAsrani** [comment]
@cosmin-serbanescu Which theme are you using?

**Comment by cosmin-serbanescu** [comment]
Neve

**Comment by HardeepAsrani** [comment]
@cosmin-serbanescu It works just fine for me: https://www.loom.com/share/3d82fb10ad314befb973f79bfc017198

**Comment by cosmin-serbanescu** [comment]
probably it's smth on my side then... I'll be back, leave this one open please

**Comment by HardeepAsrani** [comment]
@cosmin-serbanescu Any updates?
