### ISSUE TITLE
Loading Animations - Out animations leave black spaces on page

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/otter-blocks#792]
The out animations such as Fade Out Right or pretty much any of the "Out" animations cause the block to go offscreen because the animations actually happen in the editor. Leaving you with a big blank spot in the editor that when clicked **doesn't do anything.**

This makes it almost impossible to get a hold of the block again to do some editing, I tried clicking around on the page and it seems to be hit or miss.

You have to use the list view to see the blocks on the page when that happens.

To test:

- Add a youtube embed block to the page and embed any youtube link
- Add an out animation such as Fade Out Left/Right
- After the animation is done, try easily getting a hold of the block again to change its settings without making use of the block list view

**Comment by HardeepAsrani** [comment]
We can fix that but @mghenciu do you think there's any sense in us adding those `out` animations in the first place?

**Comment by mghenciu** [comment]
> We can fix that but @mghenciu do you think there's any sense in us adding those `out` animations in the first place?

I think an **out** animation would make sense **only** if you (as a user) can bind it to the scroll area, and when the scroll exists that area -> then roll the out animation. But it sounds like an edge case. At least I never have seen/used something like this. And we definitely have way too many animation options.
Maybe it would make sense to reset each block to the initial state, after the animation is played (see Quebely in the video below)

Another thing I would test more is how other Otter blocks act when they have animation on them, and one of them is duplicated. As seen in this video, it doesn't look very pretty: 

https://user-images.githubusercontent.com/52494172/157897250-ad46dad6-0f88-441f-ad07-2f1621d3f698.mov

**Comment by HardeepAsrani** [comment]
>  Maybe it would make sense to reset each block to the initial state, after the animation is played (see Quebely in the video below)

We already have that in the front-end but that looks ugly.

> Another thing I would test more is how other Otter blocks act when they have animation on them, and one of them is duplicated. As seen in this video, it doesn't look very pretty:

I suppose this should only happen in the backend?

**Comment by HardeepAsrani** [comment]
> But from an UX point of view this is a bit strange, especially if there's a lot of content in page and I, as a user just want to duplicate something, but the animation starts.

We really have no way to stop that. We can't know if it's just a block initialized with animation or just CSS class added.

But to the main point, do you think we should completely remove out animations from the list? I don't see much use of it for a simple animation builder that we have. It's more of need in a more complex website where user make some sort of presentation with the animations for which I doubt they will do it using the block editor or visually.

**Comment by mghenciu** [comment]
**Yes, I think we can remove it**. Those would make sense only if we have 2 Animation options for each block, Intro and Outro animations.
I hope none of our users are using it.

**Comment by HardeepAsrani** [comment]
@mghenciu It will still be part of the CSS so it's fine if anyone is using it.

**Comment by HardeepAsrani** [comment]
@arinaturcu You can remove all the Out animations from the animation picker.
