### ISSUE TITLE
Tabs - Enhancements

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#795]
### Should have
- [ ]  alignment controls, that will allow to have Tab items aligned Left, Center, Right, Full-width
- [ ] do we need to have the Edit Feature in a new Tab? and the edit Icon? are we planning to add more options for each item?
Maybe, if we add the option to edit the item's name directly in the Editor, that field and Icon can be removed from the Sidebar. And instead we can add a Duplicate Icon for each Tab item.

- [ ] Typography controls for the Tab Titles

- [ ] add padding controls for the Tabs titles, and for the Inner content.
- [ ] Extend the color controls. Meaning that Title tabs bg-color should be adjustable, separately from the Tab inner content.
Also we should add color controls for the Tab Title. Right now it's possible to choose only the active state.

- [ ] if we separate the Styling for Title Tabs and Tabs Inner content, then we can add also border options for both of them, with size, color, etc.

___
### Nice to have:
- [ ] HTML anchor options for Tab Items. Not sure if it's best to have an input on the advanced panel when users can add the desired HTML anchor, or automatically get from the tab name. Example here, where the link [takes users to the Review section](https://www.emag.ro/telefon-mobil-apple-iphone-13-128gb-5g-midnight-mlpf3rm-a/pd/DQFCMXMBM/#reviews-section).
Core may have something default for this. For example with wp 5.9, the Table default block has a HTML anchor option.

- [ ] option to add Icon in each Tab Title. We could add it inside the sidebar details, for each Tab (same thing for the HTML anchor):
<img width="1258" alt="Screenshot 2022-03-11 at 15 31 44" src="https://user-images.githubusercontent.com/52494172/157877774-10c567d5-d8d0-4224-96be-5f823bcdbaa4.png">
 

- [ ] Change the new default name Tabs from Untitled to Tab 1, Tab 2, Tab 3 and so on

- [ ] add a few Style variations:
![image](https://user-images.githubusercontent.com/52494172/157877916-b2eef838-33ae-481b-b06b-8f04f135aa19.png)

- [ ] Have a Vertical option:
<img width="1656" alt="Screenshot 2022-03-21 at 16 28 14" src="https://user-images.githubusercontent.com/52494172/159282670-85e80a7a-9b73-4f22-ac6c-40ec891180b0.png">
<img width="1616" alt="Screenshot 2022-03-21 at 16 27 49" src="https://user-images.githubusercontent.com/52494172/159282685-076ba289-513d-46a0-a9ec-7082be3f8904.png">

**Comment by HardeepAsrani** [comment]
>  do we need to have the Edit Feature in a new Tab? and the edit Icon? are we planning to add more options for each item? Maybe, if we add the option to edit the item's name directly in the Editor, that field and Icon can be removed from the Sidebar. And instead we can add a Duplicate Icon for each Tab item.

It's harder to select the tab you want just with the mouse so that's why we have it there. And we have tried to make it consistent with all other Sortable fields that we have so similar options.

>  add padding controls for the Tabs titles, and for the Inner content.

For inner content, people can add a Group or Section block as that gives them better control. What do you think?

**Comment by HardeepAsrani** [comment]
> And about the option to edit Tab names directly in-page, Accordion block works that way, that's why I asked if it's possible.

We can make it possible but will still recommend that we keep it in the Tab itself as the attribute is part of the Tab block so good to have the option there too if user wants to edit it while they edit it. What do you think?

> That would make sense, but only when the Group block will have the padding options. Right now, from what I know, it's only available from WP 5.9 fse. Having one single place where users can configure the Tab padding sounds easier, instead of adding and managing a Group Block.

That's just an example, they can also use Section. Do you think we should add spacing control like Section or just some pre-configured options?

**Comment by mghenciu** [comment]
- [ ] Here, would also make sense to adjust the **behavior of the Tabs on Mobile**.

Right now it looks like this on Mobile, and I think this can cause challenges especially when tabs have more content:
![image](https://user-images.githubusercontent.com/52494172/174776282-20c4e176-81f2-4045-89a0-0f6f4c97ff43.png)

Usually the content uses the standard Mobile approach, items and content going under each other.
Example from [Elementor](https://demosites.io/music-band/music-band-single-album/), but in general other Design System use this approach.
![image](https://user-images.githubusercontent.com/52494172/174776881-846bf39b-f43f-4368-80ce-e913ec374cba.png)

**Comment by mghenciu** [comment]
**Tab names**, definitely need a color control. 
For example on a Darker Background, it's hard to make them work without having the option to change the text color:

![Screenshot 2022-07-21 at 21 34 08](https://user-images.githubusercontent.com/52494172/180288139-1f233d24-b11a-4909-a681-36f9434e45d2.png)

**Comment by ineagu** [comment]
Besides more controls, the default design needs to be improved and the whole experience, I found the Greenshift one the best here is how they look. 

Having some styles options & 3 tabs as default should help
: 

https://vertis.d.pr/i/YB7Mmj
