### ISSUE TITLE
Popup block animations

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#796]
Animations are important and needed for the Popup Block.
But at this point they don't work as expected, causing multiple issues.

Normally it should work properly at least with the Slide-in & Fade-in options.

A few examples:

- [ ] This is how the popup should look in Frontend:
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/52494172/157906151-21234706-d7ec-4f3d-abd7-780ec922291a.png">
and this is how it looks after applying a Slide-in animation:
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/52494172/157906379-67528c77-37b8-47d3-98b6-78be91332009.png">

- [ ] same thing for the front-end vs backend.
This is how the popup normally looks in Backend:
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/52494172/157906605-90ddbed3-57c8-4636-bb47-b42473cfe43f.png">

and this is how it looks when an Slide-in effect is added in Backend:
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/52494172/157906840-a1e83d98-71a7-4174-9ac1-a33437cfc094.png">

**Comment by HardeepAsrani** [comment]
@mghenciu Maybe we can disable the Animations section and just add one there. I don't expect the ones coming from animate.css to work properly.

**Comment by HardeepAsrani** [comment]
Do you think it will be fine if we just add a default animation without giving user an option?

**Comment by mghenciu** [comment]
> Do you think it will be fine if we just add a default animation without giving user an option?


I think, first priority is to make sure that editing Popup is frictionless and not buggy (from a UX point of view).
If this means that we should (temporarily) disable the Animations section on Popup block, then YES - we can do that.

We can also have a default in place now, if we disable the Animations. But if we go this way, it should be something 'generally accepted' (visually speaking), maybe Fade in, and not something very fancy - that some users may not like. 
___
Long term, I think having at least a few options for how the Popup appears, will be a plus. 
I am not talking about a lot of things, just 2-4 options for effects, and positions like Top, Right, Bottom, Left, if the popup is sliding in.

____
Another thing we can look into later, is how are things rendered. So for example in the Popup above (the one with the Image), I think it's important that things are preloaded at the same time as the page does. Meaning that if I have an image there and the Popup opens, I shouldn't see/wait for the image to load (because I expect it was loaded when the page loaded). 
And this is quite important, because most popups use banners, videos.
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/52494172/158773573-03c15d8f-12e2-4be0-a006-66fa5557eaf5.png">

**Comment by HardeepAsrani** [comment]
@adelina17 Can you remove the Animations tab from the Popup block + add a default CSS animation there? It can only be for the front and a fade in will be good.

@mghenciu 

> Another thing we can look into later, is how are things rendered. So for example in the Popup above (the one with the Image), I think it's important that things are preloaded at the same time as the page does. Meaning that if I have an image there and the Popup opens, I shouldn't see/wait for the image to load (because I expect it was loaded when the page loaded).

We don't have much control over that but that can be checked. But I actually think we shouldn't preload the content as people might have Popups for very specific situations, let's say image gallery, where not every user will open the popup on the page while the assets will be loaded regardless. What do you think?

**Comment by adelina17** [comment]
@HardeepAsrani I'm pretty sure this is not for me. 👯 :D

**Comment by HardeepAsrani** [comment]
Haha. @adelina17, sorry that was meant for @arinaturcu but tagged you by mistake. :D

**Comment by mghenciu** [comment]
> We don't have much control over that but that can be checked. But I actually think we shouldn't preload the content as people might have Popups for very specific situations, let's say image gallery, where not every user will open the popup on the page while the assets will be loaded regardless. What do you think?

You know better Hardeep, if that makes sense from a technical point of view or not. And we can leave it for later.
Initially my idea was based on my past experiences with Popups, and I guess yours is the same: that usually popups just pop :) and we, as users, don't have to wait for them to load.

___
But this may be an edge case, even after doing more research, I am confused. [Elementor has them loaded](https://elementor.com/features/popup-builder/), others load them on pop:
https://popupsmart.com/showcase/
https://app.convertflow.com/websites/37859/cta/templates?cta_type=overlay

**Comment by HardeepAsrani** [comment]
@mghenciu It really depends on the purpose of Popup to be honest. If it's a popup that will open for everyone on that page, it should preload.

If it's something that opens on an action (meaning not everyone will be performing that action) then it's better to not preload it.

But yea, mostly I think we don't have much control over if we pre-load things or not. I'll take a look and see if there's something that can be done from our side for optional preloading.
