### ISSUE TITLE
[Feature requests] Add posts categories block with thumbnails

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#798]
A user suggested a new feature similar to the WooCormmece option of showing product categories on the shop page with thumbnails and the number of products.

For posts, there isn't such an option. Maybe we can add a new block for showing posts categories with thumbnails, on which page the users wants.

### Expected layout for posts
![file-ipttKSeQRf](https://user-images.githubusercontent.com/26867648/158211447-eaf8640f-d02a-4ecb-b277-42986901ebf5.png)

### Reference

https://secure.helpscout.net/conversation/1814546675/313574/

**Comment by HardeepAsrani** [comment]
There's a Category List block by Woo which allows you to display them like this. @stefan-cotitosu 

<img width="1202" alt="Screenshot 2022-03-16 at 6 57 58 PM" src="https://user-images.githubusercontent.com/2649903/158600455-b7b0651a-78f4-4d4a-8d3e-991407bb81e3.png">

Apart from that, we have no plan of adding such a block at present so I'll close that for now.

**Comment by HardeepAsrani** [comment]
Got it, sorry for confusion. But we still have no plans for something like that right now.

**Comment by stefan-cotitosu** [comment]
Ok, understood, thanks.
