### ISSUE TITLE
Paddings/Margins issue with v1.2.2

### ISSUE THREAD

**Issue by cosmin-serbanescu** [Codeinwp/otter-blocks#80]
It seems there's a bug in this version, tested with a section and if I set paddings/margins it applies them correctly when updating (both front and backend) but if somehow I refresh the page, the values are reset to their default ones

cc @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@cosmin-serbanescu It's a known issue and will be fixed by the end of the hour: https://github.com/Codeinwp/gutenberg-blocks/issues/110
