### ISSUE TITLE
Icon block default alignment

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#801]
When inserting an Icon withe the Icon Block, the Top Toolbar shows that the alignment is left, even if the icon is horizonally aligned to the center of the page.

This should be consistent, either the icon is aligned left, or the alignment Icon in the Toolbar is Center and not Left.
<img width="997" alt="Screenshot 2022-03-15 at 15 15 35" src="https://user-images.githubusercontent.com/52494172/158385767-2f49ca29-e70b-4695-ad4b-76bbab23d002.png">

**Comment by HardeepAsrani** [comment]
@mghenciu Actually that's just how it behaves. It's the default state when it's unselected. You can see the difference when it's actually left-aligned versus when it's the default. What do you think?

<img width="920" alt="Screenshot 2022-03-16 at 3 41 28 PM" src="https://user-images.githubusercontent.com/2649903/158567026-324e8b84-1f02-43b1-a573-7fb983e31d08.png">

<img width="887" alt="Screenshot 2022-03-16 at 3 41 24 PM" src="https://user-images.githubusercontent.com/2649903/158567007-69b77187-4ecd-4472-a587-17313c55c31a.png">

**Comment by mghenciu** [comment]
Ok, so if it's not a bug, then we can at least make sure there's no confusion. As the Toolbar icon looks left aligned and the inserted Icon is centered.

Maybe we can leave the inserted Icon centered, and also **make the Toolbar icon be Centered** by default. That's how the Icon blocks work on competition blocks.

___ 
Here are 2 examples from WP 5.9
Post title, that by default has the same alignment Icon in the toolbar, the difference here is the fact that the text (by default) is actually aligned to left:
![image](https://user-images.githubusercontent.com/52494172/158679679-152b795c-f886-4357-9c75-949d59abe99a.png)

Same thing for a Heading block:
![image](https://user-images.githubusercontent.com/52494172/158679755-b1912dad-adfa-4f87-bc62-b767085dd42a.png)

**Comment by HardeepAsrani** [comment]
@mghenciu It's not technically possible unless we decide to turn it into a custom control.

**Comment by mghenciu** [comment]
> @mghenciu It's not technically possible unless we decide to turn it into a custom control.

I assumed it's possible, if in the Core block they are doing it with the Heading & Post title blocks.
But essentially is not a big issue, it's more related to the overall consistency & visual cues that users see in the UI.

**Comment by JohnPixle** [comment]
You guys are both right. It would make more sense to have the icon centered by default, but I understand the technical limitations. I'd agree it's not a critical issue for now. Maybe there will be some improvements in the core-level in the future.

**Comment by HardeepAsrani** [comment]
<img width="1061" alt="Screenshot 2022-03-22 at 5 24 18 PM" src="https://user-images.githubusercontent.com/2649903/159476368-17fac828-aaf8-4a7a-b1ff-38f446297a9a.png">

I can't find this behavior in Core blocks either. Am I doing something wrong or you're using a particular version/theme? @mghenciu

**Comment by mghenciu** [comment]
Nothing special.
I was using an [Instawp](https://instawp.io/) instance, wp 5.9.2 and Twenty Twenty-Two.
Also tried locally with Twenty Twenty-One, and same thing.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/52494172/159487619-198d261c-bf1e-4e1a-94f5-aa21b6b78785.png">

**Comment by HardeepAsrani** [comment]
Closing this for now. We can revisit it in future if Block Editor gives us a way to change the default icon but I find it highly unlikely that they will.
