### ISSUE TITLE
Icon - enhancements

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#802]
### Should have
- [x]  Add Alignment options in the Right sidebar also, and make them device based. 
Usecase: I have 3 boxes with Icons and text aligned to **left**, and **on mobile I want them centered**.
- [x] Change the current default size for the Icon from 16px to 32px

___
### Nice to have:
- [ ] Add Icon templates which are basically shortcuts to a certain look, that can be adjusted later.
![image](https://user-images.githubusercontent.com/52494172/158387585-b4f020e9-a9d7-4013-a1d1-31356488429b.png)

- [x] At some point maybe add the Core selector with 3 Sizes and a 4-th one for Custom value. This one is from Qubely: 
![image](https://user-images.githubusercontent.com/52494172/158387725-85500dbb-89ed-455d-b0e7-c1e34a764e10.png)

- [ ] Maybe it's possible to add the light variation for Font Awesome. For some demos we need Icons that use a thin border, one example [is this one](https://www.figma.com/file/HH1bO1qpDwsLws7jalmTFe/Architect?node-id=344%3A2271). And even if we have the Themeisle Icon font that's thiner, I think it would help to have font-awesome variation that's thiner

**Comment by Soare-Robert-Daniel** [comment]
> ### Nice to have:
> * [ ]  Add Icon templates which are basically shortcuts to a certain look, that can be adjusted later.

> * [ ]  Maybe it's possible to add the light variation for Font Awesome. For some demos we need Icons that use a thin border, one example 

Not all icons have style variations. This makes that UI variant to be inconsistent. 

This is the [config file ](https://github.com/Codeinwp/otter-blocks/blob/feat%2Ficon-enhancement/src/blocks/helpers/fa-icons.json). You can see that at `styles`, not all icons have variants.

**Comment by mghenciu** [comment]
> Not all icons have style variations. This makes that UI variant to be inconsistent.

> This is the [config file ](https://github.com/Codeinwp/otter-blocks/blob/feat%2Ficon-enhancement/src/blocks/helpers/fa-icons.json). You can see that at styles, not all icons have variants.

For the FA Icons, **I think we are good for now**. 
Apparently there are at least 3 main variations from them: Solid, Regular and Light (I was referring to this one).

**However, what we can do here at this point, is maybe update the Icon List from FA**, not sure how long ago was this done.
___

As for the **predefined Icon Style**, we can review this later, while doing the Sidebar rework.

**Comment by mghenciu** [comment]
> @mghenciu @HardeepAsrani, If I am right, the FA from 5 & 6 is not 100% free. They have a license on it.

Yeah, I think they have a Pro version now, but on their [Git Repo](https://github.com/FortAwesome/Font-Awesome) it still says: _**Font Awesome Free is free, open source, and GPL friendly.**_
