### ISSUE TITLE
Section - enhancements 

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#803]
### Section

- [x] [Review this issue, and if we can - fix it](https://github.com/Codeinwp/gutenberg-blocks/issues/458#issuecomment-704072858)
- [x] https://github.com/Codeinwp/otter-blocks/issues/1239
- [ ] (UX issue) As a user, I want to be able to select the Section block, without using the Listview every-time. Right now when adding a default Section block, clicking on the Section margin will select the Column and not the entire Section. Maybe we can add a dotted border or something similar, outside the bounding box - that will make Section selection easier.
<img width="1658" alt="Screenshot 2022-03-15 at 16 54 59" src="https://user-images.githubusercontent.com/52494172/158407756-61a4f574-ab85-43e0-82e0-a6cc9963dc13.png">

___
- [x] (UX issue) As a user, I would love to have better background-image controls for sections, and section overlay.
 How to I know what image is selected now from the media library?   the only option available now to change the image is **Clear Image**.
 This is how it looks now:
<img width="1648" alt="Screenshot 2022-03-15 at 15 45 39" src="https://user-images.githubusercontent.com/52494172/158391457-87232119-2b42-40d0-b540-cb7ff552fa0d.png">
And from the above screen I want to get to this screen, where I see the gallery and what image is selected now:
<img width="1606" alt="image" src="https://user-images.githubusercontent.com/52494172/158391682-b017b5c1-8375-4ea8-8154-aa18581164aa.png">

____

- [x] We still have the Columns Gap option in UI. What's the status on that? are the gaps working, nor working? should we remove them?

- [ ] When technically possible, add Background Gradient options -  linked to Global Colors. Right now those are not linked to the Global Colors: 
![image](https://user-images.githubusercontent.com/52494172/158392677-a6eb4068-76e2-4e06-b876-a654fc6f28a4.png)

- [x] Add relative units to the Section Min Height and for Max Content width. 
Important are VH units for Minimum Height, when using Custom Height on sections. And Percentages units for Content Width, when using Maximum Content Width  on sections.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/52494172/158393421-38182d62-20db-4169-9405-d66c373d2ea0.png">

___

#### Nice To have
- [x] Add the option to have Shape Dividers on sections Top and/or Bottom. Example from Elementor: 
![image](https://user-images.githubusercontent.com/52494172/158392173-db892661-ee9c-4f14-9103-39862f3e8dd8.png)

- [ ] Add option to have a video in background for sections.
- [ ] Maybe add Plus Icon Between columns, for adding a new column, same way it's in Core
![image](https://user-images.githubusercontent.com/52494172/158393507-3a9fb1c3-2dd3-4906-ac67-e73eaf9b6f11.png)

_______

### Section Column - enhancements
- [x] option to have a different background-color on hover
- [x] We need to think overall how we can change the Content Color in a Column - on Hover.
Example this layout that changes Content color on hover:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/52494172/158393663-f41d8453-269f-4a47-b9c6-c8f517725369.png">

**Comment by HardeepAsrani** [comment]
>  We still have the Columns Gap option in UI. What's the status on that? are the gaps working, nor working? should we remove them?

We removed it back in 2.0. Do you still see it?

>  Add the option to have Shape Dividers on sections Top and/or Bottom. Example from Elementor:

We already have that in Section. Do you mean to add some changes?

**Comment by JohnPixle** [comment]
I am going to add here that we need to add responsive control at the background overlay positioning. The focal point UX is ok, but we need to be able to adjust it per-viewport if possible
![Screenshot 2022-05-11 at 14 49 15](https://user-images.githubusercontent.com/4193672/167843003-353bc27f-b778-4064-8e71-94f98c48aec5.png)

This is very important for [hero sections](https://demosites.io/nft-illustrator-gb/) and other cases where we have text over a section's background image.

**Comment by mghenciu** [comment]
- [ ] I think it would be a good improvement to also make the default behaviour for Columns in Sections on **Mobile**, go one on each other, as that's the most common pattern, and we are helping users by doing one extra step for them.
Right now, if I add a 3 column Otter Section with default settings:
![image](https://user-images.githubusercontent.com/52494172/175010643-c776ab81-e11d-4ccb-8580-74f381851fb1.png)
 it will remain in a 3 column layout even on Mobile:
 
![image](https://user-images.githubusercontent.com/52494172/175010873-48fe07dd-65fe-4b72-bbc1-607641d21de9.png)

___
Check Core Columns block, if curious, they are using this approach.
 

For some reason I had a feeling that we were doing this in the previous versions of Otter.
cc @JohnPixle

**Comment by JohnPixle** [comment]
@mghenciu very good catch, I was under the same impression.

**Comment by HardeepAsrani** [comment]
>  I think it would be a good improvement to also make the default behaviour for Columns in Sections on Mobile, go one on each other, as that's the most common pattern, and we are helping users by doing one extra step for them.

If we make the switch, it will happen for all the users, even for the existing users. I don't think that will be much of an issue, so what do you both think?

**Comment by mghenciu** [comment]
> If we make the switch, it will happen for all the users, even for the existing users. I don't think that will be much of an issue, so what do you both think?

In theory, most of them should already be using this approach, as it's a common practice, and we've build our demos this way.
But **as a best practice I think we should avoid overriding (existing) users settings**, especially if this causes visible changes.

**Comment by HardeepAsrani** [comment]
@mghenciu This will only cause visible changes if they update the post but by default their layout won't change.

**Comment by mghenciu** [comment]
Here, I am not sure if this was changed recently, but by Default 

- [ ] **sections that have more than 1 Column, should stack by Default on Mobile**.

___
Current behavior:


https://user-images.githubusercontent.com/52494172/188617781-5447109a-5fc0-4d51-a95b-2f947706bae3.mov

**Comment by JohnPixle** [comment]
@mghenciu this definitely makes sense but I remember discussing it somewhere in Github in the past, and if I recall well there would be legacy issues for users. Meaning that it would affect existing layouts. To be honest I don't remember what decision was made.

I agree however that stacking falls within the default and industry-standard expectations.

cc @HardeepAsrani @Soare-Robert-Daniel

**Comment by HardeepAsrani** [comment]
Yes, it was backward compatibility. @JohnPixle

**Comment by mghenciu** [comment]
> Yes, it was backward compatibility. @JohnPixle

Isn't possible to mark all the Section Blocks used until now with something like v2.3.253 (for all previous versions) - leave them as they are, and from now on, all new inserted Sections will be v3.0.1 which has this stacking by default on Mobile?

**Comment by HardeepAsrani** [comment]
We can *technically* do it, but it will make things pretty complex.

However, I'll check if we can simply make the change without breaking things. I think (not sure) but the way things were implemented when we were building Section, things might just work if we make the change.

**Comment by HardeepAsrani** [comment]
At least that's what I can see from reading the code ^

**Comment by HardeepAsrani** [comment]
>  (UX issue) As a user, I want to be able to select the Section block, without using the Listview every-time. Right now when adding a default Section block, clicking on the Section margin will select the Column and not the entire Section. Maybe we can add a dotted border or something similar, outside the bounding box - that will make Section selection easier.

I don't think having a Border will make it easier to select. Especially with the default 0px margin/padding.

**Comment by HardeepAsrani** [comment]
>  option to have a different background-color on hover

@mghenciu Two things:

Is this for Background Color or also for Overlay?

And this is only for Columns, right?

**Comment by HardeepAsrani** [comment]
> I am going to add here that we need to add responsive control at the background overlay positioning. The focal point UX is ok, but we need to be able to adjust it per-viewport if possible

That's only for overlay, right?

**Comment by mghenciu** [comment]
> 

I think **for now having just the Hover Bg should be fine**, and only for the Columns.
Essentially we want to achieve [something like this](https://demo.creativethemes.com/blocksy/petsy/) , where the Column Color changes on hover: <img width="1427" alt="image" src="https://user-images.githubusercontent.com/52494172/196913325-bcb5d2f5-5fff-4ef3-accf-09bcef61de76.png">
 
later we can add more options like different Shadow on Hover and so on.

**Comment by HardeepAsrani** [comment]
@mghenciu One thing, just a Color or do you expect it to be Color/Gradient/Image option?

**Comment by HardeepAsrani** [comment]
>  Maybe add Plus Icon Between columns, for adding a new column, same way it's in Core

I can't seem to find how Core is able to do it. I don't see anything in their code. Will look more and see if it's possible.

> I am going to add here that we need to add responsive control at the background overlay positioning. The focal point UX is ok, but we need to be able to adjust it per-viewport if possible

This one is bit tricky to do given how the current components and CSS is structured. Let me know if you think this is important for the work design team does and needs to be able to make templates/sites? @JohnPixle

**Comment by JohnPixle** [comment]
_> This one is bit tricky to do given how the current components and CSS is structured. Let me know if you think this is important for the work design team does and needs to be able to make templates/sites?_ 

@HardeepAsrani It's ok, we can live without it for sure. Great job on the section improvements so far.

May I ask for another favour (only if it's possible and easy to implement) ?
What about providing vertical alignment controls per column, instead of having them only per section?

Users should be able to still set a vertical alignment on the Section level, but should be able to override this per column if possible.

![Screenshot 2022-10-21 at 10 23 31](https://user-images.githubusercontent.com/4193672/197137373-26057695-f732-47ce-bb10-76fc6dc4ac64.png)

Let me know, not critical but quite useful :)

**Comment by HardeepAsrani** [comment]
@JohnPixle is it about alignment of content inside the column or the alignment of column within the section? Because, I think the column is same height as the content inside of it so alignment won't change anything.

**Comment by mghenciu** [comment]
As discussed in the meeting, a few sources of inspiration for the **Section Video in background:**
- Core Cover block does it, and it has the same options as with an image
- Spectra have it for the Advanced Row
- Kadence Blocks have it, but with more additional options for the Video
- Stackable have it, with not additional options if the bg is video.

Hope this helps, and I think we can start with the Core Cover block.

**Comment by HardeepAsrani** [comment]
> May I ask for another favour (only if it's possible and easy to implement) ?
What about providing vertical alignment controls per column, instead of having them only per section?

I tried but unfortunately, we can't achieve this in the backend because of all the HTML wrapping added by Core inside our blocks. Easy to do in the front but can't do it in back.

**Comment by JohnPixle** [comment]
Sorry for the late reply @HardeepAsrani 

> is it about alignment of content inside the column or the alignment of column within the section?

It was about aligning the content inside the column. No worries though, I saw your last reply about the HTML wrapping.

**Comment by JohnPixle** [comment]
@HardeepAsrani Some further thoughts about the alignment of columns and content, when Sections have a custom height. I think the behaviour is not meeting the expectations, take a look at this quick loom and let me know your thoughts:

https://www.loom.com/share/3b399f336a714ed6820f46eba88dbfd8

cc @mghenciu
