### ISSUE TITLE
(UX Bug) Countdown Block - style inheritance based on Device

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#804]
With some Otter blocks users have the option to adjust the settings based on a device.
Ideally and by default this settings should be inherited from **Desktop to Tablet to Mobile**, of course only in case there are no other Customization or Global Defaults.

One example of this is Advanced Heading, where setting a font-size on Desktop - will add the same style on Tablet & Mobile
<img width="280" alt="Screenshot 2022-03-15 at 18 28 19" src="https://user-images.githubusercontent.com/52494172/158425654-d7de2f8c-c69d-4296-8ce7-2217e32bbca3.png">

___
With the Countdown block, the Desktop style settings are **not inherited from Desktop**, and on Tablet, Mobile - those need to be configured separately. Which means a user has to repeat the same settings 3 times.

### Desktop
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/52494172/158427042-4058ea34-a8c5-4558-8b96-6353a7250a79.png">

### Tablet
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/52494172/158427121-0d4be088-711b-431d-86f5-03f70630cf40.png">

___
Another UX issue related to this are the empty field. For example with the Advanced Heading block, mentioned above, when setting a value on Desktop, which is also inherited on Tablet & Mobile - those values are not visible when switching modes and the field is empty (from Desktop to Tablet). 
My suggestion would be to use use the inherited value, and add as a placeholder in the empty fields - this way users have a clue that the value is inherited & what is that value. Here's an example where 22 is inherited from Desktop to Tablet & Mobile, I hope it's visible that on Tablet & Mobile, value 22 is a placeholder (don't mind the slider):
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/52494172/158428916-a38cc9a8-3ce0-426d-9405-2d591312524d.png">

**Comment by HardeepAsrani** [comment]
@mghenciu Can you make sure that the style inheritance issue is only for the backend or also happens in the front?

**Comment by mghenciu** [comment]
> @mghenciu Can you make sure that the style inheritance issue is only for the backend or also happens in the front?

**It's also for the Front-end**. 

Because initially, when reviewing the Countdown block, I wanted to add an issue because the border is buggy and it doesn't uses the right style on Tablet and Mobile. But after doing more testing, and realised that  all those settings act independently on each device, and making the border white (for example) won't make it white on all devices. [Notion with device images in front-end](https://www.notion.so/themeisle/Countdown-b21a988755a445c48e16d1f938cfe2ee#02ed9d8369e649ab8520f8ab04da4ce8), where's visible that even though on Desktop there's no border, on Tablet & Mobile the border is still present:

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, I specifically made the CSS on countdown independent because the inherited style from Desktop might look pretty bad on mobile or tablet (it breaks the horizontal space/layout, so the size modifiers are very sensible). I choose to force the user to tailor the block options for mobile and tablet to ensure that he is aware that some things might not look right on his page for different values.

Here are the default values.

https://github.com/Codeinwp/otter-blocks/blob/9afaf1840aaec99332786a448840d4030dfc1b2c/src/blocks/blocks/countdown/style.scss#L2-L22

The conditions look like this. 

https://github.com/Codeinwp/otter-blocks/blob/9afaf1840aaec99332786a448840d4030dfc1b2c/src/blocks/blocks/countdown/style.scss#L56-L66

**Comment by mghenciu** [comment]
In a way this makes sense, Robert - but it also can be quite annoying, because users would have to adjust the same **values 3 times**.
I get the point, that something can look good on Desktop, and can be too big on Tablet or Mobile. 
But ideally users should just adjust the values on Tablet & Mobile, and **not rewrite them from scratch**. 

___
We'll follow up on this after we have the overall block structure in Figma.

**Comment by HardeepAsrani** [comment]
Closing it as it was released in the last version.
