### ISSUE TITLE
(UX issue) Maps Block errors when adding Markers - when the API key is not valid

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#806]
Before using the Google Maps block, and its options - users have to add an Google Maps API key.
After the API key is added, users will see more Maps options in the Sidebar. The problem is that users can add anything in the API field, and the Maps settings will be visible.

This creates a problem with the Markers Tab, because the button is active (even if the API key is invalid), and pressing the button doesn't do anything, except generating errors in console. Which makes the situation confusing, as nothing happens when the button is presed. 

My suggestion will be to either add a Disabled state to the Markers button, until the API is valid and the Map is rendered. Or have that tab hidden until the map is rendered.
![Screenshot 2022-03-16 at 13 55 55](https://user-images.githubusercontent.com/52494172/158584775-4db85501-c559-4b42-a1af-e3d8eee9c53e.png)

**Comment by abaicus** [comment]
@mghenciu @HardeepAsrani I don't think there's an easy way to validate the google maps API key. Unfortunately, that's something that the user has to be careful with when adding. The fact that he can add anything in that field is out of our control. 

What I would suggest is either to make sure we add a min characters limit to the input, or just leave this as it is. I feel it's a bit far fetched to assume that users would add a wrong API key willingly. For example, we never had a validation callback inside intergeo maps and there weren't any issues there.

**Comment by mghenciu** [comment]
Thanks for your input Andrei.
Probably not a big issue, more an edge case, and it looks bad only if you look in the console - otherwise not major.

Hopefully after [reviewing this](https://github.com/Codeinwp/otter-internals/issues/5), we'll have a map in the block by default, and this issue will be fixed.
___
Not sure if we can try and catch the Key [error from here](https://developers.google.com/maps/documentation/javascript/error-messages), and when valid -> show enable the markers panel.

**Comment by HardeepAsrani** [comment]
If the user enters again an invalid key the issue is still there, but after a refresh, the placeholder should appear again.
So, the issue is partially solved.
