### ISSUE TITLE
Animation - enhancements

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#809]
### Loading Animations UX controls suggestions
- add Sliders for Delay & Animation Speed, instead of hardcoded values
- (if we don't add sliders) make the Drop-downs order, follow the common approach (from Low to High), and with Default in the Middle:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/52494172/176163292-8abf542c-775d-433d-8157-0d99152bf2f6.png">

- [x] Add **Play Animation** button in the UI, that plays the configured animation. This should help with the fact that animations won't be triggered automatically when a Block is duplicated, but only when user want's that. And also it's easier to preview an  animation. Right now if I want to preview an animation, I need to configure it and it will run once. But if I want re-run it, there's no way to do this, unless redoing the configuration steps.
- [ ] @HardeepAsrani , I am thinking to add a new Control for the Animation Position, and this way we'll have a smaller list for the effects.
For example here are Zoom effects options, the list is huge. And it could be just with 2 options: Zoom In, Zoom Out + an additional control for the Position (Down, Left, Right, Up).
<img width="213" alt="image" src="https://user-images.githubusercontent.com/52494172/158801971-0ee67216-9ab1-4239-a29b-c65ad851ad35.png">

I am aware that Elementor and other web builders use this approach, even Animations in Google Slides - work this way, with a lot of options, but I am thinking to challenge this. Let me know your thoughts, when you get to this issue.

cc @JohnPixle

**Comment by HardeepAsrani** [comment]
@mghenciu 

The first one seems nice.

For the second one, it's not possible to do it unless we do it manually for each as they're just CSS classes that are part of animate.css and we just list all the classes available.

**Comment by mghenciu** [comment]
> @mghenciu
> 
> The first one seems nice.
> 
> For the second one, it's not possible to do it unless we do it manually for each as they're just CSS classes that are part of animate.css and we just list all the classes available.

Got it!
About the second point, I see that there is an option to build a Custom package, including only things you want. But it may be an overkill to do this, and also maintain it each time they release a new update. **So I guess we can park it, and maybe at some point experiment with it.**
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/52494172/159270138-e4104617-b566-471a-b125-009f715af8e0.png">

As an example, I think Elementor uses the same library, and they have around 45 options for animations. We have at least 80+ 🚀

**Comment by HardeepAsrani** [comment]
I've also added a third item to your list by the way.
