### ISSUE TITLE
Lottie - enhancements 

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#810]
- [x] May not be an issue, it's just working this way. But the Centered horizontal alignment is not working properly in backed, but it works in Front-end:
![image](https://user-images.githubusercontent.com/52494172/158975523-e5199276-670e-45ae-8320-5de4d8f6e095.png)

- [ ] Animation Speed and the Number of Loops, are not available when scroll is enabled. We need to add speed option for Animations, on Scroll also. Right now is available only on Click & Hover.
- [ ] Options to Limit the Number of Loops for Scroll also.
- [x] Add background color for the Animation section.
When adding a Lottie animation, the SVG is inserted in a div with the class animation. We could add a new tab, where users can select the Background color for that div. By default the background should be transparent.

- [x] Besides alignment options that we already have, let’s add either responsive values (percentages) or an option to have the Lottie animation full-width. Use case here is when I, as a user place the animation in a column and want the animation to behave Responsive in that column. 
Maybe we could add a Max-width option when full-width is enabled.

- [x] Same thing as the one mentioned on the Image Block, to have an Aria label - for Accessibility reasons.
![image](https://user-images.githubusercontent.com/52494172/158975999-6ab2aa9e-cc1a-4957-8210-43f25e08db64.png)

- [x] I would rename the None option (from Trigger) to Autoplay, because None sound like nothing is happening.
![image](https://user-images.githubusercontent.com/52494172/158976233-8c357c81-e723-4bee-a63a-b72c7cfc015a.png)

- [x] Reset option in Width control

**Comment by HardeepAsrani** [comment]
>  Besides alignment options that we already have, let’s add either responsive values (percentages) or an option to have the Lottie animation full-width. Use case here is when I, as a user place the animation in a column and want the animation to behave responsibly in that column. Maybe we could add a Max-width option when full-width is enabled.

What do you mean here?

**Comment by mghenciu** [comment]
> What do you mean here?

When I am thinking about the Lottie block in general, I see it as an image (and actually it's a SVG vector).
Note, that I am not talking from a technical perspective, as I am not an CSS expert, but more how I imagine it + a usecase.
 ___
Let's say we have this 2-col layout, where the right column has a Lottie. And the width for the lottie is not defined (default state):
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/52494172/159510188-d27f075b-80b5-4b8f-8d55-2dd0be5ce031.png">
Everything good so far, this section will scale responsively on Tablet & Mobile. 

___
Now using the same 2-col layout, I've added a fixed width for the Lottie (400px), and here things get interesting because it will try to keep that FORCED width on any device, breaking the 50% | 50% width, 2-col layout. **Resulting in this on Tablet:**
<img width="816" alt="image" src="https://user-images.githubusercontent.com/52494172/159512738-36b51f68-5444-4f56-b3eb-d9268d865a56.png">
 
___
This doesn't look to be causing any issues, **if the Width control is left with the default state**. Or when I tried to use Kadence lottie block, where they use max-width, instead of width.
But overall the width control for Lottie becomes challenging because it's not based on device (it's one width for all), and because its units are fixed, not relative. In an ideal scenario, I would just set it to use 100% of the column, and be sure that the Lottie doesn't breaks the 2-col layout on any device.

Let me know if this makes more sense.

**Comment by HardeepAsrani** [comment]
Thanks for the explanation @mghenciu, makes sense!

**Comment by arinaturcu** [comment]
@HardeepAsrani Is there a reason we didn't have Loop and Speed options for Scroll animations in the first place?

**Comment by HardeepAsrani** [comment]
@arinaturcu Because if the animation is based on scroll, let's say a rocket going up as you scroll down the page, why would you want to loop it? Similar for speed.

I suppose there can be exceptions there but it didn't make much sense to us. I can't remember if there was a technical reason there as it's been so long.

But it's fine if we give the option, users can choose for themselves if it's technically possible on scroll.

**Comment by HardeepAsrani** [comment]
By the way, we use this for making Lottie user interactive: https://lottiefiles.com/interactivity

**Comment by arinaturcu** [comment]
@HardeepAsrani Great, thank you!

**Comment by arinaturcu** [comment]
@HardeepAsrani @mghenciu I can't find a way to add loop and speed options for Lottie animations on scroll using their API.
It seems that these kinds of animations are meant to work just as they are.

If someone wants to have an animation that loops, it will not be on scroll. As @HardeepAsrani said, it doesn't make much sense.

My suggestion would be to leave this part of the settings unchanged.
What do you think?

**Comment by mghenciu** [comment]
Thank you for the update, Arina. 
**I think we can skip this for now,** and review it later. Unless @HardeepAsrani has any objections.
___
And I misunderstood the Scroll concept. Basically with Otter, and Kadence Blocks, the Scroll means that the animation plays with 'each line of scrolling', when users scroll down, but it also plays in reverse when users scroll up.

While other Block libraries, for example UAG, treat Scroll as when the Lottie Animation enters the viewport, and then the animation starts playing. In this case the number of loops and animation speed, make more sense.
