### ISSUE TITLE
[Features visibility]  Otter blocks thumbnails

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#811]
Can/should we make sure Otter blocks have Thumbnails images when hovering in the Block inserter?
If we need to design thumbnails, I can add an issue for the in the Design Board.

Most of our blocks show **No Preview Available**, when hovering on them.

**Comment by mghenciu** [comment]
So based on [the guide](https://mediaron.com/how-to-enable-gutenberg-block-previews/) you mentioned Hardeep, is it possible to add thumbnails instead of code previews? or this is a hacky way of doing it.

**Comment by HardeepAsrani** [comment]
It's not possible to add thumbnails, we can add the sample data and it is generated automatically.
