### ISSUE TITLE
Post Block - enhancements

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#814]
This one has gone through a redesign recently, I would not get heavily involved at this point, but we can discuss about the following:

- adding plain / card / border styles.  In this case, instead of having the "List" as a "style", we can use a  toggle to "convert to list layout".
- Update the UI control to core UI wherever possible.
![Screenshot 2022-03-18 at 11 19 12](https://user-images.githubusercontent.com/4193672/158976267-1521b7de-f8c3-45ab-96fd-01e7eff76edd.png)

___

**Comment by HardeepAsrani** [comment]
@JohnPixle Yea, styles will be great if you can get some mockups ready. 😄

**Comment by HardeepAsrani** [comment]
@JohnPixle @mghenciu I'm working on Posts Enhancements right now, it would be nice if you could give us a few quick mockups when you have time

**Comment by JohnPixle** [comment]
@mghenciu Just an update of what Hardeep and I discussed in Slack a while ago, let me know if you agree.

### 1 -  Moving Styling controls from Image / Post title / excerpt Panels to Style tab

Hardeep noticed that some of the controls that we now have in the Style tab, are already existing in the Panels respective panels. For example, the border radius and image size are now in the image tab:

<img width="280" alt="screenshot_2022-09-26_at_2 43 19_pm" src="https://user-images.githubusercontent.com/4193672/192250218-e7bd1764-55d4-46d8-ae3b-c551629e51b2.png">

...and in the new version we will add them under style.

<img width="306" alt="screenshot_2022-09-26_at_2 42 58_pm" src="https://user-images.githubusercontent.com/4193672/192250156-7922d2ea-e07a-41b5-a180-5d53c4f6dc26.png">

My suggestion was that "Based on the approach we are taking, it makes sense to have them under the style tab, instead of the image panel. However, when / if the user disables the featured image (by deactivating the eye) then we should look if it’s possible to hide the related parts in the style tab." It is possible. Same applies for controls under the Post title and excerpt panels. We all move them into Styles tab.

IF an element is de-activated (via the eye icon ) then these controls will be removed from the Styles Tab.


### 2 -  Size control for Meta

I edited the Figma to include a separate Size control for post meta, so users can have more flexibility on this.

![screenshot_2022-09-26_at_12 24 57](https://user-images.githubusercontent.com/4193672/192251639-0743f596-5726-40ee-8f80-bd31f6272ded.png)


### Other Notes

Just a quick note / reminder @HardeepAsrani regarding the following:

- [ ] Please remember that all typographic elements should default to the Body Text color. This is related to the approach we are taking for all blocks regarding the Patterns.

- [ ] Same applies for the border. let's make sure that border color also defaults to the body text size.

Thanks you all, let me know if you have any other points / suggestions

**Comment by mghenciu** [comment]
The suggestions makes sense, John.

Nothing to add from my side at this moment. I've only changed the Name of a control in the Settings panel, to keep it consistent with the other ones: 
<img width="307" alt="image" src="https://user-images.githubusercontent.com/52494172/192257276-9bec8199-d31a-4816-af6a-6907ad194162.png">

**Comment by JohnPixle** [comment]
Alrighty then, I guess we are good with the Figma for now also, I don't see any issues. We may discover something when we test it, but for now I believe we are good. 

Any questions or clarifications regarding the UI, please do not hesitate to ping us!

Good luck.

**Comment by HardeepAsrani** [comment]
@JohnPixle @mghenciu Can you explain how these change the styles so I can implement accordingly, in context of both Grid/List layout?

<img width="434" alt="Screenshot 2022-10-04 at 1 00 37 AM" src="https://user-images.githubusercontent.com/2649903/193662568-91e97313-a7b9-464f-aab4-6fe87efe9ca5.png">

**Comment by HardeepAsrani** [comment]
Column & Row Gap ^

**Comment by mghenciu** [comment]
Each of those will be active depending on the selected Style.

(my bad here) I think it may be better to rename the Orientation to **Layout Style** or something around this lines, as in Core they also use this idea of **List view** and **Grid view**, and not Orientation.
<img width="484" alt="image" src="https://user-images.githubusercontent.com/52494172/193764314-932d89a1-da45-4e58-8b6c-689b4b26f8ef.png">


### And controls will be active like this:
- when in Grid Mode, both are visible -> **Column & Row Gap**
- when in List Mode, **only Row Gap** is visible

**Comment by JohnPixle** [comment]
@mghenciu Agreed.
@HardeepAsrani when in grid mode (3 columns x 2 rows for example) , the column gap will set the gap between the columns. Row gap would set the gap between the rows of posts.

When in list layout style, (where there will be no columns, and each post will occupy a row), then we should use only the row gap, which will define the gap between the posts.

Let us know if it makes sense or if you want us to make any tweaks on it.
