### ISSUE TITLE
Product Review - enhancements

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#816]
This one will need to go through a slight redesign, there are several things that need to be adjusted for this block in order to be more friendly. I will redesign/simplify it soon along with other blocks, but the changes will be simple.

Additionally, some things that would be nice to have would be:
- The ability to choose a rating scale. For example, 5 stars or 10 stars. 10 stars appear very long in the variant with the column.

If not possible, we'll find another way to visually hack it. 
![Screenshot 2022-03-18 at 10 39 53](https://user-images.githubusercontent.com/4193672/158965973-854b76f7-2a42-4ca6-9727-2fb939003bbd.png)

Other issues spotted:
- Need to add wide width and full width options in the block toolbar.
- Need to add color controls so user can choose color of several elements (star ratings, etc)
- Need to fine-tune the vertical spacing of the bullets on the Pros and Cons

![Screenshot 2022-03-18 at 10 53 53](https://user-images.githubusercontent.com/4193672/158970004-550fb5fd-b3e6-4adb-9ea5-539cd16ba1fe.png)

**Comment by HardeepAsrani** [comment]
@JohnPixle 

> Need to fine-tune the vertical spacing of the bullets on the Pros and Cons

How would you like to be? Like the image you have added below the comment?

> Need to add color controls so user can choose color of several elements (star ratings, etc)

Can you list the elements and I can add those?

> The ability to choose a rating scale. For example, 5 stars or 10 stars. 10 stars appear very long in the variant with the column.

We can have a select box for Rating System maybe? Default and Compact. Compact can have the same rating but will display in a scale of 0/5? Or just the stars but same in text?

**Comment by JohnPixle** [comment]
Hey @HardeepAsrani !
Good idea to have the option for 5 or 10 stars as a select box. However the text displayed must correspond to the selected scale. I mean that, for example if the user has selected a scale of 5 stars, the text must display xx/5

If the chosen scale is 10 stars, the text should be xx/10. Let me know if we have any potential drawbacks with this.
I'll need a couple of days at max for making the adjustments to the review block and sharing over the figma for you with as many clarifications as I can. I will ping you when ready.

**Comment by JohnPixle** [comment]
Hey Hardeep!

I have worked on some ideas on the product review block, you may find [the Figma files here](https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=727%3A4500). Files include a suggested UI for the inspector.

You will also find a loom video where I go through the overall logic. I'd appreciate it if you'd find the time to take a quick look.
(password is required, already shared in slack)

Some notes on your questions:

### Vertical alignment of icons

> Need to fine-tune the vertical spacing of the bullets on the Pros and Cons

Currently it is vertically aligned at the center. Need to vertically align it at the top. (as in the example on the right)

![Screenshot 2022-03-29 at 13 57 18](https://user-images.githubusercontent.com/4193672/160596898-09cea1aa-48bc-48f6-8c9f-eea890b81ecf.png)

### Color controls


> > Need to add color controls so user can choose color of several elements (star ratings, etc)
> Can you list the elements and I can add those?

Sure, here is a screenshot from the figma file. The `accent` color is renamed to `Button`.
Please also review my loom video where I refer to the global defaults sync.

![Screenshot 2022-03-29 at 13 59 31](https://user-images.githubusercontent.com/4193672/160597194-dc76b593-4076-4b41-9119-6ccb6fb9f05a.png)

### Rating Scale
For the rating scale, I explored a select box. Let me know your thoughts on this after you see it in context at the Figma file.

![Screenshot 2022-03-29 at 14 03 22](https://user-images.githubusercontent.com/4193672/160597788-2bb6eb69-2163-4658-aa92-ebc390afaeb1.png)

### Style variations
If we want to keep consistent with the style variations, we can have the three standard styles for this block as well. 


![Screenshot 2022-03-29 at 14 05 39](https://user-images.githubusercontent.com/4193672/160598140-453cc760-ae85-413e-a3e1-d2bd1a0ca140.png)

We can control the layout variations for the columns via a separate UI
![Screenshot 2022-03-29 at 14 08 10](https://user-images.githubusercontent.com/4193672/160598498-5ecbe07f-6213-4eda-8d94-e9a6e25ddde2.png)

Please let me know your thoughts and let's start a discussion on this before implementing.

cc @mghenciu

**Comment by HardeepAsrani** [comment]
Hey @JohnPixle,

Thanks for the video. I like the overall direction but have two things to discuss:

1. The styles are nice but what happens when the user updates the plugin and the old styles that uses are gone (border) and the card turns into a blue card? I do think we should at least have the Border style have the same feel as the current Review block in case the user wants to have that (we can just add the top-left border and keep the new structure). What do you think?

2. For Pro, don't think Circular and Bar will be very popular as a Pro product (also circular rating element will be shit to work with) :D - maybe we can have different card styles, such as a more compact version of review? Currently, for Pro, we offer Review Comparison and Sync with WooCommerce.

**Comment by JohnPixle** [comment]
1. Thanks, yes we can do that. In this case we will have the border style by default. ?
2. Ok, good to know, no problemo. We can have a detailed and compact layout as a pro variation, as you said. Perhaps we can work on a third layout as well (more horizontal).

Will follow up.

**Comment by HardeepAsrani** [comment]
@JohnPixle It's fine if we don't have it by default but should have it somewhere so users can switch back.
