### ISSUE TITLE
Contact Form - enhancements

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#821]
- [ ] There is already another ticket with improvements for the Contact form. But it may worth adding option to Send a Confirmation email on the Sender email (email field), besides the Admin  email. When this is enabled, additional settings will appear (could be a Pro feature). Here's an example with. more options to where the email is send after clicking the Send button:
![image](https://user-images.githubusercontent.com/52494172/158993968-d9fc5c83-2f92-44b3-83c3-2e7738725505.png)

- [ ] Have Styles for forms, at least two of them. Basically pre-made input field styles.
- [ ] At some point have the option adjust the field width, meaning that users could create 2 field of 50% Inline, for example First Name & Last Name.
___
Overall I think we can get a lot of inspiration form the Orbit Fox contact form widget, as we also have the code there.

**Comment by HardeepAsrani** [comment]
I think some of these were fixed in with: https://github.com/Codeinwp/otter-blocks/pull/797 - so might be good to update the PR to remove the ones which were fixed already.

**Comment by HardeepAsrani** [comment]
@mghenciu forgot to tag ^
