### ISSUE TITLE
Icon List - enhancements

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#824]
- [x] Option to have enable a divider between List items (only available when the list is in Vertical Mode). And that will have the basic border controls.
- [x] Separate the controls for Icon size and Text size. Users should have the options to adjust them independently, at Icon List level. 
- [ ] Global Settings controls for picking the Icon Library and Icon may be confusing. 
Initially, I thought that when adjusting the Icon on the List level, it will change the Icon for all Items. But no, it doesn’t work that way. Where you only select the Icon for the Future Icon Items that will be inserted. I would suggest that we either go the Global way, meaning that from those controls users can change the Icon Globally, for both existing & upcoming Icon List Items. Otherwise we can Remove this controls on the Global Level, and leave them only on the Icon List item level. cc @JohnPixle , if you have other ideas just for this UX issue.
![Screenshot 2022-03-18 at 15 07 58](https://user-images.githubusercontent.com/52494172/159008555-addfd27c-969e-4705-b422-3f9612a0233e.png)

- [x] Have the Text Indent options, meaning to set the spacing between the Icon and the Text.

**Comment by JohnPixle** [comment]
@mghenciu fair points. Regarding the icon UX, yes, the expectation is to have the same icon in all items, but I suppose the ability to have different icons may be what makes it special. Ideally, as a user I would like to be able to set the default icon in Global settings. And then, when / if I need to use a different icon in a list item, I can edit it on the block-level (list item).

**Comment by HardeepAsrani** [comment]
@JohnPixle @mghenciu Just a note here, we can only have things that we can change with CSS in Global Sync. :D Icons isn't one of them.

So only CSS properties can be part of Global Defaults.

**Comment by JohnPixle** [comment]
@HardeepAsrani Shall I make a quick inspector mockup for this based on @mghenciu input above? I mean if you have not yet started it. Let me know!

**Comment by HardeepAsrani** [comment]
Sure!

**Comment by mghenciu** [comment]
Maybe worth thinking about the option to have different Alignment based on Device.
Not sure how critical is this, just fyi.

In this example, the Icon List is centered on Desktop:
![image](https://user-images.githubusercontent.com/52494172/162752451-2b680664-bae2-4ad8-83e3-9e5a30b3a508.png)

It will look like this on Mobile (also centered):
![image](https://user-images.githubusercontent.com/52494172/162752534-d0079c40-2c78-41ad-8464-ae845c6f1063.png)

___
With left alignment (injected with CSS), it would look like this:
![image](https://user-images.githubusercontent.com/52494172/162752732-7dbb4459-a008-463d-9091-e4b6e07c5451.png)

**Comment by mghenciu** [comment]
- [ ] Icon list looks different in Front-end vs Backend (aligned to center all the time):
![Screenshot 2022-08-03 at 15 40 58](https://user-images.githubusercontent.com/52494172/182610234-e7aeaace-6c8a-40f8-8f0d-e8c75f280518.png)

**Comment by mghenciu** [comment]
**Is it possible as an enhancement to also Hide the Placeholders when in Horizontal Mode?** Maybe a Toggle in the Sidebar
The usecase here is that usually we use this Block for showing Rating Stars, and this is how it looks in **Front-end**:
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/52494172/186156098-e1323d4b-082e-4d79-9ee0-90da0baca6b5.png">

While in the **Backend** it has text and it can make things confusing as users don't know that the text is not visible in FE:
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/52494172/186156319-80c3887c-f075-4fc6-9b5b-7d4bd21beb87.png">


___

Another thing related to this is the **Spacing Between items**. In the same [example above](https://demosites.io/conference-gb/), the **Gap between items is set to 0** - but as seen in the Front-end, there is a lot of space between the Star Icons (attached video):

https://user-images.githubusercontent.com/52494172/186157211-648cf92a-c516-4bf2-83fb-e84e58515011.mov



My suggestion would be to use a similar approach as the one for the Button group, **where the Gap between items is more customisable, at at least make the default min Gap, a bit smaller.**
