### ISSUE TITLE
Countdown - enhancements

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#825]
- [ ] More predefined styles, like we[ initially discussed](https://github.com/Codeinwp/gutenberg-blocks/issues/737#event-5195751400). Round, filled, etc
- [x] Option to have it Responsive. For example I want to counter to be on a full screen page, but at the same time look on Mobile. Some Typography responsive settings may be needed. 
For example in the end, it should be possible to build something like this:
![image](https://user-images.githubusercontent.com/52494172/159011504-30fb70f1-b986-4b3d-adde-d73d2fcbe787.png)
Right now something like this wouldn’t be possible, as the Time Value Font Size is limited to 64px.

- [ ] Create a new tab for Style and keep in Settings only things related to settings.
- [x] Separate Number Typography controls from the Label Typography controls. Each of them should be configurable independently. And have the usual typography options, not just the font-size.
- [x] Add relative units for Font-size
- [x] Add text/content alignment options. This will align the text inside each column, Left, Center, Right:
![image](https://user-images.githubusercontent.com/52494172/159011931-b26baa93-83a2-41c7-a45b-a60bd7b11dbb.png)

### Potential issues
- [ ] Every-time when the page loads, the timer is 0 for a second, and then the numbers are loaded. Maybe could do something about this using the available lifecycles/cache, which won’t reset the dates at each refresh.

**Comment by JohnPixle** [comment]
Ok, there are a couple of more things that can be reworked with this, but better do it at the next stage where we will be processing the inspector UI and work more closely on style.

Summarising the issues here, and will follow up again:

- [ ] 1. Box width should apply to the countdown container
- [ ] 2. Styles do not cascade to mobile 
-------

### 1. Box width should apply to the countdown container
Currently the box width control applies to the individual boxes. But it must actually apply to the width of the countdown boxes container, and NOT for each of the individual boxes .

![Screenshot 2022-06-15 at 14 41 10](https://user-images.githubusercontent.com/4193672/173818927-df44f804-8d44-466b-a58d-648e7bb3915c.png)

We actually want the individual boxes to equally fill the container. SO if there are 3 boxes, each would occupy 33% of the container. IF there would be 4 boxes, they would be 25% each.

Box spacing will still dictate the gap between the boxes, like it does now.

![Screenshot 2022-06-15 at 14 43 20](https://user-images.githubusercontent.com/4193672/173819287-8f8c7e52-3d6d-4ea4-a9a9-29defc58177e.png)

I would strongly suggest that you take a look at the way Elementor approached it, and serves as a good standard:

![Screenshot 2022-06-15 at 14 48 08](https://user-images.githubusercontent.com/4193672/173820226-9f3190ab-1737-499e-8e1d-aa88b5528aa0.png)


### 2. Styles do not cascade to mobile 
When I set the styles, colors etc, these styles are being reset on the mobile viewports. They should remain, unless the user customises them.

Desktop view
![Screenshot 2022-06-15 at 14 52 23](https://user-images.githubusercontent.com/4193672/173820863-5abbf468-1839-4b33-971a-6dba10ff2f78.png)

Tablet and mobile view, where styles are reset, and the user will need to do the styling again.

![Screenshot 2022-06-15 at 14 52 30](https://user-images.githubusercontent.com/4193672/173820912-ae31db9f-fc90-4fe2-b63f-067e59600faa.png)
