### ISSUE TITLE
Masonry doesn't work inside Tabs

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#832]
If you put Masonry inside Tabs, it doesn't work.

**Comment by HardeepAsrani** [comment]
Might be a good idea to test all the blocks to make sure they work when they're added into Tabs and Accordions @irinelenache - make sure it's not in the tab that is open on load.

**Comment by HardeepAsrani** [comment]
@JohnPixle But tabs are the type of object where users might want to add anything. It might just be a simple Text block coming from a third-party plugin.

**Comment by JohnPixle** [comment]
@HardeepAsrani I understand, additionally the user might want to create really rich layouts in each tab, which -as you say- may include any kind of block. 

Just mentioned this restriction in case it technically helped somehow, in case the problems persist.
Following!

**Comment by HardeepAsrani** [comment]
@JohnPixle I get that but to be fair, it's not the Tab's problem. It's the problem of our masonry block that it doesn't work when used inside tabs.

**Comment by irinelenache** [comment]
@HardeepAsrani Checked all the blocks from otter inside accordions and tabs:

✅ Advanced heading, Business hours, About author, Button group, Circle counter, Countdown, Flip Card, Icon, Icon list, Form, Maps, Google Maps, Lottie animation, Plugin card, Posts, Progress bar, Pricing section, Sharing icons, Product review, Review comparison, Comparison table
✅ Masonry works inside the accordion only

❌ Masonry doesn't work inside tabs
❌ When the **Slider** is inside a tab, it isn't working until i resize the window. Here is a video https://vertis.d.pr/9jIqTn

**Comment by HardeepAsrani** [comment]
Take a look at it when you get some time. @Soare-Robert-Daniel

**Comment by HardeepAsrani** [comment]
@irinelenache Does the Slider work inside Accordion?

**Comment by irinelenache** [comment]
@HardeepAsrani Yes, the Slider worked fine for me inside the Accordion
