### ISSUE TITLE
Lottie animation in a post breaks the sticky block feature

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#846]
If i have a lottie animation added at the top of a post and a section under it with a sticky block, the sticky block will not work as expected. If the lottie animation is added after the sticky block, it will work fine.

Here is a video that outlines the issue:
https://vertis.d.pr/HPvh0Y

**Comment by Soare-Robert-Daniel** [comment]
The problem is that the Lottie file is loading after the sticky initialization. We need some detection to solve this.
