### ISSUE TITLE
Extra props passed to dynamic blocks causing it to break

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#86]
As reported here: https://wordpress.org/support/topic/causing-other-blocks-to-not-load-in-editor/#post-11787370

We need to fix this in composer packages, which are:

- https://github.com/Codeinwp/gutenberg-animation/
- https://github.com/Codeinwp/blocks-css/

**Comment by poonam279** [comment]
@HardeepAsrani The same conflict is happening with Otter and Nivo slider. If we disable CSS & Animation module from the otter plugin, Nivo slider works properly.

**Comment by HardeepAsrani** [comment]
@poonam279 Ask the user to use the latest version, it should be fixed.
