### ISSUE TITLE
on amp we should have the animation related scripts disabled

### ISSUE THREAD

**Issue by selul** [Codeinwp/otter-blocks#87]
@HardeepAsrani right now due to the animation module, on pages, build with Otter, the AMP validation fails.

You can replicate by installing the official AMP plugin along with Otter.

I know that there is a solution to turn off the Animation module, but I'm sure that some people will want to have animation on non-amp pages and disable them on AMP ones. 

We can do something smart and see if we are in the AMP context, no longer enqueue the assets.

**Comment by HardeepAsrani** [comment]
@selul Above two commits fixes it. Can you check if there are any other issues? @selul

**Comment by selul** [comment]
seems to be fine
