### ISSUE TITLE
Text color for Otter blocks

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#874]
Since text is one of the most important & commonly used elements in our blocks - I think it's important to establish how we should treat the **Text Color** in general, as later it may be harder to fix this. 
Even though there are cases when themes support Dark Modes, this discussion is about Text in general - and not about the Dark Mode.

**My suggestion is to use the WP approach, and add the Color option/tab for the Blocks that contain a lot of text.** 
A few example from WP blocks:

_Post Query loop_
<img width="287" alt="image" src="https://user-images.githubusercontent.com/52494172/163952221-c41754a2-3dfc-4586-9d05-36809c1d6836.png">
___
_Author Box_
<img width="285" alt="image" src="https://user-images.githubusercontent.com/52494172/163952271-4b5e4cab-df1a-470a-9acb-e3fc5507b12f.png">
___
_Media & Text_
<img width="277" alt="image" src="https://user-images.githubusercontent.com/52494172/163952655-399eff6d-0a8f-410f-b156-fffdaa68d319.png">

___
### Why this is important
While there are cases when themes have Dark Mode, we need to also consider that people use our blocks with different types of background. And for this case we are talking about Dark Backgrounds. 
So for example let's say I want to add an Author Box [on this page](https://demosites.io/exhibition-gb/), in a section with Dark bg. The text from Author box is hardcoded to a fixed color:
<img width="1700" alt="Screenshot 2022-04-19 at 11 00 12" src="https://user-images.githubusercontent.com/52494172/163955017-9a796f09-62d2-47bf-861d-b00c9d1ce593.png">

same thing if I want to add the Product Title with Woo Builder, and the list can continue:
<img width="1698" alt="Screenshot 2022-04-19 at 11 02 16" src="https://user-images.githubusercontent.com/52494172/163955238-a6381844-1491-4d05-be1f-575c1626c1c7.png">

**Comment by JohnPixle** [comment]
Hey @mghenciu, this is solid thinking, I already have something like this in my mind when designing the UIs.

The screenshot is from the [product review](https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=727%3A4500) block.
![Screenshot 2022-04-26 at 12 07 43](https://user-images.githubusercontent.com/4193672/165265190-bf04285d-1dea-4ee0-a33b-95271c521bc3.png)


Overall, I like the Background / foreground metaphor, and I agree about using it. From what I understand though, you are also speaking about the default values, correct? Text color in all of our blocks for example, should inherit the `Foreground` color from the theme settings, correct?

**Comment by mghenciu** [comment]
I didn't thought initially about the defaults, but 100% those are important. As from [WP docs](https://developer.wordpress.org/block-editor/explanations/user-interface/): _Pick good defaults, and make important actions available in the block toolbar._

The main objective here is to **have this mindset of thinking twice if a text should have color controls**, both in Design & Dev-side. So for example the Site Title can be one word, and you could say that color controls are not needed. But if we think twice about this, we'll realise that some Navbar have a darker background - where a white Site title is required:
![Screenshot 2022-04-26 at 13 18 18](https://user-images.githubusercontent.com/52494172/165279323-14922485-3107-49f7-8c91-a1593bc357ba.png)

**Comment by mghenciu** [comment]
Related to this >> https://github.com/Codeinwp/otter-blocks/issues/694

**Comment by HardeepAsrani** [comment]
I've closed this https://github.com/Codeinwp/otter-blocks/issues/694 - it's the same thing.

**Comment by HardeepAsrani** [comment]
Can you list all the blocks that you think needs this? You don't need to go thru them to see if they already have it.

**Comment by mghenciu** [comment]
I think this was fixed with the new Sidebar redesign, as we approached them from this perspective.
Not sure if those from the Woo Builder are also updated. Took a quick look now and the Woo Product Title inherits the body text color, which is good, but not ideal if that Block is added on a Dark Background.

**So I think you could do a quick review on the Woo Builder text blocks, for the rest of the blocks it should be fine - and we can close this issue.**

**Comment by HardeepAsrani** [comment]
I was thinking of adding a bunch of controls to each of the Woo block, I think we can add:

- Color
- Background
- Padding

Sometimes, you need padding if you've applied Background Color.

What do you think @mghenciu? Do you think we need any other control?

**Comment by HardeepAsrani** [comment]
Will close this in favor of this: https://github.com/Codeinwp/otter-blocks/issues/1344
