### ISSUE TITLE
Otter Icon block not working as expected in Custom Layouts

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#883]
When using Otter's Icon block, with Themeisle Icons, the Icons will become huge when placed inside a **Custom Layout Section**.
This only happens with Themeisle icons, while with Font Awesome icons - things work as expected.
And in preview it looks normal.

The icons should be 54px, like this:
![image](https://user-images.githubusercontent.com/52494172/165971083-4f767080-e907-4760-8855-f42c47624435.png)

But they look like this:
![image](https://user-images.githubusercontent.com/52494172/165971283-1b19b9b4-0d40-4a40-9880-2e1271c901be.png)

___
Robert recommended to to a Clear Cache on demosites.io, which I did - but no changes.

**Comment by HardeepAsrani** [comment]
Hey @irinelenache, can you let us in testing features of Otter Blocks when used in the context of Custom Layout? Let me know if you'll have time for this.

**Comment by irinelenache** [comment]
@HardeepAsrani Check the behaviour of blocks added inside custom layouts:

Note: I couldn't replicate @mghenciu's issue, maybe some extra steps are needed

- [ ] When i add a **Flip card** in an **After header hook**, regardless of the block width selected, the container will have full width and the hover space is bigger than it should https://vertis.d.pr/MhHSyE

Besides that, didn't find any problem here

**Comment by mghenciu** [comment]
I tried to follow up with a more detailed Repro Steps, but unfortunately as Irinel mentioned - **this is replicable only on demosites.io**. When creating a clean instance and importing the Jewellery demo, or any other site with Custom Layouts - things look ok.

The overall idea is that on demosites.io, Custom Layouts don't work anymore as they did before, when we talk about Gutenberg/Otter context. And I don't know how to fix this.

Here a few examples to get a better idea. On the [Jewellery gb demo](https://demosites.io/jewellery-shop-gb), we have a lot of Custom Layouts, and all of them were fine before.

___
News Header - **expected**:
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/52494172/167140470-711f8408-36ec-467e-a2d3-fc783d28b1ea.png">

**How it looks now**:
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/52494172/167140568-5b613ed6-40c8-41b9-8091-2f9fef9ac512.png">

___

Single Product Footer **expected**:
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/52494172/167140756-a13ad0a0-8c34-407f-b129-fb42254af6de.png">

**How it looks now**:
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/52494172/167140820-a3d9f41f-8b61-41f1-9ed2-b7e554251692.png">


___
Sports Academy before:
<img width="1729" alt="image" src="https://user-images.githubusercontent.com/52494172/167145027-beff5c1a-c699-4b29-81ef-f7e5e6ee32ae.png">

[Sports Academy now](https://demosites.io/sports-academy-gb/news/):
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/52494172/167145221-5fce19f2-0c04-4675-b3cc-ed871920a3fc.png">

**Comment by mghenciu** [comment]
As discussed with Arina on Slack, I've done more testing trying to replicate the issue with Icons, Image overlay when used in a Custom layout context. **And I couldn't reproduce it anymore, not even on demosites.io.**

Tested from 2.0.5 to 2.0.1.

**Comment by HardeepAsrani** [comment]
@mghenciu So we can close this, right?

**Comment by arinaturcu** [comment]
@HardeepAsrani Before closing I'll check the issue with the Flip Block found by Irinel.

**Comment by arinaturcu** [comment]
I could replicate what Irinel mentioned, and it seems to happen even if the block is outside of a custom layout. I am working on fixing it.

**Comment by HardeepAsrani** [comment]
Thanks, @arinaturcu! I'll consider this task as completed. Let me know if there's anything left from here @mghenciu!

**Comment by mghenciu** [comment]
> Thanks, @arinaturcu! I'll consider this task as completed. Let me know if there's anything left from here @mghenciu!

From my side, nothing to add 🚀
