### ISSUE TITLE
notification is added multiple times

### ISSUE THREAD

**Issue by selul** [Codeinwp/otter-blocks#896]
Each time when we save a page there is a high chance that this will happen https://vertis.d.pr/qunXWI by adding the snack bar multiple times even if I click just once the save.

Before adding a new notice, we should check if we don't have one visible already to avoid this kind of cascading behaviour

**Comment by HardeepAsrani** [comment]
@selul We have a check there and also a debounce wrapper but it still happens. We will check again to see see if we are doing something wrong.

**Comment by mghenciu** [comment]
I also wanted to report this issue at some point. 
But if I am not mistaking, it may be happening only on Old/existing Instances (which is also not good) - so may be worth testing on a clean Taste wp instance to see if the bug is present.

**Comment by HardeepAsrani** [comment]
It used to happen quite a lot but now it's not easily reproducible everywhere. It happens quite a lot when you preview it and then save, due to auto saves and all. But it works fine, at least for me, on new installs.

Does it happen for you on Starter Sites? @mghenciu

**Comment by selul** [comment]
@HardeepAsrani this can be replicated fairly easily on themeisle site

**Comment by mghenciu** [comment]
> Does it happen for you on Starter Sites? @mghenciu

I doesn't happens regularly, meaning that if I go and edit a page now, by changing just one char - it will act normally.
But in a 'heavy' use-case where you build a site from scratch, preview and save a lot of times -> then the queue it's noticeable, and doesn't look good. So for example in the demo below, an user would have to wait a few minutes until those  toast disappear.

https://user-images.githubusercontent.com/52494172/166907594-f8984c89-6563-4e33-b142-f2d37cee4d02.mov




![image](https://user-images.githubusercontent.com/52494172/166906468-55a248f3-7ab2-45fd-bc9b-5438eb6c0e60.png)

**Comment by selul** [comment]
@HardeepAsrani we need to do something on this, on themeisle you can replicate this fairly easily.

**Comment by HardeepAsrani** [comment]
@irinelenache You might want to try a big post with many blocks, probably one that is already published, to try to get this behavior in the current version as it's not always easy to reproduce this on new installs.
