### ISSUE TITLE
Button Group block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#9]
@ineagu @selul Should we add this block?

The issue being Gutenberg's default button block has no way of adding two buttons in one row, provides with no option to choose hover color, which will not be a good thing.

What do you guys think about it?

It also has an issue with heading block. Heading block has no option to pick a color for the heading, so if we make a layout with dark background, we can't use heading block.

1. We can use Paragraph block which will look exactly like heading, just won't have same SEO benefit until the Heading block adds color option, which is in works I believe.

2. We can develop an Advanced Heading block which will solve this, but will be obsolete in few months.

**Comment by ineagu** [comment]
Wouldn't columns solve this problem? For first?

For 2nd I think we can try to focus on the core missing pieces ( like row stuff you work on ). I see first part we did as experimental phase, row layout thing as first part, then once we get the feedback and understand what people want and how they use move forward with more blocks/settings/layouts etc.

Those are my quick thoughts on this, unless those are a blocker for theme templates.

**Comment by HardeepAsrani** [comment]
@ineagu I'm against using columns for button group, but even if I do that, major missing piece is hover colors, what should we do about them?

**Comment by HardeepAsrani** [comment]
I'm just curious, do you see hover styles as something that we need to add or something that isn't needed for now but we can add later if needed with custom blocks?

I'm obsessed with perfection, but "completed is better than perfect." :)

**Comment by selul** [comment]
@HardeepAsrani yes, I agree with @ineagu, we can postpone this until we get more insights and develop some templates using Gutenberg. Meanwhile, we can try to find some workarounds to those things for the templates we develop ( custom styles, css classes ) and later on work on a generic solution. 

Related to the hover style, if we would have to develop those, we can extend the props of the current button block with the hover style setting or we need to build a brand new button block and add those?

**Comment by HardeepAsrani** [comment]
@selul We will have to make a new button block because the current one is kind of not usable with most of the themes. They take theme styles so they can look completely 360 degrees opposite from the intended design depending on which theme you're using.

I have complete faith that this feature won't be getting improved in Gutenberg anytime soon, so a Button Group is really needed. Plus, it can be done in a couple of days with outstanding results, so we will still be able to release a very polished version of Otter Blocks with templates and all in the second quarter of January.

**Comment by selul** [comment]
@HardeepAsrani ok, let's move this forward then.
