### ISSUE TITLE
Section Block CSS breaks for Mobile after the first customization with the Energy Panels Starter Site

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/otter-blocks#903]
It seems like the Section Block when using Background Images tends to lose the mobile view CSS once you do the first modification to it. I managed to fix it with a min-height instruction set on the selector but maybe it needs to be seen why it does this in the first place.

Here is a screencast of the behavior: https://vertis.d.pr/tcpA10

Steps to reproduce:

1) Install Neve and the starter sites plugin
2) Install the Energy Panels Starter Site
3) Edit a section column using the Edit Page settings
4) Observe how the styles break on the mobile view

Expected Behavior:
The modifications are being applied without loosing the mobile style

User Reported [here](https://wordpress.org/support/topic/problem-with-the-mobile-version-with-the-section-block/#post-15614334)

WP Version: 5.9.3
Otter Version: 2.0.2

**Comment by Soare-Robert-Daniel** [comment]
I think this is a design issue. Using an empty column to act as an image block is dependent on the height of the other non-empty column. @mghenciu, in the empty column with the background image, we should add a Space block to keep its height.

E.g: 
![image](https://user-images.githubusercontent.com/17597852/166664702-60e93dc8-c531-4a67-a782-4ff7b3825279.png)

![image](https://user-images.githubusercontent.com/17597852/166664805-dc81dddf-503b-44d8-9d57-c52bf9ac03e7.png)

**Comment by mghenciu** [comment]
Thank you for reporting this Matei, and for the suggestion Robert.
I added spacers in the empty columns.

**Will check it again in some time, after the changes are synced.**

**Comment by Soare-Robert-Daniel** [comment]
@Skystream96, if the user asks for an update about this, you can recommend the client to insert a Spacer Block with the height of 460px on the column with the background image instead of the custom CSS or reimport the updated template (which I think he will not).

I will close this issue. Feel free to open this issue if there is something else or an update.

**Comment by mghenciu** [comment]
460px may be too much Robert. 
Depending on the Gb/WP versions - the spacer **can be or not** Responsive. So if the user makes it 460px on Desktop, it will have this size on all devices.
