### ISSUE TITLE
Icon Block bordering behaving weird in BE vs FE

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#904]
When you have some time, please check if this is normal.
Basically the **padding isn't visible in Backend**:
<img width="1725" alt="Screenshot 2022-05-04 at 15 29 31" src="https://user-images.githubusercontent.com/52494172/166681430-fe6efad6-2708-422d-889f-946088f89775.png">

But **it works in Front-end**:
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/52494172/166681492-7229e055-5c1b-4f83-9a1f-13aeda6b6b1a.png">

[Happening on this demo](https://demosites.io/energy-panels-gb/contact/).
And if it's an issue, please make sure to create a Regression Test for this. 
___
Another issue here is the width X heigh ratio, when the border on the Icon is round. Basically if the FE Icon shape isn't square, then the Circle formed by the border - will **also be imperfect**:
<img width="1633" alt="Screenshot 2022-05-04 at 15 32 50" src="https://user-images.githubusercontent.com/52494172/166681911-c1f2e7c2-b082-4d64-b9b6-63680b979035.png">

**Comment by Soare-Robert-Daniel** [comment]
The editor problem is caused by this misuse of the condition, which makes the values set to 0 to be ignored.

https://github.com/Codeinwp/otter-blocks/blob/9afaf1840aaec99332786a448840d4030dfc1b2c/src/blocks/blocks/font-awesome-icons/edit.js#L59-L63
