### ISSUE TITLE
WordPress 6.0 Compatibility

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#906]
Hey @irinelenache, WordPress 6.0 will be released on the 24th of May. Can you get things tested for it? @irinelenache

**Comment by irinelenache** [comment]
The style preview is not visible anymore and if the style name is longer it will be truncated
![image](https://user-images.githubusercontent.com/67897586/169025748-4658e8a0-0081-4c00-bcde-e83d16a166e6.png)

**Comment by HardeepAsrani** [comment]
> Investigate breaking style in Editor for Tabs in WP 6-RC1

@Soare-Robert-Daniel I can't reproduce it in the stable release. Can you?

> The style preview is not visible anymore and if the style name is longer it will be truncated

@irinelenache It's not really an issue but nice to point out so we can think about how to use these.
