### ISSUE TITLE
Using single filter for all the Block Editor modules

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#908]
One reason for the performance drawback is that we use filters to add modules separately.

For example:

- https://github.com/Codeinwp/otter-blocks/blob/master/src/animation/index.js
- https://github.com/Codeinwp/otter-blocks/blob/master/src/blocks/plugins/conditions/index.js

We use the same filter multiple times which makes a HOC for each time we use the filter. Instead of that, we can just use the filter one time and then hook our code there using the addFilter function which turns all our modules to use a single HOC hence reducing the HOC tree.

**Comment by HardeepAsrani** [comment]
We don't need this anymore as seems like performance issues weren't related to this.

**Comment by selul** [comment]
Maybe it wasnt the biggest, but dont you think it improves the perfomance if we do it?

**Comment by HardeepAsrani** [comment]
@selul I ran some performance tests and unfortunately not a difference. It takes less than a couple of milliseconds already so not sure how faster it can be.

**Comment by selul** [comment]
Understand. So do you think the complexity to implement does not justify the value ?

**Comment by HardeepAsrani** [comment]
Not at all, not sure there will be a value in the end. HOC wasn't making things slower now that we know in hindsight. 😄

**Comment by selul** [comment]
makes sense.
