### ISSUE TITLE
Otter Pro - Download Failed error

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#921]
Hello!

After installing Neve, Neve PRO, and Otter, the notice about downloading Otter pro to unlock the Block Editor Booster appeared:
![image](https://user-images.githubusercontent.com/86592992/168124277-ad3e056e-7cea-46de-85cd-b8306977b568.png)
After clicking on it, I was redirected to Neve options and clicked on Install:
![image](https://user-images.githubusercontent.com/86592992/168124488-e2267c45-960a-4f37-bfa7-0e23ec675238.png)
Then I got this error message: 
<img width="809" alt="image" src="https://user-images.githubusercontent.com/86592992/168124783-3da4fc43-3468-4b2f-b53c-761310e5118a.png">.
Am I doing something wrong?

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu @AndreeaCristinaRadacina Were both of you using Neve Pro license or Pirate Club?

**Comment by HardeepAsrani** [comment]
@selul Something to think here is if we allow them to use the Booster too given some of them might be using the Booster.

**Comment by cristian-ungureanu** [comment]
I was using a pirate club license but since the module was there before I think we should include it too. Not sure how many of our user still have pirate club. If we can't include it, if someone contacts us on support we should give them a neve license.

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu @AndreeaCristinaRadacina It should work fine now, we didn't take this use-case into consideration. I've also added Sparks to the packages so the same doesn't happen there. Of course, you still have time to decide that part for Sparks and make the changes in Neve if need be. 😄 Thanks for the quick reports! Please test to confirm that it works fine for you too.

**Comment by cristian-ungureanu** [comment]
All good now! Thank you! 🎉

**Comment by AndreeaCristinaRadacina** [comment]
It works for me as well!! Thank you 🥳

**Comment by HardeepAsrani** [comment]
Gald to know, thanks for the reports!
