### ISSUE TITLE
inline css vs loading a external CSS

### ISSUE THREAD

**Issue by selul** [Codeinwp/otter-blocks#922]
Right now for both free and pro, we load two very small CSS files doing two extra requests.

To improve the performance I would suggest adding those inline or have some mechanism where the saas is transformed into  .PHP files which we can use with require_once to get the content and inline them.

https://vertis.d.pr/rcpi03

**Comment by HardeepAsrani** [comment]
@selul It's better to keep the generation process the same but we can inline them using some other method. I wonder if something like will work:

```
ob_start();
include 'stye.css';
$css = ob_get_clean();
```

**Comment by HardeepAsrani** [comment]
Or we can also use `file_get_contents` I suppose.

**Comment by selul** [comment]
@HardeepAsrani using file_get_contents is good but we need to keep in mind the following: 
1. Once the file is not readable? What do we do? we should switch back to enqueue.
2. Once the file is on a different server? We might have issues getting it, in this case, we can switch back to enqueue.
3. We should use the path when using file_get_contents and not the URL to avoid doing an HTTP request, which is slower than reading from local disk.

Also, I think it's a good idea to look over if we can somehow output .PHP files instead of CSS and use native PHP include_once to get the files. The PHP file can contain something like this and use herodocs to define the style: 

```php
return  <<<CSS
.otter {padding:10px}
CSS;

**Comment by HardeepAsrani** [comment]
@selul I did a small PR to first make to test to make sure everything works normally as we have 4-5 different scenarios. I was also thinking that we can load the stylesheets of blocks (each block has a separate CSS inline). And we can keep doing this until the page has hit its inline styles threshold of 20kbs.
