### ISSUE TITLE
UX/UI improvements related to 2.0.3

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#923]
- in the current UI there are some differences between Figma & the Live version, for example buttons colors, the style of the boxes, minor differences in content. Even though those are not major issues, sometimes **UX/UI changes can influence the flow** and how users read the interface (see the next bullet point). And this can consume time on both side, Design team by working on something that's not 100% implemented, and on Dev team if for example we decide to fix those (working twice as much for the same thing).
 
So **tdlr**,  @HardeepAsrani , @Soare-Robert-Daniel , @arinaturcu  overall and **looking forward**, I think we should try to have a buy in from both sides, Dev & Design - on how some things will be implemented. I am not suggesting to micro-manage things, and I definitely appreciate when you take initiative to change something - however it would help to have at the table someone from both sides, when we change things - so everyone is aware of that.
**Note**: I am not suggesting to fix this now, just a thought to improve our workflows in future.

___ 
Here are a few things we can improve in terms of UX/UI, after the Otter Pro release:
- the upsell buttons **Explore Otter Pro** , **Get more options with Otter Pro**, etc. should take users to the **[Upgrade Page](https://themeisle.com/plugins/otter-blocks/upgrade/)**, not to the general Otter presentation page.
And we'll need a UTM tag for that, to see if/how those buttons work.
- as Marius mentioned, the Upgrade button inside the editor - should be one line. We can change the message to make shorter, and/or adjust a bit the padding to make it one line. Here's how it would look with 8px 14px padding. The message could be **Get more with Otter Pro** , or what Marius suggested on Slack:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/52494172/168236571-a80d5999-b158-4a9c-b6b6-3b03b69c3820.png">

- For the Options button, first of all I would change the text to something More positive like **Manage Otter Settings**, or else. As right now the btn message suggests & assumes that users would want/should disabled the those Otter options.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/52494172/168238800-f2a944b1-770a-4e1b-b860-3ef943ad90f1.png">

What I am thinking now, **is if it's worth to have in all panels, or maybe move it to the Otter panel** where the Global Defaults are.  
- as a rule, the Upgrade to Pro upsell message should be the main focus - and avoid having 3 buttons like we have here:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/52494172/168239097-88d157b2-d1a7-42aa-9c80-75e64d59b193.png">

And usually this type of Secondary messages should go at the bottom of the section.

**Comment by selul** [comment]
https://vertis.d.pr/XfF5HJ I like this one, maybe smaller font and being pulled in the right, at bottom always?

**Comment by HardeepAsrani** [comment]
@mghenciu It might be good if we can these things documented here: https://github.com/Codeinwp/otter-internals/wiki - an issue might be good to fix the things that we currently have but a wiki can help, I've currently added feature visibility figma link for future references.

**Comment by HardeepAsrani** [comment]
> For the Options button, first of all I would change the text to something More positive like Manage Otter Settings, or else. As right now the btn message suggests & assumes that users would want/should disabled the those Otter options.

Also, it's worth noting that this notice here was added to make user aware the setting comes from Otter, not really for showing them how to disable. For now I'll just use the Manage in Otter link but later we can decide if there's a better way.

**Comment by HardeepAsrani** [comment]
@mghenciu I've applied the border-radius and used the Otter color in the buttons. Let me know if I'm missing anything else on the Dashboard.

Rest of the issues are already mentioned here: https://github.com/Codeinwp/otter-blocks/issues/919
