### ISSUE TITLE
Posts block: excerptLength is not persistent and gets overridden by default 100

### ISSUE THREAD

**Issue by designzwang** [Codeinwp/otter-blocks#925]
Hi,

When placing a "posts" block in Neve, the value for excerpt length can be changed, the default is 100.
This works when saving a non-default value for the first time. 

However, when the page containing the block is edited again, the form field for excerpt length gets populated by the default 100 instead of loading the value that was saved before. So every time the page is edited, the value gets reset to the default value of 100.
Regards
Ulrich
![image](https://user-images.githubusercontent.com/5548014/168690200-d0aab24e-2270-460e-8ac6-2c58b9395fd1.png)

**Comment by HardeepAsrani** [comment]
@designzwang Thank you for reporting the issue. We've fixed it in https://github.com/Codeinwp/otter-blocks/pull/926 and it will be released in the next version!

**Comment by designzwang** [comment]
@HardeepAsrani - Wow, I am impressed. fixed and merget in  less then 14 hours ...
Tried to find/fix it myself, but did not succeed due to the JS/react style  - anyway,  I am looking forward to 2.0.5. Thanks again Hardeep and best regards!!
Ulrich
