### ISSUE TITLE
Accordion title goes outside the container when it's too long

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#932]
Having an accordion block with a longer title will make the title get outside the container. If it's too long, it should go on multiple lines.
![image](https://user-images.githubusercontent.com/67897586/169000474-fd3aa9d5-dd47-4dd3-99ad-c5adc69ada78.png)

**Comment by Soare-Robert-Daniel** [comment]
I could not reproduce the long text. But another issue popped out. If you have an extra tag (<strong>), the alignment will break.



![Image](https://user-images.githubusercontent.com/17597852/170439517-563c7d95-dbe1-4761-bde4-5280e7244fee.png)
