### ISSUE TITLE
Comparison table colors don't work in editor/frontend

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#933]
The colors in the comparison table block don't work neither in editor or frontend.
(Only text color works both in editor and frontend and border color in editor)

**Editor:**
![image](https://user-images.githubusercontent.com/67897586/169031850-88449d9d-f3dc-475f-a17f-f11ead4c3b12.png)

**Frontend:**
![image](https://user-images.githubusercontent.com/67897586/169031868-934f012e-5849-438c-90e1-edca0ddc1345.png)

**Comment by HardeepAsrani** [comment]
@irinelenache Might have been a one time issue. I tried and it seems to work for me. Can you try again?

**Comment by irinelenache** [comment]
@HardeepAsrani Couldn't replicate it again, so should be a one time issue. Will close this, thank you for checking 🚀
