### ISSUE TITLE
Custom CSS/additional attribute causing errors in some plugins

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#937]
More details soon. https://wordpress.org/plugins/mp3-music-player-by-sonaar/

**Comment by JohnPixle** [comment]
Do you think this might bring to the surface a broader issue with Custom CSS module? Or you already figured it out?

**Comment by HardeepAsrani** [comment]
@JohnPixle It has been there since the beginning. This only happens with Dynamic Blocks, first of all. Second, it usually happens when their blocks at times don't support the Core's className or if they somehow load their blocks way after everything else has loaded.

It's an issue for sure but not a major one, only few plugins really.

**Comment by HardeepAsrani** [comment]
Closing in favor of https://github.com/Codeinwp/otter-blocks/issues/555
