### ISSUE TITLE
JS scripts are loading even if no blocks are in use

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/otter-blocks#940]
On an empty page that is not using any blocks, Otter loads 4 js scripts. We should check and see if there is a way to avoid this.

<img width="1680" alt="Markup 2022-05-22 at 14 33 12" src="https://user-images.githubusercontent.com/9929553/169693163-ebfbb648-2c81-4df3-975a-a45f0d962006.png">

**Comment by mghenciu** [comment]
That may be for the additional options that Otter adds on all blocks. Options like Animation, CSS, Sticky.
But I am not sure if those should be initialised when a page is empty.

**Comment by HardeepAsrani** [comment]
We're aware of it and it's a duplicate of https://github.com/Codeinwp/otter-blocks/issues/927
