### ISSUE TITLE
Improve Product Review Comparison Placeholder

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/otter-blocks#946]
![CleanShot 2022-05-23 at 20 36 34](https://user-images.githubusercontent.com/7841556/169893391-09509ca4-5a57-4c7a-9354-9812e84b445c.jpg)

**Comment by HardeepAsrani** [comment]
@cristianraiber Have you added and published any posts using Review Block on your website?

**Comment by cristianraiber** [comment]
@HardeepAsrani - I have not. The plugin didn't tell me to do that ;) It's titled: "Product Review Comparison Table" - my assumption was that that's exactly what it's going to do - allow me to manually create a comparison table.

**Comment by HardeepAsrani** [comment]
@cristianraiber makes sense. We can add better placeholder text.
