### ISSUE TITLE
Button Group styling with Neve

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#947]
I am using Neve 3.2.5, Wp 5.9.3, and **Otter  2.0.4**.

### It looks like Otter Buttons don't inherit anymore the Styling from Customizer.

Usually when using Core Buttons, those inherit the Style from Customizer, which can be toggled from Styles Panel:
![Screenshot 2022-05-24 at 18 31 32](https://user-images.githubusercontent.com/52494172/170074707-f8c7d953-ac71-4c38-8997-1e3c3a7bec07.png)

___
But while working on [this issue](https://github.com/Codeinwp/neve-pro-addon/issues/1992#issuecomment-1134468319), I noticed that Otter Buttons don't inherit values styles from Customizer. So basically Styling needs to be applied locally (in the screenshot below, the btn should be yellow), in editor:
![Screenshot 2022-05-24 at 18 38 05](https://user-images.githubusercontent.com/52494172/170076040-55e70266-e021-402c-8009-50a982ec062e.png)

**Comment by mghenciu** [comment]
this is how the Core buttons options look (it's visible that those come from Customizer):
![Screenshot 2022-05-24 at 18 41 15](https://user-images.githubusercontent.com/52494172/170076765-5ba4fffc-e735-44a2-bf71-a66c409b0048.png)

**Comment by arinaturcu** [comment]
@HardeepAsrani Sure!
