### ISSUE TITLE
ACF Extension for Posts doesn't work

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#948]
If you click on add new field, nothing happens. Need to look why this might be happening, not sure how it escaped all the testing and QA.

**Comment by Soare-Robert-Daniel** [comment]
You added the Pro integration and forgot to re-add the functionality to the button

https://github.com/Codeinwp/otter-blocks/blob/0ea5cc68237fa533a3a920dd00a17a5276005fae/src/blocks/blocks/posts/components/design-layout-builder.js#L28-L39

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Nope. That's just an upsell item. It's hooked to a filter which is supposed to add the actual code.

Also it's strange how it escaped all the testing.

**Comment by Soare-Robert-Daniel** [comment]
If that is an upsell, then where is the actual button? 

I will make a PR to re-add the functionality.

**Comment by Soare-Robert-Daniel** [comment]
I show now that you add it as a plugin
