### ISSUE TITLE
Masonry Extension for new Gallery Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#956]
We need to figure out how to make it work with the new Gallery block. We can try to have it work only on the front if that is possible but currently not looking good.

Have some other ways, shitty ways, but things that can work regardless.

**Comment by AndreeaCristinaRadacina** [comment]
Hi Hardeep!

While working with the Masonry block, I encountered some problems as well.
Enabling the masonry layout does not change anything with the images in the editor.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/181464278-7cd8bd78-d933-4268-93f3-d78f32c0b6c9.png">

But on the frontend, the images are not displayed properly:
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/86592992/181464502-fab2c396-a9d1-4a0b-aaeb-ba00c88c7cec.png">

**Comment by Soare-Robert-Daniel** [comment]
@AndreeaCristinaRadacina, since some API changes were made, the Masonry is not working as expected in the new WP versions.

**Comment by HardeepAsrani** [comment]
Closing as we decided to not support this further.
