### ISSUE TITLE
Style gets resetted on tablet/mobile preview for some blocks

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#976]
When the viewport **preview** is switched in the editor, some blocks lose their styling (until going back to Desktop mode) https://www.loom.com/share/f34d706b66184c18944f40658b8c9a6c . 

This happens with some blocks like: **Progress bar, Countdown, Accordion, Tabs, Icon list, Icon, Flip card**

Tested also with other plugins, to see if it's a common problem:

**Kadence blocks** - the issue **is not** happening
**Ultimate addons for Gutenberg** - the issue **is** happening

**Comment by Soare-Robert-Daniel** [comment]
The problem seems to be that when you preview in Table or Mobile, the page is transferred in an iFrame, thus losing all its CSS nodes.

It is the same issue as in FSE.

The fix will gonna be in this #748
