### ISSUE TITLE
Otter with Ecwid store adds unknown element to the store

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#979]
We have received this issue from Ecwid by Lightspeed team -[ link here](https://secure.helpscout.net/conversation/1921466719/326351?folderId=212385).

Their client has a WordPress website where Ecwid store is added with Otter plugin.

Customer reported that on the website suddenly appeared the following text `'widgets='productbrowser']` under the store page, here is a screenshot: https://ecwid.d.pr/In4SyM. This text is reflected in the inspector https://ecwid.d.pr/50Ofwk, but you can't find it in the html code on WordPress. We tried to clean the cache. The merchant also tried to remove the store and add a new one to the site - nothing helped.

Our developers found a workaround: on the edit page, in the Otter plugin options you need to disable "Enable Block Condition Module", screenshot: https://take.ms/gR71J. The dev team looked into the issue but could not find on our end why this could happen.

**So, the question is, why when the "Enable Block Condition Module" option is enabled, a problem occurs, namely the random text label appears?** In your plugin code, this problem is related to the call `add_action( 'wp_loaded', array( $this, 'add_attributes_to_blocks' ), 999 );`.

If any info is needed from our end, please, let us know.

**Comment by HardeepAsrani** [comment]
Thanks, @poonam279, I've responded to the email. We can't do anything from our side to fix this, it's not really an issue with our code. If they reply, I'll get an email in my inbox.
