### ISSUE TITLE
Cannot accurately control column widths in Sections with a single column

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#980]
Hey @HardeepAsrani I have been facing this issue for a while, but it was until recently that I managed to wrap my head around it.

Basically, in our section block, when there is only one column available, the user has a hard time to manipulate the width of that single column. The problem is visible on the frontend only.

I created a video to outline the issue:
https://www.loom.com/share/6e200fb129ed41ac8ae87c6d556d188e

Let me know your thoughts on this and if you have any clarifications.

**Comment by HardeepAsrani** [comment]
@JohnPixle Thanks for pointing this out. It's a bug, I also made a video to give more context on this: https://www.loom.com/share/468ed6c65d0a4c04910b568d20bdd319

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel When you remove a column using the toolbar's "Remove Column" option, the switch isn't changed, so if you remove a block from a 50:50 grid, the block which is left stays 50 in width, same with other variants. Normally we should transfer that width to the next block (or previous if only one is left).

**Comment by JohnPixle** [comment]
@HardeepAsrani Thanks for  the update and the video, good to know the temporary workaround 👍🏻
