### ISSUE TITLE
[UX] Add to Cart block Woo dependency

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#981]
### Description:

When adding the Add to Cart block, and Woocommerce is not active - then users will get an error, like the block doesn't work.
From an UX perspective, it would be nice to know what it doesn't work, so for example the text could say '_**Add to Cart Button
 requires WooCommerce to be installed in order to run properly**_', instead of saying that the block is broken:
 
![image](https://user-images.githubusercontent.com/52494172/174630805-d4df9aa7-943c-47f4-aa35-8badbbebee0c.png)

This may be an edge case, and not a huge issue, but definitely a nice to have.

**Comment by HardeepAsrani** [comment]
@mghenciu Usually we don't show Woo blocks to non-Woo users as they don't care. Somehow the condition from this block was missed or removed by mistake. I've added it again.

If you don't have Woo then this block won't show up in the inserter. If you added the bock with Woo at some point and then removed Woo, then it will show a notice saying you need Woo installed to use it.
