### ISSUE TITLE
HTML anchor for the Button Group

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#985]
### Description:

@HardeepAsrani , what do you think if we add HTML anchor options for the Button group?

Currently we don't have this option, Core buttons have it.
I've tried using the Popup Close feature using an Anchor, but we don't have Anchors on our buttons, that's why I am asking.
![Screenshot 2022-06-22 at 14 34 11](https://user-images.githubusercontent.com/52494172/175019454-f01be7e7-e322-4e4a-a634-ed1c7894b2a2.png)

### Alternatives:

 Do nothing.

**Comment by HardeepAsrani** [comment]
@mghenciu You're confusing how the anchor for Popup works. You need to use the `#whatever` anchor to the link part of the button.

This is to just to give a unique ID to the button so other elements can refer to them which isn't needed to make the popup closing feature work.

Let me know what you think.
