### ISSUE TITLE
Multiple Tabs on the same page - not working as expected

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#991]
### Description:

When adding multiple Tabs blocks on the same page, those won't work as expected in terms of what tab is initially opened.
Let's also fix the Untitled Tab issue, meaning that each Tab (new tab) should have an increment: basically when I add the default Tabs block, it will have 3 Tabs (Tab 1, Tab 2, Tab 3); and when a new tab is added it will be Tab 4 (increment the number of tabs).
This will be good to avoid the issue of having all tabs Untitled:
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/52494172/175484016-8feef0dd-2133-4438-956b-926baf0533f3.png">

### How to reproduce:

1. Create a clean instance
2. Add at least 3 Tabs blocks on the page, each of them having a different Initial Tab 
3. Save and Preview

### Expected behaviour:
Have multiple Tabs on the same page, without issues related to the Initial Tab

### Current behaviour:
Only one Tab will be opened/rendered properly.

### Reference:

<img width="2189" alt="image" src="https://user-images.githubusercontent.com/52494172/175484868-a765f0ea-1c87-4926-9f5e-d9aee3a76fa1.png">

https://user-images.githubusercontent.com/52494172/175484767-59a2d680-cfcc-4eca-aad2-142dd012aea3.mov

### Technical info
* WordPress version: 5.9
* Plugin version: 2.0.5

**Comment by HardeepAsrani** [comment]
I've sent a PR that fixes + changes the fallback title, thanks for finding the issue @mghenciu. It doesn't really need a QA so I've merged it .
