### ISSUE TITLE
[UX Issue] Images are Replaced, instead of being added to the Library

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#995]
### Description:

When working with the Slider & Masonry/Gallery blocks, there is a Tab called Image where users can add, remove & arrange the images.

The strange thing happens when as an user you try manage those images, basically when adding New Images - instead of adding them to the Image List, those replace the entire existing list (see the video). 
**This may be related to the Core Component used in the Images Tab.** If so, I'll add it as a suggestion in Core.

### How to reproduce:

1. Create a clean instance
2. Add a Slider block
3. Add 3 Images to the Slider
4. Try to add another 3 Images in the slider, from the Image Tab
5. Notice that this will replace the existing images

### Expected behaviour:
New images should be appended to the existing list of images

### Current behaviour:
https://user-images.githubusercontent.com/52494172/175519044-5d6881bf-032c-4450-9851-f0cfd265bc17.mov

### Technical info
* WordPress version: 5.9
* Plugin version: 2.0.5

**Comment by HardeepAsrani** [comment]
@mghenciu That drag & drop component is from Otter so it's not an issue related to Core. We will check and see what might be causing it, thanks!

**Comment by HardeepAsrani** [comment]
@mghenciu I'm using the latest version of WordPress and can't seem to reproduce it on my end: https://www.loom.com/share/e50f6afd2cd94dbebc8869ae811370cc - am I missing anything?

**Comment by mghenciu** [comment]
> @mghenciu I'm using the latest version of WordPress and can't seem to reproduce it on my end: https://www.loom.com/share/e50f6afd2cd94dbebc8869ae811370cc - am I missing anything?

I think that's on the WP version 🤦 as it happens with 5.8.4, and not 6.0:

https://user-images.githubusercontent.com/52494172/175890339-873e5f81-0044-4a98-987b-97bbf525739b.mov





Tested with a clean instance, **wp 6.0 and it doesn't happen**, so I guess we can close it.

**Comment by HardeepAsrani** [comment]
@mghenciu Yea, I remember something similar with dragging/drop images in past version too. I'll close it.
