### ISSUE TITLE
Icon Block with themeisle Icons, not working properly with medium-high Padding

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#998]
### Description:

The Icon Block has Size, Padding, Margin & Border Controls.
Everything looks to be working as expected **until the Padding values are set to more than 25px**; from this point the SVG icon don't behave normally.

(attached JSON with the section)
[blocks-export (3).json.zip](https://github.com/Codeinwp/otter-blocks/files/8991712/blocks-export.3.json.zip)

___
**Note**: this is only happening with Themeisle Icons, the font awesome icons work as expected. 
May be related to the fact that we are using SVGs, while Font Awesome icons are <i> tags. Maybe it's time to reevaluate this, and see what we can improve.

Using 70+ px padding, may be an edge case, but using something between 25-36px is definitely something that users may use. 

### How to reproduce:

1. Create a new clean Instance
2. Add an Icon Block
3. Set the size of the Icon to 32px, and the padding to 28
4. Add a margin for the Icon

### Expected behaviour:
Icons from both libraries (FA & Themeisle Icons) should work the same way.

### Current behaviour:
This is how it looks in Backend:
<img width="1723" alt="Screenshot 2022-06-27 at 14 52 17" src="https://user-images.githubusercontent.com/52494172/175935065-e7f7d374-467e-4020-b2af-d84f408fa985.png">

___
and this is the **Frontend**, where it's noticeable that the Themeisle Icons are not displayed correctly:
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/52494172/175935568-73cc1794-cd3b-484c-90c5-cf6bfa3760e9.png">

<img width="1718" alt="Screenshot 2022-06-27 at 14 53 41" src="https://user-images.githubusercontent.com/52494172/175935294-f658d721-7873-4042-b73a-09fe81e041f3.png">

### Technical info
* WordPress version: 6.0
* Plugin version: 2.0.5

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Both icons behave strangely in editor/front compared to default/small/big padding. For me, in the front-end, somehow, the block looks smaller than the editor even tho the exact CSS is being applied. I see you made changes last time to fix the padding/margin, so can you take a look and see what is wrong with it?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, that update made the icons have the exact dimensions on the box, so they can align when used in an Icon List. The issue that @mghenciu is pointing it is about the scaling. At the same size, FA looks bigger and thicker than Themeisle.

I do not know to solve this issue with scaling since the objects are too different.
